   2  HOME 
   5  PRINT 
  10  PRINT "FUN TIMES"
  20  PRINT 
  22  PRINT "TALBOT FANTASY 7 VERSION 004"
  23  PRINT 
  24  PRINT "HTTP://WWW.DEATER.NET/WEAVE/VMWPROD/TFV"
  25  PRINT : PRINT 
  40  PRINT CHR$(4);"BRUN LOADER"
