hand04_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$88,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA, $33,$33
	.byte $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB
	.byte $A0,$01,$AA, $BA, $A0,$1D,$AA, $3A, $A0,$02,$AA, $A3,$33, $BB
	.byte $33, $A3,$BB, $BA, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A3,$33
	.byte $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A4,$33
	.byte $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33, $A6,$BB, $A0,$1A,$AA
	.byte $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33
	.byte $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33, $3B
	.byte $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33
	.byte $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB, $33
	.byte $A3,$BB, $A0,$1C,$AA, $A7,$33, $BB, $B3, $3B, $A3,$BB
	.byte $A0,$1C,$AA, $A7,$33, $A6,$BB, $A0,$AA,$AA
	.byte $A1
hand04_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $33,$33, $BB, $A0,$25,$AA, $A0,$01,$A3, $33,$33, $BB
	.byte $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33, $BB
	.byte $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB, $A0,$01,$AA
	.byte $BA, $A0,$1C,$AA, $3A,$3A, $A0,$02,$AA, $A3,$33, $BB, $33
	.byte $A3,$BB, $BA, $A0,$1B,$AA, $33,$33, $3A, $A0,$01,$AA, $A3,$33
	.byte $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A4,$33
	.byte $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33, $A6,$BB, $A0,$1A,$AA
	.byte $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33
	.byte $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33, $3B
	.byte $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33
	.byte $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB, $33
	.byte $A3,$BB, $A0,$AC,$AA
	.byte $A1
hand04_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$D6,$AA, $8A, $DA,$DA, $A0,$25,$AA, $88, $DD, $3D
	.byte $33, $BA, $A0,$23,$AA, $88, $DD, $D3, $33
	.byte $3B, $BA, $A0,$22,$AA, $A3,$A8, $33,$33, $3B, $BA
	.byte $A0,$24,$AA, $A3,$33, $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$01,$AA
	.byte $3A, $BA, $A0,$22,$AA, $A3,$33, $BB, $33, $BB
	.byte $BA, $BB, $A0,$1C,$AA, $3A, $33, $A0,$02,$AA, $A3,$33
	.byte $BB, $33, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A3,$33
	.byte $3B, $A5,$BB, $BA, $A0,$1A,$AA, $A0,$01,$A3, $33,$33, $A0,$01,$AA
	.byte $A4,$33, $3B, $A5,$BB, $BA, $A0,$1A,$AA, $A8,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A6,$33, $BB, $33, $3B, $A5,$BB, $A0,$1B,$AA
	.byte $A6,$33, $BB, $33, $3B, $A4,$BB, $A0,$1B,$AA, $A7,$33
	.byte $BB, $33, $A4,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A6,$33, $BB
	.byte $B3, $33, $A3,$BB, $A0,$AB,$AA
	.byte $A1
hand05_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$B0,$AA, $3A, $33, $BA, $A0,$25,$AA, $A0,$01,$A3, $33
	.byte $3B, $BA, $A0,$25,$AA, $33,$33, $3B, $BA, $A0,$24,$AA
	.byte $A3,$33, $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$25,$AA, $A3,$33
	.byte $BB,$BB, $3A, $33, $BB, $A0,$1C,$AA, $3A,$3A, $A0,$02,$AA
	.byte $A3,$33, $BB,$BB, $33, $A3,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA
	.byte $A3,$33, $3B, $A5,$BB, $BA, $A0,$1A,$AA, $A0,$01,$A3, $33,$33
	.byte $A0,$01,$AA, $A4,$33, $3B, $A5,$BB, $BA, $A0,$1A,$AA, $A8,$33
	.byte $A6,$BB, $A0,$1A,$AA, $A6,$33, $BB, $33, $3B, $A5,$BB
	.byte $A0,$1B,$AA, $A6,$33, $BB, $33, $3B, $A4,$BB, $A0,$1B,$AA
	.byte $A7,$33, $BB, $33, $A4,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A6,$33
	.byte $BB, $B3, $33, $A3,$BB, $A0,$1C,$AA, $A7,$33, $BB
	.byte $33, $A3,$BB, $BA, $A0,$1B,$AA, $A0,$01,$A3, $A6,$33, $3B
	.byte $BB, $B3, $A3,$BB, $BA, $A0,$A9,$AA
	.byte $A1
hand05_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$DB,$AA, $3A,$3A, $BA, $A0,$25,$AA, $A0,$01,$A3, $33, $3B
	.byte $BA, $A0,$25,$AA, $33,$33, $3B, $BA, $A0,$24,$AA, $A3,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$01,$AA, $3A, $BA
	.byte $A0,$22,$AA, $A3,$33, $BB, $33, $BB, $BA, $BB
	.byte $A0,$1C,$AA, $3A, $33, $A0,$02,$AA, $A3,$33, $BB, $33
	.byte $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A3,$33, $3B, $A5,$BB
	.byte $BA, $A0,$1A,$AA, $A0,$01,$A3, $33,$33, $A0,$01,$AA, $A4,$33, $3B
	.byte $A5,$BB, $BA, $A0,$1A,$AA, $A8,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33
	.byte $BB, $33, $3B, $A5,$BB, $A0,$1B,$AA, $A6,$33, $BB
	.byte $33, $3B, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33
	.byte $A4,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A6,$33, $BB, $B3, $33
	.byte $A3,$BB, $A0,$1C,$AA, $A7,$33, $BB, $33, $A3,$BB, $BA
	.byte $A0,$A7,$AA
	.byte $A1
hand05_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$DA,$AA, $85, $D5,$D5, $55, $A0,$24,$AA, $88, $DD
	.byte $33,$33, $BB, $A0,$23,$AA, $88, $8D,$8D, $33,$33, $BB
	.byte $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33, $BB
	.byte $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB, $A0,$01,$AA
	.byte $BA, $A0,$20,$AA, $A3,$33, $BB, $33, $A3,$BB, $BA
	.byte $A0,$1F,$AA, $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33
	.byte $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1A,$AA, $A3,$33, $3A, $A5,$33
	.byte $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA
	.byte $A0,$01,$A3, $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA
	.byte $A6,$33, $3B, $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33
	.byte $BB, $33, $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B
	.byte $BB, $33, $A3,$BB, $A0,$A7,$AA
	.byte $A1
hand05_04_rle:	.byte $28 ; ysize=48
	.byte $A0,$B5,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA, $33,$33
	.byte $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB
	.byte $A0,$01,$AA, $BA, $A0,$20,$AA, $A3,$33, $BB, $33, $A3,$BB
	.byte $BA, $A0,$1A,$AA, $A3,$3A, $A0,$02,$AA, $A3,$33, $BB, $B3
	.byte $A4,$BB, $A0,$1A,$AA, $A4,$33, $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1A,$AA
	.byte $A3,$33, $3A, $A5,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3
	.byte $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33, $3B, $B3
	.byte $33, $A5,$BB, $A0,$1B,$AA, $A6,$33, $3B, $B3, $33
	.byte $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33, $3B, $A3,$BB
	.byte $A0,$1C,$AA, $A6,$33, $3B, $BB, $33, $A3,$BB, $A0,$1C,$AA
	.byte $A7,$33, $BB, $B3, $3B, $A3,$BB, $A0,$A6,$AA
	.byte $A1
hand01_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$28,$AA, $3A, $33, $BA, $A0,$25,$AA, $A0,$01,$A3
	.byte $33, $3B, $BA, $A0,$25,$AA, $33,$33, $3B, $BA
	.byte $A0,$24,$AA, $A3,$33, $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$01,$AA
	.byte $3A, $BA, $A0,$22,$AA, $A3,$33, $BB, $33, $BB
	.byte $BA, $BB, $A0,$1C,$AA, $3A, $33, $A0,$02,$AA, $A3,$33
	.byte $BB, $33, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A3,$33
	.byte $3B, $A5,$BB, $BA, $A0,$1A,$AA, $A0,$01,$A3, $33,$33, $A0,$01,$AA
	.byte $A4,$33, $3B, $A5,$BB, $BA, $A0,$1A,$AA, $A8,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A6,$33, $BB, $33, $3B, $A5,$BB, $A0,$1B,$AA
	.byte $A6,$33, $BB, $33, $3B, $A4,$BB, $A0,$1B,$AA, $A7,$33
	.byte $BB, $33, $A4,$BB, $A0,$AC,$AA
	.byte $A1
hand01_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$4F,$AA, $8A, $DA,$DA, $A0,$25,$AA, $88, $DD
	.byte $33,$33, $BB, $A0,$23,$AA, $88, $8D,$8D, $33,$33, $BB
	.byte $A0,$22,$AA, $A3,$A6, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB
	.byte $A0,$01,$AA, $BA, $A0,$20,$AA, $A3,$33, $BB, $B3, $A3,$BB
	.byte $BA, $A0,$1B,$AA, $33,$33, $3A, $A0,$01,$AA, $A3,$33, $A6,$BB
	.byte $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33
	.byte $3A, $A5,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3, $33
	.byte $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33, $3B, $B3, $33
	.byte $A5,$BB, $A0,$AB,$AA
	.byte $A1
hand01_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$2A,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA
	.byte $33,$33, $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3
	.byte $33,$33, $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33,$33
	.byte $A0,$22,$AA, $A3,$33, $BB, $33, $A3,$BB, $BA, $A0,$1B,$AA
	.byte $33,$33, $3A, $A0,$01,$AA, $A3,$33, $BB, $B3, $A4,$BB
	.byte $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33
	.byte $3A, $A5,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3, $33
	.byte $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33, $3B, $B3, $33
	.byte $A5,$BB, $A0,$1B,$AA, $A6,$33, $3B, $B3, $33, $A4,$BB
	.byte $A0,$AB,$AA
	.byte $A1
hand09_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$2B,$AA, $BA, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA
	.byte $33,$33, $BB, $A0,$25,$AA, $33,$33, $BB,$BB, $A0,$24,$AA, $A0,$01,$A3
	.byte $33, $3B,$3B, $BB, $A0,$24,$AA, $A3,$33, $BB, $3A
	.byte $33, $BB, $BA, $A0,$1D,$AA, $3A, $A0,$02,$AA, $A3,$33
	.byte $BB, $33, $A3,$BB, $BA,$BA, $A0,$1A,$AA, $33,$33, $3A
	.byte $A0,$01,$AA, $A3,$33, $BB, $B3, $A5,$BB, $A0,$1A,$AA, $A3,$33
	.byte $A0,$01,$AA, $A4,$33, $A7,$BB, $A0,$1A,$AA, $33,$33, $3A, $A5,$33
	.byte $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA
	.byte $A0,$01,$A3, $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA
	.byte $A6,$33, $3B, $B3, $33, $A4,$BB, $A0,$AA,$AA
	.byte $A1
hand09_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$B5,$AA, $BA, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA, $33,$33
	.byte $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $3A,$3A, $BA,$BA
	.byte $A0,$20,$AA, $A3,$33, $BB, $33, $B3, $BB,$BB, $BA
	.byte $BB, $A0,$19,$AA, $3A, $33,$33, $A0,$02,$AA, $A3,$33, $BB
	.byte $B3, $A5,$BB, $A0,$19,$AA, $A4,$33, $A0,$01,$AA, $A4,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A3,$33, $3A, $A5,$33, $A6,$BB, $A0,$19,$AA, $A7,$33
	.byte $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33, $3B
	.byte $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33, $3B, $B3
	.byte $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33, $3B
	.byte $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB, $33, $A3,$BB
	.byte $A0,$1C,$AA, $A7,$33, $BB, $B3, $3B, $A3,$BB, $A0,$A6,$AA
	.byte $A1
hand09_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$67,$AA, $3A, $A0,$26,$AA, $A3,$33, $A0,$26,$AA, $33,$33, $BB
	.byte $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33, $BB
	.byte $A0,$25,$AA, $33,$33, $3B, $BA, $33, $B3, $A0,$01,$AA
	.byte $BA, $A0,$20,$AA, $A3,$33, $BB, $33, $A3,$BB, $BA
	.byte $A0,$1A,$AA, $A3,$33, $A0,$02,$AA, $A3,$33, $BB, $B3, $A4,$BB
	.byte $A0,$1A,$AA, $A3,$33, $3A, $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1A,$AA
	.byte $A3,$33, $3A, $A5,$33, $A6,$BB, $A0,$19,$AA, $A0,$01,$A3, $A6,$33
	.byte $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3, $A5,$33, $3B
	.byte $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33, $3B, $B3
	.byte $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33, $3B
	.byte $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB, $33, $A3,$BB
	.byte $A0,$1C,$AA, $A7,$33, $BB, $B3, $3B, $A3,$BB, $A0,$1C,$AA
	.byte $A7,$33, $A6,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A7,$33, $A6,$BB, $A0,$A2,$AA
	.byte $A1
hand09_04_rle:	.byte $28 ; ysize=48
	.byte $A0,$18,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA, $33,$33
	.byte $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB
	.byte $A0,$01,$AA, $BA, $A0,$1D,$AA, $3A, $A0,$02,$AA, $A3,$33, $BB
	.byte $33, $A3,$BB, $BA, $A0,$1B,$AA, $33,$33, $3A, $A0,$01,$AA
	.byte $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA
	.byte $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3
	.byte $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33
	.byte $3B, $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB
	.byte $33, $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB
	.byte $33, $A3,$BB, $A0,$1C,$AA, $A7,$33, $BB, $B3, $3B
	.byte $A3,$BB, $A0,$1C,$AA, $A7,$33, $A6,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A7,$33
	.byte $A6,$BB, $A0,$1C,$AA, $A7,$33, $A6,$BB, $A0,$1B,$AA, $A7,$33, $A6,$BB
	.byte $A0,$A0,$AA
	.byte $A1
hand09_05_rle:	.byte $28 ; ysize=48
	.byte $A0,$66,$AA, $8A, $DA,$DA, $A0,$25,$AA, $88, $DD, $33,$33
	.byte $BB, $A0,$23,$AA, $88, $8D,$8D, $33,$33, $BB, $A0,$25,$AA
	.byte $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33, $BB, $A0,$25,$AA
	.byte $33,$33, $3B, $BA, $33, $BB, $A0,$01,$AA, $BA
	.byte $A0,$20,$AA, $A3,$33, $BB, $33, $A3,$BB, $BA, $A0,$1A,$AA
	.byte $3A, $33, $3A, $A0,$02,$AA, $A3,$33, $BB, $B3
	.byte $A4,$BB, $A0,$19,$AA, $A4,$33, $3A, $A0,$01,$AA, $A4,$33, $A6,$BB
	.byte $A0,$19,$AA, $A0,$01,$A3, $A3,$33, $3A, $A5,$33, $A6,$BB, $A0,$19,$AA
	.byte $A0,$01,$A3, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3
	.byte $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33
	.byte $3B, $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB
	.byte $33, $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB
	.byte $33, $A3,$BB, $A0,$1C,$AA, $A7,$33, $BB, $B3, $3B
	.byte $A3,$BB, $A0,$1C,$AA, $A7,$33, $A6,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A7,$33
	.byte $A6,$BB, $A0,$A0,$AA
	.byte $A1
hand03_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$68,$AA, $3B,$3B, $BA, $A0,$25,$AA, $A0,$01,$A3, $33, $3B
	.byte $BA, $A0,$25,$AA, $33,$33, $3B, $BA, $A0,$24,$AA, $A3,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$01,$AA, $3A,$3A, $A0,$22,$AA
	.byte $A3,$33, $BB, $33, $BB, $BA, $BB, $A0,$1B,$AA
	.byte $A3,$3A, $A0,$02,$AA, $A3,$33, $BB, $33, $A4,$BB, $A0,$1A,$AA
	.byte $A3,$33, $3A, $A0,$01,$AA, $A3,$33, $3B, $A5,$BB, $BA
	.byte $A0,$19,$AA, $A0,$01,$A3, $A3,$33, $A0,$01,$AA, $A4,$33, $3B, $A5,$BB
	.byte $BA, $A0,$19,$AA, $A0,$01,$A3, $A8,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33
	.byte $BB, $33, $3B, $A5,$BB, $A0,$1B,$AA, $A6,$33, $BB
	.byte $33, $3B, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB, $33
	.byte $A4,$BB, $A0,$1B,$AA, $A0,$01,$A3, $A6,$33, $BB, $B3, $33
	.byte $A3,$BB, $A0,$1C,$AA, $A7,$33, $BB, $33, $A3,$BB, $BA
	.byte $A0,$1B,$AA, $A0,$01,$A3, $A6,$33, $3B, $BB, $B3, $A3,$BB
	.byte $BA, $A0,$1B,$AA, $A7,$33, $3B, $A5,$BB, $BA, $A0,$1B,$AA
	.byte $A7,$A3, $A6,$AB, $A0,$A0,$AA
	.byte $A1
hand03_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$E0,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA, $33,$33
	.byte $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB
	.byte $A0,$01,$AA, $BA, $A0,$1D,$AA, $3A, $A0,$02,$AA, $A3,$33, $BB
	.byte $33, $A3,$BB, $BA, $A0,$1B,$AA, $33,$33, $3A, $A0,$01,$AA
	.byte $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA
	.byte $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3
	.byte $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33
	.byte $3B, $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB
	.byte $33, $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB
	.byte $33, $A3,$BB, $A0,$A4,$AA
	.byte $A1
hand03_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$58,$AA, $3A,$3A, $BA, $A0,$25,$AA, $A0,$01,$A3, $33
	.byte $3B, $BA, $A0,$25,$AA, $33,$33, $3B, $BA, $A0,$24,$AA
	.byte $A3,$33, $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$01,$AA, $3A,$3A
	.byte $A0,$22,$AA, $A3,$33, $BB, $33, $BB, $BA, $BB
	.byte $A0,$1C,$AA, $3A, $33, $A0,$02,$AA, $A3,$33, $BB, $33
	.byte $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA, $A3,$33, $3B, $A5,$BB
	.byte $BA, $A0,$1A,$AA, $A0,$01,$A3, $33,$33, $A0,$01,$AA, $A4,$33, $3B
	.byte $A5,$BB, $BA, $A0,$1A,$AA, $A8,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33
	.byte $BB, $33, $3B, $A5,$BB, $A0,$1B,$AA, $A6,$33, $BB
	.byte $33, $3B, $A4,$BB, $A0,$A4,$AA
	.byte $A1
hand03_04_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$57,$AA, $8A, $DA,$DA, $A0,$25,$AA, $88, $DD
	.byte $33, $3B, $BA, $A0,$23,$AA, $88, $8D, $33,$33
	.byte $3B, $BA, $A0,$24,$AA, $A3,$33, $BB, $A0,$25,$AA, $33,$33
	.byte $BB, $A0,$01,$AA, $3A,$3A, $A0,$22,$AA, $A3,$33, $BB, $33
	.byte $BB, $BA,$BA, $A0,$20,$AA, $A3,$33, $BB, $33, $A4,$BB
	.byte $A0,$1B,$AA, $33, $3A, $A0,$02,$AA, $A3,$33, $3B, $A5,$BB
	.byte $BA, $A0,$1A,$AA, $A3,$33, $A0,$01,$AA, $A4,$33, $3B, $A5,$BB
	.byte $BA, $A0,$19,$AA, $A9,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33, $BB
	.byte $33, $3B, $A5,$BB, $A0,$1B,$AA, $A6,$A3, $A0,$01,$AB, $A0,$01,$A3
	.byte $A5,$AB, $A0,$A4,$AA
	.byte $A1
hand02_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$55,$AA, $33,$33, $BA, $A0,$25,$AA, $A0,$01,$A3, $33
	.byte $3B, $BA, $A0,$25,$AA, $33,$33, $3B, $BA, $A0,$24,$AA
	.byte $A3,$33, $BB, $A0,$25,$AA, $33,$33, $BB, $A0,$01,$AA, $3A,$3A
	.byte $A0,$22,$AA, $A3,$33, $BB, $33, $BB, $BA,$BA, $A0,$1C,$AA
	.byte $33,$33, $A0,$02,$AA, $A3,$33, $BB, $33, $A4,$BB, $A0,$1B,$AA
	.byte $A3,$33, $A0,$01,$AA, $A3,$33, $3B, $A5,$BB, $BA, $A0,$1A,$AA
	.byte $A0,$01,$A3, $33,$33, $A0,$01,$AA, $A4,$33, $3B, $A5,$BB, $BA
	.byte $A0,$1A,$AA, $A8,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33, $BB, $33
	.byte $3B, $A5,$BB, $A0,$1B,$AA, $A6,$33, $BB, $33, $3B
	.byte $A4,$BB, $A0,$A7,$AA
	.byte $A1
hand02_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$2C,$AA, $33, $BB, $A0,$25,$AA, $33,$33, $BB
	.byte $A0,$26,$AA, $33,$33, $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA
	.byte $A0,$01,$A3, $33,$33, $BB, $A0,$25,$AA, $33,$33, $3B, $BA
	.byte $33, $B3, $A0,$1F,$AA, $3A, $A0,$02,$AA, $A3,$33, $BB
	.byte $33, $A3,$BB, $BA, $A0,$1B,$AA, $33,$33, $3A, $A0,$01,$AA
	.byte $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA
	.byte $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3
	.byte $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33
	.byte $3B, $B3, $33, $A4,$BB, $A0,$A9,$AA
	.byte $A1
hand02_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$53,$AA, $85, $D5,$D5, $35, $A0,$24,$AA, $88
	.byte $DD, $A3,$33, $BB, $A0,$22,$AA, $88, $8D,$8D, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $BB,$BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $BB, $BA, $33, $BB
	.byte $A0,$22,$AA, $A3,$33, $BB, $33, $A3,$BB, $BA, $A0,$1B,$AA
	.byte $A3,$3A, $A0,$01,$AA, $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA
	.byte $A3,$33, $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1A,$AA, $A3,$33, $3A
	.byte $A5,$33, $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB
	.byte $A0,$1A,$AA, $A0,$01,$A3, $A5,$33, $3B, $B3, $33, $A5,$BB
	.byte $A0,$A7,$AA
	.byte $A1
hand02_04_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$7D,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA
	.byte $33,$33, $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3
	.byte $33,$33, $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33
	.byte $BB, $A0,$01,$AA, $BA, $A0,$1D,$AA, $3A, $A0,$02,$AA, $A3,$33
	.byte $BB, $33, $A3,$BB, $BA, $A0,$1B,$AA, $33,$33, $3A
	.byte $A0,$01,$AA, $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33
	.byte $A0,$01,$AA, $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33
	.byte $A6,$BB, $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$A8,$AA
	.byte $A1
hand02_05_rle:	.byte $28 ; ysize=48
	.byte $A0,$DB,$AA, $3A, $A0,$26,$AA, $33,$33, $BB, $A0,$26,$AA, $33,$33
	.byte $BB, $A0,$25,$AA, $A3,$33, $BB, $A0,$24,$AA, $A0,$01,$A3, $33,$33
	.byte $BB, $A0,$25,$AA, $33,$33, $3B, $BA, $33, $BB
	.byte $A0,$01,$AA, $BA, $A0,$1D,$AA, $3A, $A0,$02,$AA, $A3,$33, $BB
	.byte $33, $A3,$BB, $BA, $A0,$1B,$AA, $33,$33, $3A, $A0,$01,$AA
	.byte $A3,$33, $BB, $B3, $A4,$BB, $A0,$1B,$AA, $A3,$33, $A0,$01,$AA
	.byte $A4,$33, $A6,$BB, $A0,$1B,$AA, $33,$33, $3A, $A5,$33, $A6,$BB
	.byte $A0,$1A,$AA, $A6,$33, $B3, $33, $A6,$BB, $A0,$1A,$AA, $A0,$01,$A3
	.byte $A5,$33, $3B, $B3, $33, $A5,$BB, $A0,$1B,$AA, $A6,$33
	.byte $3B, $B3, $33, $A4,$BB, $A0,$1B,$AA, $A7,$33, $BB
	.byte $33, $3B, $A3,$BB, $A0,$1C,$AA, $A6,$33, $3B, $BB
	.byte $33, $A3,$BB, $A0,$A9,$AA
	.byte $A1
