5 HOME
10 PRINT "         -= DON'T TELL VALVE =-"
12 PRINT "           ------------------"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN DONT2'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN DONT2"
