include ../../../../../Makefile.inc

PNG2GR = ../../../../../utils/gr-utils/png2gr
LZSA = ~/research/lzsa/lzsa/lzsa

all:	ootw_l1end.inc

#####

ootw_l1end.inc:	\
	l1end01.lzsa l1end02.lzsa l1end03.lzsa \
	l1end04.lzsa l1end05.lzsa l1end06.lzsa \
	l1end07.lzsa l1end08.lzsa l1end09.lzsa \
	l1end10.lzsa l1end11.lzsa l1end12.lzsa \
	l1end13.lzsa l1end14.lzsa l1end15.lzsa \
	l1end16.lzsa l1end17.lzsa l1end18.lzsa \
	l1end19.lzsa l1end20.lzsa l1end21.lzsa \
	l1end22.lzsa l1end23.lzsa l1end24.lzsa \
	l1end25.lzsa l1end26.lzsa l1end27.lzsa \
	l1end28.lzsa l1end29.lzsa l1end30.lzsa \
	l1end31.lzsa l1end32.lzsa l1end33.lzsa \
	ootw_deadbeast.lzsa \
	ootw_gunguy.lzsa \
	ootw_peace.lzsa \
	l1end36.lzsa l1end37.lzsa l1end38.lzsa \
	l1end39.lzsa l1end40.lzsa l1end41.lzsa \
	l1end42.lzsa l1end43.lzsa l1end44.lzsa \
	l1end45.lzsa l1end46.lzsa l1end47.lzsa \
	l1end48.lzsa l1end49.lzsa l1end50.lzsa \
	l1end51.lzsa black.lzsa
	echo "l1end01_lzsa: .incbin \"l1end01.lzsa\"" > ootw_l1end.inc
	echo "l1end02_lzsa: .incbin \"l1end02.lzsa\"" >> ootw_l1end.inc
	echo "l1end03_lzsa: .incbin \"l1end03.lzsa\"" >> ootw_l1end.inc
	echo "l1end04_lzsa: .incbin \"l1end04.lzsa\"" >> ootw_l1end.inc
	echo "l1end05_lzsa: .incbin \"l1end05.lzsa\"" >> ootw_l1end.inc
	echo "l1end06_lzsa: .incbin \"l1end06.lzsa\"" >> ootw_l1end.inc
	echo "l1end07_lzsa: .incbin \"l1end07.lzsa\"" >> ootw_l1end.inc
	echo "l1end08_lzsa: .incbin \"l1end08.lzsa\"" >> ootw_l1end.inc
	echo "l1end09_lzsa: .incbin \"l1end09.lzsa\"" >> ootw_l1end.inc
	echo "l1end10_lzsa: .incbin \"l1end10.lzsa\"" >> ootw_l1end.inc
	echo "l1end11_lzsa: .incbin \"l1end11.lzsa\"" >> ootw_l1end.inc
	echo "l1end12_lzsa: .incbin \"l1end12.lzsa\"" >> ootw_l1end.inc
	echo "l1end13_lzsa: .incbin \"l1end13.lzsa\"" >> ootw_l1end.inc
	echo "l1end14_lzsa: .incbin \"l1end14.lzsa\"" >> ootw_l1end.inc
	echo "l1end15_lzsa: .incbin \"l1end15.lzsa\"" >> ootw_l1end.inc
	echo "l1end16_lzsa: .incbin \"l1end16.lzsa\"" >> ootw_l1end.inc
	echo "l1end17_lzsa: .incbin \"l1end17.lzsa\"" >> ootw_l1end.inc
	echo "l1end18_lzsa: .incbin \"l1end18.lzsa\"" >> ootw_l1end.inc
	echo "l1end19_lzsa: .incbin \"l1end19.lzsa\"" >> ootw_l1end.inc
	echo "l1end20_lzsa: .incbin \"l1end20.lzsa\"" >> ootw_l1end.inc
	echo "l1end21_lzsa: .incbin \"l1end21.lzsa\"" >> ootw_l1end.inc
	echo "l1end22_lzsa: .incbin \"l1end22.lzsa\"" >> ootw_l1end.inc
	echo "l1end23_lzsa: .incbin \"l1end23.lzsa\"" >> ootw_l1end.inc
	echo "l1end24_lzsa: .incbin \"l1end24.lzsa\"" >> ootw_l1end.inc
	echo "l1end25_lzsa: .incbin \"l1end25.lzsa\"" >> ootw_l1end.inc
	echo "l1end26_lzsa: .incbin \"l1end26.lzsa\"" >> ootw_l1end.inc
	echo "l1end27_lzsa: .incbin \"l1end27.lzsa\"" >> ootw_l1end.inc
	echo "l1end28_lzsa: .incbin \"l1end28.lzsa\"" >> ootw_l1end.inc
	echo "l1end29_lzsa: .incbin \"l1end29.lzsa\"" >> ootw_l1end.inc
	echo "l1end30_lzsa: .incbin \"l1end30.lzsa\"" >> ootw_l1end.inc
	echo "l1end31_lzsa: .incbin \"l1end31.lzsa\"" >> ootw_l1end.inc
	echo "l1end32_lzsa: .incbin \"l1end32.lzsa\"" >> ootw_l1end.inc
	echo "l1end33_lzsa: .incbin \"l1end33.lzsa\"" >> ootw_l1end.inc
	echo "l1end36_lzsa: .incbin \"l1end36.lzsa\"" >> ootw_l1end.inc
	echo "l1end37_lzsa: .incbin \"l1end37.lzsa\"" >> ootw_l1end.inc
	echo "l1end38_lzsa: .incbin \"l1end38.lzsa\"" >> ootw_l1end.inc
	echo "l1end39_lzsa: .incbin \"l1end39.lzsa\"" >> ootw_l1end.inc
	echo "l1end40_lzsa: .incbin \"l1end40.lzsa\"" >> ootw_l1end.inc
	echo "l1end41_lzsa: .incbin \"l1end41.lzsa\"" >> ootw_l1end.inc
	echo "l1end42_lzsa: .incbin \"l1end42.lzsa\"" >> ootw_l1end.inc
	echo "l1end43_lzsa: .incbin \"l1end43.lzsa\"" >> ootw_l1end.inc
	echo "l1end44_lzsa: .incbin \"l1end44.lzsa\"" >> ootw_l1end.inc
	echo "l1end45_lzsa: .incbin \"l1end45.lzsa\"" >> ootw_l1end.inc
	echo "l1end46_lzsa: .incbin \"l1end46.lzsa\"" >> ootw_l1end.inc
	echo "l1end47_lzsa: .incbin \"l1end47.lzsa\"" >> ootw_l1end.inc
	echo "l1end48_lzsa: .incbin \"l1end48.lzsa\"" >> ootw_l1end.inc
	echo "l1end49_lzsa: .incbin \"l1end49.lzsa\"" >> ootw_l1end.inc
	echo "l1end50_lzsa: .incbin \"l1end50.lzsa\"" >> ootw_l1end.inc
	echo "l1end51_lzsa: .incbin \"l1end51.lzsa\"" >> ootw_l1end.inc
#	$(PNG2RLE) asm ootw_deadbeast.png deadbeast_rle >> ootw_l1end.inc
	echo "gunguy_lzsa: .incbin \"ootw_gunguy.lzsa\"" >> ootw_l1end.inc
	echo "peace_lzsa: .incbin \"ootw_peace.lzsa\"" >> ootw_l1end.inc
	echo "black_lzsa: .incbin \"black.lzsa\"" >> ootw_l1end.inc

#####

%.gr:	%.png
	$(PNG2GR) $< $@

%.lzsa:	%.gr
	$(LZSA) -r -f2 $< $@

#####

clean:		
		rm -f *~ *.o *.lst *.inc *.gr *.lzsa

