l1end01_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$E0,$AA, $9A, $A8,$AA, $0A, $A0,$1E,$AA, $99
	.byte $A7,$AA, $A3,$00, $A0,$1D,$AA, $0B, $A4,$AA, $0A, $A5,$00
	.byte $0A, $A0,$1C,$AA, $BB, $A0,$01,$AA, $0A,$0A, $A8,$00, $0A
	.byte $A0,$1B,$AA, $BB, $A0,$02,$AA, $A4,$A0, $A4,$AA, $A0,$02,$A0, $A0,$1B,$AA
	.byte $44, $A0,$27,$AA, $44, $A0,$27,$AA, $A0,$01,$AF, $A0,$C8,$AA
	.byte $A1
l1end02_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$DE,$AA, $9A,$9A, $A9,$AA, $0A, $A0,$1C,$AA, $99
	.byte $BB, $A8,$AA, $A3,$00, $A0,$1B,$AA, $0B, $A6,$AA, $0A
	.byte $A5,$00, $0A, $A0,$1A,$AA, $BB, $00, $A0,$02,$AA, $0A,$0A
	.byte $A8,$00, $0A, $A0,$19,$AA, $A0,$01,$AB, $40, $A3,$AA, $A4,$A0
	.byte $A4,$AA, $A0,$02,$A0, $A0,$1A,$AA, $C4, $4A, $A0,$26,$AA, $CC
	.byte $44, $A0,$26,$AA, $A0,$01,$A7, $A0,$01,$AF, $A0,$C8,$AA
	.byte $A1
l1end03_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A6,$AA, $99, $B9, $A9,$AA, $A3,$0A
	.byte $00,$00, $A0,$18,$AA, $B9, $A0,$01,$AB, $A8,$AA, $A7,$00, $A0,$16,$AA
	.byte $BB, $00, $A6,$AA, $0A,$0A, $A8,$00, $A0,$16,$AA, $A0,$01,$AB
	.byte $B0, $A6,$AA, $A4,$A0, $A3,$AA, $A0,$01,$A0, $A3,$00, $A0,$16,$AA
	.byte $C4, $44, $CC, $77, $A0,$26,$AA, $A0,$01,$AF, $A0,$F1,$AA
	.byte $A1
l1end04_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A0,$14,$AA, $0A, $A0,$01,$AA, $0A,$0A, $A0,$15,$AA
	.byte $99, $B9, $AB,$AA, $0A, $A5,$00, $A0,$15,$AA, $B9
	.byte $A0,$01,$AB, $A8,$AA, $0A,$0A, $A7,$00, $A0,$14,$AA, $BB, $00
	.byte $A9,$AA, $A0,$02,$A0, $0A,$0A, $A4,$00, $A0,$01,$A0, $A0,$14,$AA, $A0,$01,$AB
	.byte $B0, $AA,$AA, $A5,$A0, $A0,$01,$AA, $A0,$01,$A0, $00, $A0,$15,$AA
	.byte $C4, $44, $CC, $77, $A0,$26,$AA, $A0,$01,$AF, $A0,$CA,$AA
	.byte $A1
l1end05_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A0,$17,$AA, $0A, $00, $0A, $A0,$12,$AA
	.byte $9A,$9A, $A3,$AA, $00, $AA,$AA, $0A,$0A, $A4,$00, $A0,$12,$AA
	.byte $99, $BB, $AC,$AA, $A7,$00, $A0,$01,$A0, $A0,$11,$AA, $BA
	.byte $0B, $AC,$AA, $0A, $A3,$00, $A0,$02,$A0, $00, $A0,$13,$AA
	.byte $BB, $00, $AB,$AA, $A5,$A0, $A0,$02,$AA, $00, $A0,$14,$AA
	.byte $4B, $4A, $CA, $7A, $A0,$24,$AA, $A0,$01,$AC, $A0,$01,$A4
	.byte $FC, $A0,$01,$A7, $A0,$CA,$AA
	.byte $A1
l1end06_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A9,$AA, $00, $AD,$AA, $0A, $00
	.byte $0A, $A0,$16,$AA, $00,$00, $AA,$AA, $0A,$0A, $A4,$00, $A0,$10,$AA
	.byte $99, $B9, $A5,$AA, $00, $A9,$AA, $A6,$00, $A0,$01,$A0
	.byte $A0,$10,$AA, $B9, $A0,$01,$AB, $A5,$AA, $00, $A7,$AA, $0A,$0A
	.byte $00,$00, $A0,$01,$AA, $A0,$01,$A0, $00, $A0,$11,$AA, $BB, $00
	.byte $BA, $A5,$AA, $00, $A6,$AA, $A0,$02,$A0, $00, $A0,$01,$A0
	.byte $00, $A0,$02,$AA, $00, $A0,$11,$AA, $A0,$01,$AB, $B0, $4A
	.byte $FA, $A0,$01,$AA, $7A, $A0,$02,$AA, $00, $A0,$20,$AA, $A0,$01,$A4
	.byte $44, $FF, $CC, $77, $A0,$CB,$AA
	.byte $A1
l1end07_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$E0,$AA, $00, $A0,$27,$AA, $00, $AE,$AA, $0A
	.byte $00, $0A, $A0,$15,$AA, $00,$00, $AC,$AA, $0A, $A4,$00
	.byte $AD,$AA, $9A,$9A, $A7,$AA, $00, $AB,$AA, $A6,$00, $AD,$AA
	.byte $99, $BB, $A7,$AA, $00, $AB,$AA, $A0,$01,$A0, $A3,$00
	.byte $A0,$01,$A0, $AE,$AA, $0B,$0B, $BA, $A6,$AA, $00, $AC,$AA
	.byte $00, $A0,$01,$A0, $00, $AF,$AA, $BB, $00, $44
	.byte $4A, $FF, $CA, $7A, $A0,$02,$AA, $00, $A0,$1E,$AA
	.byte $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $77, $A0,$02,$AA
	.byte $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end08_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$90,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$27,$AA, $00, $A0,$10,$AA, $0A,$0A, $A0,$14,$AA, $00,$00, $AE,$AA
	.byte $0A, $A5,$00, $A8,$AA, $9A,$9A, $A9,$AA, $00, $AD,$AA
	.byte $A7,$00, $A8,$AA, $99, $BB, $A9,$AA, $00, $AD,$AA
	.byte $A0,$01,$A0, $A4,$00, $A0,$01,$A0, $A9,$AA, $A0,$01,$AB, $0B, $0A
	.byte $BA, $A7,$AA, $00, $AF,$AA, $00,$00, $0A, $AB,$AA
	.byte $BB, $00, $44, $4A, $FF, $CA, $77
	.byte $A3,$AA, $00, $AF,$AA, $A0,$01,$A0, $A0,$01,$AA, $A0,$01,$A0, $AB,$AA
	.byte $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A3,$AA
	.byte $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end09_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$90,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$27,$AA, $00, $A0,$13,$AA, $0A, $00,$00, $A0,$10,$AA, $00,$00
	.byte $AE,$AA, $0A, $00,$00, $0A, $A5,$00, $A4,$AA, $9A,$9A
	.byte $AA,$AA, $00, $AD,$AA, $A9,$00, $A0,$01,$A0, $A4,$AA, $99
	.byte $BB, $AA,$AA, $00, $AD,$AA, $A0,$01,$A0, $00,$00, $A3,$A0
	.byte $00, $A0,$01,$A0, $A7,$AA, $0B, $0A, $BA, $A8,$AA
	.byte $00, $AE,$AA, $00, $A4,$AA, $00, $A8,$AA, $BB
	.byte $00, $44, $4A, $FF, $CA, $77, $A4,$AA
	.byte $00, $A0,$1C,$AA, $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC
	.byte $A0,$01,$A7, $A4,$AA, $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end10_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$90,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$27,$AA, $00, $A0,$13,$AA, $0A, $00,$00, $A0,$10,$AA, $00,$00
	.byte $A0,$11,$AA, $0A, $A5,$00, $A4,$AA, $9A,$9A, $AA,$AA, $00
	.byte $AF,$AA, $0A, $A6,$00, $A0,$01,$A0, $A4,$AA, $99, $BB
	.byte $AA,$AA, $00, $AD,$AA, $0A, $A3,$00, $A0,$01,$A0, $A3,$AA
	.byte $A0,$01,$A0, $00, $A5,$AA, $0B, $0A, $BA, $A8,$AA
	.byte $00, $AC,$AA, $00,$00, $A0,$01,$A0, $00, $AC,$AA, $BB
	.byte $00, $44, $4A, $FF, $CA, $77, $A4,$AA
	.byte $00, $A0,$1C,$AA, $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC
	.byte $A0,$01,$A7, $A4,$AA, $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end11_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$90,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$16,$AA, $0A,$0A, $AF,$AA, $00, $A0,$14,$AA, $0A, $A4,$00
	.byte $AD,$AA, $00,$00, $A0,$12,$AA, $0A, $A7,$00, $9A,$9A, $AB,$AA
	.byte $00, $A0,$10,$AA, $0A, $A3,$00, $A5,$A0, $00, $99
	.byte $BB, $AB,$AA, $00, $A0,$10,$AA, $00,$00, $A9,$AA, $0B
	.byte $0A, $BA, $A9,$AA, $00, $A0,$10,$AA, $A0,$01,$A0, $AA,$AA
	.byte $BB, $00, $44, $4A, $FF, $CA, $77
	.byte $A5,$AA, $00, $A0,$1B,$AA, $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A5,$AA, $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end12_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00
	.byte $A0,$16,$AA, $A3,$0A, $AD,$AA, $00,$00, $A0,$15,$AA, $A4,$00, $AC,$AA
	.byte $0A, $00,$00, $A0,$12,$AA, $0A, $A0,$01,$AA, $0A, $A4,$00
	.byte $0A, $AB,$AA, $A3,$00, $A0,$12,$AA, $A7,$00, $90, $9A
	.byte $AB,$AA, $00,$00, $A0,$10,$AA, $0A,$0A, $A6,$00, $A0,$01,$A0, $99
	.byte $BB, $AB,$AA, $00,$00, $A0,$10,$AA, $A4,$A0, $A6,$AA, $0B
	.byte $0A, $BA, $A9,$AA, $00,$00, $A0,$1A,$AA, $BB, $00
	.byte $44,$44, $FF, $CA, $77, $A5,$AA, $00,$00, $A0,$1A,$AA
	.byte $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A4,$AA
	.byte $A3,$A0, $A0,$C8,$AA
	.byte $A1
l1end13_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00
	.byte $A0,$16,$AA, $A3,$0A, $AD,$AA, $00,$00, $A0,$15,$AA, $A5,$00, $AB,$AA
	.byte $0A, $00,$00, $A0,$14,$AA, $0A, $A5,$00, $AB,$AA, $A3,$00
	.byte $A0,$14,$AA, $00,$00, $10, $00,$00, $90, $9A, $AB,$1A
	.byte $10,$10, $A0,$14,$AA, $00,$00, $11, $00, $A0,$01,$A0, $99
	.byte $BB, $AB,$AA, $00,$00, $A0,$14,$AA, $00,$00, $A0,$01,$AA, $A0,$01,$A0
	.byte $A0,$02,$AA, $0B, $0A, $BA, $A9,$AA, $00,$00, $A0,$14,$AA
	.byte $A0,$01,$A0, $00, $A4,$AA, $BB, $00, $44,$44, $FF
	.byte $CA, $77, $A5,$AA, $00,$00, $A0,$15,$AA, $A0,$01,$A0, $A4,$AA
	.byte $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A6,$AA
	.byte $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end14_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00
	.byte $A0,$16,$AA, $0A, $AF,$AA, $00,$00, $A0,$15,$AA, $A3,$00, $0A
	.byte $AC,$AA, $0A, $00,$00, $A0,$14,$AA, $0A, $A4,$00, $AC,$AA
	.byte $A3,$00, $A0,$14,$AA, $00,$00, $13, $00, $1A, $9A,$9A
	.byte $AB,$1A, $10,$10, $A0,$13,$AA, $A3,$00, $11, $00, $A0,$01,$AA
	.byte $99, $BB, $AB,$AA, $00,$00, $A0,$13,$AA, $A0,$01,$A0, $00,$00
	.byte $A0,$01,$AA, $A0,$02,$A0, $A0,$01,$AA, $0B, $0A, $BA, $A9,$AA
	.byte $00,$00, $A0,$14,$AA, $A0,$01,$A0, $00, $A4,$AA, $BB, $00
	.byte $44,$44, $FF, $CA, $77, $A5,$AA, $00,$00, $A0,$15,$AA
	.byte $A0,$01,$A0, $A4,$AA, $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC
	.byte $A0,$01,$A7, $A6,$AA, $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end15_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$13,$AA, $A3,$0A
	.byte $A0,$10,$AA, $00,$00, $A0,$11,$AA, $0A, $A4,$00, $0A, $AF,$AA
	.byte $00,$00, $A0,$11,$AA, $A6,$00, $AF,$AA, $00,$00, $A0,$11,$AA, $A3,$00
	.byte $30, $00, $0A, $AF,$AA, $00,$00, $A0,$11,$AA, $A3,$00
	.byte $33, $11, $00, $1A,$1A, $9A,$9A, $AB,$1A, $10,$10
	.byte $A0,$11,$AA, $A3,$00, $13, $11, $A3,$AA, $99, $BB
	.byte $AB,$AA, $00,$00, $A0,$11,$AA, $00,$00, $A0,$01,$A0, $A0,$01,$A1, $A0,$01,$A0
	.byte $A4,$AA, $0B, $0A, $BA, $A9,$AA, $00,$00, $A0,$12,$AA
	.byte $A0,$01,$A0, $00, $A6,$AA, $BB, $00, $44,$44, $FF
	.byte $CA, $77, $A5,$AA, $00,$00, $A0,$13,$AA, $A0,$01,$A0, $A6,$AA
	.byte $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A6,$AA
	.byte $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end16_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$10,$AA, $0A
	.byte $A0,$15,$AA, $00,$00, $AF,$AA, $A3,$00, $A0,$14,$AA, $00,$00, $AE,$AA
	.byte $0A, $A4,$00, $A0,$13,$AA, $00,$00, $AD,$AA, $A4,$00, $A0,$02,$A0
	.byte $A0,$13,$AA, $00,$00, $AC,$AA, $A3,$00, $13, $00, $A8,$1A
	.byte $9A,$9A, $AB,$1A, $10,$10, $AC,$AA, $00,$00, $03, $A0,$01,$A1
	.byte $A0,$01,$A0, $A8,$AA, $99, $BB, $AB,$AA, $00,$00, $AD,$AA
	.byte $A0,$01,$A0, $00, $0A, $AA,$AA, $0B, $0A, $BA
	.byte $A9,$AA, $00,$00, $A0,$1A,$AA, $BB, $00, $44,$44, $FF
	.byte $CA, $77, $A5,$AA, $00,$00, $A0,$1A,$AA, $A0,$02,$AB, $A0,$01,$AF
	.byte $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A6,$AA, $A0,$01,$A0, $A0,$C8,$AA
	.byte $A1
l1end17_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00
	.byte $AB,$AA, $0A,$0A, $A0,$01,$AA, $0A,$0A, $A0,$16,$AA, $00,$00, $AA,$AA
	.byte $A6,$00, $0A, $A0,$15,$AA, $00,$00, $AA,$AA, $A0,$01,$A0, $A6,$00
	.byte $A0,$15,$AA, $00,$00, $A0,$02,$AA, $A9,$1A, $00, $1A,$1A, $10
	.byte $1A, $00, $A8,$1A, $9A,$9A, $1A,$1A, $A9,$AA, $00,$00
	.byte $AB,$AA, $A0,$01,$A0, $A0,$02,$AA, $A0,$01,$A0, $0A, $A0,$01,$A0, $A8,$AA
	.byte $99, $BB, $AB,$AA, $00,$00, $A0,$1A,$AA, $0B, $0A
	.byte $BA, $A9,$AA, $00,$00, $A0,$1A,$AA, $BB, $00, $44,$44
	.byte $FF, $CA, $77, $A5,$AA, $00,$00, $A0,$1A,$AA, $A0,$02,$AB
	.byte $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A5,$AA, $A0,$02,$A0
	.byte $A0,$C8,$AA
	.byte $A1
l1end18_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00
	.byte $A0,$26,$AA, $00,$00, $A9,$AA, $00, $0A, $A0,$1B,$AA, $00,$00
	.byte $A8,$AA, $A4,$00, $A3,$0A, $A0,$17,$AA, $00,$00, $A7,$1A, $10,$10
	.byte $1A, $10,$10, $A3,$00, $11, $1A, $A8,$AA, $9A,$9A
	.byte $AA,$AA, $A3,$00, $AC,$AA, $00,$00, $A0,$01,$A0, $A0,$01,$A1, $A9,$AA
	.byte $99, $BB, $AB,$AA, $00,$00, $AC,$AA, $00, $AD,$AA
	.byte $0B, $0A, $BA, $A9,$AA, $00,$00, $AC,$AA, $A0,$01,$A0
	.byte $AD,$AA, $BB, $00, $44,$44, $FF, $CA, $77
	.byte $A5,$AA, $00,$00, $A0,$1A,$AA, $A0,$02,$AB, $A0,$01,$AF, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A5,$AA, $A0,$02,$A0, $A0,$C8,$AA
	.byte $A1
l1end19_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$68,$AA, $0A, $A0,$25,$AA, $0A, $00,$00, $A0,$25,$AA
	.byte $00,$00, $0A, $A0,$25,$AA, $A3,$00, $A0,$25,$AA, $A3,$00, $A0,$24,$AA
	.byte $0A, $20, $00,$00, $A0,$19,$AA, $9A,$9A, $A9,$AA, $A4,$00
	.byte $A0,$19,$AA, $99, $BB, $AA,$AA, $A3,$00, $A0,$1A,$AA, $0B
	.byte $0A, $BA, $A8,$AA, $A3,$00, $A0,$1A,$AA, $BB, $00
	.byte $44,$44, $FF, $CA, $77, $A4,$AA, $A3,$00, $A0,$1A,$AA
	.byte $A3,$AB, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A4,$AA, $A3,$A0
	.byte $A0,$C8,$AA
	.byte $A1
l1end20_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8D,$AA, $0A,$0A, $00, $A0,$25,$AA, $A3,$00, $A0,$25,$AA
	.byte $A0,$01,$A0, $00,$00, $A0,$26,$AA, $20, $00, $A0,$25,$AA, $0A
	.byte $02, $00, $A0,$1A,$AA, $9A,$9A, $A9,$AA, $A3,$00, $A0,$1A,$AA
	.byte $99, $BB, $AA,$AA, $00,$00, $A0,$1B,$AA, $0B, $0A
	.byte $BA, $A8,$AA, $00,$00, $A0,$1B,$AA, $BB, $00, $44,$44
	.byte $FF, $CA, $77, $A4,$AA, $A3,$00, $A0,$1A,$AA, $A3,$AB
	.byte $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC, $A0,$01,$A7, $A4,$AA, $A3,$A0, $A0,$C8,$AA
	.byte $A1
l1end21_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8D,$AA, $0A,$0A, $00, $A0,$25,$AA, $A3,$00, $A0,$25,$AA
	.byte $A0,$01,$A0, $00,$00, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00, $A0,$1A,$AA
	.byte $9A,$9A, $A9,$AA, $A3,$00, $A0,$1A,$AA, $99, $BB, $AA,$AA
	.byte $00,$00, $A0,$1B,$AA, $0B, $0A, $BA, $A8,$AA, $00,$00
	.byte $A0,$1B,$AA, $BB, $00, $44,$44, $FF, $CA, $77
	.byte $A4,$AA, $00,$00, $A0,$1B,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC
	.byte $A0,$01,$A7, $A4,$AA, $A0,$02,$A0, $A0,$C9,$AA
	.byte $A1
l1end22_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8D,$AA, $0A,$0A, $00, $A0,$24,$AA, $A3,$00, $A0,$25,$AA
	.byte $A0,$01,$A0, $00,$00, $A0,$26,$AA, $00,$00, $A0,$25,$AA, $0A, $00,$00
	.byte $A0,$1B,$AA, $9A,$9A, $A8,$AA, $A3,$00, $A0,$1B,$AA, $99, $BB
	.byte $A9,$AA, $00,$00, $A0,$1C,$AA, $0B, $0A, $BA, $A7,$AA
	.byte $00,$00, $A0,$1C,$AA, $BB, $00, $44,$44, $FF, $CA
	.byte $77, $A3,$AA, $A3,$00, $A0,$1B,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A3,$AA, $A3,$A0, $A0,$C9,$AA
	.byte $A1
l1end23_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8C,$AA, $0A,$0A, $00, $A0,$24,$AA, $A3,$00, $A0,$25,$AA
	.byte $A0,$01,$A0, $00,$00, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00, $A0,$1C,$AA
	.byte $9A,$9A, $A8,$AA, $00,$00, $A0,$1C,$AA, $99, $BB, $A8,$AA
	.byte $00,$00, $A0,$1D,$AA, $0B, $0A, $BA, $A6,$AA, $00,$00
	.byte $0A, $A0,$1C,$AA, $BB, $00, $44,$44, $FF, $CA
	.byte $77, $A0,$02,$AA, $A3,$00, $A0,$1C,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A0,$02,$AA, $A3,$A0, $A0,$CA,$AA
	.byte $A1
l1end24_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8C,$AA, $0A,$0A, $00, $A0,$24,$AA, $A3,$00, $A0,$25,$AA
	.byte $A0,$01,$A0, $00,$00, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $00,$00, $A0,$1C,$AA
	.byte $9A,$9A, $A7,$AA, $A3,$00, $A0,$1C,$AA, $99, $BB, $A8,$AA
	.byte $00,$00, $A0,$1D,$AA, $0B, $0A, $BA, $A6,$AA, $00,$00
	.byte $0A, $A0,$1C,$AA, $BB, $00, $44,$44, $FF, $CA
	.byte $77, $A0,$02,$AA, $A3,$00, $A0,$1C,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A0,$02,$AA, $A3,$A0, $A0,$CA,$AA
	.byte $A1
l1end25_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$25,$AA, $A0,$01,$A0, $A3,$00, $A0,$25,$AA, $A3,$00, $A0,$24,$AA, $A4,$00
	.byte $A0,$1C,$AA, $9A,$9A, $A7,$AA, $A3,$00, $A0,$1C,$AA, $99, $BB
	.byte $A7,$AA, $A3,$00, $A0,$1D,$AA, $0B, $0A, $BA, $A5,$AA
	.byte $A3,$00, $A0,$1D,$AA, $BB, $00, $44,$44, $FF, $CA
	.byte $77, $A0,$01,$AA, $A3,$00, $A0,$1D,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A0,$01,$AA, $A3,$A0, $A0,$CB,$AA
	.byte $A1
l1end26_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$25,$AA, $A3,$00, $A0,$26,$AA, $00,$00, $A0,$25,$AA, $A3,$00, $A0,$1D,$AA
	.byte $9A,$9A, $A7,$AA, $00,$00, $A0,$1D,$AA, $99, $BB, $A7,$AA
	.byte $00,$00, $A0,$1E,$AA, $0B, $0A, $BA, $A5,$AA, $00,$00
	.byte $A0,$1E,$AA, $BB, $00, $44,$44, $FF, $CA, $77
	.byte $A0,$01,$AA, $A3,$00, $A0,$1D,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF, $A0,$01,$AC
	.byte $A0,$01,$A7, $A0,$01,$AA, $A3,$A0, $A0,$CB,$AA
	.byte $A1
l1end27_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$25,$AA, $A3,$00, $A0,$26,$AA, $00,$00, $A0,$25,$AA, $A3,$00, $A0,$1E,$AA
	.byte $99, $B9, $A6,$AA, $00,$00, $A0,$1E,$AA, $B9, $A0,$01,$AB
	.byte $A6,$AA, $00,$00, $A0,$1E,$AA, $00, $0B, $4A, $A5,$AA
	.byte $00,$00, $A0,$1E,$AA, $BB, $00, $44,$44, $FF, $CA
	.byte $77, $A0,$01,$AA, $A3,$00, $A0,$1D,$AA, $A3,$AB, $A0,$01,$A4, $A0,$01,$AF
	.byte $A0,$01,$AC, $A0,$01,$A7, $A0,$01,$AA, $A3,$A0, $A0,$CB,$AA
	.byte $A1
l1end28_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$25,$AA, $A3,$00, $A0,$26,$AA, $00,$00, $A0,$20,$AA, $99, $B9
	.byte $A3,$AA, $A3,$00, $A0,$20,$AA, $B9, $A0,$01,$AB, $A4,$AA, $00,$00
	.byte $A0,$1F,$AA, $B0, $00, $A5,$AA, $00,$00, $A0,$1F,$AA, $BB
	.byte $40, $A5,$AA, $00,$00, $A0,$1F,$AA, $BB, $44, $C4
	.byte $A4,$AA, $A3,$00, $A0,$1F,$AA, $A0,$02,$AF, $A0,$01,$A7, $A3,$AA, $A3,$A0
	.byte $A0,$CB,$AA
	.byte $A1
l1end29_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$25,$AA, $A3,$00, $A0,$21,$AA, $9A,$9A, $A3,$AA, $00,$00, $A0,$21,$AA
	.byte $99, $BB, $A0,$02,$AA, $A3,$00, $A0,$21,$AA, $0B, $A4,$AA
	.byte $00,$00, $A0,$20,$AA, $0A, $BB, $A4,$AA, $00,$00, $A0,$20,$AA
	.byte $40, $BB, $BA, $A3,$AA, $00,$00, $A0,$20,$AA, $44
	.byte $C4, $A4,$AA, $A3,$00, $A0,$1F,$AA, $A0,$02,$AF, $A0,$01,$A7, $A3,$AA
	.byte $A3,$A0, $A0,$CB,$AA
	.byte $A1
l1end30_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$25,$AA, $A3,$00, $A0,$20,$AA, $99, $B9, $A4,$AA, $00,$00
	.byte $A0,$20,$AA, $B9, $A0,$01,$AB, $A3,$AA, $A3,$00, $A0,$20,$AA, $B0
	.byte $A5,$AA, $00,$00, $A0,$20,$AA, $BB, $A0,$01,$AB, $A4,$AA, $00,$00
	.byte $A0,$20,$AA, $4B, $A5,$AA, $00,$00, $A0,$20,$AA, $44, $C4
	.byte $A4,$AA, $A3,$00, $A0,$1F,$AA, $A0,$02,$AF, $A0,$01,$A7, $A3,$AA, $A3,$A0
	.byte $A0,$CB,$AA
	.byte $A1
l1end31_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$20,$AA, $9A,$9A, $A3,$AA, $A3,$00, $A0,$20,$AA, $99, $BB
	.byte $A4,$AA, $00,$00, $A0,$20,$AA, $0B, $A4,$AA, $A3,$00, $A0,$20,$AA
	.byte $BB, $BA, $A4,$AA, $00,$00, $A0,$20,$AA, $BB, $A0,$01,$AB
	.byte $A4,$AA, $00,$00, $A0,$20,$AA, $44, $A5,$AA, $00,$00, $A0,$20,$AA
	.byte $C4, $44, $A4,$AA, $A3,$00, $A0,$1F,$AA, $A0,$01,$AC, $A0,$02,$AF
	.byte $A3,$AA, $A3,$A0, $A0,$CB,$AA
	.byte $A1
l1end32_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$20,$AA, $9A,$9A, $A3,$AA, $A3,$00, $A0,$20,$AA, $99, $BB
	.byte $A4,$AA, $00,$00, $A0,$20,$AA, $0B, $A0,$01,$AA, $BA, $A0,$02,$AA
	.byte $A3,$00, $A0,$20,$AA, $BB, $A0,$01,$A0, $A4,$AA, $00,$00, $A0,$20,$AA
	.byte $BB, $A5,$AA, $00,$00, $A0,$20,$AA, $44, $A5,$AA, $00,$00
	.byte $A0,$20,$AA, $C4, $44, $A4,$AA, $A3,$00, $A0,$1F,$AA, $A0,$01,$AC
	.byte $A0,$02,$AF, $A3,$AA, $A3,$A0, $A0,$CB,$AA
	.byte $A1
l1end33_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$8B,$AA, $0A, $A0,$01,$AA, $00, $A0,$24,$AA, $A3,$00
	.byte $A0,$20,$AA, $9A,$9A, $A3,$AA, $A3,$00, $A0,$20,$AA, $99, $BB
	.byte $A4,$AA, $00,$00, $A0,$20,$AA, $0B, $A0,$01,$AA, $BB, $A0,$02,$AA
	.byte $A3,$00, $A0,$20,$AA, $BB, $A0,$01,$A0, $A4,$AA, $00,$00, $A0,$20,$AA
	.byte $BB, $A5,$AA, $00,$00, $A0,$20,$AA, $44, $A5,$AA, $00,$00
	.byte $A0,$20,$AA, $C4, $44, $A4,$AA, $A3,$00, $A0,$1F,$AA, $A0,$01,$AC
	.byte $A0,$02,$AF, $A3,$AA, $A3,$A0, $A0,$CB,$AA
	.byte $A1
