5 HOME
10 PRINT " STARGATE -- A 128 BYTE APPLE II INTRO"
15 PRINT "           BY DEATER / DSR"
17 PRINT:PRINT"    *** WARNING! FLASHING LIGHTS ***"
18 PRINT
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN STARGATE'"
30 GET A$
35 PRINT
40 PRINT "]BRUN STARGATE"
50 PRINT CHR$(4)"BRUN STARGATE"
