5 HOME
10 PRINT "  COSMIC_FISH -- 256B FOR OUTLINE 2024"
15 PRINT "           BY DEATER / DSR"
20 PRINT CHR$(4)"CATALOG"
22 PRINT:PRINT "PRESS Q TO RUN VERSION W/O SOUND"
25 PRINT:PRINT "ANY OTHER KEY TO 'BRUN COSMIC_FISH'"
30 GET A$
32 IF A$="Q" OR A$="q" THEN PRINT:PRINT CHR$(4)"BRUN COSMIC_FISH_QUIET"
35 PRINT
40 PRINT CHR$(4)"BRUN COSMIC_FISH"
