all:
	cd 3d && make
	cd dhgr && make
	cd dhgr_viewer && make
	cd dgr && make
	cd galaxy && make
	cd gr && make
#	cd gr_viewer && make
	cd hgr && make
#	cd hgr_viewer && make

clean:
	cd 3d && make clean
	cd dhgr && make clean
	cd dhgr_viewer && make clean
	cd dgr && make clean
	cd galaxy && make clean
	cd gr && make clean
	cd gr_viewer && make clean
	cd hgr && make clean
	cd hgr_viewer && make clean
	rm -f *~
