
PNG2RLE = ../../../../utils/gr-utils/png2rle
PNG2GR = ../../../../utils/gr-utils/png2gr
PNG2HGR = ../../../../utils/hgr-utils/png2hgr
LZSA = ~/research/lzsa/lzsa/lzsa
B2D = ../../../../utils/bmp2dhr/b2d

all:	rocket.inc


rocket.inc:	\
	ootw_uboot_bg.lzsa \
	ootw_uboot_flash1.lzsa \
	ootw_uboot_flash2.lzsa \
	swim01.lzsa swim02.lzsa swim03.lzsa \
	swim04.lzsa swim05.lzsa swim06.lzsa \
	another_pool.lzsa \
	ashore01.lzsa ashore02.lzsa ashore03.lzsa ashore04.lzsa \
	ashore05.lzsa ashore06.lzsa ashore07.lzsa ashore08.lzsa \
	ashore09.lzsa ashore10.lzsa ashore11.lzsa ashore12.lzsa \
	ashore13.lzsa ashore14.lzsa ashore15.lzsa ashore16.lzsa \
	ashore17.lzsa ashore18.lzsa ashore19.lzsa ashore20.lzsa \
	ashore21.lzsa ashore22.lzsa ashore23.lzsa ashore24.lzsa \
	clock_n.lzsa tree5_n.lzsa tree4_n.lzsa tree2_n.lzsa tree1_n.lzsa \
	pool_n.lzsa step_top_n.lzsa pad_n.lzsa spaceship_path_w.lzsa \
	spaceship_far_n.lzsa spaceship_switch_n.lzsa spaceship_door_n.lzsa \
	spaceship_door_open.lzsa \
	takeoff01.lzsa takeoff02.lzsa takeoff03.lzsa takeoff04.lzsa \
	takeoff05.lzsa takeoff06.lzsa takeoff07.lzsa takeoff08.lzsa \
	takeoff09.lzsa takeoff10.lzsa takeoff11.lzsa takeoff12.lzsa
	echo "ootw_uboot_bg_lzsa: .incbin \"ootw_uboot_bg.lzsa\"" > rocket.inc
	echo "ootw_uboot_flash1_lzsa: .incbin \"ootw_uboot_flash1.lzsa\"" >> rocket.inc
	echo "ootw_uboot_flash2_lzsa: .incbin \"ootw_uboot_flash2.lzsa\"" >> rocket.inc
	echo "swim01_lzsa: .incbin \"swim01.lzsa\"" >> rocket.inc
	echo "swim02_lzsa: .incbin \"swim02.lzsa\"" >> rocket.inc
	echo "swim03_lzsa: .incbin \"swim03.lzsa\"" >> rocket.inc
	echo "swim04_lzsa: .incbin \"swim04.lzsa\"" >> rocket.inc
	echo "swim05_lzsa: .incbin \"swim05.lzsa\"" >> rocket.inc
	echo "swim06_lzsa: .incbin \"swim06.lzsa\"" >> rocket.inc
	echo "another_pool_lzsa: .incbin \"another_pool.lzsa\"" >> rocket.inc
	echo "ashore01_lzsa: .incbin \"ashore01.lzsa\"" >> rocket.inc
	echo "ashore02_lzsa: .incbin \"ashore02.lzsa\"" >> rocket.inc
	echo "ashore03_lzsa: .incbin \"ashore03.lzsa\"" >> rocket.inc
	echo "ashore04_lzsa: .incbin \"ashore04.lzsa\"" >> rocket.inc
	echo "ashore05_lzsa: .incbin \"ashore05.lzsa\"" >> rocket.inc
	echo "ashore06_lzsa: .incbin \"ashore06.lzsa\"" >> rocket.inc
	echo "ashore07_lzsa: .incbin \"ashore07.lzsa\"" >> rocket.inc
	echo "ashore08_lzsa: .incbin \"ashore08.lzsa\"" >> rocket.inc
	echo "ashore09_lzsa: .incbin \"ashore09.lzsa\"" >> rocket.inc
	echo "ashore10_lzsa: .incbin \"ashore10.lzsa\"" >> rocket.inc
	echo "ashore11_lzsa: .incbin \"ashore11.lzsa\"" >> rocket.inc
	echo "ashore12_lzsa: .incbin \"ashore12.lzsa\"" >> rocket.inc
	echo "ashore13_lzsa: .incbin \"ashore13.lzsa\"" >> rocket.inc
	echo "ashore14_lzsa: .incbin \"ashore14.lzsa\"" >> rocket.inc
	echo "ashore15_lzsa: .incbin \"ashore15.lzsa\"" >> rocket.inc
	echo "ashore16_lzsa: .incbin \"ashore16.lzsa\"" >> rocket.inc
	echo "ashore17_lzsa: .incbin \"ashore17.lzsa\"" >> rocket.inc
	echo "ashore18_lzsa: .incbin \"ashore18.lzsa\"" >> rocket.inc
	echo "ashore19_lzsa: .incbin \"ashore19.lzsa\"" >> rocket.inc
	echo "ashore20_lzsa: .incbin \"ashore20.lzsa\"" >> rocket.inc
	echo "ashore21_lzsa: .incbin \"ashore21.lzsa\"" >> rocket.inc
	echo "ashore22_lzsa: .incbin \"ashore22.lzsa\"" >> rocket.inc
	echo "ashore23_lzsa: .incbin \"ashore23.lzsa\"" >> rocket.inc
	echo "ashore24_lzsa: .incbin \"ashore24.lzsa\"" >> rocket.inc
	echo "clock_n_lzsa: .incbin \"clock_n.lzsa\"" >> rocket.inc
	echo "tree5_n_lzsa: .incbin \"tree5_n.lzsa\"" >> rocket.inc
	echo "tree4_n_lzsa: .incbin \"tree4_n.lzsa\"" >> rocket.inc
	echo "tree2_n_lzsa: .incbin \"tree2_n.lzsa\"" >> rocket.inc
	echo "tree1_n_lzsa: .incbin \"tree1_n.lzsa\"" >> rocket.inc
	echo "pool_n_lzsa: .incbin \"pool_n.lzsa\"" >> rocket.inc
	echo "step_top_n_lzsa: .incbin \"step_top_n.lzsa\"" >> rocket.inc
	echo "pad_n_lzsa: .incbin \"pad_n.lzsa\"" >> rocket.inc
	echo "spaceship_path_w_lzsa: .incbin \"spaceship_path_w.lzsa\"" >> rocket.inc
	echo "spaceship_far_n_lzsa: .incbin \"spaceship_far_n.lzsa\"" >> rocket.inc
	echo "spaceship_switch_n_lzsa: .incbin \"spaceship_switch_n.lzsa\"" >> rocket.inc
	echo "spaceship_door_n_lzsa: .incbin \"spaceship_door_n.lzsa\"" >> rocket.inc
	echo "spaceship_door_open_lzsa: .incbin \"spaceship_door_open.lzsa\"" >> rocket.inc
	echo "takeoff01_lzsa: .incbin \"takeoff01.lzsa\"" >> rocket.inc
	echo "takeoff02_lzsa: .incbin \"takeoff02.lzsa\"" >> rocket.inc
	echo "takeoff03_lzsa: .incbin \"takeoff03.lzsa\"" >> rocket.inc
	echo "takeoff04_lzsa: .incbin \"takeoff04.lzsa\"" >> rocket.inc
	echo "takeoff05_lzsa: .incbin \"takeoff05.lzsa\"" >> rocket.inc
	echo "takeoff06_lzsa: .incbin \"takeoff06.lzsa\"" >> rocket.inc
	echo "takeoff07_lzsa: .incbin \"takeoff07.lzsa\"" >> rocket.inc
	echo "takeoff08_lzsa: .incbin \"takeoff08.lzsa\"" >> rocket.inc
	echo "takeoff09_lzsa: .incbin \"takeoff09.lzsa\"" >> rocket.inc
	echo "takeoff10_lzsa: .incbin \"takeoff10.lzsa\"" >> rocket.inc
	echo "takeoff11_lzsa: .incbin \"takeoff11.lzsa\"" >> rocket.inc
	echo "takeoff12_lzsa: .incbin \"takeoff12.lzsa\"" >> rocket.inc


###

%.gr:	%.png
	$(PNG2GR) $< $@

%.lzsa:	%.gr
	$(LZSA) -r -f2 $< $@

###


clean:	
	rm -f *~ rocket.inc *.lzsa *.gr *.hgr

