;; Things that normally would go in the zero page


AY_REGISTERS:
A_FINE_TONE:	.byte $00
A_COARSE_TONE:	.byte $00
B_FINE_TONE:	.byte $00
B_COARSE_TONE:	.byte $00
C_FINE_TONE:	.byte $00
C_COARSE_TONE:	.byte $00
NOISE:		.byte $00
ENABLE:
PT3_MIXER_VAL:	.byte $00
A_VOLUME:	.byte $00
B_VOLUME:	.byte $00
C_VOLUME:	.byte $00
ENVELOPE_FINE:	.byte $00
ENVELOPE_COARSE:.byte $00
ENVELOPE_SHAPE:	.byte $00

LOOP:		.byte $00
MB_VALUE:	.byte $00
DONE_PLAYING:	.byte $00
DONE_SONG:	.byte $00
PT3_TEMP:	.byte $00


