DHGR_SPRITE = ../../../utils/hgr-utils/dhgr_make_sprite

all:	numbers.inc \
	ball_sprites.inc


numbers.inc:	a2_nine.png
	$(DHGR_SPRITE) -s -l one a2_nine.png 14 7  41 28 > numbers.inc

ball_sprites.inc:	ball_sprites2.png ball_sprites.png
	$(DHGR_SPRITE) -s -l erase ball_sprites2.png 14 13  41  27 > ball_sprites.inc
	$(DHGR_SPRITE) -s -l erase_hat ball_sprites.png 98  20 111  69 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l erase_hat2 ball_sprites.png 84  69 125  80 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l text0 ball_sprites.png 0 153 62 161 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l text1 ball_sprites.png 0 167 188 175 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l text2 ball_sprites.png 0 181 20 189 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red0 ball_sprites2.png 14  28  41  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red1 ball_sprites2.png 14  43  41  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red2 ball_sprites2.png 14  58  41  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red3 ball_sprites2.png 14  73  41  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red4 ball_sprites2.png 14  88  41 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red5 ball_sprites2.png 14 103  41 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l red6 ball_sprites2.png 14 118  41 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange0 ball_sprites2.png 42  28  69  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange1 ball_sprites2.png 42  43  69  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange2 ball_sprites2.png 42  58  69  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange3 ball_sprites2.png 42  73  69  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange4 ball_sprites2.png 42  88  69 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange5 ball_sprites2.png 42 103  69 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l orange6 ball_sprites2.png 42 118  69 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow0 ball_sprites2.png 70  28  97  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow1 ball_sprites2.png 70  43  97  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow2 ball_sprites2.png 70  58  97  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow3 ball_sprites2.png 70  73  97  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow4 ball_sprites2.png 70  88  97 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow5 ball_sprites2.png 70 103  97 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l yellow6 ball_sprites2.png 70 118  97 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green0 ball_sprites2.png 98  28 125  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green1 ball_sprites2.png 98  43 125  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green2 ball_sprites2.png 98  58 125  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green3 ball_sprites2.png 98  73 125  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green4 ball_sprites2.png 98  88 125 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green5 ball_sprites2.png 98 103 125 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l green6 ball_sprites2.png 98 118 125 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue0 ball_sprites2.png 126  28 153  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue1 ball_sprites2.png 126  43 153  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue2 ball_sprites2.png 126  58 153  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue3 ball_sprites2.png 126  73 153  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue4 ball_sprites2.png 126  88 153 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue5 ball_sprites2.png 126 103 153 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l blue6 ball_sprites2.png 126 118 153 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple0 ball_sprites2.png 154  28 181  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple1 ball_sprites2.png 154  43 181  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple2 ball_sprites2.png 154  58 181  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple3 ball_sprites2.png 154  73 181  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple4 ball_sprites2.png 154  88 181 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple5 ball_sprites2.png 154 103 181 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l purple6 ball_sprites2.png 154 118 181 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey0 ball_sprites2.png 182  28 209  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey1 ball_sprites2.png 182  43 209  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey2 ball_sprites2.png 182  58 209  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey3 ball_sprites2.png 182  73 209  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey4 ball_sprites2.png 182  88 209 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey5 ball_sprites2.png 182 103 209 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l grey6 ball_sprites2.png 182 118 209 132 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown0 ball_sprites2.png 210  28 237  42 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown1 ball_sprites2.png 210  43 237  57 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown2 ball_sprites2.png 210  58 237  72 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown3 ball_sprites2.png 210  73 237  87 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown4 ball_sprites2.png 210  88 237 102 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown5 ball_sprites2.png 210 103 237 117 >> ball_sprites.inc
	$(DHGR_SPRITE) -s -l brown6 ball_sprites2.png 210 118 237 132 >> ball_sprites.inc




clean:
	rm -f *~ numbers.inc ball_sprites.inc

