HGR_SPRITE = ../../../../utils/hgr-utils/hgr_make_sprite

all:	haystack_gone_sprite.inc

# 189 49 244 96
haystack_gone_sprite.inc:	haystack_gone.png
	$(HGR_SPRITE) -s -l hg_sprite0 haystack_gone.png 189  49 244  73 > haystack_gone_sprite.inc

clean:
	rm -f *~ haystack_gone_sprite.inc
