5 HOME
10 PRINT "       -= SAWBLADE -- 32 BYTES =-"
12 PRINT "         ----------------------
15 PRINT "             LOVEBYTE  2024"
17 PRINT "            BY: DEATER / DSR"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN SAWBLADE'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN SAWBLADE"
