   5  HOME
  10  PRINT "VMW PRODUCTIONS 2018 CHRISTMAS DEMO V1.1"
  20  PRINT
  30  PRINT "    ONLY 22 YEARS SINCE THE LAST ONE"
  40  PRINT:PRINT
  50  PRINT "* CODE:       DEATER"
  60  PRINT "* LZ4/DISK:   QKUMBA"
  70  PRINT "* MUSIC:      F. MENDELSSOHN"
  80  PRINT "* WREATH PIC: KITTELENDAN"
  90  PRINT:PRINT "   TAKES 30 SECONDS TO LOAD FROM DISK"
 100  PRINT:PRINT "          PRESS M TO MUTE MUSIC"
 105  PRINT  CHR$ (4)"BRUN XMAS2018"
