   5  HOME
  10  PRINT "   VMW PRODUCTIONS 2018 CHRISTMAS DEMO"
  20  PRINT
  30  PRINT "    ONLY 22 YEARS SINCE THE LAST ONE"
  40  PRINT:PRINT
  50  PRINT "* CODE:     DEATER"
  60  PRINT "* LZ4:      QKUMBA"
  70  PRINT "* MUSIC:    F. MENDELSSOHN"
  80  PRINT "* PICTURES: KITTELENDAN"
 100  PRINT  CHR$ (4)"BRUN XMAS2018"
