wide_flame0:
	.byte $2,$3
	.byte $dd,$dd
	.byte $dd,$dd
	.byte $dd,$dd
	; 00=0 0X=0 X0=0 XX=6 
	; = 33 + Y*(52)+ [30A + 64B + 69C + 54D]-Y
	; = 33 + 3*52 + 30*0 + 64*0 + 69*0 + 54*6 - 3
	; = 510

wide_flame1:
	.byte $2,$3
	.byte $dd,$dd
	.byte $dd,$dd
	.byte $dd,$dd
	; 00=0 0X=0 X0=0 XX=6 
	; = 33 + Y*(52)+ [30A + 64B + 69C + 54D]-Y
	; = 33 + 3*52 + 30*0 + 64*0 + 69*0 + 54*6 - 3
	; = 510

wide_flame2:
	.byte $2,$3
	.byte $dd,$dd
	.byte $dd,$dd
	.byte $dd,$dd
	; 00=0 0X=0 X0=0 XX=6 
	; = 33 + Y*(52)+ [30A + 64B + 69C + 54D]-Y
	; = 33 + 3*52 + 30*0 + 64*0 + 69*0 + 54*6 - 3
	; = 510

wide_flame3:
	.byte $2,$3
	.byte $dd,$dd
	.byte $dd,$dd
	.byte $dd,$dd
	; 00=0 0X=0 X0=0 XX=6 
	; = 33 + Y*(52)+ [30A + 64B + 69C + 54D]-Y
	; = 33 + 3*52 + 30*0 + 64*0 + 69*0 + 54*6 - 3
	; = 510


