all:
	cd duke && make
	cd glados3.3 && make
	cd ksp && make
	cd mist && make
	cd monkey && make
	cd ootw && make
	cd space_bars && make
	cd tb_6502 && make
	cd tfv && make

clean:
	cd duke && make clean
	cd glados3.3 && make clean
	cd ksp && make clean
	cd mist && make clean
	cd monkey && make clean
	cd ootw && make clean
	cd space_bars && make clean
	cd tb_6502 && make clean
	cd tfv && make clean
	rm -f *~
