include ../../../../Makefile.inc

ZX02 = ~/research/6502_compression/zx02.git/build/zx02 -f
PNG_TO_HGR = ../../../../utils/hgr-utils/png2hgr

all:	chair_graphics.inc

chair_graphics.inc:	\
	chair_n.hgr.zx02
	echo "chair_n_zx02: .incbin \"chair_n.hgr.zx02\"" > chair_graphics.inc


####

%.hgr: %.png
	$(PNG_TO_HGR) $< > $@

%.hgr.zx02: %.hgr
	$(ZX02) -f $< $@

####

clean:
	rm -f *~ *.o *.lst  *.zx02 *.hgr chair_graphics.inc

