5 HOME
10 PRINT " BLUE_FLAME -- A 1K BYTE APPLE II INTRO"
15 PRINT "         BY DEATER & MA2E / DSR"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN BF'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN BF"

