5 HOME
10 PRINT "  BUBBLE_BLOB -- 256B FOR OUTLINE 2024"
15 PRINT "           BY DEATER / DSR"
20 PRINT CHR$(4)"CATALOG"
22 PRINT:PRINT "PRESS Q TO RUN VERSION W/O SOUND"
25 PRINT:PRINT "ANY OTHER KEY TO 'BRUN BUBBLE_BLOB'"
30 GET A$
32 IF A$="Q" OR A$="q" THEN PRINT:PRINT CHR$(4)"BRUN BUBBLE_BLOB_QUIET"
35 PRINT
40 PRINT CHR$(4)"BRUN BUBBLE_BLOB"
