all:
	cd l1_caves && make
	cd l1_end && make
	cd l1_beast_end && make
	cd l1_pool && make
	cd l1_rope && make
	cd l1_underwater && make

clean:
	cd l1_caves && make clean
	cd l1_end && make clean
	cd l1_beast_end && make clean
	cd l1_pool && make clean
	cd l1_rope && make clean
	cd l1_underwater && make clean

