
HGR_SPRITE = ../../../../utils/hgr-utils/hgr_make_sprite

all:	keeper1_sprites.inc \
	keeper2_sprites.inc \
	other_sprites.inc

other_sprites.inc:	other_sprites.png
#	$(HGR_SPRITE) -s -l star0_sprite other_sprites.png  0 0  13 1 > other_sprites.inc
#	$(HGR_SPRITE) -s -l star1_sprite other_sprites.png 14 0  27 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l star2_sprite other_sprites.png 28 0  41 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l star3_sprite other_sprites.png 42 0  55 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l star4_sprite other_sprites.png 56 0  69 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l star5_sprite other_sprites.png 70 0  83 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l star6_sprite other_sprites.png 84 0  97 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l star7_sprite other_sprites.png 98 0 111 1 >> other_sprites.inc
#	$(HGR_SPRITE) -s -l book_sprite  other_sprites.png 14 140 48 184 >> other_sprites.inc
	$(HGR_SPRITE) -s -l demosplash_sprite other_sprites.png 14 8 34 25 > other_sprites.inc
#	$(HGR_SPRITE) -s -l falling_sprite other_sprites.png 70 140 90 155 >> other_sprites.inc
	$(HGR_SPRITE) -s -l vmw_sprite other_sprites.png 42 8 90 20 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal0_sprite other_sprites.png 14 35 27 46 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal1_sprite other_sprites.png 14 47 27 58 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal2_sprite other_sprites.png 14 59 27 71 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal3_sprite other_sprites.png 14 72 27 84 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal4_sprite other_sprites.png 14 85 27 94 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal5_sprite other_sprites.png 14 95 27 108 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal6_sprite other_sprites.png 14 109 27 122 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal7_sprite other_sprites.png 42 35 55 45 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal8_sprite other_sprites.png 42 46 55 55 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal9_sprite other_sprites.png 42 56 55 65 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal10_sprite other_sprites.png 42 66 55 76 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal11_sprite other_sprites.png 42 77 55 86 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal12_sprite other_sprites.png 42 87 55 98 >> other_sprites.inc
	$(HGR_SPRITE) -s -l animal13_sprite other_sprites.png 42 99 55 109 >> other_sprites.inc

keeper1_sprites.inc:	keeper1_sprites.png
	$(HGR_SPRITE) -s -l keeper_r0 keeper1_sprites.png  14 128  27 156 > keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r1 keeper1_sprites.png  42 128  62 156 >> keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r2 keeper1_sprites.png  70 128  90 156 >> keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r3 keeper1_sprites.png  98 128 118 156 >> keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r4 keeper1_sprites.png 126 128 146 156 >> keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r5 keeper1_sprites.png 154 128 174 156 >> keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r6 keeper1_sprites.png 182 128 202 156 >> keeper1_sprites.inc
	$(HGR_SPRITE) -s -l keeper_r7 keeper1_sprites.png 210 128 230 156 >> keeper1_sprites.inc

keeper2_sprites.inc:	keeper2_sprites.png
	$(HGR_SPRITE) -s -l keeper_l0 keeper2_sprites.png  14 128  34 156 > keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l1 keeper2_sprites.png  42 128  62 156 >> keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l2 keeper2_sprites.png  70 128  90 156 >> keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l3 keeper2_sprites.png  98 128 118 156 >> keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l4 keeper2_sprites.png 126 128 146 156 >> keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l5 keeper2_sprites.png 154 128 174 156 >> keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l6 keeper2_sprites.png 182 128 202 156 >> keeper2_sprites.inc
	$(HGR_SPRITE) -s -l keeper_l7 keeper2_sprites.png 210 128 230 156 >> keeper2_sprites.inc


clean:
	rm -f *~ *.inc


