   5  HOME
  10  PRINT "OOTW PROOF-OF-CONCEPT V1.0 BY DEATER"
  20  PRINT:PRINT
  30  PRINT "ORIGINAL BY ERIC CHAHI"
  40  PRINT "INSPIRED BY PAUL NICHOLAS PICO-8 VERSION" 
  50  PRINT
  60  PRINT "WASD OR ARROWS TO MOVE"
  70  PRINT "SPACEBAR FOR ACTION"
  80  PRINT:PRINT
  85  HTAB 10:PRINT "  ______"
  90  HTAB 10:PRINT "A \/\/\/ PRODUCTION"
  92  PRINT
  95  HTAB 12:PRINT "APPLE ][ FOREVER"
 100  PRINT  CHR$ (4)"BRUN OOTW"

