duke_sprite_stand_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$2b,$b7,$A7
	.byte $AA,$52,$52,$AA

duke_sprite_stand_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$b7,$2b,$AA
	.byte $AA,$52,$52,$AA

duke_sprite_walking_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$2b,$b7,$A7
	.byte $52,$A2,$A2,$5A

duke_sprite_walking_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$b7,$2b,$AA
	.byte $5A,$A2,$A2,$52

duke_sprite_jumping_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$2b,$b7,$A7
	.byte $55,$A2,$AA,$AA

duke_sprite_jumping_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$b7,$2b,$AA
	.byte $AA,$AA,$A2,$55

duke_sprite_falling_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$2b,$27,$A7
	.byte $5A,$A2,$52,$AA

duke_sprite_falling_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$27,$2b,$AA
	.byte $AA,$52,$A2,$5A

duke_sprite_shooting_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$b7,$A7,$AA
	.byte $AA,$52,$52,$AA

duke_sprite_shooting_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $AA,$A7,$b7,$AA
	.byte $AA,$52,$52,$AA

