duke_sprite_stand_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$6b,$b7,$A7
	.byte $AA,$56,$56,$AA

duke_sprite_stand_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$b7,$6b,$AA
	.byte $AA,$56,$56,$AA

duke_sprite_walking_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$6b,$b7,$A7
	.byte $56,$A6,$A6,$5A

duke_sprite_walking_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$b7,$6b,$AA
	.byte $5A,$A6,$A6,$56

duke_sprite_jumping_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$6b,$b7,$A7
	.byte $55,$A6,$AA,$AA

duke_sprite_jumping_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$b7,$6b,$AA
	.byte $AA,$AA,$A6,$55

duke_sprite_falling_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$6b,$67,$A7
	.byte $5A,$A6,$56,$AA

duke_sprite_falling_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $A7,$67,$6b,$AA
	.byte $AA,$56,$A6,$5A

duke_sprite_shooting_right:
	.byte 4,4
	.byte $AA,$dd,$bd,$AA
	.byte $AA,$3d,$Ab,$AA
	.byte $AA,$b7,$A7,$AA
	.byte $AA,$56,$56,$AA

duke_sprite_shooting_left:
	.byte 4,4
	.byte $AA,$bd,$dd,$AA
	.byte $AA,$Ab,$3d,$AA
	.byte $AA,$A7,$b7,$AA
	.byte $AA,$56,$56,$AA

