5 HOME
10 PRINT " XDRAW WAVE -- A 16 BYTE APPLE II INTRO"
15 PRINT "           BY DEATER / DSR"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN XDRAW_WAVE'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN XDRAW_WAVE"
