include ../../../../Makefile.inc

ZX02 = ~/research/6502_compression/zx02.git/build/zx02
PNG2GR = ../../../../utils/gr-utils/png2gr

all:	movie_maglev_ride.inc

movie_maglev_ride.inc:	\
	img096_bg.gr.zx02 \
	img114_bg.gr.zx02
#	img115_bg.gr.zx02 img116_bg.gr.zx02 \
#	img117_bg.gr.zx02 img118_bg.gr.zx02 img119_bg.gr.zx02 \
#	img120_bg.gr.zx02 img121_bg.gr.zx02 img122_bg.gr.zx02 \
#	img123_bg.gr.zx02 img124_bg.gr.zx02 img125_bg.gr.zx02 \
#	img126_bg.gr.zx02 img127_bg.gr.zx02 img128_bg.gr.zx02 \
#	img129_bg.gr.zx02 img130_bg.gr.zx02 img131_bg.gr.zx02 \
#	img132_bg.gr.zx02 img133_bg.gr.zx02 img134_bg.gr.zx02 \
#	img135_bg.gr.zx02 img136_bg.gr.zx02 img137_bg.gr.zx02 \
#	img138_bg.gr.zx02 img139_bg.gr.zx02 img140_bg.gr.zx02 \
#	img141_bg.gr.zx02 img142_bg.gr.zx02 img143_bg.gr.zx02 \
#	img144_bg.gr.zx02 img145_bg.gr.zx02 img146_bg.gr.zx02 \
#	img147_bg.gr.zx02 img148_bg.gr.zx02 img149_bg.gr.zx02 \
#	img150_bg.gr.zx02 img151_bg.gr.zx02 img152_bg.gr.zx02 \
#	img153_bg.gr.zx02 img154_bg.gr.zx02 img155_bg.gr.zx02 \
#	img156_bg.gr.zx02 img157_bg.gr.zx02 img158_bg.gr.zx02 \
#	img159_bg.gr.zx02 img160_bg.gr.zx02 img161_bg.gr.zx02 \
#	img162_bg.gr.zx02 img163_bg.gr.zx02 img164_bg.gr.zx02 \
#	img165_bg.gr.zx02 img166_bg.gr.zx02 img167_bg.gr.zx02 \
#	img168_bg.gr.zx02 img169_bg.gr.zx02 img170_bg.gr.zx02 \
#	img171_bg.gr.zx02 img172_bg.gr.zx02 img173_bg.gr.zx02 \
#	img174_bg.gr.zx02 img175_bg.gr.zx02 img176_bg.gr.zx02 \
#	img177_bg.gr.zx02 img178_bg.gr.zx02 img179_bg.gr.zx02 \
#	img180_bg.gr.zx02 img181_bg.gr.zx02 img182_bg.gr.zx02 \
#	img183_bg.gr.zx02 img184_bg.gr.zx02 img185_bg.gr.zx02 \
#	img186_bg.gr.zx02 img187_bg.gr.zx02 img188_bg.gr.zx02 \
#	img189_bg.gr.zx02 img190_bg.gr.zx02 img191_bg.gr.zx02 \
#	img192_bg.gr.zx02 img193_bg.gr.zx02 img194_bg.gr.zx02 \
#	img195_bg.gr.zx02 img196_bg.gr.zx02 img197_bg.gr.zx02 \
#	img198_bg.gr.zx02 img199_bg.gr.zx02 img200_bg.gr.zx02 \
#	img201_bg.gr.zx02 img202_bg.gr.zx02 img203_bg.gr.zx02 \
#	img204_bg.gr.zx02 img205_bg.gr.zx02 img206_bg.gr.zx02 \
#	img207_bg.gr.zx02 img208_bg.gr.zx02 img209_bg.gr.zx02 \
#	img210_bg.gr.zx02 img211_bg.gr.zx02 img212_bg.gr.zx02 \
#	img213_bg.gr.zx02 img214_bg.gr.zx02 img215_bg.gr.zx02 \
#	img216_bg.gr.zx02 img217_bg.gr.zx02 img218_bg.gr.zx02 \
#	img219_bg.gr.zx02 img220_bg.gr.zx02 img221_bg.gr.zx02 \
#	img222_bg.gr.zx02 img223_bg.gr.zx02 img224_bg.gr.zx02 \
#	img225_bg.gr.zx02 img226_bg.gr.zx02 img227_bg.gr.zx02 \
#	img228_bg.gr.zx02 img229_bg.gr.zx02 img230_bg.gr.zx02 \
#	img231_bg.gr.zx02 img232_bg.gr.zx02 img233_bg.gr.zx02 \
##	img234_bg.gr.zx02 img235_bg.gr.zx02 img236_bg.gr.zx02 \
#	img237_bg.gr.zx02 img238_bg.gr.zx02 img239_bg.gr.zx02 \
#	img240_bg.gr.zx02 img241_bg.gr.zx02 img242_bg.gr.zx02 \
#	img243_bg.gr.zx02 img244_bg.gr.zx02 img245_bg.gr.zx02 \
#	img246_bg.gr.zx02 img247_bg.gr.zx02 img248_bg.gr.zx02 \
#	img249_bg.gr.zx02
	echo "img096_bg_zx02: .incbin \"img096_bg.gr.zx02\"" > movie_maglev_ride.inc
	echo "img114_bg_zx02: .incbin \"img114_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img115_bg_zx02: .incbin \"img115_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img116_bg_zx02: .incbin \"img116_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img117_bg_zx02: .incbin \"img117_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img118_bg_zx02: .incbin \"img118_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img119_bg_zx02: .incbin \"img119_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img120_bg_zx02: .incbin \"img120_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img121_bg_zx02: .incbin \"img121_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img122_bg_zx02: .incbin \"img122_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img123_bg_zx02: .incbin \"img123_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img124_bg_zx02: .incbin \"img124_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img125_bg_zx02: .incbin \"img125_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img126_bg_zx02: .incbin \"img126_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img127_bg_zx02: .incbin \"img127_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img128_bg_zx02: .incbin \"img128_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img129_bg_zx02: .incbin \"img129_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img130_bg_zx02: .incbin \"img130_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img131_bg_zx02: .incbin \"img131_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img132_bg_zx02: .incbin \"img132_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img133_bg_zx02: .incbin \"img133_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img134_bg_zx02: .incbin \"img134_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img135_bg_zx02: .incbin \"img135_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img136_bg_zx02: .incbin \"img136_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img137_bg_zx02: .incbin \"img137_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img138_bg_zx02: .incbin \"img138_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img139_bg_zx02: .incbin \"img139_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img140_bg_zx02: .incbin \"img140_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img141_bg_zx02: .incbin \"img141_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img142_bg_zx02: .incbin \"img142_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img143_bg_zx02: .incbin \"img143_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img144_bg_zx02: .incbin \"img144_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img145_bg_zx02: .incbin \"img145_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img146_bg_zx02: .incbin \"img146_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img147_bg_zx02: .incbin \"img147_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img148_bg_zx02: .incbin \"img148_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img149_bg_zx02: .incbin \"img149_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img150_bg_zx02: .incbin \"img150_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img151_bg_zx02: .incbin \"img151_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img152_bg_zx02: .incbin \"img152_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img153_bg_zx02: .incbin \"img153_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img154_bg_zx02: .incbin \"img154_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img155_bg_zx02: .incbin \"img155_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img156_bg_zx02: .incbin \"img156_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img157_bg_zx02: .incbin \"img157_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img158_bg_zx02: .incbin \"img158_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img159_bg_zx02: .incbin \"img159_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img160_bg_zx02: .incbin \"img160_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img161_bg_zx02: .incbin \"img161_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img162_bg_zx02: .incbin \"img162_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img163_bg_zx02: .incbin \"img163_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img164_bg_zx02: .incbin \"img164_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img165_bg_zx02: .incbin \"img165_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img166_bg_zx02: .incbin \"img166_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img167_bg_zx02: .incbin \"img167_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img168_bg_zx02: .incbin \"img168_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img169_bg_zx02: .incbin \"img169_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img170_bg_zx02: .incbin \"img170_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img171_bg_zx02: .incbin \"img171_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img172_bg_zx02: .incbin \"img172_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img173_bg_zx02: .incbin \"img173_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img174_bg_zx02: .incbin \"img174_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img175_bg_zx02: .incbin \"img175_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img176_bg_zx02: .incbin \"img176_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img177_bg_zx02: .incbin \"img177_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img178_bg_zx02: .incbin \"img178_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img179_bg_zx02: .incbin \"img179_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img180_bg_zx02: .incbin \"img180_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img181_bg_zx02: .incbin \"img181_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img182_bg_zx02: .incbin \"img182_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img183_bg_zx02: .incbin \"img183_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img184_bg_zx02: .incbin \"img184_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img185_bg_zx02: .incbin \"img185_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img186_bg_zx02: .incbin \"img186_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img187_bg_zx02: .incbin \"img187_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img188_bg_zx02: .incbin \"img188_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img189_bg_zx02: .incbin \"img189_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img190_bg_zx02: .incbin \"img190_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img191_bg_zx02: .incbin \"img191_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img192_bg_zx02: .incbin \"img192_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img193_bg_zx02: .incbin \"img193_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img194_bg_zx02: .incbin \"img194_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img195_bg_zx02: .incbin \"img195_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img196_bg_zx02: .incbin \"img196_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img197_bg_zx02: .incbin \"img197_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img198_bg_zx02: .incbin \"img198_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img199_bg_zx02: .incbin \"img199_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img200_bg_zx02: .incbin \"img200_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img201_bg_zx02: .incbin \"img201_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img202_bg_zx02: .incbin \"img202_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img203_bg_zx02: .incbin \"img203_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img204_bg_zx02: .incbin \"img204_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img205_bg_zx02: .incbin \"img205_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img206_bg_zx02: .incbin \"img206_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img207_bg_zx02: .incbin \"img207_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img208_bg_zx02: .incbin \"img208_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img209_bg_zx02: .incbin \"img209_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img210_bg_zx02: .incbin \"img210_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img211_bg_zx02: .incbin \"img211_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img212_bg_zx02: .incbin \"img212_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img213_bg_zx02: .incbin \"img213_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img214_bg_zx02: .incbin \"img214_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img215_bg_zx02: .incbin \"img215_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img216_bg_zx02: .incbin \"img216_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img217_bg_zx02: .incbin \"img217_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img218_bg_zx02: .incbin \"img218_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img219_bg_zx02: .incbin \"img219_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img220_bg_zx02: .incbin \"img220_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img221_bg_zx02: .incbin \"img221_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img222_bg_zx02: .incbin \"img222_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img223_bg_zx02: .incbin \"img223_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img224_bg_zx02: .incbin \"img224_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img225_bg_zx02: .incbin \"img225_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img226_bg_zx02: .incbin \"img226_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img227_bg_zx02: .incbin \"img227_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img228_bg_zx02: .incbin \"img228_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img229_bg_zx02: .incbin \"img229_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img230_bg_zx02: .incbin \"img230_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img231_bg_zx02: .incbin \"img231_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img232_bg_zx02: .incbin \"img232_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img233_bg_zx02: .incbin \"img233_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img234_bg_zx02: .incbin \"img234_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img235_bg_zx02: .incbin \"img235_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img236_bg_zx02: .incbin \"img236_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img237_bg_zx02: .incbin \"img237_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img238_bg_zx02: .incbin \"img238_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img239_bg_zx02: .incbin \"img239_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img240_bg_zx02: .incbin \"img240_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img241_bg_zx02: .incbin \"img241_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img242_bg_zx02: .incbin \"img242_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img243_bg_zx02: .incbin \"img243_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img244_bg_zx02: .incbin \"img244_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img245_bg_zx02: .incbin \"img245_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img246_bg_zx02: .incbin \"img246_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img247_bg_zx02: .incbin \"img247_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img248_bg_zx02: .incbin \"img248_bg.gr.zx02\"" >> movie_maglev_ride.inc
#	echo "img249_bg_zx02: .incbin \"img249_bg.gr.zx02\"" >> movie_maglev_ride.inc


####

%.gr:	%.png
	$(PNG2GR) $< $@

%.gr.zx02: %.gr
	$(ZX02) -f $< $@

####

clean:
	rm -f *~ *.o *.lst  *.zx02 *.gr movie_maglev_ride.inc

distclean:
	rm -f *~ *.o *.lst  *.zx02 *.gr movie_maglev_ride.inc
	cd overlays && make clean

