5 HOME
10 PRINT "          -= BOX_ENTROPY 64 =-"
11 PRINT "            ''''''''''''''''"
12 PRINT "           FOR LOVEBYTE 2024"
15 PRINT "            BY DEATER / DSR"
17 PRINT "    BASED ON 2-LINER BY D. MCKELLAR"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN BOX_ENTROPY'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN BOX_ENTROPY"
