; zero page

; pre-defined applesoft vars

CH      = $24
CV      = $25
GBASL   = $26
GBASH   = $27
BASL    = $28
BASH    = $29

AY_REGS		= $70

SONG_L		= $80
SONG_H		= $81
SONG_OFFSET	= $82
SONG_COUNTDOWN	= $83
OCTAVE		= $84
REGISTER	= $85

OUR_ROT		= $A5

HGR_X           = $E0
HGR_XH          = $E1
HGR_Y           = $E2
HGR_COLOR       = $E4
HGR_PAGE        = $E6
HGR_SCALE	= $E7

LETTER_X	= $F8
LETTER_Y	= $F9
COUNT		= $FA
FRAME		= $FB
WHICH_TRACK	= $FC
INL		= $FD
INH		= $FE
TEMP		= $FF
