; zero page

; pre-defined applesoft vars

CH      = $24
CV      = $25
GBASL   = $26
GBASH   = $27
BASL    = $28
BASH    = $29

AY_REGS		= $70
;	through = $7D

FRAME		= $80
BAMP_COUNTDOWN	= $81
WHICH_TRACK	= $82
SONG_COUNTDOWN	= $83


OUR_ROT		= $A5

HGR_X           = $E0
HGR_XH          = $E1
HGR_Y           = $E2
HGR_COLOR       = $E4
HGR_PAGE        = $E6
HGR_SCALE	= $E7


SAVE_Y		= $F7
LETTER_X	= $F8
LETTER_Y	= $F9
COUNT		= $FA
INL		= $FD
INH		= $FE
TEMP		= $FF
