soda_bg_rle:	.byte $28 ; ysize=48
	.byte $A9,$00, $55, $A5,$00, $55, $A4,$00, $55, $A5,$00
	.byte $55,$55, $A8,$00, $55, $A3,$66, $A9,$00, $55, $A5,$00
	.byte $55, $A4,$00, $55, $A5,$00, $55,$55, $A8,$00, $55
	.byte $66,$66, $56, $A9,$00, $55, $A5,$00, $55, $A4,$00
	.byte $55, $A4,$00, $50, $55, $A8,$00, $55, $66,$66
	.byte $55, $AA,$00, $55, $A5,$00, $55, $A4,$00, $55
	.byte $A4,$00, $55,$55, $A8,$00, $55, $66, $56, $05
	.byte $AA,$00, $05, $55, $A4,$00, $55, $A4,$00, $55
	.byte $A4,$00, $55,$55, $A7,$00, $50, $65, $66, $55
	.byte $AC,$00, $55, $A4,$00, $55, $A4,$00, $55, $A4,$00
	.byte $55,$55, $A7,$00, $55, $66, $56, $05, $AC,$00
	.byte $55, $A4,$00, $55, $A3,$00, $50, $55, $A4,$00
	.byte $55, $A7,$00, $50, $65, $66, $55, $AD,$00
	.byte $55, $A4,$00, $55, $A3,$00, $55, $A4,$00, $50
	.byte $55, $A7,$00, $55, $66, $55, $AE,$00, $05
	.byte $55, $A3,$00, $55, $A3,$00, $55, $A4,$00, $55,$55
	.byte $A6,$00, $50, $65, $56, $05, $AF,$00, $55
	.byte $A7,$00, $55, $A4,$00, $55,$55, $A6,$00, $55, $66
	.byte $55, $A0,$10,$00, $55, $A7,$00, $55, $A4,$00, $55
	.byte $A6,$00, $50, $65, $56, $05, $A0,$10,$00, $05
	.byte $A7,$00, $55, $A4,$00, $55, $A6,$00, $55, $66
	.byte $55, $A0,$19,$00, $05, $A3,$00, $55,$55, $A6,$00, $65
	.byte $56, $A0,$1E,$00, $55,$55, $A5,$00, $55, $66, $55
	.byte $A0,$1E,$00, $55, $A6,$00, $65, $56, $A7,$00, $50
	.byte $A0,$17,$00, $55, $A5,$00, $55, $66, $05, $A6,$00
	.byte $50, $66, $A0,$17,$00, $55, $A5,$00, $65, $56
	.byte $A6,$00, $50, $66,$66, $A0,$16,$00, $55,$55, $A4,$00, $65
	.byte $56, $A7,$00, $66,$66, $05, $A0,$16,$00, $55, $A5,$00
	.byte $56, $05, $A6,$00, $65, $66, $05, $A0,$17,$00
	.byte $55, $A4,$00, $50, $55, $A6,$00, $65, $66
	.byte $05, $A0,$18,$00, $55, $A4,$00, $55, $05, $A5,$00
	.byte $65, $66, $05, $A0,$18,$00, $50, $55, $A3,$00
	.byte $50, $55, $A5,$00, $50, $66, $05, $A0,$19,$00
	.byte $55, $A4,$00, $55, $A5,$00, $50, $66, $05
	.byte $A0,$1A,$00, $55, $A4,$00, $55, $A4,$00, $50, $66
	.byte $05, $A6,$00
	.byte $A1
soda01_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$27,$AA, $BA,$BA, $BB,$BB, $BA, $A0,$1F,$AA, $BA
	.byte $A9,$BB, $BA, $A0,$1C,$AA, $BA, $A5,$BB, $2B, $A3,$02
	.byte $2B, $BB, $A0,$1B,$AA, $BA, $A5,$BB, $22, $20
	.byte $A3,$22, $20, $2B, $BB, $A0,$18,$AA, $BA, $A6,$BB
	.byte $22,$22, $26, $02,$02, $06, $22,$22, $2B, $A0,$17,$AA
	.byte $BA, $A7,$BB, $22,$22, $00, $22,$22, $00, $A3,$22
	.byte $A0,$15,$AA, $BA, $A9,$BB, $A3,$22, $00, $22, $00
	.byte $A3,$22, $A4,$AA, $BA,$BA, $AC,$AA, $BA, $AC,$BB, $A3,$22
	.byte $02, $20, $A4,$22, $A0,$01,$AA, $BA,$BA, $A3,$BB, $3A
	.byte $BB, $AA,$AA, $AD,$BB, $B2, $A7,$22, $B2, $A3,$BB
	.byte $00, $BB,$BB, $B3, $3B, $BB, $A9,$AA, $A4,$BB
	.byte $B2, $22, $A8,$BB, $00, $22, $20, $02,$02
	.byte $26, $02, $0B, $A4,$BB, $00, $BB,$BB, $33
	.byte $BB, $3A, $A8,$AA, $A7,$BB, $A5,$3B, $BB,$BB, $00,$00
	.byte $A4,$02, $00,$00, $0B, $A6,$BB, $B3, $BB, $33
	.byte $BB, $A7,$AA, $A4,$BB, $3B, $A0,$02,$A3, $A5,$AA, $A0,$01,$A3
	.byte $A0,$01,$AB, $A0,$01,$AA, $A6,$A0, $33, $00, $0B, $A3,$BB
	.byte $33, $A3,$BB, $33, $BB, $BA, $A6,$AA, $BB
	.byte $3B,$3B, $A0,$01,$A3, $A0,$11,$AA, $33, $30, $00, $A3,$BB
	.byte $33, $A6,$BB, $A6,$AA, $A0,$01,$A3, $A0,$15,$AA, $33, $00
	.byte $AB,$BB, $A0,$1B,$AA, $33, $00, $AB,$BB, $A0,$1B,$AA, $33
	.byte $30, $AB,$BB, $A0,$1C,$AA, $33, $AB,$BB, $A5,$AA
	.byte $A1
soda02_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$4D,$AA, $A4,$BA, $BB,$BB, $BA, $A0,$1F,$AA, $BA
	.byte $A9,$BB, $BA, $A0,$1C,$AA, $BA, $A6,$BB, $2B, $02
	.byte $2B, $BB,$BB, $A0,$02,$AA, $BA,$BA, $3A, $A0,$15,$AA, $BA
	.byte $A6,$BB, $2B, $22, $20, $22,$22, $B2, $BB
	.byte $BA, $A3,$BB, $33, $BB,$BB, $A0,$11,$AA, $BA, $A7,$BB
	.byte $2B, $A3,$22, $02,$02, $A3,$BB, $00, $0B, $BB
	.byte $B3, $3B, $BB,$BB, $AE,$AA, $BA, $A8,$BB, $55
	.byte $A3,$22, $00, $22, $00,$00, $A3,$BB, $00, $BB,$BB
	.byte $33, $BB, $3B, $AB,$AA, $BA, $AB,$BB, $55
	.byte $A3,$22, $00, $22, $00,$00, $A3,$BB, $00, $BB,$BB
	.byte $33, $BB, $33, $BB, $AA,$AA, $AD,$BB, $A4,$22
	.byte $50, $A3,$00, $A3,$BB, $33, $BB, $B3, $BB
	.byte $B3, $3B, $BB, $A9,$AA, $A5,$BB, $22, $2B
	.byte $A6,$BB, $00, $A4,$22, $A3,$00, $A8,$BB, $33, $BB
	.byte $A9,$AA, $AD,$BB, $00, $02, $20, $02,$02, $A3,$00
	.byte $AB,$BB, $A8,$AA, $A3,$BB, $3B,$3B, $A7,$A3, $3B, $33
	.byte $00,$00, $A3,$02, $00,$00, $33, $AA,$BB, $BA, $A7,$AA
	.byte $3B, $A0,$02,$A3, $AA,$AA, $A0,$01,$A3, $A0,$01,$AA, $A4,$A0, $A0,$02,$AA
	.byte $33, $AB,$BB, $A0,$1C,$AA, $33, $AB,$BB, $A0,$1C,$AA, $33
	.byte $3B, $AA,$BB, $A0,$1D,$AA, $33, $AA,$BB, $A0,$1D,$AA, $33
	.byte $AA,$BB, $A7,$AA
	.byte $A1
soda03_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$74,$AA, $A3,$BA, $A5,$BB, $A3,$AA, $BA, $A0,$1A,$AA
	.byte $BA, $AA,$BB, $BA, $BB,$BB, $3A, $BB, $BA
	.byte $A0,$15,$AA, $BA, $A8,$BB, $2B, $22, $B2, $2B
	.byte $0B, $BB,$BB, $B3, $3B, $BB, $BA, $A0,$12,$AA
	.byte $BA, $A7,$BB, $5B, $2B, $22,$22, $BB,$BB, $B0
	.byte $00, $A3,$BB, $33, $BB,$BB, $3A, $AF,$AA, $BA
	.byte $A9,$BB, $55, $22,$22, $62, $0B, $BB,$BB, $00
	.byte $A3,$BB, $B3, $3B, $BB, $33, $BB, $AC,$AA
	.byte $BA, $AA,$BB, $B5, $55, $A3,$22, $00, $A3,$BB
	.byte $B3, $3B, $BB,$BB, $33, $BB, $B3, $BB
	.byte $BA, $AA,$AA, $AD,$BB, $B5, $A3,$22, $00, $0B
	.byte $A3,$BB, $33, $A7,$BB, $AA,$AA, $A5,$BB, $2B, $A7,$BB
	.byte $0B, $A3,$22, $00,$00, $AB,$BB, $AA,$AA, $A5,$BB, $B2,$B2
	.byte $A6,$BB, $00, $22, $02, $22, $A3,$00, $AA,$BB
	.byte $BA, $A9,$AA, $A5,$BB, $A6,$3B, $BB,$BB, $30, $00
	.byte $02, $20, $A3,$00, $3B, $AA,$BB, $A9,$AA, $BB,$BB
	.byte $3B, $A0,$02,$A3, $A6,$AA, $A0,$01,$A3, $3B, $33, $A0,$01,$A0
	.byte $A5,$00, $33, $AA,$BB, $A9,$AA, $A0,$02,$A3, $AE,$AA, $A3,$A0
	.byte $A0,$01,$AA, $33, $AA,$BB, $A0,$1D,$AA, $33, $AA,$BB, $A0,$1D,$AA
	.byte $33, $AA,$BB, $A0,$1E,$AA, $33, $A9,$BB, $A9,$AA
	.byte $A1
soda04_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$55,$AA, $BA, $BB,$BB, $A0,$25,$AA, $A3,$BB, $33
	.byte $BA, $A0,$19,$AA, $BA, $A8,$BB, $B0, $00, $BB,$BB
	.byte $33, $BB, $A0,$17,$AA, $BA, $AB,$BB, $00, $BB,$BB
	.byte $33, $BB,$BB, $A0,$14,$AA, $BA, $A8,$BB, $2B, $0B
	.byte $A3,$BB, $B0, $A3,$BB, $33, $BB, $3A, $BA
	.byte $A0,$10,$AA, $BA, $A9,$BB, $02, $20,$20, $A7,$BB, $33
	.byte $BB, $B3, $3B, $AE,$AA, $BA, $A9,$BB, $5B
	.byte $00, $A3,$22, $00, $BB,$BB, $3B, $A4,$BB, $33
	.byte $BB, $33, $BB, $AB,$AA, $BA, $AB,$BB, $55
	.byte $00, $22,$22, $26, $00, $BB,$BB, $B3, $3B
	.byte $A8,$BB, $AA,$AA, $AD,$BB, $00, $A3,$22, $00,$00, $AB,$BB
	.byte $AA,$AA, $A4,$BB, $2B,$2B, $A7,$BB, $00, $A3,$22, $00,$00
	.byte $AB,$BB, $BA, $A9,$AA, $A5,$BB, $B2, $A7,$BB, $00
	.byte $A3,$22, $00,$00, $33, $AB,$BB, $A9,$AA, $A3,$BB, $A4,$3B
	.byte $A3,$AB, $3B, $BB,$BB, $00, $02, $20, $02
	.byte $00,$00, $33, $AB,$BB, $A9,$AA, $3B,$3B, $A0,$01,$A3, $A8,$AA
	.byte $A0,$01,$A3, $3B, $00,$00, $02,$02, $00,$00, $33, $AB,$BB
	.byte $A0,$17,$AA, $A4,$A0, $A0,$02,$AA, $33, $AA,$BB, $A0,$1D,$AA, $33
	.byte $AA,$BB, $BA, $A0,$1C,$AA, $33, $AB,$BB, $A8,$AA
	.byte $A1
soda05_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$9C,$AA, $BA, $A7,$BB, $BA, $A0,$01,$AA, $BA,$BA
	.byte $A0,$1A,$AA, $BA, $AA,$BB, $3A, $BB,$BB, $BA, $A0,$16,$AA
	.byte $BA,$BA, $AC,$BB, $B3, $A4,$BB, $BA, $A0,$12,$AA, $BA
	.byte $AA,$BB, $0B, $02, $A9,$BB, $BA,$BA, $AE,$AA, $BA
	.byte $AB,$BB, $00,$00, $22, $00, $AA,$BB, $AC,$AA, $BA
	.byte $AB,$BB, $55, $00, $20, $22, $62, $00
	.byte $AB,$BB, $AB,$AA, $AC,$BB, $55, $00, $A3,$22, $00
	.byte $AB,$BB, $AB,$AA, $A5,$BB, $2B, $A7,$BB, $00, $A3,$22
	.byte $00, $0B, $AA,$BB, $BA, $AA,$AA, $A4,$BB, $A3,$B2
	.byte $A6,$BB, $00, $A3,$22, $00,$00, $AB,$BB, $AA,$AA, $A4,$BB
	.byte $A7,$3B, $BB,$BB, $00, $22, $02, $22, $00,$00
	.byte $AB,$BB, $AA,$AA, $3B,$3B, $A0,$02,$A3, $A7,$AA, $A0,$01,$A3, $3B
	.byte $00,$00, $22, $20, $00,$00, $3B, $AA,$BB, $BA
	.byte $A0,$17,$AA, $A0,$01,$A0, $00, $02, $00,$00, $A0,$01,$A3, $3B
	.byte $AA,$BB, $A0,$1D,$AA, $A0,$01,$A3, $3B, $A9,$BB, $A0,$1E,$AA, $33
	.byte $AA,$BB, $A8,$AA
	.byte $A1
soda06_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$74,$AA, $A3,$BA, $A4,$BB, $BA, $A0,$1F,$AA, $AA,$BB
	.byte $BA, $A0,$1B,$AA, $BA, $A6,$BB, $2B, $A3,$22, $2B
	.byte $BB, $A0,$19,$AA, $BA, $A7,$BB, $A3,$22, $00, $22,$22
	.byte $2B, $A0,$17,$AA, $BA, $A8,$BB, $52, $22, $00
	.byte $A5,$22, $A0,$01,$AA, $BA, $BB,$BB, $A0,$10,$AA, $BA, $AA,$BB
	.byte $55, $00, $A5,$22, $B2,$B2, $A5,$BB, $BA, $AD,$AA
	.byte $AD,$BB, $00, $A3,$22, $AC,$BB, $BA, $AA,$AA, $A5,$BB
	.byte $2B, $A7,$BB, $00, $A3,$22, $00, $AC,$BB, $AA,$AA
	.byte $A5,$BB, $B2,$B2, $A6,$BB, $00, $22, $02, $22
	.byte $00, $AC,$BB, $AA,$AA, $A4,$BB, $A6,$3B, $A3,$BB, $00
	.byte $02, $22, $20, $00, $AC,$BB, $AA,$AA, $3B,$3B
	.byte $A0,$02,$A3, $A6,$AA, $A0,$02,$A3, $BB, $A5,$00, $AC,$BB, $BA
	.byte $A0,$15,$AA, $A0,$01,$A3, $A6,$AA, $AC,$BB, $A0,$1C,$AA, $AC,$BB, $A0,$1D,$AA
	.byte $AC,$BB, $A0,$1C,$AA, $A0,$01,$AB, $AB,$BB, $A8,$AA
	.byte $A1
soda07_rle:	.byte $28 ; ysize=48
	.byte $A0,$81,$AA, $BA,$BA, $BB, $BA, $A0,$22,$AA, $BA, $BB,$BB
	.byte $A4,$2B, $BB, $A0,$1F,$AA, $A3,$BB, $22,$22, $52, $F2
	.byte $F5, $52, $A0,$1E,$AA, $A3,$BB, $A3,$22, $55, $FF,$FF
	.byte $55, $22, $A0,$1C,$AA, $A4,$BB, $A3,$22, $55, $FF
	.byte $2F, $25, $22, $A0,$1B,$AA, $A5,$BB, $22,$22, $55
	.byte $FF, $0F, $A3,$22, $A0,$1A,$AA, $A6,$BB, $22,$22, $55
	.byte $FF, $F0, $00, $22,$22, $A0,$19,$AA, $BA, $A6,$BB
	.byte $00, $22, $55, $FF,$FF, $20, $22, $02
	.byte $A0,$18,$AA, $BA, $A7,$BB, $B0, $00, $02, $25
	.byte $2A, $22, $02, $00, $A0,$18,$AA, $A9,$BB, $B0
	.byte $A6,$00, $A0,$18,$AA, $BB,$BB, $22, $2B, $A6,$BB, $B0,$B0
	.byte $00,$00, $A0,$02,$A0, $A0,$18,$AA, $AD,$BB, $A9,$AA, $3A, $A3,$AA
	.byte $3A,$3A, $33,$33, $AA,$AA, $BB,$BB, $A3,$3B, $A3,$A3, $AE,$AA
	.byte $33, $B3, $33,$33, $A4,$BB, $BA, $A4,$3A, $A5,$AA
	.byte $A0,$02,$A3, $A0,$14,$AA, $33, $A9,$BB, $B3,$B3, $BB, $3A
	.byte $A0,$1A,$AA, $A0,$01,$A3, $33, $AB,$BB, $B3, $BA, $A0,$1A,$AA
	.byte $33, $BB, $33, $3B, $A6,$BB, $33, $3B
	.byte $BB,$BB, $BA, $A0,$19,$AA, $33, $BB, $00, $33
	.byte $A6,$BB, $B3, $33, $A3,$BB, $A0,$19,$AA, $33, $BB
	.byte $B0, $00, $03, $0B, $A9,$BB, $BA, $A0,$18,$AA
	.byte $33, $BB,$BB, $B3, $00,$00, $AA,$BB, $A0,$19,$AA, $33
	.byte $BB,$BB, $33,$33, $AA,$BB, $A0,$19,$AA, $33, $BB,$BB, $33,$33
	.byte $AA,$BB, $A0,$01,$AA
	.byte $A1
soda08_rle:	.byte $28 ; ysize=48
	.byte $A0,$2F,$AA, $A3,$BA, $A0,$23,$AA, $BA, $A6,$BB, $A0,$1F,$AA, $BA
	.byte $A3,$BB, $22, $F2, $22, $A0,$01,$A2, $2B, $BB
	.byte $A0,$1D,$AA, $BA, $A3,$BB, $A3,$22, $52, $FF, $55
	.byte $22, $A0,$1D,$AA, $A3,$BB, $22, $2F, $22,$22, $55
	.byte $FF, $55, $22, $A0,$1B,$AA, $BA, $A3,$BB, $5B
	.byte $A4,$22, $25, $FF, $55, $22, $A0,$1B,$AA, $A4,$BB
	.byte $B5, $A4,$22, $5A, $F0, $05, $22, $A0,$1B,$AA
	.byte $A5,$BB, $A4,$22, $F5, $FF, $20, $02, $A0,$1B,$AA
	.byte $A5,$BB, $B0, $A3,$02, $05, $02,$02, $00, $A0,$1B,$AA
	.byte $A6,$BB, $A7,$00, $A0,$1B,$AA, $A7,$BB, $B3,$B3, $B0, $30
	.byte $A0,$02,$A0, $A0,$1B,$AA, $A9,$BB, $3B, $33, $A0,$1D,$AA, $BB
	.byte $3B,$3B, $A4,$A3, $A0,$21,$AA, $A0,$01,$A3, $A0,$FF,$AA, $A0,$3B,$AA, $A3,$3A
	.byte $A0,$20,$AA, $33, $3A,$3A, $33, $A4,$B3, $33, $A0,$1F,$AA
	.byte $33, $BB, $B3,$B3, $A5,$BB, $B3
	.byte $A1
soda09_rle:	.byte $28 ; ysize=48
	.byte $A0,$AC,$AA, $BA, $BB,$BB, $BA, $A0,$22,$AA, $BA, $A6,$BB
	.byte $BA,$BA, $A0,$1E,$AA, $A3,$BB, $22,$22, $F2, $22, $A0,$01,$A2
	.byte $2B, $BB, $A0,$1D,$AA, $A3,$BB, $A4,$22, $55, $FF
	.byte $22,$22, $A0,$1C,$AA, $A4,$BB, $22, $2F, $22,$22, $55
	.byte $FF, $22,$22, $A0,$1B,$AA, $BA, $A3,$BB, $55, $A4,$22
	.byte $05, $FF, $22,$22, $A0,$1A,$AA, $BA, $A4,$BB, $B5
	.byte $A3,$22, $55, $F0, $00, $22,$22, $A0,$19,$AA, $BA
	.byte $A6,$BB, $02, $22,$22, $55, $FF, $20, $22
	.byte $A0,$01,$A2, $A0,$18,$AA, $BA, $A7,$BB, $B0, $A3,$A2, $A0,$01,$A5
	.byte $A0,$02,$A2, $A0,$17,$AA, $BA, $AA,$BB, $BA, $A0,$1B,$AA, $A3,$BB
	.byte $2B,$2B, $A9,$BB, $B3, $BA, $A0,$18,$AA, $A4,$BB, $B2
	.byte $A6,$BB, $A4,$3B, $A0,$01,$AB, $A0,$18,$AA, $A6,$BB, $3B,$3B, $A3,$A3
	.byte $A0,$1D,$AA, $A4,$BB, $3B, $A0,$01,$A3, $A0,$22,$AA, $A3,$BB, $3B
	.byte $A0,$24,$AA, $BB, $3B, $A0,$01,$A3, $A0,$25,$AA, $A0,$01,$A3, $A0,$9F,$AA
	.byte $A1
