	.byte SET_COLOR | DARK_BLUE
	.byte BOX,4,6,34,23
	.byte BOX_ADD,6,32,37	; 24
	.byte SET_COLOR | GREY1
	.byte BOX,14,6,15,13
	.byte 23,6,24,13
	.byte 12,13,26,19
	.byte BOX_ADD,14,16,37	; 20
	.byte BOX,22,20,24,37
	.byte 18,27,20,37
	.byte 5,35,6,36
	.byte 4,38,33,39
	.byte 18,39,20,40
	.byte HLIN,4,5,24
	.byte 4,6,37
	.byte VLIN,6,23,5
	.byte VLIN_ADD,33,34	; 6
	.byte VLIN,6,13,19
	.byte 34,35,33
	.byte PLOT,33,23
	.byte SET_COLOR | BROWN
	.byte BOX,14,20,15,38
	.byte 22,20,23,38
	.byte HLIN,13,25,12
	.byte HLIN_ADD,12,26	; 13
	.byte HLIN,31,32,22
	.byte 7,8,31
	.byte 18,20,35
	.byte 18,20,37
	.byte 18,20,39
	.byte VLIN,6,30,7
	.byte VLIN_ADD,32,38	; 8
	.byte VLIN,23,38,31
	.byte VLIN_ADD,6,21	; 32
	.byte PLOT,15,39
	.byte 23,39
	.byte SET_COLOR | GREEN
	.byte BOX,34,10,35,35
	.byte BOX_ADD_RSAME,33,41
	.byte VLIN,6,9,35
	.byte SET_COLOR | LIGHT_BLUE
	.byte 6,22,5
	.byte END
; total size = 143
