	.byte SET_COLOR | DARK_BLUE
	.byte BOX,4,6,35,41
	.byte SET_COLOR | BROWN
	.byte 11,34,29,35
	.byte BOX_ADD_LSAME,30,41 ; 11, 36
	.byte BOX,4,38,5,41
	.byte HLIN,20,29,33
	.byte VLIN,30,37,4
	.byte SET_COLOR | GREY2
	.byte BOX,19,6,21,20
	.byte 27,6,29,8
	.byte BOX_ADD_LSAME,28,24 ; 27, 9
	.byte BOX,13,17,14,34
	.byte 20,21,21,34
	.byte 26,25,28,26
	.byte 12,6,13,15
	.byte HLIN,12,14,16
	.byte BOX,26,27,27,33
	.byte END
; total size = 67
