	.byte SET_COLOR | DARK_BLUE
	.byte BOX,4,6,29,24
	.byte BOX_ADD_RSAME,8,33
	.byte SET_COLOR | GREY2
	.byte BOX,14,6,15,11
	.byte 18,6,19,11
	.byte 22,6,23,11
	.byte 12,11,26,15
	.byte BOX_ADD,14,16,33	; 16
	.byte BOX,22,16,24,33
	.byte 18,24,20,33
	.byte BOX_ADD,5,30,35	; 34
	.byte BOX,4,40,18,41
	.byte 25,40,30,41
	.byte 6,32,7,33
	.byte HLIN,4,7,24
	.byte VLIN,30,31,7
	.byte SET_COLOR | GREEN
	.byte BOX,31,6,35,41
	.byte SET_COLOR | BROWN
	.byte 14,16,15,35
	.byte 22,16,23,35
	.byte HLIN,12,26,11
	.byte 18,20,32
	.byte 18,20,34
	.byte 18,20,36
	.byte VLIN,6,34,30
	.byte 6,22,8
	.byte 23,34,9
	.byte SET_COLOR | LIGHT_BLUE
	.byte 6,23,6
	.byte END
; total size = 108
