	.byte SET_COLOR | GREY1
	.byte BOX,4,13,34,16
	.byte 17,33,34,39
	.byte 19,27,34,30
	.byte 4,17,18,20
	.byte BOX_ADD_LSAME,17,22 ; 4, 21
	.byte BOX,4,36,10,37
	.byte HLIN,12,34,32
	.byte 17,34,31
	.byte 18,34,40
	.byte HLIN_ADD_RSAME,19	; 19 34 41
	.byte HLIN,5,17,23
	.byte HLIN_ADD_LSAME,16 ; 5, 16, 24
	.byte HLIN,6,16,25
	.byte 4,14,41
	.byte 7,16,26
	.byte 4,13,40
	.byte 8,16,27
	.byte 4,12,39
	.byte 8,15,28
	.byte 4,11,38
	.byte 9,15,29
	.byte HLIN_ADD_RSAME,10	; 10 15 30
	.byte HLIN,4,9,35
	.byte 11,15,31
	.byte 4,8,34
	.byte 4,7,33
	.byte 4,6,32
	.byte 4,5,31
	.byte 13,14,33
	.byte PLOT,20,26
	.byte 4,30
	.byte SET_COLOR | BROWN
	.byte BOX,4,6,35,12
	.byte BOX_ADD_RSAME,20,25
	.byte BOX,4,13,18,15
	.byte BOX_ADD,7,17,19	; 16
	.byte BOX,23,28,35,38
	.byte BOX_ADD_LSAME,30,40 ; 23, 39
	.byte HLIN,21,35,26
	.byte HLIN_ADD_RSAME,22	; 22 35 27
	.byte HLIN,33,35,39
	.byte HLIN_ADD_RSAME,34	; 34 35 40
	.byte HLIN,23,29,41
	.byte PLOT,35,41
	.byte SET_COLOR | ORANGE
	.byte BOX,24,20,35,25
	.byte 23,27,34,29
	.byte HLIN,21,27,6
	.byte HLIN_ADD,22,26	; 7
	.byte HLIN_ADD_RSAME,23	; 23 26 8
	.byte 24	; 24 26 9
	.byte 25	; 25 26 10
	.byte HLIN,26,27,12
	.byte HLIN_ADD_LSAME,28 ; 26, 28, 13
	.byte HLIN,25,29,14
	.byte HLIN_ADD_LSAME,30 ; 25, 30, 15
	.byte 31
	.byte 32
	.byte 33
	.byte 34
	.byte HLIN,23,35,26
	.byte 24,33,30
	.byte HLIN_ADD_RSAME,25	; 25 33 31
	.byte 26	; 26 33 32
	.byte HLIN,27,32,33
	.byte HLIN_ADD_RSAME,28	; 28 32 34
	.byte 29	; 29 32 35
	.byte HLIN,30,31,36
	.byte PLOT,26,11
	.byte 31,37
	.byte SET_COLOR | LIGHT_BLUE
	.byte BOX,9,6,18,9
	.byte BOX_ADD_LSAME,19,12 ; 9, 10
	.byte 18,15
	.byte 17,19
	.byte 16,22
	.byte 15,25
	.byte BOX,11,27,14,28
	.byte HLIN,10,15,26
	.byte 12,14,29
	.byte 14,17,32
	.byte 9,11,41
	.byte VLIN,39,40,10
	.byte 30,31,17
	.byte PLOT,17,33
	.byte SET_COLOR | DARK_BLUE
	.byte BOX,4,18,9,20
	.byte 4,36,8,37
	.byte BOX_ADD_LSAME,9,40 ; 4, 38
	.byte HLIN,4,5,15
	.byte HLIN_ADD_LSAME,6 ; 4, 6, 16
	.byte 7
	.byte HLIN,5,9,21
	.byte HLIN_ADD_RSAME,6	; 6 9 22
	.byte HLIN,7,10,23
	.byte HLIN_ADD_RSAME,8	; 8 10 24
	.byte HLIN,9,11,25
	.byte HLIN_ADD_RSAME,10	; 10 11 26
	.byte HLIN,11,12,28
	.byte 13,15,31
	.byte HLIN_ADD_RSAME,14	; 14 15 32
	.byte HLIN,4,5,33
	.byte HLIN_ADD_LSAME,6 ; 4, 6, 34
	.byte 7
	.byte HLIN,4,8,41
	.byte VLIN,33,34,14
	.byte PLOT,4,14
	.byte 11,27
	.byte 12,29
	.byte 13,30
	.byte 15,30
	.byte 4,32
	.byte SET_COLOR | PINK
	.byte BOX,7,7,12,8
	.byte BOX_ADD_LSAME,11,10 ; 7, 9
	.byte BOX,8,11,10,14
	.byte BOX_ADD_LSAME,9,16 ; 8, 15
	.byte HLIN,6,12,6
	.byte VLIN,17,18,9
	.byte SET_COLOR | YELLOW
	.byte PLOT,15,32
	.byte END
; total size = 359
