	.byte SET_COLOR | BROWN
	.byte BOX,24,6,35,36
	.byte SET_COLOR | WHITE
	.byte 4,6,23,41
	.byte SET_COLOR | MEDIUM_BLUE
	.byte 33,11,35,17
	.byte 33,25,35,30
	.byte SET_COLOR | GREY1
	.byte 24,37,35,40
	.byte 26,20,32,23
	.byte HLIN,24,30,36
	.byte 29,35,41
	.byte 27,31,19
	.byte SET_COLOR | LIGHT_BLUE
	.byte 26,32,23
	.byte HLIN_ADD,27,31	; 24
	.byte SET_COLOR | RED
	.byte HLIN,26,32,22
	.byte END
; total size = 52
