	.byte SET_COLOR | MEDIUM_BLUE
	.byte BOX,4,6,28,9
	.byte BOX_ADD_RSAME,5,17
	.byte HLIN,6,9,18
	.byte SET_COLOR | GREY1
	.byte BOX,11,12,25,17
	.byte 4,21,21,22
	.byte BOX_ADD_LSAME,35,30 ; 4, 23
	.byte 9,38
	.byte BOX,16,33,35,34
	.byte BOX_ADD_RSAME,17,37
	.byte 18,39	; 35 38
	.byte BOX,4,39,6,40
	.byte 19,40,35,41
	.byte HLIN,10,27,18
	.byte HLIN_ADD,4,25	; 19
	.byte HLIN_ADD_LSAME,22 ; 4, 22, 20
	.byte HLIN,27,28,20
	.byte HLIN_ADD_RSAME,25	; 25 28 21
	.byte 24	; 24 28 22
	.byte HLIN,11,35,31
	.byte HLIN_ADD_RSAME,15	; 15 35 32
	.byte HLIN,4,7,41
	.byte PLOT,28,17
	.byte SET_COLOR | LIGHT_BLUE
	.byte BOX,16,14,22,15
	.byte 4,17,5,18
	.byte 9,24,10,26
	.byte 16,25,17,26
	.byte 18,28,19,29
	.byte 4,31,9,35
	.byte 20,34,21,36
	.byte HLIN,11,22,13
	.byte HLIN_ADD_RSAME,14	; 14 22 14
	.byte HLIN,6,8,19
	.byte 13,14,21
	.byte 8,9,23
	.byte 16,20,27
	.byte 13,20,30
	.byte 9,10,30
	.byte HLIN_ADD,11,15	; 31
	.byte HLIN,18,20,31
	.byte HLIN_ADD_RSAME,19	; 19 20 32
	.byte HLIN,19,21,33
	.byte 5,9,36
	.byte HLIN_ADD_RSAME,6	; 6 9 37
	.byte 7	; 7 9 38
	.byte 8	; 8 9 39
	.byte VLIN,8,21,22
	.byte VLIN_ADD,27,29	; 9
	.byte VLIN,11,14,19
	.byte 20,19,20
	.byte VLIN_ADD,21,23	; 21
	.byte 24,32	; 22
	.byte PLOT,17,16
	.byte 18,17
	.byte 19,18
	.byte 7,20
	.byte 10,20
	.byte 12,20
	.byte 14,22
	.byte 15,23
	.byte 16,24
	.byte 20,26
	.byte 9,40
	.byte SET_COLOR | BROWN
	.byte BOX,10,6,24,8
	.byte 28,6,35,10
	.byte 10,9,25,11
	.byte 29,11,35,25
	.byte BOX_ADD_RSAME,30,34
	.byte HLIN,31,35,35
	.byte HLIN_ADD_RSAME,32	; 32 35 36
	.byte 33	; 33 35 37
	.byte 34	; 34 35 38
	.byte PLOT,35,39
	.byte SET_COLOR | DARK_BLUE
	.byte BOX,19,6,24,8
	.byte BOX_ADD_LSAME,25,15 ; 19, 9
	.byte HLIN,20,25,16
	.byte HLIN_ADD_RSAME,23	; 23 25 17
	.byte SET_COLOR | PINK
	.byte BOX,11,6,18,11
	.byte HLIN,12,18,12
	.byte HLIN_ADD_RSAME,14	; 14 18 13
	.byte 16	; 16 18 14
	.byte 17	; 17 18 15
	.byte SET_COLOR | RED
	.byte HLIN,4,5,28
	.byte HLIN_ADD_LSAME,6 ; 4, 6, 29
	.byte 7
	.byte HLIN,5,9,31
	.byte HLIN_ADD_RSAME,6	; 6 9 32
	.byte 7	; 7 9 33
	.byte 8	; 8 9 34
	.byte PLOT,4,27
	.byte SET_COLOR | YELLOW
	.byte BOX,13,29,16,30
	.byte HLIN,14,16,28
	.byte 14,15,31
	.byte END
; total size = 287
