5 HOME
10 PRINT "           -= DESIRE WIRES =-"
12 PRINT "             --------------"
15 PRINT "     256 BYTE INTRO AT LOVEBYTE2024"
17 PRINT "            BY DEATER/DESIRE"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN DSR_WIRES'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN DSR_WIRES"
