; hgr_make_sprite ./peasant_sprites.png  35 1 35 31

peasant_right1_sprite:
	.byte $00
	.byte $00
	.byte $00
	.byte $40
	.byte $40
	.byte $40
	.byte $70
	.byte $0C
	.byte $00
	.byte $00
	.byte $00
	.byte $0C
	.byte $0C
	.byte $0C
	.byte $1C
	.byte $70
	.byte $F5
	.byte $00
	.byte $00
	.byte $00
	.byte $00
	.byte $00
	.byte $0C
	.byte $3C
	.byte $0F
	.byte $0F
	.byte $0F
	.byte $1C
	.byte $FF
	.byte $FF

; hgr_make_sprite peasant_sprites.png  21 1 21 31
peasant_right1_mask:
	.byte $03
	.byte $00
	.byte $00
	.byte $00
	.byte $00
	.byte $00
	.byte $00
	.byte $73
	.byte $70
	.byte $70
	.byte $70
	.byte $70
	.byte $70
	.byte $70
	.byte $60
	.byte $00
	.byte $00
	.byte $70
	.byte $70
	.byte $03
	.byte $03
	.byte $03
	.byte $03
	.byte $43
	.byte $70
	.byte $70
	.byte $70
	.byte $63
	.byte $00
	.byte $00
