5 HOME
10 PRINT "       LOADING APPLEBOT DEMO V0.1"
20 PRINT
30 PRINT "      A COLLECTION OF BASIC DEMOS"
40 PRINT " THAT EACH FIT IN A 280 CHARACTER TWEET"
42 PRINT "    FIRST TESTED ON THE @APPLEIIBOT"
45 PRINT
50 HTAB 15:PRINT "     _    "
60 HTAB 15:PRINT " _: :_   _"
70 HTAB 15:PRINT ":_:  _: : "
80 PRINT CHR$(4)"BRUN LOADER"
