; these need to be in zero page
; can we find a location that works?

PATTERN_L	= $06
PATTERN_H	= $07
ORNAMENT_L	= $08
ORNAMENT_H	= $09
SAMPLE_L	= $0A
SAMPLE_H	= $0B
MB_ADDR_L	= $0C
MB_ADDR_H	= $0D


TEMP            =       $FA
TEMPY           =       $FB
INL             =       $FC
INH             =       $FD
OUTL            =       $FE
OUTH            =       $FF

; pre-defined applesoft vars

CH      = $24
CV      = $25
GBASL   = $26
GBASH   = $27
BASL    = $28
BASH    = $29
