all:
	cd fancy_lores && make
	cd racebeam && make
	cd rasterbars && make
	cd tfv_credits && make
	cd waterfall && make

clean:
	cd fancy_lores && make clean
	cd racebeam && make clean
	cd rasterbars && make clean
	cd tfv_credits && make clean
	cd waterfall && make clean
	rm -f *~
