CODE_arr	=	$6008		; CODE array (dummy address)
X_arr		=	$602f		; X array (dummy address)
Y_arr		=	$6056		; Y array (dummy address)
SCALE_arr	=	$607d		; SCALE array (dummy address)
XROT_arr	=	$60a4		; XROT array (dummy address)
YROT_arr	=	$60cb		; YROT array (dummy address)
ZROT_arr	=	$60f2		; ZROT array (dummy address)
SX_arr		=	$6119		; SX array (dummy address)
SY_arr		=	$6140		; SY array (dummy address)

; soft switches
TXTCLR		=	$c050		; RW display graphics
MIXCLR		=	$c052		; RW display full screen
TXTPAGE1	=	$c054		; RW display page 1
TXTPAGE2	=	$c055		; RW display page 2 (or read/write aux mem)
HIRES		=	$c057		; RW display hi-res graphics

