5 HOME
10 PRINT "LOADING LEMM V0.01"
20 PRINT "  LEMM PROOF-OF-CONCEPT DEMAKE"
30 PRINT:PRINT
70 PRINT "BASED ON LEMMINGS BY DMA DESIGN"
75 PRINT:PRINT
80 PRINT "APPLE II PORT: VINCE WEAVER"
90 PRINT "DISK CODE    : QKUMBA"
94 PRINT "LZSA CODE    : EMMANUEL MARTY"
95 PRINT
100 PRINT "WASD/ARROWS MOVE, ENTER ACTION"
105 PRINT "J TOGGLE JOYSTICK"
125 PRINT "       ______"
130 PRINT "     A \/\/\/ SOFTWARE PRODUCTION"
135 PRINT
140 PRINT " HTTP://WWW.DEATER.NET/WEAVE/VMWPROD"
150 PRINT CHR$(4)"BRUN LEMM"
