; 0 0 20 7
grey_fish_sprite:
	.byte $03,$07
	.byte $D5,$2A,$D5
	.byte $51,$2A,$55
	.byte $51,$2A,$55
	.byte $55,$2F,$55
	.byte $5F,$2B,$55
	.byte $55,$2A,$55
	.byte $55,$2A,$55
; 0 9 20 16
green_fish_sprite:
	.byte $03,$07
	.byte $D5,$54,$5A
	.byte $1A,$55,$62
	.byte $2A,$55,$62
	.byte $29,$7D,$6A
	.byte $29,$75,$7E
	.byte $2A,$55,$6A
	.byte $5A,$54,$5A
; 0 18 27 25
red_fish_sprite:
	.byte $04,$07
	.byte $D6,$D4,$AA,$AD
	.byte $9A,$D5,$AA,$B1
	.byte $AA,$D5,$AE,$B1
	.byte $A9,$D5,$AF,$D5
	.byte $A9,$D5,$AE,$F5
	.byte $9A,$D5,$AA,$D5
	.byte $D6,$D4,$AA,$AD
; 42 0 62 7
grey_fish_mask:
	.byte $03,$07
	.byte $70,$7F,$00
	.byte $7C,$7F,$33
	.byte $7F,$7F,$3F
	.byte $7F,$7F,$0F
	.byte $7F,$7F,$0F
	.byte $7F,$7F,$3F
	.byte $7C,$7F,$33
; 42 9 62 16
green_fish_mask:
	.byte $03,$07
	.byte $00,$7E,$0F
	.byte $4F,$7F,$3F
	.byte $7F,$7F,$3F
	.byte $7C,$7F,$3F
	.byte $7C,$7F,$3F
	.byte $7F,$7F,$3F
	.byte $0F,$7E,$0F
; 42 18 69 25
red_fish_mask:
	.byte $04,$07
	.byte $03,$7E,$7F,$07
	.byte $4F,$7F,$7F,$1F
	.byte $7F,$7F,$7F,$1F
	.byte $7C,$7F,$7F,$7F
	.byte $7C,$7F,$7F,$7F
	.byte $4F,$7F,$7F,$7F
	.byte $03,$7E,$7F,$07
; 0 29 20 36
left_fish_sprite:
	.byte $03,$07
	.byte $CA,$88,$AA
	.byte $92,$A2,$88
	.byte $C4,$88,$91
	.byte $91,$A2,$A4
	.byte $C4,$88,$A1
	.byte $91,$A2,$84
	.byte $C6,$88,$99
; 0 38 20 45
right_fish_sprite:
	.byte $03,$07
	.byte $AA,$89,$A1
	.byte $A1,$A2,$84
	.byte $C4,$88,$91
	.byte $92,$A2,$84
	.byte $C6,$88,$91
	.byte $91,$A2,$84
	.byte $A4,$89,$A1
; 0 47 27 54
big_fish_sprite:
	.byte $04,$07
	.byte $A9,$A3,$C4,$D0
	.byte $E4,$88,$91,$C2
	.byte $91,$A2,$C4,$C8
	.byte $C6,$88,$91,$A2
	.byte $92,$A2,$C4,$88
	.byte $E4,$88,$91,$A2
	.byte $A9,$A3,$C4,$D0
; 42 29 62 36
left_fish_mask:
	.byte $03,$07
	.byte $30,$66,$00
	.byte $4C,$19,$33
	.byte $33,$66,$0C
	.byte $4C,$19,$03
	.byte $33,$66,$0C
	.byte $4C,$19,$33
	.byte $30,$66,$00
; 42 38 62 45
right_fish_mask:
	.byte $03,$07
	.byte $00,$66,$0C
	.byte $4C,$19,$33
	.byte $33,$66,$0C
	.byte $4C,$19,$33
	.byte $30,$66,$0C
	.byte $4C,$19,$33
	.byte $03,$66,$0C
; 42 47 69 54
big_fish_mask:
	.byte $04,$07
	.byte $00,$18,$33,$06
	.byte $03,$66,$4C,$19
	.byte $4C,$19,$33,$06
	.byte $30,$66,$4C,$19
	.byte $4C,$19,$33,$66
	.byte $03,$66,$4C,$19
	.byte $00,$18,$33,$06
; 0 72 6 79
zero_sprite:
	.byte $01,$07
	.byte $1C
	.byte $36
	.byte $36
	.byte $36
	.byte $36
	.byte $36
	.byte $1C
; 14 72 20 79
one_sprite:
	.byte $01,$07
	.byte $18
	.byte $1C
	.byte $18
	.byte $18
	.byte $18
	.byte $18
	.byte $18
; 28 72 34 79
two_sprite:
	.byte $01,$07
	.byte $1E
	.byte $30
	.byte $30
	.byte $1C
	.byte $06
	.byte $06
	.byte $3E
; 42 72 48 79
three_sprite:
	.byte $01,$07
	.byte $1E
	.byte $30
	.byte $30
	.byte $1C
	.byte $30
	.byte $30
	.byte $1E
; 56 72 62 79
four_sprite:
	.byte $01,$07
	.byte $30
	.byte $38
	.byte $3C
	.byte $3E
	.byte $30
	.byte $30
	.byte $30
; 0 80 6 87
five_sprite:
	.byte $01,$07
	.byte $3E
	.byte $06
	.byte $1E
	.byte $30
	.byte $30
	.byte $30
	.byte $1E
; 14 80 20 87
six_sprite:
	.byte $01,$07
	.byte $3C
	.byte $06
	.byte $1E
	.byte $36
	.byte $36
	.byte $36
	.byte $1C
; 28 80 34 87
seven_sprite:
	.byte $01,$07
	.byte $3E
	.byte $30
	.byte $18
	.byte $18
	.byte $0C
	.byte $0C
	.byte $0C
; 42 80 48 87
eight_sprite:
	.byte $01,$07
	.byte $1C
	.byte $36
	.byte $36
	.byte $1C
	.byte $36
	.byte $36
	.byte $1C
; 56 80 62 87
nine_sprite:
	.byte $01,$07
	.byte $3C
	.byte $36
	.byte $36
	.byte $36
	.byte $3C
	.byte $30
	.byte $1E
