5 REM FUN TIMES
7 PRINT
10 PRINT "** DECEPTIVE LIST **"
20 PRINT "        BY          "
30 PRINT "   VINCE WEAVER     "
40 PRINT "********************"
50 PRINT
55 PRINT "WHATEVER YOU DO, DON'T TYPE LIST"
60 PRINT
70 END

