blue_zappo_rle:	.byte $28 ; ysize=48
	.byte $A5,$66, $62, $66, $22, $26, $A5,$66, $26
	.byte $A3,$22, $66, $A3,$22, $6E, $66, $22, $A3,$66
	.byte $22, $62, $E2, $A3,$22, $F6, $A5,$22, $A8,$66
	.byte $62, $22, $26, $66, $26, $22, $62
	.byte $22,$22, $66, $22, $62, $22,$22, $26,$26, $22
	.byte $66, $62, $66, $22, $66,$66, $A3,$22, $2F
	.byte $F2, $A4,$22, $66,$66, $26, $22, $26, $A5,$66
	.byte $62, $22, $62, $66,$66, $22, $66, $22,$22
	.byte $66,$66, $62, $22, $62, $26, $22, $66
	.byte $22, $26, $62, $A5,$22, $2F, $F2, $A3,$22
	.byte $A3,$66, $62,$62, $AA,$66, $22,$22, $62, $22, $A4,$66
	.byte $62, $22,$22, $66, $A3,$22, $26, $62, $66,$66
	.byte $22,$22, $6F, $A3,$22, $AB,$66, $26, $E6, $66,$66
	.byte $62, $22, $66, $22, $26, $A5,$66, $E2
	.byte $E6, $62,$62, $66,$66, $26, $A3,$66, $A5,$22, $AA,$66
	.byte $62, $2E, $EE, $6E, $66, $22,$22, $66
	.byte $A6,$22, $26, $EF, $EE, $66, $A7,$26, $22
	.byte $F6, $A3,$22, $A6,$66, $22, $A3,$EF, $66,$66, $62
	.byte $66,$66, $22,$22, $66, $A5,$22, $62, $26, $22
	.byte $66, $62, $A8,$22, $FF, $A3,$22, $A6,$66, $22
	.byte $A3,$EE, $66,$66, $A3,$26, $22,$22, $66, $22,$22, $62
	.byte $66,$66, $26, $22, $66, $22, $66, $62
	.byte $A7,$22, $FF, $A3,$22, $A6,$66, $22, $EE, $E6
	.byte $EE, $22,$22, $A3,$F2, $22, $62, $22, $62
	.byte $A3,$66, $26, $A5,$22, $66,$66, $A6,$22, $FF, $A3,$22
	.byte $A6,$66, $22, $A3,$EE, $6F,$6F, $A3,$66, $22, $26
	.byte $62, $22, $66,$66, $A3,$22, $6E,$6E, $FF, $22
	.byte $26, $66, $6F, $F2, $A4,$22, $26, $A3,$22
	.byte $A6,$66, $22, $A3,$EE, $66,$66, $26, $66, $A3,$22
	.byte $26, $62, $A5,$22, $66,$66, $EF, $22,$22, $A3,$66
	.byte $A3,$22, $62, $A4,$22, $A6,$66, $22,$22, $EE,$EE, $FE
	.byte $66,$66, $22,$22, $62, $26, $22, $26, $22,$22
	.byte $66, $22,$22, $26,$26, $2E, $22,$22, $26, $62
	.byte $26, $22,$22, $62, $26, $A4,$22, $A6,$66, $22,$22
	.byte $EE,$EE, $FF, $66, $26, $22,$22, $66, $A3,$22
	.byte $62,$62, $26, $AB,$22, $62, $26, $A5,$22, $A6,$66
	.byte $22,$22, $EE, $2E, $A5,$22, $F2, $22, $2F
	.byte $A4,$22, $A4,$EE, $22, $F2, $2F, $E2, $EE
	.byte $22, $F2, $A7,$22, $A6,$66, $A8,$22, $2F, $22
	.byte $2F, $A5,$22, $62, $6E, $26, $22, $2F
	.byte $22,$22, $2F, $E2, $EE, $FF, $A7,$22, $A4,$66
	.byte $26, $AD,$22, $26, $66, $6E, $EE, $A8,$22
	.byte $EE, $E6, $FF, $A7,$22, $66,$66, $26, $AF,$22
	.byte $26, $66, $22, $6E, $A3,$22, $2F, $A4,$22
	.byte $EE,$EE, $FF, $A7,$22, $26, $A0,$11,$22, $66, $E2
	.byte $22, $E2,$E2, $2E, $A7,$22, $EE, $FF, $A0,$15,$22
	.byte $62, $A3,$22, $26,$26, $66, $AA,$22, $EE, $FF
	.byte $A0,$16,$22, $26, $A4,$22, $66,$66, $62, $A8,$22, $2F
	.byte $A0,$A8,$22
	.byte $A1
zappo01_rle:	.byte $28 ; ysize=48
	.byte $A0,$19,$AA, $A3,$AF, $A0,$7B,$AA, $EA, $FF,$FF, $A0,$26,$AA, $EE
	.byte $FF,$FF, $A0,$25,$AA, $A0,$01,$AE, $A0,$02,$AF, $A0,$41,$AA, $EA, $A0,$25,$AA
	.byte $EA, $A0,$01,$AE, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$6E,$AA
	.byte $A1
zappo02_rle:	.byte $28 ; ysize=48
	.byte $A0,$41,$AA, $A3,$FF, $A0,$53,$AA, $FA, $FF, $EE, $A0,$25,$AA
	.byte $A0,$01,$AE, $FF, $EE, $A0,$25,$AA, $A0,$01,$AE, $A0,$01,$AF, $A0,$01,$AE
	.byte $A0,$42,$AA, $EA, $A0,$01,$AE, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$94,$AA
	.byte $A1
zappo03_rle:	.byte $28 ; ysize=48
	.byte $A7,$EE, $22, $2E, $A5,$EE, $2E, $22, $EE,$EE
	.byte $22, $A3,$EE, $2E, $A5,$EE, $22, $A5,$EE, $22
	.byte $AD,$EE, $E2, $22, $2E, $EE, $2E, $22
	.byte $E2, $2E, $EE, $22, $EE, $FE, $EE
	.byte $E2, $A6,$EE, $22, $A5,$EE, $E2, $2E, $AE,$EE
	.byte $E2, $22, $E2, $EE,$EE, $22,$22, $A3,$EE, $EF
	.byte $FE, $A4,$EE, $FF, $22, $E2, $2E, $EE
	.byte $FE, $A3,$EE, $E2, $2E, $A0,$12,$EE, $22, $EE
	.byte $2E, $A4,$EE, $EF, $FE, $EE,$EE, $66, $22
	.byte $EE, $FE, $EF, $A5,$EE, $22, $AE,$EE, $2E
	.byte $FE, $EE,$EE, $22, $EE, $22, $EE, $E2
	.byte $A4,$2E, $6F, $EE, $E6, $E2, $EF, $FF,$FF
	.byte $A0,$13,$EE, $E2, $2F, $FF, $EF, $EE, $22
	.byte $EE, $22, $A6,$EE, $E6, $FF, $EE,$EE, $2E
	.byte $2F,$2F, $A4,$2E, $EE, $22, $A9,$EE, $22, $A3,$FF
	.byte $EE,$EE, $E2, $EE,$EE, $22, $EE, $22, $A5,$EE
	.byte $FE, $EF, $EE, $2E, $A9,$EE, $22, $A9,$EE
	.byte $22, $A3,$FF, $A5,$EE, $22, $EE, $22, $EE,$EE
	.byte $FE, $EF,$EF, $2F, $EE, $66, $EE, $2E
	.byte $EF, $FE, $A6,$EE, $22, $A9,$EE, $22, $FF
	.byte $F6, $FF, $EE,$EE, $A3,$FE, $22, $2E, $EE
	.byte $FE, $EF, $EE,$EE, $2E, $AD,$EE, $22, $A9,$EE
	.byte $22, $A3,$FF, $EF,$EF, $A3,$EE, $22, $E2, $2E
	.byte $A3,$EE, $E2, $EE,$EE, $6E,$6E, $FF, $EE, $E2
	.byte $EE, $EF, $FE, $A4,$EE, $E2, $A9,$EE, $22
	.byte $A3,$FF, $EE,$EE, $2E, $EE, $22,$22, $2E, $E2
	.byte $2E, $EE, $E2, $A3,$EE, $66,$66, $EF, $A8,$EE
	.byte $2E, $AA,$EE, $22,$22, $A3,$FF, $EE,$EE, $22,$22, $62
	.byte $26, $EE, $E2, $EE,$EE, $FF, $EE,$EE, $E6,$E6
	.byte $A3,$EE, $E2, $62, $A3,$EE, $2E, $E2, $AA,$EE
	.byte $22,$22, $A3,$FF, $EE, $2E, $22,$22, $66, $E2
	.byte $EE,$EE, $FE,$FE, $2F, $AA,$2E, $EE, $2E, $E2
	.byte $AB,$EE, $22,$22, $FF, $2F, $A4,$22, $E2, $FE
	.byte $2E, $2F, $A4,$22, $A4,$FF, $22, $F2, $2F
	.byte $E2, $EE, $22, $F2, $AD,$EE, $22,$22, $E2
	.byte $2E, $A3,$22, $EE, $2F, $22, $2F, $A5,$22
	.byte $62, $6F, $26, $22, $2F, $22,$22, $EF
	.byte $F2, $FF,$FF, $AB,$EE, $2E, $22, $E2, $2E
	.byte $A5,$22, $2E, $A4,$EE, $E6, $66, $6E, $EE
	.byte $2E,$2E, $EE, $2E, $EE, $22, $EE,$EE, $FF
	.byte $F6, $FF, $A4,$2E, $A5,$EE, $2E, $A3,$22, $EE
	.byte $A7,$22, $A4,$EE, $E6, $66, $22, $6E, $22,$22
	.byte $EE, $EF, $EE, $22, $EE,$EE, $A3,$FF, $A7,$22
	.byte $2E, $A6,$22, $2E,$2E, $E2, $A4,$22, $A4,$EE, $66
	.byte $F2, $22, $F2,$F2, $2E, $A7,$EE, $FF,$FF, $AF,$22
	.byte $E2, $2E, $A4,$22, $A4,$EE, $E6,$E6, $66, $A3,$22
	.byte $A7,$EE, $FF,$FF, $AD,$22, $E2, $2E, $A7,$22, $2E
	.byte $22, $A3,$2E, $66,$66, $62, $22, $2E, $A6,$EE
	.byte $2F, $A0,$A8,$22
	.byte $A1
zappo04_rle:	.byte $28 ; ysize=48
	.byte $A0,$92,$AA, $FF, $A0,$29,$AA, $FA, $FF, $A0,$26,$AA, $A0,$02,$AF
	.byte $A0,$21,$AA, $FA, $A0,$01,$AF, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$B9,$AA
	.byte $A1
zappo05_rle:	.byte $28 ; ysize=48
	.byte $A0,$B8,$AA, $EE, $EA, $EF, $FA, $A0,$24,$AA, $A0,$01,$AE
	.byte $EF, $EE, $FF, $A0,$24,$AA, $A0,$01,$AF, $A0,$01,$AA, $A0,$01,$AE
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A0,$B7,$AA
	.byte $A1
zappo06_rle:	.byte $28 ; ysize=48
	.byte $A0,$B7,$AA, $FA, $EF,$EF, $FA,$FA, $EA,$EA, $A0,$20,$AA, $FF
	.byte $EE, $FF,$FF, $EE, $FF, $A0,$02,$AE, $A0,$20,$AA, $FF
	.byte $FE, $EF,$EF, $FE, $FF, $A0,$22,$AA, $A6,$AF, $A0,$FF,$AA
	.byte $A0,$FF,$AA, $A0,$8E,$AA
	.byte $A1
zappo07_rle:	.byte $28 ; ysize=48
	.byte $A0,$E1,$AA, $FF, $A0,$27,$AA, $FF, $A0,$26,$AA, $FA, $A0,$01,$AF
	.byte $A0,$26,$AA, $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $FF, $A0,$27,$AA
	.byte $FF, $A0,$27,$AA, $FF, $A0,$FF,$AA, $A0,$C8,$AA
	.byte $A1
zappo08_rle:	.byte $28 ; ysize=48
	.byte $A0,$E1,$AA, $A0,$01,$AF, $A0,$25,$AA, $FA, $A0,$01,$AF, $A0,$26,$AA, $FF
	.byte $A0,$27,$AA, $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $FF, $A0,$28,$AA
	.byte $FF, $A0,$27,$AA, $FF, $A0,$FF,$AA, $A0,$C8,$AA
	.byte $A1
zappo09_rle:	.byte $28 ; ysize=48
	.byte $A0,$B7,$AA, $FA, $FF,$FF, $FA,$FA, $A0,$22,$AA, $A6,$FF, $A0,$22,$AA
	.byte $A6,$FF, $A0,$22,$AA, $FF,$FF, $A4,$AF, $A0,$23,$AA, $FF, $A0,$27,$AA
	.byte $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $FF
	.byte $A0,$FF,$AA, $A0,$C9,$AA
	.byte $A1
zappo10_rle:	.byte $28 ; ysize=48
	.byte $A0,$66,$AA, $A3,$FF, $A0,$24,$AA, $FA, $A3,$FF, $A0,$24,$AA, $FF
	.byte $A0,$01,$AF, $A0,$01,$AA, $A0,$01,$AF, $FA, $A0,$23,$AA, $FF, $A3,$AA
	.byte $A0,$01,$AF, $A0,$23,$AA, $FF, $A0,$28,$AA, $A0,$01,$AF, $FA, $A0,$27,$AA
	.byte $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $FF
	.byte $A0,$27,$AA, $FF, $A0,$FF,$AA, $A0,$C9,$AA
	.byte $A1
zappo11_rle:	.byte $28 ; ysize=48
	.byte $A0,$3F,$AA, $FF, $A0,$27,$AA, $FF,$FF, $A0,$26,$AA, $FF,$FF, $A0,$24,$AA
	.byte $FA, $A4,$FF, $FA,$FA, $A0,$21,$AA, $A0,$01,$AF, $A6,$FF, $A0,$22,$AA
	.byte $A6,$FF, $A0,$21,$AA, $A0,$01,$AF, $A3,$FF, $A3,$AF, $A0,$22,$AA, $A3,$FF
	.byte $A0,$24,$AA, $A4,$FF, $A0,$23,$AA, $A3,$AF, $FF,$FF, $A0,$26,$AA, $FF,$FF
	.byte $A0,$25,$AA, $FA, $FF, $A0,$02,$AF, $A0,$FF,$AA, $A0,$C7,$AA
	.byte $A1
zappo12_rle:	.byte $28 ; ysize=48
	.byte $A0,$E1,$AA, $FF, $A0,$27,$AA, $FF, $A0,$26,$AA, $FF,$FF, $A0,$24,$AA
	.byte $FA, $FF,$FF, $A0,$23,$AA, $FA, $A3,$FF, $A0,$01,$AF, $A0,$22,$AA
	.byte $A5,$FF, $FA, $A0,$21,$AA, $FA, $A6,$FF, $A0,$21,$AA, $A7,$FF
	.byte $FA, $A0,$FF,$AA, $A0,$C7,$AA
	.byte $A1
zappo13_rle:	.byte $28 ; ysize=48
	.byte $A0,$E1,$AA, $FF, $A0,$27,$AA, $FF, $A0,$26,$AA, $FF,$FF, $A0,$24,$AA
	.byte $FA, $FF,$FF, $A0,$23,$AA, $FA, $A4,$FF, $A0,$01,$AA, $FF
	.byte $A0,$20,$AA, $A8,$FF, $A0,$1D,$AA, $A3,$FA, $A8,$FF, $A4,$FA, $A0,$19,$AA
	.byte $A0,$11,$FF, $A0,$18,$AA, $A0,$01,$AF, $A0,$FF,$AA, $A0,$A7,$AA
	.byte $A1
zappo14_rle:	.byte $28 ; ysize=48
	.byte $A0,$E1,$AA, $FF, $A0,$27,$AA, $FF, $A0,$26,$AA, $FF,$FF, $A0,$24,$AA
	.byte $FA, $FF,$FF, $A0,$23,$AA, $FA, $A4,$FF, $A0,$01,$AA, $FF
	.byte $A0,$20,$AA, $A8,$FF, $A0,$1D,$AA, $A3,$FA, $A8,$FF, $A4,$FA, $A0,$19,$AA
	.byte $A0,$11,$FF, $A0,$15,$AA, $A0,$13,$FF, $A0,$14,$AA, $FA, $A0,$13,$FF, $A0,$14,$AA
	.byte $A0,$14,$FF, $A0,$15,$AA, $FF,$FF, $A0,$02,$AF, $AF,$FF, $A0,$15,$AA, $FF,$FF
	.byte $A0,$02,$AA, $A0,$01,$AF, $AE,$FF, $A0,$15,$AA, $FF,$FF, $A6,$AA, $FF
	.byte $A8,$AA, $FF,$FF, $A0,$01,$AF, $A0,$13,$AA, $A4,$AF, $A8,$AA, $FA,$FA
	.byte $A4,$AA, $A0,$01,$AF, $A0,$22,$AA, $A3,$AF, $A0,$83,$AA
	.byte $A1
zappo15_rle:	.byte $28 ; ysize=48
	.byte $A0,$3F,$AA, $FF, $A0,$27,$AA, $FF,$FF, $A0,$26,$AA, $FF,$FF, $A0,$24,$AA
	.byte $FA, $A4,$FF, $FA,$FA, $A0,$21,$AA, $A0,$01,$AF, $A6,$FF, $A0,$22,$AA
	.byte $A6,$FF, $A0,$22,$AA, $A7,$FF, $FA, $A0,$20,$AA, $A8,$FF, $A0,$1C,$AA
	.byte $A3,$FA, $AA,$FF, $FA, $A0,$19,$AA, $FA, $EF, $AD,$FF
	.byte $A0,$17,$AA, $FA, $FF,$FF, $FE, $EF, $AD,$FF, $FA
	.byte $A0,$12,$AA, $EF,$EF, $A5,$FF, $FE, $AD,$FF, $EF, $FA
	.byte $AF,$AA, $A3,$EE, $A0,$13,$FF, $EF, $FE, $FF, $AF,$AA
	.byte $EE,$EE, $A0,$14,$FF, $FE, $FF,$FF, $FA, $AE,$AA, $EE,$EE
	.byte $EF, $A0,$16,$FF, $EF,$EF, $AB,$AA, $EA,$EA, $A3,$EE, $A0,$14,$FF
	.byte $A5,$EE, $22,$22, $A8,$AA, $EF, $FE, $A3,$EE, $A0,$14,$FF
	.byte $A5,$EE, $22,$22, $A8,$AA, $FE, $EF, $A3,$EE, $A0,$14,$FF
	.byte $A5,$EE, $22,$22, $A8,$AA, $A5,$EE, $EF,$EF, $A0,$10,$FF, $EF
	.byte $A6,$EE, $22,$22, $A8,$AA, $A7,$EE, $FE, $FF,$FF, $EE
	.byte $EF, $FF, $FE, $A0,$10,$EE, $22,$22, $A8,$AA, $A5,$EE
	.byte $FE, $FF,$FF, $EF, $A4,$EE, $EF,$EF, $AF,$EE, $22,$22
	.byte $A8,$AA, $A0,$1E,$EE, $22,$22, $A8,$AA, $A0,$1E,$EE, $22,$22
	.byte $A1
zappo16_rle:	.byte $28 ; ysize=48
	.byte $A0,$18,$AA, $A3,$FF, $A0,$25,$AA, $A3,$FF, $A0,$25,$AA, $A3,$FF, $A0,$25,$AA
	.byte $A3,$FF, $A0,$25,$AA, $A3,$FF, $A0,$25,$AA, $A3,$FF, $A0,$25,$AA, $A3,$FF
	.byte $EA, $A0,$24,$AA, $A4,$FF, $E6, $6A, $A0,$20,$AA, $FA
	.byte $A6,$FF, $EE, $A3,$66, $6A,$6A, $A0,$19,$AA, $FA, $AA,$FF
	.byte $F6, $A3,$66, $A0,$18,$AA, $AD,$FF, $F6, $66,$66, $EA
	.byte $A0,$13,$AA, $6A, $F6, $FA,$FA, $AE,$FF, $66, $E6
	.byte $A0,$01,$AE, $A0,$13,$AA, $66, $A0,$11,$FF, $E6, $6E, $A0,$10,$AA
	.byte $6A, $66,$66, $A0,$13,$FF, $66,$66, $A0,$10,$AA, $A0,$01,$A6, $66
	.byte $F6, $A0,$13,$FF, $66,$66, $A0,$11,$AA, $66, $A0,$14,$FF, $66,$66
	.byte $A0,$11,$AA, $66,$66, $A0,$13,$FF, $66,$66, $A0,$11,$AA, $66,$66, $A0,$13,$FF
	.byte $66,$66, $A0,$11,$AA, $66,$66, $A0,$13,$FF, $6F, $66, $A0,$10,$AA
	.byte $6A, $66, $6F, $A0,$12,$FF, $A3,$66, $A0,$10,$AA, $A4,$66
	.byte $6F, $A0,$10,$FF, $A3,$66, $A0,$10,$AA, $A6,$66, $6F, $AD,$FF
	.byte $A4,$66, $A0,$10,$AA, $A8,$66, $6F, $AA,$FF, $6F, $A4,$66
	.byte $A0,$10,$AA, $A0,$01,$A6, $A8,$66, $AA,$FF, $A4,$66, $A0,$01,$A6, $A5,$AA
	.byte $A1
zappo17_rle:	.byte $28 ; ysize=48
	.byte $A0,$12,$AA, $A0,$10,$FF, $A0,$19,$AA, $AE,$FF, $A0,$1B,$AA, $AC,$FF, $A0,$1C,$AA
	.byte $AA,$FF, $A0,$01,$AF, $A0,$1E,$AA, $A0,$01,$AF, $A6,$FF, $A0,$01,$AF, $A0,$21,$AA
	.byte $A6,$FF, $A0,$22,$AA, $A6,$FF, $A0,$22,$AA, $A8,$FF, $FA,$FA, $A0,$11,$AA
	.byte $FA, $A0,$02,$AA, $A6,$FA, $A0,$11,$FF, $FA,$FA, $A3,$AA, $FF
	.byte $A5,$EE, $66, $A3,$FF, $6F,$6F, $A4,$FF, $F6, $A0,$16,$FF
	.byte $A0,$01,$AA, $FF, $A5,$EE, $66, $A3,$FF, $66,$66, $A0,$1B,$FF
	.byte $A0,$01,$AA, $FF, $A5,$EE, $66,$66, $A3,$FF, $66, $A0,$1B,$FF
	.byte $A0,$01,$AA, $FF,$FF, $A4,$EE, $66,$66, $A3,$FF, $66, $A0,$1B,$FF
	.byte $A0,$01,$AA, $FF,$FF, $A4,$EE, $66,$66, $FF, $6F, $66
	.byte $A0,$1C,$FF, $FA, $A3,$FF, $FE, $EE,$EE, $A5,$66, $A0,$22,$FF
	.byte $A3,$66, $F6,$F6, $A0,$FF,$FF, $A0,$5F,$FF
	.byte $A1
