include ../../../Makefile.inc

PNG2RLE = ../../../gr-utils/png2rle
PNG2LZ4 = ../../../gr-utils/png2lz4


all:	intro_zappo.inc intro_gone.inc intro_zappo_lz4.inc

#####

intro_zappo.inc:	$(PNG2RLE) \
	blue_zappo.png \
	zappo01.png zappo02.png zappo03.png zappo04.png \
	zappo05.png zappo06.png zappo07.png zappo08.png \
	zappo09.png zappo10.png zappo11.png zappo12.png \
	zappo13.png zappo14.png zappo15.png zappo16.png \
	zappo17.png
	$(PNG2RLE) asm blue_zappo.png blue_zappo_rle > intro_zappo.inc
	$(PNG2RLE) asm zappo01.png zappo01_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo02.png zappo02_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo03.png zappo03_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo04.png zappo04_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo05.png zappo05_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo06.png zappo06_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo07.png zappo07_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo08.png zappo08_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo09.png zappo09_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo10.png zappo10_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo11.png zappo11_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo12.png zappo12_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo13.png zappo13_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo14.png zappo14_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo15.png zappo15_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo16.png zappo16_rle >> intro_zappo.inc
	$(PNG2RLE) asm zappo17.png zappo17_rle >> intro_zappo.inc


intro_zappo_lz4.inc:	$(PNG2LZ4) \
	blue_zappo.png \
	zappo01.png zappo02.png zappo03.png zappo04.png \
	zappo05.png zappo06.png zappo07.png zappo08.png \
	zappo09.png zappo10.png zappo11.png zappo12.png \
	zappo13.png zappo14.png zappo15.png zappo16.png \
	zappo17.png
	$(PNG2LZ4) asm blue_zappo.png blue_zappo_rle > intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo01.png zappo01_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo02.png zappo02_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo03.png zappo03_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo04.png zappo04_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo05.png zappo05_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo06.png zappo06_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo07.png zappo07_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo08.png zappo08_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo09.png zappo09_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo10.png zappo10_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo11.png zappo11_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo12.png zappo12_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo13.png zappo13_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo14.png zappo14_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo15.png zappo15_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo16.png zappo16_rle >> intro_zappo_lz4.inc
	$(PNG2LZ4) asm zappo17.png zappo17_rle >> intro_zappo_lz4.inc


#####

intro_gone.inc:	$(PNG2RLE) \
	intro_gone.png \
	gone01.png gone02.png gone03.png gone04.png gone05.png \
	gone06.png gone07.png gone08.png gone09.png gone10.png \
	gone11.png gone12.png gone13.png gone14.png gone15.png \
	gone16.png gone17.png gone18.png gone19.png gone20.png \
	gone21.png gone22.png gone23.png gone24.png gone25.png \
	gone26.png gone27.png gone28.png gone29.png gone30.png \
	gone31.png gone32.png gone33.png gone34.png gone35.png \
	gone36.png gone37.png gone38.png gone39.png gone40.png \
	gone41.png gone42.png gone43.png
	$(PNG2RLE) asm intro_gone.png gone_rle > intro_gone.inc
	$(PNG2RLE) asm gone01.png gone01_rle >> intro_gone.inc
	$(PNG2RLE) asm gone02.png gone02_rle >> intro_gone.inc
	$(PNG2RLE) asm gone03.png gone03_rle >> intro_gone.inc
	$(PNG2RLE) asm gone04.png gone04_rle >> intro_gone.inc
	$(PNG2RLE) asm gone05.png gone05_rle >> intro_gone.inc
	$(PNG2RLE) asm gone06.png gone06_rle >> intro_gone.inc
	$(PNG2RLE) asm gone07.png gone07_rle >> intro_gone.inc
	$(PNG2RLE) asm gone08.png gone08_rle >> intro_gone.inc
	$(PNG2RLE) asm gone09.png gone09_rle >> intro_gone.inc
	$(PNG2RLE) asm gone10.png gone10_rle >> intro_gone.inc
	$(PNG2RLE) asm gone11.png gone11_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone12.png gone12_rle >> intro_gone.inc
	$(PNG2RLE) asm gone13.png gone13_rle >> intro_gone.inc
	$(PNG2RLE) asm gone14.png gone14_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone15.png gone15_rle >> intro_gone.inc
	$(PNG2RLE) asm gone16.png gone16_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone17.png gone17_rle >> intro_gone.inc
	$(PNG2RLE) asm gone18.png gone18_rle >> intro_gone.inc
	$(PNG2RLE) asm gone19.png gone19_rle >> intro_gone.inc
	$(PNG2RLE) asm gone20.png gone20_rle >> intro_gone.inc
	$(PNG2RLE) asm gone21.png gone21_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone22.png gone22_rle >> intro_gone.inc
	$(PNG2RLE) asm gone23.png gone23_rle >> intro_gone.inc
	$(PNG2RLE) asm gone24.png gone24_rle >> intro_gone.inc
	$(PNG2RLE) asm gone25.png gone25_rle >> intro_gone.inc
	$(PNG2RLE) asm gone26.png gone26_rle >> intro_gone.inc
	$(PNG2RLE) asm gone27.png gone27_rle >> intro_gone.inc
	$(PNG2RLE) asm gone28.png gone28_rle >> intro_gone.inc
	$(PNG2RLE) asm gone29.png gone29_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone30.png gone30_rle >> intro_gone.inc
	$(PNG2RLE) asm gone31.png gone31_rle >> intro_gone.inc
	$(PNG2RLE) asm gone32.png gone32_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone33.png gone33_rle >> intro_gone.inc
	$(PNG2RLE) asm gone34.png gone34_rle >> intro_gone.inc
	$(PNG2RLE) asm gone35.png gone35_rle >> intro_gone.inc
	$(PNG2RLE) asm gone36.png gone36_rle >> intro_gone.inc
	$(PNG2RLE) asm gone37.png gone37_rle >> intro_gone.inc
	$(PNG2RLE) asm gone38.png gone38_rle >> intro_gone.inc
	$(PNG2RLE) asm gone39.png gone39_rle >> intro_gone.inc
	$(PNG2RLE) asm gone40.png gone40_rle >> intro_gone.inc
	$(PNG2RLE) asm gone41.png gone41_rle >> intro_gone.inc
	$(PNG2RLE) asm gone42.png gone42_rle >> intro_gone.inc
	$(PNG2RLE) asm gone43.png gone43_rle >> intro_gone.inc


#####

clean:		
		rm -f *~ *.inc

