5 HOME
10 PRINT "LOADING DUKE V0.02"
20 PRINT "  DUKE NUKEM PROOF-OF-CONCEPT DEMAKE"
30 PRINT:PRINT
70 PRINT "BASED ON DUKE NUKEM1 BY APOGEE"
75 PRINT:PRINT
80 PRINT "APPLE II PORT: VINCE WEAVER"
90 PRINT "DISK CODE    : QKUMBA"
94 PRINT "LZSA CODE    : EMMANUEL MARTY"
95 PRINT
100 PRINT "       ______"
110 PRINT "     A \/\/\/ SOFTWARE PRODUCTION"
115 PRINT
120 PRINT " HTTP://WWW.DEATER.NET/WEAVE/VMWPROD"
130 PRINT CHR$(4);"BRUN LOADER"

