include ../../../../../Makefile.inc

PNG2GR = ../../../../../utils/gr-utils/png2gr
LZSA = ~/research/lzsa/lzsa/lzsa

all:	ootw_c14_arena.inc

#####

ootw_c14_arena.inc:	\
	arena.lzsa inside_bg.lzsa \
	inside03.lzsa inside04.lzsa inside05.lzsa inside06.lzsa \
	inside07.lzsa inside08.lzsa inside09.lzsa inside10.lzsa \
	inside11.lzsa inside12.lzsa inside13.lzsa inside14.lzsa \
	inside15.lzsa inside16.lzsa inside17.lzsa inside18.lzsa \
	inside19.lzsa inside20.lzsa inside21.lzsa inside22.lzsa \
	inside23.lzsa inside24.lzsa inside25.lzsa inside26.lzsa \
	inside27.lzsa inside28.lzsa inside29.lzsa inside30.lzsa \
	inside31.lzsa inside32.lzsa inside33.lzsa inside34.lzsa \
	inside35.lzsa inside36.lzsa inside37.lzsa inside38.lzsa \
	inside39.lzsa inside40.lzsa inside41.lzsa inside42.lzsa \
	inside43.lzsa inside44.lzsa inside45.lzsa \
	lidclose_bg.lzsa \
	lidclose01.lzsa lidclose02.lzsa lidclose03.lzsa lidclose04.lzsa \
	lidclose05.lzsa lidclose06.lzsa lidclose07.lzsa lidclose08.lzsa \
	lidclose09.lzsa lidclose10.lzsa lidclose11.lzsa lidclose12.lzsa \
	lidclose13.lzsa lidclose14.lzsa lidclose15.lzsa lidclose16.lzsa \
	lidclose17.lzsa \
	door_open_bg.lzsa
	echo "arena_lzsa: .incbin \"arena.lzsa\"" > ootw_c14_arena.inc
	echo "inside_bg_lzsa: .incbin \"inside_bg.lzsa\"" >> ootw_c14_arena.inc
	echo "inside03_lzsa: .incbin \"inside03.lzsa\"" >> ootw_c14_arena.inc
	echo "inside04_lzsa: .incbin \"inside04.lzsa\"" >> ootw_c14_arena.inc
	echo "inside05_lzsa: .incbin \"inside05.lzsa\"" >> ootw_c14_arena.inc
	echo "inside06_lzsa: .incbin \"inside06.lzsa\"" >> ootw_c14_arena.inc
	echo "inside07_lzsa: .incbin \"inside07.lzsa\"" >> ootw_c14_arena.inc
	echo "inside08_lzsa: .incbin \"inside08.lzsa\"" >> ootw_c14_arena.inc
	echo "inside09_lzsa: .incbin \"inside09.lzsa\"" >> ootw_c14_arena.inc
	echo "inside10_lzsa: .incbin \"inside10.lzsa\"" >> ootw_c14_arena.inc
	echo "inside11_lzsa: .incbin \"inside11.lzsa\"" >> ootw_c14_arena.inc
	echo "inside12_lzsa: .incbin \"inside12.lzsa\"" >> ootw_c14_arena.inc
	echo "inside13_lzsa: .incbin \"inside13.lzsa\"" >> ootw_c14_arena.inc
	echo "inside14_lzsa: .incbin \"inside14.lzsa\"" >> ootw_c14_arena.inc
	echo "inside15_lzsa: .incbin \"inside15.lzsa\"" >> ootw_c14_arena.inc
	echo "inside16_lzsa: .incbin \"inside16.lzsa\"" >> ootw_c14_arena.inc
	echo "inside17_lzsa: .incbin \"inside17.lzsa\"" >> ootw_c14_arena.inc
	echo "inside18_lzsa: .incbin \"inside18.lzsa\"" >> ootw_c14_arena.inc
	echo "inside19_lzsa: .incbin \"inside19.lzsa\"" >> ootw_c14_arena.inc
	echo "inside20_lzsa: .incbin \"inside20.lzsa\"" >> ootw_c14_arena.inc
	echo "inside21_lzsa: .incbin \"inside21.lzsa\"" >> ootw_c14_arena.inc
	echo "inside22_lzsa: .incbin \"inside22.lzsa\"" >> ootw_c14_arena.inc
	echo "inside23_lzsa: .incbin \"inside23.lzsa\"" >> ootw_c14_arena.inc
	echo "inside24_lzsa: .incbin \"inside24.lzsa\"" >> ootw_c14_arena.inc
	echo "inside25_lzsa: .incbin \"inside25.lzsa\"" >> ootw_c14_arena.inc
	echo "inside26_lzsa: .incbin \"inside26.lzsa\"" >> ootw_c14_arena.inc
	echo "inside27_lzsa: .incbin \"inside27.lzsa\"" >> ootw_c14_arena.inc
	echo "inside28_lzsa: .incbin \"inside28.lzsa\"" >> ootw_c14_arena.inc
	echo "inside29_lzsa: .incbin \"inside29.lzsa\"" >> ootw_c14_arena.inc
	echo "inside30_lzsa: .incbin \"inside30.lzsa\"" >> ootw_c14_arena.inc
	echo "inside31_lzsa: .incbin \"inside31.lzsa\"" >> ootw_c14_arena.inc
	echo "inside32_lzsa: .incbin \"inside32.lzsa\"" >> ootw_c14_arena.inc
	echo "inside33_lzsa: .incbin \"inside33.lzsa\"" >> ootw_c14_arena.inc
	echo "inside34_lzsa: .incbin \"inside34.lzsa\"" >> ootw_c14_arena.inc
	echo "inside35_lzsa: .incbin \"inside35.lzsa\"" >> ootw_c14_arena.inc
	echo "inside36_lzsa: .incbin \"inside36.lzsa\"" >> ootw_c14_arena.inc
	echo "inside37_lzsa: .incbin \"inside37.lzsa\"" >> ootw_c14_arena.inc
	echo "inside38_lzsa: .incbin \"inside38.lzsa\"" >> ootw_c14_arena.inc
	echo "inside39_lzsa: .incbin \"inside39.lzsa\"" >> ootw_c14_arena.inc
	echo "inside40_lzsa: .incbin \"inside40.lzsa\"" >> ootw_c14_arena.inc
	echo "inside41_lzsa: .incbin \"inside41.lzsa\"" >> ootw_c14_arena.inc
	echo "inside42_lzsa: .incbin \"inside42.lzsa\"" >> ootw_c14_arena.inc
	echo "inside43_lzsa: .incbin \"inside43.lzsa\"" >> ootw_c14_arena.inc
	echo "inside44_lzsa: .incbin \"inside44.lzsa\"" >> ootw_c14_arena.inc
	echo "inside45_lzsa: .incbin \"inside45.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose_bg_lzsa: .incbin \"lidclose_bg.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose01_lzsa: .incbin \"lidclose01.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose02_lzsa: .incbin \"lidclose02.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose03_lzsa: .incbin \"lidclose03.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose04_lzsa: .incbin \"lidclose04.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose05_lzsa: .incbin \"lidclose05.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose06_lzsa: .incbin \"lidclose06.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose07_lzsa: .incbin \"lidclose07.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose08_lzsa: .incbin \"lidclose08.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose09_lzsa: .incbin \"lidclose09.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose10_lzsa: .incbin \"lidclose10.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose11_lzsa: .incbin \"lidclose11.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose12_lzsa: .incbin \"lidclose12.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose13_lzsa: .incbin \"lidclose13.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose14_lzsa: .incbin \"lidclose14.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose15_lzsa: .incbin \"lidclose15.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose16_lzsa: .incbin \"lidclose16.lzsa\"" >> ootw_c14_arena.inc
	echo "lidclose17_lzsa: .incbin \"lidclose17.lzsa\"" >> ootw_c14_arena.inc
	echo "door_open_bg_lzsa: .incbin \"door_open_bg.lzsa\"" >> ootw_c14_arena.inc


#####

%.gr:	%.png
	$(PNG2GR) $< $@

%.lzsa:	%.gr
	$(LZSA) -r -f2 $< $@

#####

clean:		
		rm -f *~ *.o *.lst *.lzsa *.inc
