all:
	cd boxes && make
	cd checkers && make
	cd drops && make
	cd mode7 && make
	cd plasma && make
	cd rasterbars && make
	cd rotozoom && make
	cd scroll_text && make
	cd sierp && make
	cd starfield && make

clean:
	cd boxes && make clean
	cd checkers && make clean
	cd drops && make clean
	cd mode7 && make clean
	cd plasma && make clean
	cd rasterbars && make clean
	cd rotozoom && make clean
	cd scroll_text && make clean
	cd sierp && make clean
	cd starfield && make clean
	rm -f *~

