all:
	cd boxes && make
	cd mode7 && make
	cd rasterbars && make
	cd rotozoom && make
	cd scroll_text && make
	cd starfield && make

clean:
	cd boxes && make clean
	cd mode7 && make clean
	cd rasterbars && make clean
	cd rotozoom && make clean
	cd scroll_text && make clean
	cd starfield && make clean
	rm -f *~

