aperture:
	.asciiz "              .,-:;//;:=,"
	.asciiz "          . :H@@@MM@M#H/.,+%;,"
	.asciiz "       ,/X+ +M@@M@MM%=,-%HMMM@X/,"
	.asciiz "     -+@MM; $M@@MH+-,;XMMMM@MMMM@+-"
	.asciiz "    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/."
	.asciiz "  ,%MM@@MH ,@%=            .---=-=:=,."
	.asciiz "  =@#@@@MX .,              -%HX$$%%%+;"
	.asciiz " =-./@M@M$                  .;@MMMM@MM:"
	.asciiz " X@/ -$MM/                    .+MM@@@M$"
	.asciiz ",@M@H: :@:                    . =X#@@@@-";
	.asciiz ",@@@MMX, .                    /H- ;@M@M=";
	.asciiz ".H@@@@M@+,                    %MM+..%#$.";
	.asciiz " /MMMM@MMH/.                  XM@MH; =;"
	.asciiz "  /%+%$XHH@$=              , .H@@@@MX,"
	.asciiz "   .=--------.           -%H.,@@@@@MX,"
	.asciiz "   .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%."
	.asciiz "     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX="
	.asciiz "       =%@M@M#@$-.=$@MM@@@M; %M%="
	.asciiz "         ,:+$+-,/H#MMMMMMM@= =,"
	.asciiz "               =++%%%%+/:-."

radioactive:
	.asciiz "             =+$HM####@H%;,"
	.asciiz "          /H###############M$,"
	.asciiz "          ,@################+"
	.asciiz "           .H##############+"
	.asciiz "             X############/"
	.asciiz "              $##########/"
	.asciiz "               %########/"
	.asciiz "                /X/;;+X/"
	.asciiz " "
	.asciiz "                 -XHHX-"
	.asciiz "                ,######,"
	.asciiz "#############X  .M####M.  X#############";
	.asciiz "##############-   -//-   -##############";
	.asciiz "X##############%,      ,+##############X";
	.asciiz "-##############X        X##############-";
	.asciiz " %############%          %############%"
	.asciiz "  %##########;            ;##########%"
	.asciiz "   ;#######M=              =M#######;"
	.asciiz "    .+M###@,                ,@###M+."
	.asciiz "       :XH.                  .HX:"

atom:
	.asciiz "                 =/;;/-"
	.asciiz "                +:    //"
	.asciiz "               /;      /;"
	.asciiz "              -X        H."
	.asciiz ".//;;;:;;-,   X=        :+   .-;:=;:;%;.";
	.asciiz "M-       ,=;;;#:,      ,:#;;:=,       ,@";
	.asciiz ":%           :%.=/++++/=.$=           %=";
	.asciiz " ,%;         %/:+/;,,/++:+/         ;+."
	.asciiz "   ,+/.    ,;@+,        ,%H;,    ,/+,"
	.asciiz "      ;+;;/= @.  .H##X   -X :///+;"
	.asciiz "      ;+=;;;.@,  .XM@$.  =X.//;=%/."
	.asciiz "   ,;:      :@%=        =$H:     .+%-"
	.asciiz " ,%=         %;-///==///-//         =%,"
	.asciiz ";+           :%-;;;:;;;;-X-           +:";
	.asciiz "@-      .-;;;;M-        =M/;;;-.      -X";
	.asciiz " :;;::;;-.    %-        :+    ,-;;-;:=="
	.asciiz "              ,X        H."
	.asciiz "               ;/      %="
	.asciiz "                //    +;"
	.asciiz "                 ,////,"

broken_heart:
	.asciiz "                          .,---."
	.asciiz "                        ,/XM#MMMX;,"
	.asciiz "                      -%##########M%,"
	.asciiz "                     -@######%  $###@="
	.asciiz "      .,--,         -H#######$   $###M:"
	.asciiz "   ,;$M###MMX;     .;##########$;HM###X=";
	.asciiz " ,/@##########H=      ;################+";
	.asciiz "-+#############M/,      %##############+";
	.asciiz "%M###############=      /##############:";
	.asciiz "H################      .M#############;.";
	.asciiz "@###############M      ,@###########M:."
	.asciiz "X################,      -$=X#######@:"
	.asciiz "/@##################%-     +######$-"
	.asciiz ".;##################X     .X#####+,"
	.asciiz " .;H################/     -X####+."
	.asciiz "   ,;X##############,       .MM/"
	.asciiz "      ,:+$H@M#######M#$-    .$$="
	.asciiz "           .,-=;+$@###X:    ;/=."
	.asciiz "                  .,/X$;   .::,"
	.asciiz "                      .,    .."

explosion:
	.asciiz "            .+"
	.asciiz "             /M;"
	.asciiz "              H#@:              ;,"
	.asciiz "              -###H-          -@/"
	.asciiz "               %####$.  -;  .%#X"
	.asciiz "                M#####+;#H :M#M."
	.asciiz "..          .+/;%#########X###-"
	.asciiz " -/%H%+;-,    +##############/"
	.asciiz "    .:$M###MH$%+############X  ,--=;-"
	.asciiz "        -/H#####################H+=."
	.asciiz "           .+#################X."
	.asciiz "         =%M####################H;."
	.asciiz "            /@###############+;;/%%;,"
	.asciiz "         -%###################$."
	.asciiz "       ;H######################M="
	.asciiz "    ,%#####MH$%;+#####M###-/@####%"
	.asciiz "  :$H%+;=-      -####X.,H#   -+M##@-"
	.asciiz " .              ,###;    ;      =$##+"
	.asciiz "                .#H,               :XH,"
	.asciiz "                 +                   .;-";

file:
	.asciiz "                     -$-"
	.asciiz "                    .H##H,"
	.asciiz "                   +######+"
	.asciiz "                .+#########H."
	.asciiz "              -$############@."
	.asciiz "            =H###############@  -X:"
	.asciiz "          .$##################:  @#@-"
	.asciiz "     ,;  .M###################;  H###;"
	.asciiz "   ;@#:  @###################@  ,#####:"
	.asciiz " -M###.  M#################@.  ;######H"
	.asciiz " M####-  +###############$   =@#######X"
	.asciiz " H####$   -M###########+   :#########M,"
	.asciiz "  /####X-   =########%   :M########@/."
	.asciiz "    ,;%H@X;   .$###X   :##MM@%+;:-"
	.asciiz "                 .."
	.asciiz "  -/;:-,.              ,,-==+M########H"
	.asciiz " -##################@HX%%+%%$%%%+:,,"
	.asciiz "    .-/H%%%+%%$H@###############M@+=:/+:";
	.asciiz "/XHX%:#####MH%=    ,---:;;;;/%%XHM,:###$";
	.asciiz "$@#MX %+;-                           ."


check:
	.asciiz "                                     :X-";
	.asciiz "                                  :X###"
	.asciiz "                                ;@####@"
	.asciiz "                              ;M######X"
	.asciiz "                            -@########$"
	.asciiz "                          .$##########@"
	.asciiz "                         =M############-";
	.asciiz "                        +##############$";
	.asciiz "                      .H############$=."
	.asciiz "         ,/:         ,M##########M;."
	.asciiz "      -+@###;       =##########M;"
	.asciiz "   =%M#######;     :#########M/"
	.asciiz "-$M###########;   :#########/"
	.asciiz " ,;X###########; =########$."
	.asciiz "     ;H#########+#######M="
	.asciiz "       ,+##############+"
	.asciiz "          /M#########@-"
	.asciiz "            ;M######%"
	.asciiz "              +####:"
	.asciiz "               ,$M-"

black_mesa:
	.asciiz "           .-;+$XHHHHHHX$+;-."
	.asciiz "        ,;X@@X%/;=----=:/%X@@X/,"
	.asciiz "      =$@@%=.              .=+H@X:"
	.asciiz "    -XMX:                      =XMX="
	.asciiz "   /@@:                          =H@+"
	.asciiz "  %@X,                            .$@$"
	.asciiz " +@X.                               $@%"
	.asciiz "-@@,                                .@@=";
	.asciiz "%@%                                  +@$";
	.asciiz "H@:                                  :@H";
	.asciiz "H@:         :HHHHHHHHHHHHHHHHHHX,    =@H";
	.asciiz "%@%         ;@M@@@@@@@@@@@@@@@@@H-   +@$";
	.asciiz "=@@,        :@@@@@@@@@@@@@@@@@@@@@= .@@:";
	.asciiz " +@X        :@@@@@@@@@@@@@@@M@@@@@@:%@%"
	.asciiz "  $@$,      ;@@@@@@@@@@@@@@@@@M@@@@@@$."
	.asciiz "   +@@HHHHHHH@@@@@@@@@@@@@@@@@@@@@@@+"
	.asciiz "    =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@X="
	.asciiz "      :$@@@@@@@@@@@@@@@@@@@M@@@@$:"
	.asciiz "        ,;$@@@@@@@@@@@@@@@@@@X/-"
	.asciiz "           .-;+$XXHHHHHX$+;-."

cake:
	.asciiz "            ,:/+/-"
	.asciiz "            /M/              .,-=;//;-"
	.asciiz "       .:/= ;MH/,    ,=/+%$XH@MM#@:"
	.asciiz "      -$##@+$###@H@MMM#######H:.    -/H#";
	.asciiz " .,H@H@ X######@ -H#####@+-     -+H###@X";
	.asciiz "  .,@##H;      +XM##M/,     =%@###@X;-"
	.asciiz "X%-  :M##########$.    .:%M###@%:"
	.asciiz "M##H,   +H@@@$/-.  ,;$M###@%,          -";
	.asciiz "M####M=,,---,.-%%H####M$:          ,+@##";
	.asciiz "@##################@/.         :%H##@$-"
	.asciiz "M###############H,         ;HM##M$="
	.asciiz "#################.    .=$M##M$="
	.asciiz "################H..;XM##M$=          .:+";
	.asciiz "M###################@%=           =+@MH%";
	.asciiz "@################M/.          =+H#X%="
	.asciiz "=+M##############M,       -/X#X+;."
	.asciiz "  .;XM##########H=    ,/X#H+:,"
	.asciiz "     .=+HM######M+/+HM@+=."
	.asciiz "         ,:/%XM####H/."
	.asciiz "              ,.:=-."


glados:
	.asciiz "       #+ @      # #              M#@"
	.asciiz " .    .X  X.%##@;# #   +@#######X. @#%"
	.asciiz "   ,==.   ,######M+  -#####%M####M-    #";
	.asciiz "  :H##M%:=##+ .M##M,;#####/+#######% ,M#";
	.asciiz " .M########=  =@#@.=#####M=M#######=  X#";
	.asciiz " :@@MMM##M.  -##M.,#######M#######. =  M";
	.asciiz "             @##..###:.    .H####. @@ X,";
	.asciiz "   ############: ###,/####;  /##= @#. M"
	.asciiz "           ,M## ;##,@#M;/M#M  @# X#% X#"
	.asciiz ".%=   ######M## ##.M#:   ./#M ,M #M ,#$"
	.asciiz "##/         $## #+;#: #### ;#/ M M- @# :";
	.asciiz "#+ #M@MM###M-;M #:$#-##$H# .#X @ + $#. #";
	.asciiz "      ######/.: #%=# M#:MM./#.-#  @#: H#";
	.asciiz "+,.=   @###: /@ %#,@  ##@X #,-#@.##% .@#";
	.asciiz "#####+;/##/ @##  @#,+       /#M    . X,"
	.asciiz "   ;###M#@ M###H .#M-     ,##M  ;@@; ###";
	.asciiz "   .M#M##H ;####X ,@#######M/ -M###$  -H";
	.asciiz "    .M###%  X####H  .@@MM@;  ;@#M@"
	.asciiz "      H#M    /@####/      ,++.  / ==-,"
	.asciiz "               ,=/:, .+X@MMH@#H  #####$=";


