; 0 "\iForms "
.byte	$00,$C6,$EF,$F2,$ED,$F3,$A0,$00
; 12 "\iFORM-"
.byte	$0C,$C6,$CF,$D2,$CD,$AD,$00
; 24 "\i29827"
.byte	$18,$B2,$B9,$B8,$B2,$B7,$00
; 36 "\i281-12:\n"
.byte	$24,$B2,$B8,$B1,$AD,$B1,$B2,$BA,$8D,$00
; 48 "\iTest "
.byte	$30,$D4,$E5,$F3,$F4,$A0,$00
; 60 "\iAssess"
.byte	$3C,$C1,$F3,$F3,$E5,$F3,$F3,$00
; 72 "\iment "
.byte	$48,$ED,$E5,$EE,$F4,$A0,$00
; 84 "\iReport\n"
.byte	$54,$D2,$E5,$F0,$EF,$F2,$F4,$8D,$00
; 96 "\i\n"
.byte	$60,$8D,$00
; 144 "This "
.byte	$90,$D4,$E8,$E9,$F3,$A0,$00
; 156 "was "
.byte	$9C,$F7,$E1,$F3,$A0,$00
; 168 "a "
.byte	$A8,$E1,$A0,$00
; 180 "tri"
.byte	$B4,$F4,$F2,$E9,$00
; 204 "umph.\n"
.byte	$CC,$F5,$ED,$F0,$E8,$AE,$8D,$00
; 324 "I'm "
.byte	$44,$C9,$A7,$ED,$A0,$00
; 336 "ma"
.byte	$50,$ED,$E1,$00
; 348 "king "
.byte	$5C,$EB,$E9,$EE,$E7,$A0,$00
; 360 "a "
.byte	$68,$E1,$A0,$00
; 372 "note "
.byte	$74,$EE,$EF,$F4,$E5,$A0,$00
; 396 "here:\n"
.byte	$8C,$E8,$E5,$F2,$E5,$BA,$8D,$00
; 432 "HUGE "
.byte	$B0,$C8,$D5,$C7,$C5,$A0,$00
; 456 "SUC"
.byte	$C8,$D3,$D5,$C3,$00
; 468 "CESS.\n"
.byte	$D4,$C3,$C5,$D3,$D3,$AE,$8D,$00
; 564 "It's "
.byte	$34,$C9,$F4,$A7,$F3,$A0,$00
; 576 "hard "
.byte	$40,$E8,$E1,$F2,$E4,$A0,$00
; 600 "to "
.byte	$58,$F4,$EF,$A0,$00
; 612 "o"
.byte	$64,$EF,$00
; 648 "ver"
.byte	$88,$F6,$E5,$F2,$00
; 660 "state\n"
.byte	$94,$F3,$F4,$E1,$F4,$E5,$8D,$00
; 684 "my "
.byte	$AC,$ED,$F9,$A0,$00
; 720 "sat"
.byte	$D0,$F3,$E1,$F4,$00
; 744 "is"
.byte	$E8,$E9,$F3,$00
; 756 "fac"
.byte	$F4,$E6,$E1,$E3,$00
; 780 "tion.\n"
.byte	$0C,$F4,$E9,$EF,$EE,$AE,$8D,$00
; 912 "\1Ap"
.byte	$90,$01,$C1,$F0,$00
; 924 "er"
.byte	$9C,$E5,$F2,$00
; 936 "ture "
.byte	$A8,$F4,$F5,$F2,$E5,$A0,$00
; 948 "Sci"
.byte	$B4,$D3,$E3,$E9,$00
; 972 "ence\n"
.byte	$CC,$E5,$EE,$E3,$E5,$8D,$00
; 1092 "We "
.byte	$44,$D7,$E5,$A0,$00
; 1104 "do "
.byte	$50,$E4,$EF,$A0,$00
; 1116 "what "
.byte	$5C,$F7,$E8,$E1,$F4,$A0,$00
; 1128 "we "
.byte	$68,$F7,$E5,$A0,$00
; 1140 "must\n"
.byte	$74,$ED,$F5,$F3,$F4,$8D,$00
; 1176 "be"
.byte	$98,$E2,$E5,$00
; 1188 "cause "
.byte	$A4,$E3,$E1,$F5,$F3,$E5,$A0,$00
; 1224 "we "
.byte	$C8,$F7,$E5,$A0,$00
; 1236 "can.\n"
.byte	$D4,$E3,$E1,$EE,$AE,$8D,$00
; 1344 "For "
.byte	$40,$C6,$EF,$F2,$A0,$00
; 1368 "the "
.byte	$58,$F4,$E8,$E5,$A0,$00
; 1380 "good "
.byte	$64,$E7,$EF,$EF,$E4,$A0,$00
; 1416 "of "
.byte	$88,$EF,$E6,$A0,$00
; 1428 "all "
.byte	$94,$E1,$EC,$EC,$A0,$00
; 1464 "of "
.byte	$B8,$EF,$E6,$A0,$00
; 1476 "us.\n"
.byte	$C4,$F5,$F3,$AE,$8D,$00
; 1500 "\2Ex"
.byte	$DC,$02,$C5,$F8,$00
; 1512 "cept "
.byte	$E8,$E3,$E5,$F0,$F4,$A0,$00
; 1524 "the "
.byte	$F4,$F4,$E8,$E5,$A0,$00
; 1536 "ones "
.byte	$00,$EF,$EE,$E5,$F3,$A0,$00
; 1548 "who "
.byte	$0C,$F7,$E8,$EF,$A0,$00
; 1560 "are "
.byte	$18,$E1,$F2,$E5,$A0,$00
; 1572 "dead.\n\n"
.byte	$24,$E4,$E5,$E1,$E4,$AE,$8D,$8D,$00
; 1608 "\1But "
.byte	$48,$01,$C2,$F5,$F4,$A0,$00
; 1620 "there"
.byte	$54,$F4,$E8,$E5,$F2,$E5,$00
; 1632 "'s no "
.byte	$60,$A7,$F3,$A0,$EE,$EF,$A0,$00
; 1656 "sense "
.byte	$78,$F3,$E5,$EE,$F3,$E5,$A0,$00
; 1680 "cry"
.byte	$90,$E3,$F2,$F9,$00
; 1692 "ing\n"
.byte	$9C,$E9,$EE,$E7,$8D,$00
; 1704 "ov"
.byte	$A8,$EF,$F6,$00
; 1716 "er "
.byte	$B4,$E5,$F2,$A0,$00
; 1722 "eve"
.byte	$BA,$E5,$F6,$E5,$00
; 1734 "ry "
.byte	$C6,$F2,$F9,$A0,$00
; 1752 "mis"
.byte	$D8,$ED,$E9,$F3,$00
; 1776 "take.\n"
.byte	$F0,$F4,$E1,$EB,$E5,$AE,$8D,$00
; 1800 "You "
.byte	$08,$D9,$EF,$F5,$A0,$00
; 1812 "just "
.byte	$14,$EA,$F5,$F3,$F4,$A0,$00
; 1824 "keep "
.byte	$20,$EB,$E5,$E5,$F0,$A0,$00
; 1848 "on "
.byte	$38,$EF,$EE,$A0,$00
; 1872 "try"
.byte	$50,$F4,$F2,$F9,$00
; 1884 "ing\n"
.byte	$5C,$E9,$EE,$E7,$8D,$00
; 1896 "till "
.byte	$68,$F4,$E9,$EC,$EC,$A0,$00
; 1908 "you "
.byte	$74,$F9,$EF,$F5,$A0,$00
; 1920 "run "
.byte	$80,$F2,$F5,$EE,$A0,$00
; 1932 "out "
.byte	$8C,$EF,$F5,$F4,$A0,$00
; 1944 "of "
.byte	$98,$EF,$E6,$A0,$00
; 1968 "cake.\n"
.byte	$B0,$E3,$E1,$EB,$E5,$AE,$8D,$00
; 1992 "\3And "
.byte	$C8,$03,$C1,$EE,$E4,$A0,$00
; 2004 "the "
.byte	$D4,$F4,$E8,$E5,$A0,$00
; 2016 "Sci"
.byte	$E0,$D3,$E3,$E9,$00
; 2028 "ence "
.byte	$EC,$E5,$EE,$E3,$E5,$A0,$00
; 2040 "gets "
.byte	$F8,$E7,$E5,$F4,$F3,$A0,$00
; 2064 "done.\n"
.byte	$10,$E4,$EF,$EE,$E5,$AE,$8D,$00
; 2088 "And "
.byte	$28,$C1,$EE,$E4,$A0,$00
; 2097 "you "
.byte	$31,$F9,$EF,$F5,$A0,$00
; 2112 "make "
.byte	$40,$ED,$E1,$EB,$E5,$A0,$00
; 2124 "a "
.byte	$4C,$E1,$A0,$00
; 2136 "neat "
.byte	$58,$EE,$E5,$E1,$F4,$A0,$00
; 2160 "gun.\n"
.byte	$70,$E7,$F5,$EE,$AE,$8D,$00
; 2184 "\1For "
.byte	$88,$01,$C6,$EF,$F2,$A0,$00
; 2196 "the "
.byte	$94,$F4,$E8,$E5,$A0,$00
; 2202 "peo"
.byte	$9A,$F0,$E5,$EF,$00
; 2220 "ple "
.byte	$AC,$F0,$EC,$E5,$A0,$00
; 2232 "who "
.byte	$B8,$F7,$E8,$EF,$A0,$00
; 2244 "are\n"
.byte	$C4,$E1,$F2,$E5,$8D,$00
; 2268 "still"
.byte	$DC,$F3,$F4,$E9,$EC,$EC,$00
; 2280 " a"
.byte	$E8,$A0,$E1,$00
; 2304 "live.\n"
.byte	$00,$EC,$E9,$F6,$E5,$AE,$8D,$00
; 2316 "\f"
.byte	$0C,$0C,$00
; 2400 "\iForms "
.byte	$60,$C6,$EF,$F2,$ED,$F3,$A0,$00
; 2412 "\iFORM-"
.byte	$6C,$C6,$CF,$D2,$CD,$AD,$00
; 2424 "\i5555"
.byte	$78,$B5,$B5,$B5,$B5,$00
; 2436 "\i1-5:\n"
.byte	$84,$B1,$AD,$B5,$BA,$8D,$00
; 2448 "\iPerson"
.byte	$90,$D0,$E5,$F2,$F3,$EF,$EE,$00
; 2460 "\inel "
.byte	$9C,$EE,$E5,$EC,$A0,$00
; 2472 "\iFile "
.byte	$A8,$C6,$E9,$EC,$E5,$A0,$00
; 2484 "\iAdden"
.byte	$B4,$C1,$E4,$E4,$E5,$EE,$00
; 2496 "\idum:\n"
.byte	$C0,$E4,$F5,$ED,$BA,$8D,$00
; 2508 "\i\n"
.byte	$CC,$8D,$00
; 2520 "\iDear "
.byte	$D8,$C4,$E5,$E1,$F2,$A0,$00
; 2532 "\i<<Sub"
.byte	$E4,$BC,$BC,$D3,$F5,$E2,$00
; 2544 "\iject "
.byte	$F0,$EA,$E5,$E3,$F4,$A0,$00
; 2556 "\iName "
.byte	$FC,$CE,$E1,$ED,$E5,$A0,$00
; 2568 "\iHere>>"
.byte	$08,$C8,$E5,$F2,$E5,$BE,$BE,$00
; 2580 "\i,\n"
.byte	$14,$AC,$8D,$00
; 2592 "\i\n"
.byte	$20,$8D,$00
; 2628 "I'm "
.byte	$44,$C9,$A7,$ED,$A0,$00
; 2640 "not "
.byte	$50,$EE,$EF,$F4,$A0,$00
; 2652 "ev"
.byte	$5C,$E5,$F6,$00
; 2664 "en "
.byte	$68,$E5,$EE,$A0,$00
; 2676 "an"
.byte	$74,$E1,$EE,$00
; 2700 "gry.\n"
.byte	$8C,$E7,$F2,$F9,$AE,$8D,$00
; 2832 "I'm "
.byte	$10,$C9,$A7,$ED,$A0,$00
; 2844 "be"
.byte	$1C,$E2,$E5,$00
; 2856 "ing "
.byte	$28,$E9,$EE,$E7,$A0,$00
; 2868 "so "
.byte	$34,$F3,$EF,$A0,$00
; 2892 "sin"
.byte	$4C,$F3,$E9,$EE,$00
; 2928 "cere "
.byte	$70,$E3,$E5,$F2,$E5,$A0,$00
; 2952 "right "
.byte	$88,$F2,$E9,$E7,$E8,$F4,$A0,$00
; 2964 "now.\n"
.byte	$94,$EE,$EF,$F7,$AE,$8D,$00
; 3072 "Ev"
.byte	$00,$C5,$F6,$00
; 3096 "en "
.byte	$18,$E5,$EE,$A0,$00
; 3108 "though "
.byte	$24,$F4,$E8,$EF,$F5,$E7,$E8,$A0,$00
; 3144 "you "
.byte	$48,$F9,$EF,$F5,$A0,$00
; 3168 "broke "
.byte	$60,$E2,$F2,$EF,$EB,$E5,$A0,$00
; 3192 "my "
.byte	$78,$ED,$F9,$A0,$00
; 3204 "\4heart.\n"
.byte	$84,$04,$E8,$E5,$E1,$F2,$F4,$AE,$8D,$00
; 3228 "And "
.byte	$9C,$C1,$EE,$E4,$A0,$00
; 3252 "killed "
.byte	$B4,$EB,$E9,$EC,$EC,$E5,$E4,$A0,$00
; 3276 "me.\n"
.byte	$CC,$ED,$E5,$AE,$8D,$00
; 3396 "\5And "
.byte	$44,$05,$C1,$EE,$E4,$A0,$00
; 3408 "tore "
.byte	$50,$F4,$EF,$F2,$E5,$A0,$00
; 3420 "me "
.byte	$5C,$ED,$E5,$A0,$00
; 3432 "to "
.byte	$68,$F4,$EF,$A0,$00
; 3444 "pie"
.byte	$74,$F0,$E9,$E5,$00
; 3468 "ces.\n"
.byte	$8C,$E3,$E5,$F3,$AE,$8D,$00
; 3588 "And "
.byte	$04,$C1,$EE,$E4,$A0,$00
; 3600 "threw "
.byte	$10,$F4,$E8,$F2,$E5,$F7,$A0,$00
; 3612 "eve"
.byte	$1C,$E5,$F6,$E5,$00
; 3624 "ry "
.byte	$28,$F2,$F9,$A0,$00
; 3636 "piece "
.byte	$34,$F0,$E9,$E5,$E3,$E5,$A0,$00
; 3660 "in"
.byte	$4C,$E9,$EE,$00
; 3696 "to "
.byte	$70,$F4,$EF,$A0,$00
; 3720 "a "
.byte	$88,$E1,$A0,$00
; 3732 "\6fire.\n"
.byte	$94,$06,$E6,$E9,$F2,$E5,$AE,$8D,$00
; 3840 "As "
.byte	$00,$C1,$F3,$A0,$00
; 3864 "they "
.byte	$18,$F4,$E8,$E5,$F9,$A0,$00
; 3876 "burned "
.byte	$24,$E2,$F5,$F2,$EE,$E5,$E4,$A0,$00
; 3912 "it "
.byte	$48,$E9,$F4,$A0,$00
; 3936 "hurt "
.byte	$60,$E8,$F5,$F2,$F4,$A0,$00
; 3960 "be"
.byte	$78,$E2,$E5,$00
; 3972 "cause\n"
.byte	$84,$E3,$E1,$F5,$F3,$E5,$8D,$00
; 3996 "I "
.byte	$9C,$C9,$A0,$00
; 4008 "was "
.byte	$A8,$F7,$E1,$F3,$A0,$00
; 4020 "so "
.byte	$B4,$F3,$EF,$A0,$00
; 4032 "hap"
.byte	$C0,$E8,$E1,$F0,$00
; 4044 "py "
.byte	$CC,$F0,$F9,$A0,$00
; 4056 "for "
.byte	$D8,$E6,$EF,$F2,$A0,$00
; 4068 "you!\n"
.byte	$E4,$F9,$EF,$F5,$A1,$8D,$00
; 4104 "\7Now "
.byte	$08,$07,$CE,$EF,$F7,$A0,$00
; 4116 "these "
.byte	$14,$F4,$E8,$E5,$F3,$E5,$A0,$00
; 4128 "points "
.byte	$20,$F0,$EF,$E9,$EE,$F4,$F3,$A0,$00
; 4152 "of "
.byte	$38,$EF,$E6,$A0,$00
; 4176 "da"
.byte	$50,$E4,$E1,$00
; 4188 "ta\n"
.byte	$5C,$F4,$E1,$8D,$00
; 4200 "make "
.byte	$68,$ED,$E1,$EB,$E5,$A0,$00
; 4212 "a "
.byte	$74,$E1,$A0,$00
; 4224 "beau"
.byte	$80,$E2,$E5,$E1,$F5,$00
; 4236 "ti"
.byte	$8C,$F4,$E9,$00
; 4248 "ful "
.byte	$98,$E6,$F5,$EC,$A0,$00
; 4272 "line.\n"
.byte	$B0,$EC,$E9,$EE,$E5,$AE,$8D,$00
; 4296 "And "
.byte	$C8,$C1,$EE,$E4,$A0,$00
; 4308 "we're "
.byte	$D4,$F7,$E5,$A7,$F2,$E5,$A0,$00
; 4320 "out "
.byte	$E0,$EF,$F5,$F4,$A0,$00
; 4344 "of "
.byte	$F8,$EF,$E6,$A0,$00
; 4368 "be"
.byte	$10,$E2,$E5,$00
; 4380 "ta.\n"
.byte	$1C,$F4,$E1,$AE,$8D,$00
; 4392 "We're "
.byte	$28,$D7,$E5,$A7,$F2,$E5,$A0,$00
; 4404 "re"
.byte	$34,$F2,$E5,$00
; 4416 "leas"
.byte	$40,$EC,$E5,$E1,$F3,$00
; 4428 "ing "
.byte	$4C,$E9,$EE,$E7,$A0,$00
; 4440 "on "
.byte	$58,$EF,$EE,$A0,$00
; 4464 "time.\n"
.byte	$70,$F4,$E9,$ED,$E5,$AE,$8D,$00
; 4488 "\5So "
.byte	$88,$05,$D3,$EF,$A0,$00
; 4500 "I'm "
.byte	$94,$C9,$A7,$ED,$A0,$00
; 4512 "GLaD. "
.byte	$A0,$C7,$CC,$E1,$C4,$AE,$A0,$00
; 4524 "I "
.byte	$AC,$C9,$A0,$00
; 4536 "got "
.byte	$B8,$E7,$EF,$F4,$A0,$00
; 4560 "burned.\n"
.byte	$D0,$E2,$F5,$F2,$EE,$E5,$E4,$AE,$8D,$00
; 4584 "\3Think "
.byte	$E8,$03,$D4,$E8,$E9,$EE,$EB,$A0,$00
; 4596 "of "
.byte	$F4,$EF,$E6,$A0,$00
; 4608 "all "
.byte	$00,$E1,$EC,$EC,$A0,$00
; 4620 "the "
.byte	$0C,$F4,$E8,$E5,$A0,$00
; 4632 "things "
.byte	$18,$F4,$E8,$E9,$EE,$E7,$F3,$A0,$00
; 4644 "we "
.byte	$24,$F7,$E5,$A0,$00
; 4656 "learned\n"
.byte	$30,$EC,$E5,$E1,$F2,$EE,$E5,$E4,$8D,$00
; 4680 "\1for "
.byte	$48,$01,$E6,$EF,$F2,$A0,$00
; 4692 "the "
.byte	$54,$F4,$E8,$E5,$A0,$00
; 4704 "peo"
.byte	$60,$F0,$E5,$EF,$00
; 4716 "ple "
.byte	$6C,$F0,$EC,$E5,$A0,$00
; 4728 "who "
.byte	$78,$F7,$E8,$EF,$A0,$00
; 4740 "are\n"
.byte	$84,$E1,$F2,$E5,$8D,$00
; 4764 "still "
.byte	$9C,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 4776 "a"
.byte	$A8,$E1,$00
; 4800 "live.\n"
.byte	$C0,$EC,$E9,$F6,$E5,$AE,$8D,$00
; 4812 "\f"
.byte	$CC,$0C,$00
; 4818 "\iForms "
.byte	$D2,$C6,$EF,$F2,$ED,$F3,$A0,$00
; 4830 "\iFORM-"
.byte	$DE,$C6,$CF,$D2,$CD,$AD,$00
; 4842 "\i5555"
.byte	$EA,$B5,$B5,$B5,$B5,$00
; 4854 "\i1-6:\n"
.byte	$F6,$B1,$AD,$B6,$BA,$8D,$00
; 4866 "\iPerson"
.byte	$02,$D0,$E5,$F2,$F3,$EF,$EE,$00
; 4878 "\inel "
.byte	$0E,$EE,$E5,$EC,$A0,$00
; 4890 "\iFile "
.byte	$1A,$C6,$E9,$EC,$E5,$A0,$00
; 4902 "\iAdd"
.byte	$26,$C1,$E4,$E4,$00
; 4914 "\iendum "
.byte	$32,$E5,$EE,$E4,$F5,$ED,$A0,$00
; 4926 "\iAdd"
.byte	$3E,$C1,$E4,$E4,$00
; 4938 "\iendum"
.byte	$4A,$E5,$EE,$E4,$F5,$ED,$00
; 4950 "\i:\n\n"
.byte	$56,$BA,$8D,$8D,$00
; 5088 "\iOne "
.byte	$E0,$CF,$EE,$E5,$A0,$00
; 5100 "\ilast "
.byte	$EC,$EC,$E1,$F3,$F4,$A0,$00
; 5112 "\ithing:\n"
.byte	$F8,$F4,$E8,$E9,$EE,$E7,$BA,$8D,$00
; 5124 "\i\n"
.byte	$04,$8D,$00
; 5136 "Go "
.byte	$10,$C7,$EF,$A0,$00
; 5148 "ah"
.byte	$1C,$E1,$E8,$00
; 5154 "ead"
.byte	$22,$E5,$E1,$E4,$00
; 5160 " and "
.byte	$28,$A0,$E1,$EE,$E4,$A0,$00
; 5172 "leave "
.byte	$34,$EC,$E5,$E1,$F6,$E5,$A0,$00
; 5196 "me.\n"
.byte	$4C,$ED,$E5,$AE,$8D,$00
; 5316 "I "
.byte	$C4,$C9,$A0,$00
; 5328 "think "
.byte	$D0,$F4,$E8,$E9,$EE,$EB,$A0,$00
; 5340 "I "
.byte	$DC,$C9,$A0,$00
; 5352 "pre"
.byte	$E8,$F0,$F2,$E5,$00
; 5364 "fer "
.byte	$F4,$E6,$E5,$F2,$A0,$00
; 5388 "to "
.byte	$0C,$F4,$EF,$A0,$00
; 5424 "stay "
.byte	$30,$F3,$F4,$E1,$F9,$A0,$00
; 5448 "in"
.byte	$48,$E9,$EE,$00
; 5460 "side.\n"
.byte	$54,$F3,$E9,$E4,$E5,$AE,$8D,$00
; 5568 "May"
.byte	$C0,$CD,$E1,$F9,$00
; 5592 "be "
.byte	$D8,$E2,$E5,$A0,$00
; 5604 "you'll "
.byte	$E4,$F9,$EF,$F5,$A7,$EC,$EC,$A0,$00
; 5640 "find "
.byte	$08,$E6,$E9,$EE,$E4,$A0,$00
; 5664 "some"
.byte	$20,$F3,$EF,$ED,$E5,$00
; 5688 "one "
.byte	$38,$EF,$EE,$E5,$A0,$00
; 5700 "else\n"
.byte	$44,$E5,$EC,$F3,$E5,$8D,$00
; 5724 "to "
.byte	$5C,$F4,$EF,$A0,$00
; 5748 "help "
.byte	$74,$E8,$E5,$EC,$F0,$A0,$00
; 5772 "you.\n"
.byte	$8C,$F9,$EF,$F5,$AE,$8D,$00
; 5904 "\8May"
.byte	$10,$08,$CD,$E1,$F9,$00
; 5916 "be "
.byte	$1C,$E2,$E5,$A0,$00
; 5928 "Black "
.byte	$28,$C2,$EC,$E1,$E3,$EB,$A0,$00
; 5940 "Me"
.byte	$34,$CD,$E5,$00
; 5964 "sa"
.byte	$4C,$F3,$E1,$00
; 6012 "."
.byte	$7C,$AE,$00
; 6036 "."
.byte	$94,$AE,$00
; 6060 ".\n"
.byte	$AC,$AE,$8D,$00
; 6096 "THAT "
.byte	$D0,$D4,$C8,$C1,$D4,$A0,$00
; 6108 "WAS "
.byte	$DC,$D7,$C1,$D3,$A0,$00
; 6120 "A "
.byte	$E8,$C1,$A0,$00
; 6132 "JOKE. "
.byte	$F4,$CA,$CF,$CB,$C5,$AE,$A0,$00
; 6216 "FAT "
.byte	$48,$C6,$C1,$D4,$A0,$00
; 6228 "CHANCE.\n"
.byte	$54,$C3,$C8,$C1,$CE,$C3,$C5,$AE,$8D,$00
; 6336 "\9An"
.byte	$C0,$09,$C1,$EE,$00
; 6360 "y"
.byte	$D8,$F9,$00
; 6372 "way, "
.byte	$E4,$F7,$E1,$F9,$AC,$A0,$00
; 6408 "this "
.byte	$08,$F4,$E8,$E9,$F3,$A0,$00
; 6432 "cake "
.byte	$20,$E3,$E1,$EB,$E5,$A0,$00
; 6456 "is "
.byte	$38,$E9,$F3,$A0,$00
; 6468 "great.\n"
.byte	$44,$E7,$F2,$E5,$E1,$F4,$AE,$8D,$00
; 6492 "It's "
.byte	$5C,$C9,$F4,$A7,$F3,$A0,$00
; 6504 "so "
.byte	$68,$F3,$EF,$A0,$00
; 6516 "de"
.byte	$74,$E4,$E5,$00
; 6528 "li"
.byte	$80,$EC,$E9,$00
; 6540 "cious "
.byte	$8C,$E3,$E9,$EF,$F5,$F3,$A0,$00
; 6552 "and "
.byte	$98,$E1,$EE,$E4,$A0,$00
; 6564 "moist.\n"
.byte	$A4,$ED,$EF,$E9,$F3,$F4,$AE,$8D,$00
; 6600 "\:Look "
.byte	$C8,$0A,$CC,$EF,$EF,$EB,$A0,$00
; 6612 "at "
.byte	$D4,$E1,$F4,$A0,$00
; 6624 "me "
.byte	$E0,$ED,$E5,$A0,$00
; 6648 "still "
.byte	$F8,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 6672 "talk"
.byte	$10,$F4,$E1,$EC,$EB,$00
; 6684 "ing\n"
.byte	$1C,$E9,$EE,$E7,$8D,$00
; 6696 "when "
.byte	$28,$F7,$E8,$E5,$EE,$A0,$00
; 6708 "there's "
.byte	$34,$F4,$E8,$E5,$F2,$E5,$A7,$F3,$A0,$00
; 6720 "\2Sci"
.byte	$40,$02,$D3,$E3,$E9,$00
; 6732 "ence "
.byte	$4C,$E5,$EE,$E3,$E5,$A0,$00
; 6744 "to "
.byte	$58,$F4,$EF,$A0,$00
; 6768 "do.\n"
.byte	$70,$E4,$EF,$AE,$8D,$00
; 6792 "\1When "
.byte	$88,$01,$D7,$E8,$E5,$EE,$A0,$00
; 6804 "I "
.byte	$94,$C9,$A0,$00
; 6816 "look "
.byte	$A0,$EC,$EF,$EF,$EB,$A0,$00
; 6840 "out "
.byte	$B8,$EF,$F5,$F4,$A0,$00
; 6864 "there,\n"
.byte	$D0,$F4,$E8,$E5,$F2,$E5,$AC,$8D,$00
; 6876 "it "
.byte	$DC,$E9,$F4,$A0,$00
; 6888 "makes "
.byte	$E8,$ED,$E1,$EB,$E5,$F3,$A0,$00
; 6900 "me "
.byte	$F4,$ED,$E5,$A0,$00
; 6912 "GLaD "
.byte	$00,$C7,$CC,$E1,$C4,$A0,$00
; 6924 "I'm "
.byte	$0C,$C9,$A7,$ED,$A0,$00
; 6936 "not "
.byte	$18,$EE,$EF,$F4,$A0,$00
; 6960 "you.\n"
.byte	$30,$F9,$EF,$F5,$AE,$8D,$00
; 6984 "\3I've "
.byte	$48,$03,$C9,$A7,$F6,$E5,$A0,$00
; 6996 "ex"
.byte	$54,$E5,$F8,$00
; 7008 "per"
.byte	$60,$F0,$E5,$F2,$00
; 7020 "i"
.byte	$6C,$E9,$00
; 7032 "ments "
.byte	$78,$ED,$E5,$EE,$F4,$F3,$A0,$00
; 7044 "to "
.byte	$84,$F4,$EF,$A0,$00
; 7056 "run.\n"
.byte	$90,$F2,$F5,$EE,$AE,$8D,$00
; 7080 "\5There "
.byte	$A8,$05,$D4,$E8,$E5,$F2,$E5,$A0,$00
; 7092 "is "
.byte	$B4,$E9,$F3,$A0,$00
; 7104 "re"
.byte	$C0,$F2,$E5,$00
; 7116 "search "
.byte	$CC,$F3,$E5,$E1,$F2,$E3,$E8,$A0,$00
; 7128 "to "
.byte	$D8,$F4,$EF,$A0,$00
; 7140 "be "
.byte	$E4,$E2,$E5,$A0,$00
; 7152 "done.\n"
.byte	$F0,$E4,$EF,$EE,$E5,$AE,$8D,$00
; 7176 "\1On "
.byte	$08,$01,$CF,$EE,$A0,$00
; 7188 "the "
.byte	$14,$F4,$E8,$E5,$A0,$00
; 7200 "peo"
.byte	$20,$F0,$E5,$EF,$00
; 7212 "ple "
.byte	$2C,$F0,$EC,$E5,$A0,$00
; 7224 "who "
.byte	$38,$F7,$E8,$EF,$A0,$00
; 7236 "are "
.byte	$44,$E1,$F2,$E5,$A0,$00
; 7260 "still "
.byte	$5C,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 7272 "a"
.byte	$68,$E1,$00
; 7278 "l"
.byte	$6E,$EC,$00
; 7284 "i"
.byte	$74,$E9,$00
; 7290 "v"
.byte	$7A,$F6,$00
; 7296 "e"
.byte	$80,$E5,$00
; 7302 "."
.byte	$86,$AE,$00
; 7308 "\n"
.byte	$8C,$8D,$00
; 7320 "\f"
.byte	$98,$0C,$00
; 7332 "\n"
.byte	$A4,$8D,$00
; 7344 "\n"
.byte	$B0,$8D,$00
; 7356 "\iPS: "
.byte	$BC,$D0,$D3,$BA,$A0,$00
; 7368 "And "
.byte	$C8,$C1,$EE,$E4,$A0,$00
; 7380 "be"
.byte	$D4,$E2,$E5,$00
; 7392 "lieve "	
.byte	$E0,$EC,$E9,$E5,$F6,$E5,$A0,$00
; 7404 "me "
.byte	$EC,$ED,$E5,$A0,$00
; 7416 "I "
.byte	$F8,$C9,$A0,$00
; 7428 "am\n"
.byte	$04,$E1,$ED,$8D,$00
; 7452 "still "
.byte	$1C,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 7464 "a"
.byte	$28,$E1,$00
; 7476 "live.\n"
.byte	$34,$EC,$E9,$F6,$E5,$AE,$8D,$00
; 7536 "\iPPS: "
.byte	$70,$D0,$D0,$D3,$BA,$A0,$00
; 7548 "I'm "
.byte	$7C,$C9,$A7,$ED,$A0,$00
; 7560 "do"
.byte	$88,$E4,$EF,$00
; 7572 "ing "
.byte	$94,$E9,$EE,$E7,$A0,$00
; 7584 "sci"
.byte	$A0,$F3,$E3,$E9,$00
; 7596 "ence "
.byte	$AC,$E5,$EE,$E3,$E5,$A0,$00
; 7608 "and "
.byte	$B8,$E1,$EE,$E4,$A0,$00
; 7620 "I'm\n"
.byte	$C4,$C9,$A7,$ED,$8D,$00
; 7644 "still "
.byte	$DC,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 7656 "a"
.byte	$E8,$E1,$00
; 7668 "live.\n"
.byte	$F4,$EC,$E9,$F6,$E5,$AE,$8D,$00
; 7728 "\iPPPS: "
.byte	$30,$D0,$D0,$D0,$D3,$BA,$A0,$00
; 7740 "I "
.byte	$3C,$C9,$A0,$00
; 7752 "feel "
.byte	$48,$E6,$E5,$E5,$EC,$A0,$00
; 7764 "FAN"
.byte	$54,$C6,$C1,$CE,$00
; 7776 "TAS"
.byte	$60,$D4,$C1,$D3,$00
; 7788 "TIC "
.byte	$6C,$D4,$C9,$C3,$A0,$00
; 7800 "and "
.byte	$78,$E1,$EE,$E4,$A0,$00
; 7812 "I'm\n"
.byte	$84,$C9,$A7,$ED,$8D,$00
; 7836 "still "
.byte	$9C,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 7848 "a"
.byte	$A8,$E1,$00
; 7860 "live.\n\n"
.byte	$B4,$EC,$E9,$F6,$E5,$AE,$8D,$8D,$00
; 7908 "\iFIN"
.byte	$E4,$C6,$C9,$CE,$00
; 7920 "\iAL TH"
.byte	$F0,$C1,$CC,$A0,$D4,$C8,$00
; 7932 "\iOUGHT:\n"
.byte	$FC,$CF,$D5,$C7,$C8,$D4,$BA,$8D,$00
; 7944 "While "
.byte	$08,$D7,$E8,$E9,$EC,$E5,$A0,$00
; 7956 "you're "
.byte	$14,$F9,$EF,$F5,$A7,$F2,$E5,$A0,$00
; 7968 "dy"
.byte	$20,$E4,$F9,$00
; 7980 "ing "
.byte	$2C,$E9,$EE,$E7,$A0,$00
; 7992 "I'll "
.byte	$38,$C9,$A7,$EC,$EC,$A0,$00
; 8004 "be\n"
.byte	$44,$E2,$E5,$8D,$00
; 8028 "still "
.byte	$5C,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 8040 "a"
.byte	$68,$E1,$00
; 8052 "live.\n\n"
.byte	$74,$EC,$E9,$F6,$E5,$AE,$8D,$8D,$00
; 8064 "\iFIN"
.byte	$80,$C6,$C9,$CE,$00
; 8076 "\iAL "
.byte	$8C,$C1,$CC,$A0,$00
; 8088 "\iTHO"
.byte	$98,$D4,$C8,$CF,$00
; 8100 "\iUGHT "
.byte	$A4,$D5,$C7,$C8,$D4,$A0,$00
; 8112 "\iPS:\n"
.byte	$B0,$D0,$D3,$BA,$8D,$00
; 8124 "And "
.byte	$BC,$C1,$EE,$E4,$A0,$00
; 8136 "when "
.byte	$C8,$F7,$E8,$E5,$EE,$A0,$00
; 8148 "you're "
.byte	$D4,$F9,$EF,$F5,$A7,$F2,$E5,$A0,$00
; 8160 "dead "
.byte	$E0,$E4,$E5,$E1,$E4,$A0,$00
; 8172 "I "
.byte	$EC,$C9,$A0,$00
; 8184 "will "
.byte	$F8,$F7,$E9,$EC,$EC,$A0,$00
; 8196 "be\n"
.byte	$04,$E2,$E5,$8D,$00
; 8220 "still "
.byte	$1C,$F3,$F4,$E9,$EC,$EC,$A0,$00
; 8232 "a"
.byte	$28,$E1,$00
; 8244 "live.\n"
.byte	$34,$EC,$E9,$F6,$E5,$AE,$8D,$00
; 8280 "\n"
.byte	$58,$8D,$00
; 8292 "\n"
.byte	$64,$8D,$00
; 8316 "STILL "
.byte	$7C,$D3,$D4,$C9,$CC,$CC,$A0,$00
; 8328 "A"
.byte	$88,$C1,$00
; 8340 "LIVE\n"
.byte	$94,$CC,$C9,$D6,$C5,$8D,$00
; 8352 "\f"
.byte	$A0,$0C,$00
; 8688 "\iTHANK"
.byte	$F0,$D4,$C8,$C1,$CE,$CB,$00
; 8700 "\i YOU "
.byte	$FC,$A0,$D9,$CF,$D5,$A0,$00
; 8712 "\iFOR "
.byte	$08,$C6,$CF,$D2,$A0,$00
; 8724 "\iPAR"
.byte	$14,$D0,$C1,$D2,$00
; 8736 "\iTIC"
.byte	$20,$D4,$C9,$C3,$00
; 8748 "\iIPAT"
.byte	$2C,$C9,$D0,$C1,$D4,$00
; 8760 "\iING\n"
.byte	$38,$C9,$CE,$C7,$8D,$00
; 8772 "\iIN "
.byte	$44,$C9,$CE,$A0,$00
; 8784 "\iTHIS\n"
.byte	$50,$D4,$C8,$C9,$D3,$8D,$00
; 8796 "\iENRICH"
.byte	$5C,$C5,$CE,$D2,$C9,$C3,$C8,$00
; 8808 "\iMENT"
.byte	$68,$CD,$C5,$CE,$D4,$00
; 8820 "\i CEN"
.byte	$74,$A0,$C3,$C5,$CE,$00
; 8832 "\iTER "
.byte	$80,$D4,$C5,$D2,$A0,$00
; 8844 "\iACT"
.byte	$8C,$C1,$C3,$D4,$00
; 8856 "\iIVIT"
.byte	$98,$C9,$D6,$C9,$D4,$00
; 8868 "\iY!!\n"
.byte	$A4,$D9,$A1,$A1,$8D,$00
; HACK to make sure we don't run off the end waiting for the song to finish
.byte $A4,$8D,$00
.byte $A4,$8D,$00
.byte $A4,$8D,$00


