5 HOME
10 PRINT "         -= PLASMA MASK - 1K =-"
12 PRINT "           ------------------"
13 PRINT "             BY: DEATER/DSR"
14 PRINT "             LOVEBYTE  2024"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN PLASMA_NEW'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN PLASMA_NEW"
