5 HOME
10 PRINT "LOVE_DUCK -- A 512B BYTE APPLE II INTRO"
15 PRINT "         BY DEATER & MA2E / DSR"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN LOVE_DUCK'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN LOVE_DUCK"

