   5  HOME
  10  PRINT "LOADING LORES-ESCAPE, DEMOSPLASH 2019"
  15  PRINT "                                 V1.1"
  20  PRINT
  30  PRINT "NOTE: ON REAL HARDWARE THIS MAY"
  40  PRINT "      TAKE A WHILE (45 SECONDS)"
' 200  PRINT  CHR$ (4)"CATALOG"
  200  PRINT  CHR$ (4)"BRUN LOADER"

