;============================
; Burninated Trees / Lantern
;============================

; + look
crooked_look_day_message:
.byte "A signal lantern of some",13
.byte "kind hangs from a",13
.byte "burninated tree.",0

; + look (night)
crooked_look_night_message:
.byte "A burning signal lantern",13
.byte "hangs from a severely",13
.byte "burninated tree. ",0

; + look lantern (day)
crooked_look_lantern_day_message:
.byte "It's unlit at the moment.",13
.byte "That fancy pants royal",13
.byte "knight probably lights it",13
.byte "on nights when Troggie's on",13
.byte "the prowl.",0

; + look lantern (night)
crooked_look_lantern_night_message:
.byte "It's lit! Musta been a",13
.byte "Trogdor sighting tonight.",0

; + look stump
crooked_look_stump_message:
.byte "NOT a good place to sit.",0

; + look tree
crooked_look_tree_message:
.byte "Severely burninated. They",13
.byte "could probably use some",13
.byte "salve.",0

; +10 POINTS
; + (walking under candle in burninated trees)
crooked_catch_fire_message:
.byte "Whoa! The horse grease on",13
.byte "your robe caught fire!",13
.byte "You're a for-real peasant",13
.byte "now.",0

; + light lantern (day)
crooked_tree_light_lantern_day_message:
.byte "With what? Your red-hot",13
.byte "intellect?",0

; + light lantern (night)
crooked_tree_light_lantern_night_message:
.byte "Already lit, moron.",0
 
; + get fire (at night, before grease)
crooked_tree_get_fire_not_greased_message:
.byte "You're just not flammable",13
.byte "enough.",0

; + get fire (at night, after grease)
crooked_tree_get_fire_greased_message:
.byte "You don't need to get IT.",13
.byte "Just let IT get YOU.",0

; + get fire (at night, after getting on fire)
crooked_tree_get_fire_already_message:
.byte "You're already on fire!",13
.byte "What? You want to be MORE",13
.byte "on fire?",0

; + get lantern
crooked_tree_get_lantern_message:
.byte "Better not. There's an",13
.byte "engraved plaque on it that",13
.byte "says, ",34,"Do Not Remove Under",13
.byte "Penalty Of 'You Die'.",34,0

; + get plague
crooked_tree_get_plague_message:
.byte "Wrong game, Mispeller",13
.byte "Jones. Try the little",13
.byte "button to the left of the",13
.byte "'W'.",0

; + get plaque
crooked_tree_get_plaque_message:
.byte "You have enough of that on",13
.byte "your browning, rotten",13
.byte "peasant teeth already.",0

; + climb cliff
crooked_tree_climb_cliff_message:
.byte "There aren't enough",13
.byte "footholds and you don't",13
.byte "have any carabeaners on",13
.byte "you.",0


