;===================
; Cliffland Heights
;===================

; arrive
; +3 POINTS (maybe at the top?, makes noise after you dismiss message)
; lightning makes sound effect, same as rock crashing noise

; shows once atop
cliff_heights_top_message:
.byte "Nice jorb climbing the",13
.byte "cliff. You have a real way",13
.byte "with those arrow keys.",0

; + look
cliff_heights_look_at_message:
.byte "Wow! It sure gets creepy",13
.byte "fast around here! What with",13
.byte "all the lightning and the",13
.byte "scary cave entrances.",0

; + look bone/skull
cliff_heights_look_bone_message:
.byte "You can't be sure but you",13
.byte "think those are dead person",13
.byte "bones.",0

; + look cave
cliff_heights_look_cave_message:
.byte "The cave entrance beckons",13
.byte "to you like a hot mutton",13
.byte "sandwich might.",0
 
; + look lightning
cliff_heights_look_lightning_message:
.byte "Scary. Like Auntie",13
.byte "Gerelda's crow's feet.",0

; + climb cliff (at top)
cliff_heights_climb_message:
.byte "They don't show how the",13
.byte "sports-drink people get",13
.byte "down from the cliff. You've",13
.byte "no idea how to start.",0

; + get/take/steal bone/skull
cliff_heights_get_bone_message:
.byte "Eww. No. Grody. You're",13
.byte "grody. No. Eww.",0

