
#############
# Cliff Base
#############

# + look 
You're at the base of a very climbable cliff that leads to Trogdor's lair. This cliff is huge - the kind where rocks start falling down the minute you try to climb it.
# + climb
With a new determination you dig your fingers into the cliff face and begin to haul yourself up the mountain like you were in a sports drink commercial
The mountain starts rumbling and big loose boulders start tumblin down. You'd best avoid thems.

##############
# Cliff
##############

#    (Hit by rock or pterodactyl when climbing the cliff) — {You fall to the ground and lie in a heap}
Oops! You climbed real bad. You knew that you were AVOIDING the rocks, right? Not collecting them. Anyways, nice try. You dead. Thanks for playing.

####################
# Cliffland Heights
####################

# + look
Wow! It sure gets creepy fast around here! What with all the lightning and scary cave entrances.
# + look bone/skull
You can't be sure but you think those are dead person bones.
# + look cave
The cave entrance beckons to you like a hot mutton sandwich might. 
# + look lightning
Scary. Like Auntie Gerelda's crow's feet.
# +  (successfully climbing the cliff without dying)
Nice jorb climbing the cliff. You have a real way with those arrow keys.
# + climb cliff (at top)
They don't show how the sports-drink people get down from the cliff. You've no idea how to start.
# + get/take/steal bone/skull
Eww. No. Grody. You're grody. No. Eww.


#######################################
# Trogdor's Outer Sanctum / Outer Cave
#######################################

# Type any command other than "take the quiz" or "give (requested item)"
# after being apporached by a Keeper
I think he wants something from your inventory. Or you could just tell him "take the quiz"
# + look
There are 3 openings with a little cliff in front of each. A beaded curtain hangs in a doorway on the far wall.
# + look curtain/beads
That thing's awesome. You always wanted one for your dorm room but your roommate was a total drag and said no.
# + look door
A wicked beaded curtain hangs in the doorway.
# + look openings
They're mysterious and out of reach. Like girls were to you in high school.
# + look skeleton
You can't be sure but you think those are dead person bones.
# + (approached by first keeper)
Foolish peasant! How dare you enter this fairly sacred chamber!
You explain that you're here to smote Trogdor and if he doesn't get outta your way, him too!
You cannot vanquish Trogdor! Only the Three Keepers of Trogdor hold the tools with which to destroy the Burninator. The Trog-Shield, the Trog-Helmet, and the Trog-Sword.
And the only way we'll give them up is if you answer the three Trog-Trivia questions correctly.
Unless you happen to have something to eat on ya. Then we could forego my question.
# + give sandwich
No way! I was just kidding but you've really got a meatball sub. This rules! Here, you can have the Trog-Shield.
# + (approached by second keeper)
Hold, peasant! You must answer the second dreaded Trog-Trivia question!
Or we could call it even if I had an ice cold drink right now.
# + give soda
Sweet deal, peasant. I underestimated you. Wear this Trog-Helmet with style.
# + (approached by third keeper)
Think you're pretty hot stuff, eh? Let's see you answer the deadly and pretty impossible THIRD TROG-TRIVIA QUESTION!
That is, unless you've got something for my lower back. Man, it's killin me!
# + give pills
Whoa! Where'd you find this stuff? I don't think this is even legal anymore. These babies'll definitely smote LUMBAGO the, um, LOWER BACKINATOR!!
The fabled Trog-Sword is yours. You now have the means to strike down Trogdor. Good luck, peasant.
# + climb cliff
Nope. It's too sheer. 


####################################
# Trogdor's Posh Lair / Inner Cave
####################################

# Type any command other than "Talk" or "Talk Trogdor" after Trogdor wakes up
Trogdor is awake and a couple seconds from a Rather Dashing BBQ. Might as well say your peace with him. 	Trogdor's Posh Lair 
# (Walk too close to Trogdor while he's asleep)
# {Trogdor burninates you without waking up}
Yow. Looks like you got a little too close. You dead. Maybe next time don't get too close. 
# + look
You're in a giant cavern which houses a giant dragon. You didn't shrink or anything. 
# + look trogdor (while he's asleep)
Holy crap! Trogdor's way bigger in person than he looks in most tapestries you've seen. All of the sudden, losing your cottage doesn't seem so bad anymore.
# + look trogdor (when he's awake)
Trogdor is looming menacingly over you with a tiny wee sword stuck in his belly. He looks like he's gonna kill you really soon.
# + (enter Trogdor's cave)
the beaded curtain slams shut behind you. There's no turning back now.
# + throw sword
This is it! You hurl the Trog-Sword with all your might at the sleeping Burninator.
Now you've done it! Trogdor's awake and the Trog-Sword doesn't seem to be doing a whole lot.
Your legs lock in fear, your eyes glaze over and you wish for some Depeasant adult undergarments. But you think you hear Trogdor whimpering!
Aw crap, that's you whimpering. At least your voice still works, I guess.
# + talk trogdor
You scream that your name is Rather Dashing and that Trogdor burninated your cottage and you're here for revenge!
"Sup, mortal," booms Trogdor. "I really appreciate you making the effort to come all the way up here and vanquish me and all. But, I'm kinda indestructible."
"Yeah, I can't be killed. I'm surprised nobody mentioned that to you. I'll admit though, you've gotten farther than anybody else ever has. I bet they'll make a statue or something in honor of you somewheres."
"I can honestly say it'll be a pleasure and an honor to burninate you, Rather Dashing."
Aw that sure was nice of him!
Congratulations! You've won! No one can kill Trogdor but you came closer than anybody ever! Way to go!
# + attack trogdor (when he's asleep)
Like how? 
# + wake up trogdor
'Troggie...', you murmur. 'Troggie, wake up it's time for Burnination school.' He's not budging.
# + kill / slay trogdor (while Trogdor's asleep, in his lair)
Like how?
# + talk trogdor (while he's asleep)
You yell some choice expletives at Trogdor but he doesn't wake up. There's a cool echo, though.

