;============
; Cliff Base
;============

; + look 
cliff_base_look_message:
.byte "You're at the base of a",13
.byte "very climbable cliff that",13
.byte "leads to Trogdor's",13
.byte "lair. This cliff is huge -",13
.byte "the kind where rocks start",13
.byte "falling down the minute you",13
.byte "try to climb it.",0

; + climb  (walks to center of cliff)
cliff_base_climb_message:
.byte "With a new determination",13
.byte "you dig your fingers into",13
.byte "the cliff face and begin to",13
.byte "haul yourself up the",13
.byte "mountain like you were in a",13
.byte "sports drink commercial.",0

cliff_base_climb2_message:
.byte "The mountain starts",13
.byte "rumbling and big loose",13
.byte "boulders start tumblin",13
.byte "down. You'd best avoid",13
.byte "thems.",0

