;===========
; Waterfall
;===========

; + look
waterfall_look_at_message:
.byte "There's a beautiful,",13
.byte "magical waterfall",13
.byte "cascading down the cliff",13
.byte "side.",0

; + look tree
waterfall_look_tree_message:
.byte "You see some trees in the",13
.byte "distance. You hold your",13
.byte "fingers up to one eye and",13
.byte "pretend to squash it.",0

; + look waterfall
waterfall_look_waterfall_message:
.byte "Upon closer inspection,",13
.byte "you discover it's not",13
.byte "magical. That's just mist,",13
.byte "not magic sparkles or",13
.byte "anything.",0

; + swim
waterfall_swim_message:
.byte "That waterfall would",13
.byte "probably churn you into one",13
.byte "of those weight-gain",13
.byte "protein smoothies.",0

; + climb cliff
waterfall_climb_cliff_message:
.byte "There aren't enough",13
.byte "footholds and you don't",13
.byte "have any carabeaners on",13
.byte "you.",0

