cottage_text1:
.byte	"YOU are Rather Dashing, a",13
.byte	"humble peasant living in",13
.byte	"the peasant kingdom of",13
.byte	"Peasantry.",0

; wait a few seconds

cottage_text2:
.byte	"You return home from a",13
.byte	"vacation on Scalding Lake",13
.byte	"only to find that TROGDOR",13
.byte	"THE BURNINATOR has",13
.byte	"burninated your thatched",13
.byte	"roof cottage along with all",13
.byte	"your goods and services.",0

; wait a few seconds, then start walking toward cottage

cottage_text3:
.byte	"With nothing left to lose,",13
.byte	"you swear to get revenge on",13
.byte	"the Wingaling Dragon in the",13
.byte	"name of burninated peasants",13
.byte	"everywhere.",0

; Walk to edge of screen


lake_w_message1:
.byte	"You head east toward the",13
.byte	"mountain atop which",13
.byte	"TROGDOR lives.",0

lake_e_message1:
.byte	"That's a nice looking lake.",0

; walk up a bit

river_message1:
.byte	"You can start playing in a",13
.byte	"second here.",0

; walks behind tree


; continues displaying previous message

; stops as approach knight

knight_message1:
.byte	"OK go for it.",0
