DIALOG_ALREADY		= $80
DIALOG_COTTAGE		= $81
DIALOG_PEASANT		= $82
DIALOG_CAPITAL_THERES	= $83
DIALOG_CAPITAL_TROGDOR	= $84

DIALOG_LITTLE		= $85
DIALOG_YOURE		= $86
DIALOG_CAPITAL_YOURE	= $87

DIALOG_ABOUT		= $88
DIALOG_CANT		= $89
DIALOG_DONT		= $8A
DIALOG_THERE		= $8B
DIALOG_CAPITAL_THERE	= $8C

DIALOG_BABY		= $8D
DIALOG_DEAD		= $8E
DIALOG_FROM		= $8F
DIALOG_HAVE		= $90
DIALOG_HERE		= $91
DIALOG_INTO		= $92
DIALOG_ITS		= $93
DIALOG_CAPITAL_ITS	= $94
DIALOG_JUST		= $95
DIALOG_LIKE		= $96
DIALOG_SAYS		= $97
DIALOG_SOME		= $98
DIALOG_THAT		= $99
DIALOG_CAPITAL_THAT	= $9A
DIALOG_THIS		= $9B
DIALOG_WITH		= $9C
DIALOG_YOUR		= $9D

DIALOG_ALL		= $9E
DIALOG_AND		= $9F
DIALOG_ARE		= $A0
DIALOG_BUT		= $A1
DIALOG_FOR		= $A2
DIALOG_GET		= $A3
DIALOG_GOT		= $A4
DIALOG_HIM		= $A5
DIALOG_HIS		= $A6
DIALOG_NOT		= $A7
DIALOG_NOW		= $A8
DIALOG_OLD		= $A9
DIALOG_ONE		= $AA
DIALOG_OUT		= $AB
DIALOG_SEE		= $AC
DIALOG_THE		= $AD
DIALOG_CAPITAL_THE	= $AE
DIALOG_WAS		= $AF
DIALOG_YOU		= $B0
DIALOG_CAPITAL_YOU	= $B1

DIALOG_AN		= $B2
DIALOG_AT		= $B3
DIALOG_BE		= $B4
DIALOG_DO		= $B5
DIALOG_GO		= $B6
DIALOG_HE		= $B7
DIALOG_CAPITAL_HE	= $B8
DIALOG_IN		= $B9
DIALOG_IS		= $BA
DIALOG_IT		= $BB
DIALOG_CAPITAL_IT	= $BC
DIALOG_MY		= $BD
DIALOG_NO		= $BE
DIALOG_CAPITAL_NO	= $BF
DIALOG_OF		= $C0
DIALOG_ON		= $C1
DIALOG_OR		= $C2
DIALOG_SO		= $C3
DIALOG_TO		= $C4
DIALOG_UP		= $C5

;.byte "already","cottage","peasant","There's","Trogdor"
;.byte "little","you're","You're"
;.byte "about","can't","don't","there","There"
;.byte "baby","dead","from","have","here","into","it's","It's"
;.byte "just","like","says","some","that","That","this","with","your",
;.byte "all","and","are","but","for","get","got","him","his","not"
;.byte "now","old","one","out","see","the","The","was","you","You"
;.byte "an","at","be","do","go","he","He","in","is","it","It"
;.byte "my","no","No","of","on","or","so","to","up"
