DIALOG_ALREADY		= $80
DIALOG_COTTAGE		= $81
DIALOG_PEASANT		= $82
DIALOG_CAPITAL_THERES	= $83
DIALOG_CAPITAL_TROGDOR	= $84

DIALOG_LITTLE		= $85
DIALOG_YOURE		= $86
DIALOG_CAPITAL_YOURE	= $87

DIALOG_ABOUT		= $88
DIALOG_CANT		= $89
DIALOG_DONT		= $8A
DIALOG_LOOKS		= $8B
DIALOG_THERE		= $8C
DIALOG_THOSE		= $8D
DIALOG_CAPITAL_THERE	= $8E

DIALOG_BABY		= $8F
DIALOG_DEAD		= $90
DIALOG_FROM		= $91
DIALOG_GAME		= $92
DIALOG_GOOD		= $93
DIALOG_HAVE		= $94
DIALOG_HERE		= $95
DIALOG_INTO		= $96
DIALOG_ITS		= $97
DIALOG_CAPITAL_ITS	= $98
DIALOG_JUST		= $99
DIALOG_LIKE		= $9A
DIALOG_OVER		= $9B
DIALOG_SAYS		= $9C
DIALOG_SOME		= $9D
DIALOG_THAT		= $9E
DIALOG_CAPITAL_THAT	= $9F
DIALOG_THIS		= $A0
DIALOG_WITH		= $A1
DIALOG_YOUR		= $A2

DIALOG_ALL		= $A3
DIALOG_AND		= $A4
DIALOG_ARE		= $A5
DIALOG_BUT		= $A6
DIALOG_FOR		= $A7
DIALOG_GET		= $A8
DIALOG_GOT		= $A9
DIALOG_HIM		= $AA
DIALOG_HIS		= $AB
DIALOG_NOT		= $AC
DIALOG_NOW		= $AD
DIALOG_OLD		= $AE
DIALOG_ONE		= $AF
DIALOG_OUT		= $B0
DIALOG_SEE		= $B1
DIALOG_THE		= $B2
DIALOG_CAPITAL_THE	= $B3
DIALOG_WAS		= $B4
DIALOG_YOU		= $B5
DIALOG_CAPITAL_YOU	= $B6

DIALOG_AN		= $B7
DIALOG_AT		= $B8
DIALOG_BE		= $B9
DIALOG_DO		= $BA
DIALOG_GO		= $BB
DIALOG_HE		= $BC
DIALOG_CAPITAL_HE	= $BD
DIALOG_IN		= $BE
DIALOG_IS		= $BF
DIALOG_IT		= $C0
DIALOG_CAPITAL_IT	= $C1
DIALOG_MY		= $C2
DIALOG_NO		= $C3
DIALOG_CAPITAL_NO	= $C4
DIALOG_OF		= $C5
DIALOG_ON		= $C6
DIALOG_OR		= $C7
DIALOG_SO		= $C8
DIALOG_TO		= $C9
DIALOG_UP		= $CA

;.byte "already","cottage","peasant","There's","Trogdor"
;.byte "little","you're","You're"
;.byte "about","can't","don't","there","There"
;.byte "baby","dead","from","have","here","into","it's","It's"
;.byte "just","like","says","some","that","That","this","with","your",
;.byte "all","and","are","but","for","get","got","him","his","not"
;.byte "now","old","one","out","see","the","The","was","you","You"
;.byte "an","at","be","do","go","he","He","in","is","it","It"
;.byte "my","no","No","of","on","or","so","to","up"
