;===================
; Outside Giant Inn
;===================

; + (exiting inn with pot on head)
outside_inn_pot_message:
.byte "Phew! You discard the big",13
.byte "black pot and wipe the",13
.byte "horse grease from your",13
.byte "eyes. The hood of your robe",13
.byte "is still covered in highly",13
.byte "flammable horse grease,",13
.byte "though.",0


; + look
outside_inn_look_message:
.byte "There's a giant Inn here.",13
.byte "It takes up, like, the",13
.byte "entire screen.",0

; + look door
outside_inn_door_look_note_message:
.byte "Just a door. A door with a",13
.byte "note on it.",0

; + look door (after fish fed)
outside_inn_door_look_message:
.byte "Just a door.",0

; + look inn
outside_inn_inn_look_message:
.byte "Looks okay from out here.",13
.byte "But do they have a free",13
.byte "breakfast buffet?",0

; + look sign
outside_inn_sign_look_message:
.byte "If you can't read that",13
.byte "sign, you need to quit",13
.byte "playing this game.",0
 
; + look window
outside_inn_window_look_message:
.byte "Check it out! There's an",13
.byte "INN in there.",0

; + look note
; + read note (before feed in lake)
outside_inn_note_look_message:
.byte "It says, ",34,"Gone Fishin",34," just",13
.byte "like that grog coozie your",13
.byte "cousin got you.",0

; + get/look/read note (after feed in lake)
outside_inn_note_look_gone_message:
.byte "The note is gone.",0

; + open
; + open door (after old man)
outside_inn_door_open_message:
.byte "You open the door and step",13
.byte "inside the inn.",0

; + open {none}/door (before old man)
outside_inn_door_open_locked_message:
.byte "It's locked fast!",0

; + knock {none}/door (closed)
outside_inn_door_knock_locked_message:
.byte "No answer.",0

; + knock (open)
outside_inn_door_knock_message:
.byte "Just open it, man!",0

; + get note
outside_inn_note_get_message:
.byte "What is it with you and",13
.byte "notes?! No!! ",0

; +3 POINTS: leave inn with pot on head


