;=================
; River and Stone
;=================

; + look
river_look_message:
.byte "Not much to see. River's",13
.byte "got a rock in it.",0

; + look water/river
river_look_at_water_message:
.byte "Got a rock in it.",0

; + look rock/stone
river_look_at_rock_message:
.byte "The ages have worn this",13
.byte "rock down. It is a rock of",13
.byte "ages. Still a-rollin.",0

; + swim river/water/rock/stone
river_swim_message:
.byte "Peasants can't swim. Like,",13
.byte "it's illegal.",0

; + get/take/steal rock
river_get_rock_message:
.byte "For what? Now you're just",13
.byte "making up puzzles to solve.",0

