;===================================
; Trogdor's Posh Lair / Inner Cave
;===================================

; Type any command other than "Talk" or "Talk Trogdor" after Trogdor wakes up
.byte "Trogdor is awake and a couple seconds from a Rather Dashing BBQ. Might as well say your peace with him.",0

; (Walk too close to Trogdor while he's asleep)
; {Trogdor burninates you without waking up}
.byte "Yow. Looks like you got a little too close. You dead. Maybe next time don't get too close.",0

; + look
.byte "You're in a giant cavern which houses a giant dragon. You didn't shrink or anything.",0

; + look trogdor (while he's asleep)
.byte "Holy crap! Trogdor's way bigger in person than he looks in most tapestries you've seen. All of the sudden, losing your cottage doesn't seem so bad anymore.",0

; + look trogdor (when he's awake)
.byte "Trogdor is looming menacingly over you with a tiny wee sword stuck in his belly. He looks like he's gonna kill you really soon.",0

; + (enter Trogdor's cave)
.byte "the beaded curtain slams shut behind you. There's no turning back now.",0

; +7 POINTS
; + throw sword
.byte "This is it! You hurl the Trog-Sword with all your might at the sleeping Burninator.",0
.byte "Now you've done it! Trogdor's awake and the Trog-Sword doesn't seem to be doing a whole lot.",0
.byte "Your legs lock in fear, your eyes glaze over and you wish for some Depeasant adult undergarments. But you think you hear Trogdor whimpering!",0
.byte "Aw crap, that's you whimpering. At least your voice still works, I guess.",0

; +10 POINTS
; + talk trogdor
.byte "You scream that your name is Rather Dashing and that Trogdor burninated your cottage and you're here for revenge!",0
.byte 34,"Sup, mortal,",34," booms Trogdor. ",34,"I really appreciate you making the effort to come all the way up here and vanquish me and all. But, I'm kinda indestructible.",34,0
.byte 34,"Yeah, I can't be killed. I'm surprised nobody mentioned that to you. I'll admit though, you've gotten farther than anybody else ever has. I bet they'll make a statue or something in honor of you somewheres.",34,0
.byte 34,"I can honestly say it'll be a pleasure and an honor to burninate you, Rather Dashing.",34,0
.byte "Aw that sure was nice of him!",0
.byte "Congratulations! You've won! No one can kill Trogdor but you came closer than anybody ever! Way to go!",0

; + wake up trogdor
.byte "'Troggie...', you murmur. 'Troggie, wake up it's time for Burnination school.' He's not budging.",0

; + attack trogdor (when he's asleep)
; + kill / slay trogdor (while Trogdor's asleep, in his lair)
.byte "Like how?",0

; + talk trogdor (while he's asleep)
.byte "You yell some choice expletives at Trogdor but he doesn't wake up. There's a cool echo, though.",0

