;=============
; Yellow Tree
;=============

; + look
yellow_tree_look_message:
.byte "Rushing river b/w yellow",13
.byte "tree.",0

; + look tree
yellow_tree_look_tree_message:
.byte "You're really hurtin' for",13
.byte "puzzle solutions, huh?",0

; + look cottage
yellow_tree_look_cottage_message:
.byte "You see a cottage in the",13
.byte "distance. You hold your",13
.byte "fingers up to one eye and",13
.byte "pretend to squash it.",0

