include ../../../Makefile.inc

PNG2RLE = ../../../gr-utils/png2rle
PNG2LZ4 = ../../../gr-utils/png2lz4

all:	ootw_c15_bath.inc ootw_c15_walk.inc ootw_c15_final.inc \
	ootw_c15_walkway.inc ootw_c15_bridge.inc ootw_c15_fall.inc

#####

ootw_c15_bath.inc:	$(PNG2RLE) \
	bath_00.png bath_01.png bath_02.png bath_03.png bath_04.png \
	bath_05.png bath_06.png bath_07.png bath_08.png bath_09.png \
	bath_10.png bath_11.png bath_12.png bath_13.png bath_14.png \
	bath_15.png bath_16.png bath_17.png bath_18.png bath_19.png \
	bath_20.png bath_21.png bath_22.png bath_23.png bath_24.png \
	bath_25.png bath_26.png bath_27.png bath_28.png bath_29.png \
	bath_30.png bath_31.png bath_32.png bath_33.png bath_34.png \
	bath_35.png bath_end.png
	$(PNG2RLE) asm bath_00.png bath_00_rle > ootw_c15_bath.inc
	$(PNG2RLE) asm bath_01.png bath_01_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_02.png bath_02_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_03.png bath_03_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_04.png bath_04_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_05.png bath_05_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_06.png bath_06_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_07.png bath_07_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_08.png bath_08_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_09.png bath_09_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_10.png bath_10_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_11.png bath_11_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_12.png bath_12_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_13.png bath_13_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_14.png bath_14_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_15.png bath_15_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_16.png bath_16_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_17.png bath_17_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_18.png bath_18_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_19.png bath_19_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_20.png bath_20_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_21.png bath_21_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_22.png bath_22_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_23.png bath_23_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_24.png bath_24_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_25.png bath_25_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_26.png bath_26_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_27.png bath_27_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_28.png bath_28_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_29.png bath_29_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_30.png bath_30_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_31.png bath_31_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_32.png bath_32_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_33.png bath_33_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_34.png bath_34_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_35.png bath_35_rle >> ootw_c15_bath.inc
	$(PNG2RLE) asm bath_end.png bath_end_rle >> ootw_c15_bath.inc

ootw_c15_walk.inc:	$(PNG2RLE) \
	walk_00.png walk_01.png walk_02.png walk_03.png walk_04.png \
	walk_05.png walk_06.png walk_07.png walk_08.png walk_09.png \
	walk_10.png bigshot_01.png bigshot_02.png bigshot_03.png bigshot_04.png
	$(PNG2RLE) asm walk_00.png walk00_rle > ootw_c15_walk.inc
	$(PNG2RLE) asm walk_01.png walk01_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_02.png walk02_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_03.png walk03_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_04.png walk04_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_05.png walk05_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_06.png walk06_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_07.png walk07_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_08.png walk08_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_09.png walk09_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm walk_10.png walk10_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm bigshot_01.png bigshot01_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm bigshot_02.png bigshot02_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm bigshot_03.png bigshot03_rle >> ootw_c15_walk.inc
	$(PNG2RLE) asm bigshot_04.png bigshot04_rle >> ootw_c15_walk.inc


ootw_c15_final.inc:	$(PNG2RLE) \
	walkway1.png above_pit.png final.png
	$(PNG2RLE) asm walkway1.png walkway1_rle > ootw_c15_final.inc
	$(PNG2RLE) asm above_pit.png above_pit_rle >> ootw_c15_final.inc
	$(PNG2RLE) asm final.png final_rle >> ootw_c15_final.inc

ootw_c15_walkway.inc:	$(PNG2RLE) \
	walkway2.png walkway2_after.png crash1.png \
	crash2.png crash3.png crash4.png crash5.png crash6.png crash7.png
	$(PNG2RLE) asm walkway2.png walkway2_rle > ootw_c15_walkway.inc
	$(PNG2RLE) asm walkway2_after.png walkway2_after_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash1.png crash1_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash2.png crash2_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash3.png crash3_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash4.png crash4_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash5.png crash5_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash6.png crash6_rle >> ootw_c15_walkway.inc
	$(PNG2RLE) asm crash7.png crash7_rle >> ootw_c15_walkway.inc


ootw_c15_bridge.inc:	$(PNG2RLE) \
	walkway3.png \
	lshot1.png lshot2.png lshot3.png lshot4.png lshot5.png lshot6.png
	$(PNG2RLE) asm walkway3.png walkway3_rle > ootw_c15_bridge.inc
	$(PNG2RLE) asm lshot1.png lshot1_rle >> ootw_c15_bridge.inc
	$(PNG2RLE) asm lshot2.png lshot2_rle >> ootw_c15_bridge.inc
	$(PNG2RLE) asm lshot3.png lshot3_rle >> ootw_c15_bridge.inc
	$(PNG2RLE) asm lshot4.png lshot4_rle >> ootw_c15_bridge.inc
	$(PNG2RLE) asm lshot5.png lshot5_rle >> ootw_c15_bridge.inc
	$(PNG2RLE) asm lshot6.png lshot6_rle >> ootw_c15_bridge.inc

ootw_c15_fall.inc:	$(PNG2RLE) \
	fall_bg.png \
	fall01.png fall02.png fall03.png fall04.png fall05.png \
	fall06.png fall07.png fall08.png fall09.png fall10.png \
	fall11.png fall12.png fall13.png fall14.png fall15.png \
	fall16.png fall17.png fall18.png fall19.png fall20.png \
	fall21.png fall22.png fall23.png
	$(PNG2RLE) asm fall_bg.png fall_bg_rle > ootw_c15_fall.inc
	$(PNG2RLE) asm fall01.png fall01_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall02.png fall02_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall03.png fall03_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall04.png fall04_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall05.png fall05_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall06.png fall06_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall07.png fall07_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall08.png fall08_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall09.png fall09_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall10.png fall10_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall11.png fall11_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall12.png fall12_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall13.png fall13_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall14.png fall14_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall15.png fall15_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall16.png fall16_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall17.png fall17_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall18.png fall18_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall19.png fall19_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall20.png fall20_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall21.png fall21_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall22.png fall22_rle >> ootw_c15_fall.inc
	$(PNG2RLE) asm fall23.png fall23_rle >> ootw_c15_fall.inc

#####

clean:		
		rm -f *~ *.o *.lst *.lzz *.inc

