include ../../../../../Makefile.inc

PNG2GR = ../../../../../utils/gr-utils/png2gr
LZSA = ~/research/lzsa/lzsa/lzsa

all:	intro_zappo.inc intro_gone.inc

#####

intro_zappo.inc:	\
	blue_zappo.lzsa \
	zappo01.lzsa zappo02.lzsa zappo03.lzsa zappo04.lzsa \
	zappo05.lzsa zappo06.lzsa zappo07.lzsa zappo08.lzsa \
	zappo09.lzsa zappo10.lzsa zappo11.lzsa zappo12.lzsa \
	zappo13.lzsa zappo14.lzsa zappo15.lzsa zappo16.lzsa \
	zappo17.lzsa
	echo "blue_zappo_lzsa: .incbin \"blue_zappo.lzsa\"" > intro_zappo.inc
	echo "zappo01_lzsa: .incbin \"zappo01.lzsa\"" >> intro_zappo.inc
	echo "zappo02_lzsa: .incbin \"zappo02.lzsa\"" >> intro_zappo.inc
	echo "zappo03_lzsa: .incbin \"zappo03.lzsa\"" >> intro_zappo.inc
	echo "zappo04_lzsa: .incbin \"zappo04.lzsa\"" >> intro_zappo.inc
	echo "zappo05_lzsa: .incbin \"zappo05.lzsa\"" >> intro_zappo.inc
	echo "zappo06_lzsa: .incbin \"zappo06.lzsa\"" >> intro_zappo.inc
	echo "zappo07_lzsa: .incbin \"zappo07.lzsa\"" >> intro_zappo.inc
	echo "zappo08_lzsa: .incbin \"zappo08.lzsa\"" >> intro_zappo.inc
	echo "zappo09_lzsa: .incbin \"zappo09.lzsa\"" >> intro_zappo.inc
	echo "zappo10_lzsa: .incbin \"zappo10.lzsa\"" >> intro_zappo.inc
	echo "zappo11_lzsa: .incbin \"zappo11.lzsa\"" >> intro_zappo.inc
	echo "zappo12_lzsa: .incbin \"zappo12.lzsa\"" >> intro_zappo.inc
	echo "zappo13_lzsa: .incbin \"zappo13.lzsa\"" >> intro_zappo.inc
	echo "zappo14_lzsa: .incbin \"zappo14.lzsa\"" >> intro_zappo.inc
	echo "zappo15_lzsa: .incbin \"zappo15.lzsa\"" >> intro_zappo.inc
	echo "zappo16_lzsa: .incbin \"zappo16.lzsa\"" >> intro_zappo.inc
	echo "zappo17_lzsa: .incbin \"zappo17.lzsa\"" >> intro_zappo.inc

intro_gone.inc:	\
	intro_gone.lzsa \
	gone01.lzsa gone02.lzsa gone03.lzsa gone04.lzsa gone05.lzsa \
	gone06.lzsa gone07.lzsa gone08.lzsa gone09.lzsa gone10.lzsa \
	gone11.lzsa gone12.lzsa gone13.lzsa gone14.lzsa gone15.lzsa \
	gone16.lzsa gone17.lzsa gone18.lzsa gone19.lzsa gone20.lzsa \
	gone21.lzsa gone22.lzsa gone23.lzsa gone24.lzsa gone25.lzsa \
	gone26.lzsa gone27.lzsa gone28.lzsa gone29.lzsa gone30.lzsa \
	gone31.lzsa gone32.lzsa gone33.lzsa gone34.lzsa gone35.lzsa \
	gone36.lzsa gone37.lzsa gone38.lzsa gone39.lzsa gone40.lzsa \
	gone41.lzsa gone42.lzsa gone43.lzsa
	echo "gone_lzsa: .incbin \"intro_gone.lzsa\"" > intro_gone.inc
	echo "gone01_lzsa: .incbin \"gone01.lzsa\"" >> intro_gone.inc
	echo "gone02_lzsa: .incbin \"gone02.lzsa\"" >> intro_gone.inc
	echo "gone03_lzsa: .incbin \"gone03.lzsa\"" >> intro_gone.inc
	echo "gone04_lzsa: .incbin \"gone04.lzsa\"" >> intro_gone.inc
	echo "gone05_lzsa: .incbin \"gone05.lzsa\"" >> intro_gone.inc
	echo "gone06_lzsa: .incbin \"gone06.lzsa\"" >> intro_gone.inc
	echo "gone07_lzsa: .incbin \"gone07.lzsa\"" >> intro_gone.inc
	echo "gone08_lzsa: .incbin \"gone08.lzsa\"" >> intro_gone.inc
	echo "gone09_lzsa: .incbin \"gone09.lzsa\"" >> intro_gone.inc
	echo "gone10_lzsa: .incbin \"gone10.lzsa\"" >> intro_gone.inc
	echo "gone11_lzsa: .incbin \"gone11.lzsa\"" >> intro_gone.inc
#	echo "gone12_lzsa: .incbin \"gone12.lzsa\"" >> intro_gone.inc
	echo "gone13_lzsa: .incbin \"gone13.lzsa\"" >> intro_gone.inc
	echo "gone14_lzsa: .incbin \"gone14.lzsa\"" >> intro_gone.inc
#	echo "gone15_lzsa: .incbin \"gone15.lzsa\"" >> intro_gone.inc
	echo "gone16_lzsa: .incbin \"gone16.lzsa\"" >> intro_gone.inc
#	echo "gone17_lzsa: .incbin \"gone17.lzsa\"" >> intro_gone.inc
	echo "gone18_lzsa: .incbin \"gone18.lzsa\"" >> intro_gone.inc
	echo "gone19_lzsa: .incbin \"gone19.lzsa\"" >> intro_gone.inc
	echo "gone20_lzsa: .incbin \"gone20.lzsa\"" >> intro_gone.inc
	echo "gone21_lzsa: .incbin \"gone21.lzsa\"" >> intro_gone.inc
#	echo "gone22_lzsa: .incbin \"gone22.lzsa\"" >> intro_gone.inc
	echo "gone23_lzsa: .incbin \"gone23.lzsa\"" >> intro_gone.inc
	echo "gone24_lzsa: .incbin \"gone24.lzsa\"" >> intro_gone.inc
	echo "gone25_lzsa: .incbin \"gone25.lzsa\"" >> intro_gone.inc
	echo "gone26_lzsa: .incbin \"gone26.lzsa\"" >> intro_gone.inc
	echo "gone27_lzsa: .incbin \"gone27.lzsa\"" >> intro_gone.inc
	echo "gone28_lzsa: .incbin \"gone28.lzsa\"" >> intro_gone.inc
#	echo "gone29_lzsa: .incbin \"gone29.lzsa\"" >> intro_gone.inc
#	echo "gone30_lzsa: .incbin \"gone30.lzsa\"" >> intro_gone.inc
	echo "gone31_lzsa: .incbin \"gone31.lzsa\"" >> intro_gone.inc
	echo "gone32_lzsa: .incbin \"gone32.lzsa\"" >> intro_gone.inc
#	echo "gone33_lzsa: .incbin \"gone33.lzsa\"" >> intro_gone.inc
	echo "gone34_lzsa: .incbin \"gone34.lzsa\"" >> intro_gone.inc
	echo "gone35_lzsa: .incbin \"gone35.lzsa\"" >> intro_gone.inc
	echo "gone36_lzsa: .incbin \"gone36.lzsa\"" >> intro_gone.inc
	echo "gone37_lzsa: .incbin \"gone37.lzsa\"" >> intro_gone.inc
	echo "gone38_lzsa: .incbin \"gone38.lzsa\"" >> intro_gone.inc
	echo "gone39_lzsa: .incbin \"gone39.lzsa\"" >> intro_gone.inc
	echo "gone40_lzsa: .incbin \"gone40.lzsa\"" >> intro_gone.inc
#	echo "gone41_lzsa: .incbin \"gone41.lzsa\"" >> intro_gone.inc
	echo "gone42_lzsa: .incbin \"gone42.lzsa\"" >> intro_gone.inc
	echo "gone43_lzsa: .incbin \"gone43.lzsa\"" >> intro_gone.inc


%.gr:	%.png
	$(PNG2GR) $< $@

%.lzsa:	%.gr
	$(LZSA) -r -f2 $< $@

#####

clean:		
		rm -f *~ *.inc *.gr *.lzsa

