include ../../../../../Makefile.inc

#PNG2RLE = ../../../gr-utils/png2rle
#PNG2LZ4 = ../../../gr-utils/png2lz4
PNG2GR = ../../../../../utils/gr-utils/png2gr
LZSA = ~/research/lzsa/lzsa/lzsa

all:	intro_zappo.inc intro_gone.inc

#####

intro_zappo.inc:	\
	blue_zappo.lzsa \
	zappo01.lzsa zappo02.lzsa zappo03.lzsa zappo04.lzsa \
	zappo05.lzsa zappo06.lzsa zappo07.lzsa zappo08.lzsa \
	zappo09.lzsa zappo10.lzsa zappo11.lzsa zappo12.lzsa \
	zappo13.lzsa zappo14.lzsa zappo15.lzsa zappo16.lzsa \
	zappo17.lzsa
	echo "blue_zappo_lzsa: .incbin \"blue_zappo.lzsa\"" > intro_zappo.inc
	echo "zappo01_lzsa: .incbin \"zappo01.lzsa\"" >> intro_zappo.inc
	echo "zappo02_lzsa: .incbin \"zappo02.lzsa\"" >> intro_zappo.inc
	echo "zappo03_lzsa: .incbin \"zappo03.lzsa\"" >> intro_zappo.inc
	echo "zappo04_lzsa: .incbin \"zappo04.lzsa\"" >> intro_zappo.inc
	echo "zappo05_lzsa: .incbin \"zappo05.lzsa\"" >> intro_zappo.inc
	echo "zappo06_lzsa: .incbin \"zappo06.lzsa\"" >> intro_zappo.inc
	echo "zappo07_lzsa: .incbin \"zappo07.lzsa\"" >> intro_zappo.inc
	echo "zappo08_lzsa: .incbin \"zappo08.lzsa\"" >> intro_zappo.inc
	echo "zappo09_lzsa: .incbin \"zappo09.lzsa\"" >> intro_zappo.inc
	echo "zappo10_lzsa: .incbin \"zappo10.lzsa\"" >> intro_zappo.inc
	echo "zappo11_lzsa: .incbin \"zappo11.lzsa\"" >> intro_zappo.inc
	echo "zappo12_lzsa: .incbin \"zappo12.lzsa\"" >> intro_zappo.inc
	echo "zappo13_lzsa: .incbin \"zappo13.lzsa\"" >> intro_zappo.inc
	echo "zappo14_lzsa: .incbin \"zappo14.lzsa\"" >> intro_zappo.inc
	echo "zappo15_lzsa: .incbin \"zappo15.lzsa\"" >> intro_zappo.inc
	echo "zappo16_lzsa: .incbin \"zappo16.lzsa\"" >> intro_zappo.inc
	echo "zappo17_lzsa: .incbin \"zappo17.lzsa\"" >> intro_zappo.inc

intro_gone.inc:	\
	intro_gone.lzsa \
	gone01.lzsa gone02.lzsa gone03.lzsa gone04.lzsa gone05.lzsa \
	gone06.lzsa gone07.lzsa gone08.lzsa gone09.lzsa gone10.lzsa \
	gone11.lzsa gone12.lzsa gone13.lzsa gone14.lzsa gone15.lzsa \
	gone16.lzsa gone17.lzsa gone18.lzsa gone19.lzsa gone20.lzsa \
	gone21.lzsa gone22.lzsa gone23.lzsa gone24.lzsa gone25.lzsa \
	gone26.lzsa gone27.lzsa gone28.lzsa gone29.lzsa gone30.lzsa \
	gone31.lzsa gone32.lzsa gone33.lzsa gone34.lzsa gone35.lzsa \
	gone36.lzsa gone37.lzsa gone38.lzsa gone39.lzsa gone40.lzsa \
	gone41.lzsa gone42.lzsa gone43.lzsa
	echo "gone_lzsa: .incbin \"intro_gone.lzsa\"" > intro_gone.inc
	echo "gone01_lzsa: .incbin \"gone01.lzsa\"" >> intro_gone.inc
	echo "gone02_lzsa: .incbin \"gone02.lzsa\"" >> intro_gone.inc
	echo "gone03_lzsa: .incbin \"gone03.lzsa\"" >> intro_gone.inc
	echo "gone04_lzsa: .incbin \"gone04.lzsa\"" >> intro_gone.inc
	echo "gone05_lzsa: .incbin \"gone05.lzsa\"" >> intro_gone.inc
	echo "gone06_lzsa: .incbin \"gone06.lzsa\"" >> intro_gone.inc
	echo "gone07_lzsa: .incbin \"gone07.lzsa\"" >> intro_gone.inc
	echo "gone08_lzsa: .incbin \"gone08.lzsa\"" >> intro_gone.inc
	echo "gone09_lzsa: .incbin \"gone09.lzsa\"" >> intro_gone.inc
	echo "gone10_lzsa: .incbin \"gone10.lzsa\"" >> intro_gone.inc
	echo "gone11_lzsa: .incbin \"gone11.lzsa\"" >> intro_gone.inc
#	echo "gone12_lzsa: .incbin \"gone12.lzsa\"" >> intro_gone.inc
	echo "gone13_lzsa: .incbin \"gone13.lzsa\"" >> intro_gone.inc
	echo "gone14_lzsa: .incbin \"gone14.lzsa\"" >> intro_gone.inc
#	echo "gone15_lzsa: .incbin \"gone15.lzsa\"" >> intro_gone.inc
	echo "gone16_lzsa: .incbin \"gone16.lzsa\"" >> intro_gone.inc
#	echo "gone17_lzsa: .incbin \"gone17.lzsa\"" >> intro_gone.inc
	echo "gone18_lzsa: .incbin \"gone18.lzsa\"" >> intro_gone.inc
	echo "gone19_lzsa: .incbin \"gone19.lzsa\"" >> intro_gone.inc
	echo "gone20_lzsa: .incbin \"gone20.lzsa\"" >> intro_gone.inc
	echo "gone21_lzsa: .incbin \"gone21.lzsa\"" >> intro_gone.inc
#	echo "gone22_lzsa: .incbin \"gone22.lzsa\"" >> intro_gone.inc
	echo "gone23_lzsa: .incbin \"gone23.lzsa\"" >> intro_gone.inc
	echo "gone24_lzsa: .incbin \"gone24.lzsa\"" >> intro_gone.inc
	echo "gone25_lzsa: .incbin \"gone25.lzsa\"" >> intro_gone.inc
	echo "gone26_lzsa: .incbin \"gone26.lzsa\"" >> intro_gone.inc
	echo "gone27_lzsa: .incbin \"gone27.lzsa\"" >> intro_gone.inc
	echo "gone28_lzsa: .incbin \"gone28.lzsa\"" >> intro_gone.inc
#	echo "gone29_lzsa: .incbin \"gone29.lzsa\"" >> intro_gone.inc
#	echo "gone30_lzsa: .incbin \"gone30.lzsa\"" >> intro_gone.inc
	echo "gone31_lzsa: .incbin \"gone31.lzsa\"" >> intro_gone.inc
	echo "gone32_lzsa: .incbin \"gone32.lzsa\"" >> intro_gone.inc
#	echo "gone33_lzsa: .incbin \"gone33.lzsa\"" >> intro_gone.inc
	echo "gone34_lzsa: .incbin \"gone34.lzsa\"" >> intro_gone.inc
	echo "gone35_lzsa: .incbin \"gone35.lzsa\"" >> intro_gone.inc
	echo "gone36_lzsa: .incbin \"gone36.lzsa\"" >> intro_gone.inc
	echo "gone37_lzsa: .incbin \"gone37.lzsa\"" >> intro_gone.inc
	echo "gone38_lzsa: .incbin \"gone38.lzsa\"" >> intro_gone.inc
	echo "gone39_lzsa: .incbin \"gone39.lzsa\"" >> intro_gone.inc
	echo "gone40_lzsa: .incbin \"gone40.lzsa\"" >> intro_gone.inc
#	echo "gone41_lzsa: .incbin \"gone41.lzsa\"" >> intro_gone.inc
	echo "gone42_lzsa: .incbin \"gone42.lzsa\"" >> intro_gone.inc
	echo "gone43_lzsa: .incbin \"gone43.lzsa\"" >> intro_gone.inc


%.gr:	%.png
	$(PNG2GR) $< $@

%.lzsa:	%.gr
	$(LZSA) -r -f2 $< $@


#####

#
#intro_zappo.inc:	$(PNG2RLE) \
#	blue_zappo.png \
#	zappo01.png zappo02.png zappo03.png zappo04.png \
#	zappo05.png zappo06.png zappo07.png zappo08.png \
#	zappo09.png zappo10.png zappo11.png zappo12.png \
#	zappo13.png zappo14.png zappo15.png zappo16.png \
#	zappo17.png
#	$(PNG2RLE) asm blue_zappo.png blue_zappo_rle > intro_zappo.inc
#	$(PNG2RLE) asm zappo01.png zappo01_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo02.png zappo02_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo03.png zappo03_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo04.png zappo04_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo05.png zappo05_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo06.png zappo06_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo07.png zappo07_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo08.png zappo08_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo09.png zappo09_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo10.png zappo10_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo11.png zappo11_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo12.png zappo12_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo13.png zappo13_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo14.png zappo14_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo15.png zappo15_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo16.png zappo16_rle >> intro_zappo.inc
#	$(PNG2RLE) asm zappo17.png zappo17_rle >> intro_zappo.inc


#intro_zappo_lz4.inc:	$(PNG2LZ4) \
#	blue_zappo.png \
#	zappo01.png zappo02.png zappo03.png zappo04.png \
#	zappo05.png zappo06.png zappo07.png zappo08.png \
#	zappo09.png zappo10.png zappo11.png zappo12.png \
#	zappo13.png zappo14.png zappo15.png zappo16.png \
#	zappo17.png
#	$(PNG2LZ4) asm blue_zappo.png blue_zappo_rle > intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo01.png zappo01_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo02.png zappo02_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo03.png zappo03_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo04.png zappo04_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo05.png zappo05_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo06.png zappo06_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo07.png zappo07_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo08.png zappo08_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo09.png zappo09_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo10.png zappo10_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo11.png zappo11_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo12.png zappo12_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo13.png zappo13_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo14.png zappo14_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo15.png zappo15_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo16.png zappo16_rle >> intro_zappo_lz4.inc
#	$(PNG2LZ4) asm zappo17.png zappo17_rle >> intro_zappo_lz4.inc


#####

#intro_gone.inc:	$(PNG2RLE) \
#	intro_gone.png \
#	gone01.png gone02.png gone03.png gone04.png gone05.png \
#	gone06.png gone07.png gone08.png gone09.png gone10.png \
#	gone11.png gone12.png gone13.png gone14.png gone15.png \
#	gone16.png gone17.png gone18.png gone19.png gone20.png \
#	gone21.png gone22.png gone23.png gone24.png gone25.png \
#	gone26.png gone27.png gone28.png gone29.png gone30.png \
#	gone31.png gone32.png gone33.png gone34.png gone35.png \
#	gone36.png gone37.png gone38.png gone39.png gone40.png \
#	gone41.png gone42.png gone43.png
#	$(PNG2RLE) asm intro_gone.png gone_rle > intro_gone.inc
#	$(PNG2RLE) asm gone01.png gone01_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone02.png gone02_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone03.png gone03_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone04.png gone04_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone05.png gone05_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone06.png gone06_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone07.png gone07_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone08.png gone08_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone09.png gone09_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone10.png gone10_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone11.png gone11_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone12.png gone12_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone13.png gone13_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone14.png gone14_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone15.png gone15_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone16.png gone16_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone17.png gone17_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone18.png gone18_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone19.png gone19_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone20.png gone20_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone21.png gone21_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone22.png gone22_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone23.png gone23_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone24.png gone24_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone25.png gone25_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone26.png gone26_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone27.png gone27_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone28.png gone28_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone29.png gone29_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone30.png gone30_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone31.png gone31_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone32.png gone32_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone33.png gone33_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone34.png gone34_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone35.png gone35_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone36.png gone36_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone37.png gone37_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone38.png gone38_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone39.png gone39_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone40.png gone40_rle >> intro_gone.inc
##	$(PNG2RLE) asm gone41.png gone41_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone42.png gone42_rle >> intro_gone.inc
#	$(PNG2RLE) asm gone43.png gone43_rle >> intro_gone.inc


#intro_gone_lz4.inc:	$(PNG2LZ4) \
#	intro_gone.png \
#	gone01.png gone02.png gone03.png gone04.png gone05.png \
#	gone06.png gone07.png gone08.png gone09.png gone10.png \
#	gone11.png gone12.png gone13.png gone14.png gone15.png \
#	gone16.png gone17.png gone18.png gone19.png gone20.png \
#	gone21.png gone22.png gone23.png gone24.png gone25.png \
#	gone26.png gone27.png gone28.png gone29.png gone30.png \
#	gone31.png gone32.png gone33.png gone34.png gone35.png \
#	gone36.png gone37.png gone38.png gone39.png gone40.png \
#	gone41.png gone42.png gone43.png
#	$(PNG2LZ4) asm intro_gone.png gone_rle > intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone01.png gone01_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone02.png gone02_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone03.png gone03_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone04.png gone04_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone05.png gone05_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone06.png gone06_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone07.png gone07_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone08.png gone08_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone09.png gone09_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone10.png gone10_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone11.png gone11_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone12.png gone12_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone13.png gone13_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone14.png gone14_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone15.png gone15_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone16.png gone16_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone17.png gone17_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone18.png gone18_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone19.png gone19_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone20.png gone20_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone21.png gone21_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone22.png gone22_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone23.png gone23_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone24.png gone24_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone25.png gone25_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone26.png gone26_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone27.png gone27_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone28.png gone28_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone29.png gone29_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone30.png gone30_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone31.png gone31_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone32.png gone32_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone33.png gone33_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone34.png gone34_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone35.png gone35_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone36.png gone36_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone37.png gone37_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone38.png gone38_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone39.png gone39_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone40.png gone40_rle >> intro_gone_lz4.inc
##	$(PNG2LZ4) asm gone41.png gone41_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone42.png gone42_rle >> intro_gone_lz4.inc
#	$(PNG2LZ4) asm gone43.png gone43_rle >> intro_gone_lz4.inc
#


#####

clean:		
		rm -f *~ *.inc *.gr *.lzsa

