swim_progression:
	.word swimming1
	.word swimming2
	.word swimming3
	.word swimming4
	.word swimming5
	.word swimming6
	.word swimming7
	.word swimming8


swimming1:
	.byte 2,8
	.byte $77,$AA
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $22,$22
	.byte $55,$77

swimming2:
	.byte 2,8
	.byte $77,$7A
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $52,$22
	.byte $A5,$77

swimming3:
	.byte 2,8
	.byte $77,$77
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $55,$22
	.byte $AA,$77

swimming4:
	.byte 2,8
	.byte $7A,$77
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $52,$22
	.byte $A5,$77

swimming5:
	.byte 2,8
	.byte $AA,$77
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $22,$22
	.byte $55,$77

swimming6:
	.byte 2,8
	.byte $7A,$77
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $22,$72
	.byte $55,$A7

swimming7:
	.byte 2,8
	.byte $77,$77
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $22,$77
	.byte $55,$AA

swimming8:
	.byte 2,8
	.byte $77,$7A
	.byte $55,$55
	.byte $05,$05
	.byte $00,$00
	.byte $00,$00
	.byte $22,$22
	.byte $22,$72
	.byte $55,$A7

