; Danger: if you mess with QLOAD you'll have to update these

QLOAD_LOC=$B00

load_file = QLOAD_LOC+$20

;pt3_init_song=QLOAD_LOC+$BF9
;mockingboard_init=QLOAD_LOC+$E31
;reset_ay_both=QLOAD_LOC+$E40
;clear_ay_both=QLOAD_LOC+$E82
;mockingboard_setup_interrupt=QLOAD_LOC+$E8F
;mockingboard_disable_interrupt=QLOAD_LOC+$EC1
;interrupt_handler=QLOAD_LOC+$ECD
;mockingboard_patch=QLOAD_LOC+$F4E
;mockingboard_detect=QLOAD_LOC+$F76

;PT3_LOC=QLOAD_LOC+$1000

