collider_rle:	.byte $28 ; ysize=48
	.byte $A4,$00, $04, $44, $AB,$C4, $A0,$12,$44, $04, $AA,$00
	.byte $CC, $A7,$04, $C4, $04, $CC, $0C, $C4
	.byte $A5,$04, $C4, $CC, $A3,$0C, $CC, $C4, $04
	.byte $44, $04, $AC,$00, $CC, $00, $0C, $A7,$00
	.byte $CC, $00, $CC, $A4,$00, $CC, $0C, $A5,$00
	.byte $0C, $CC, $C4, $AD,$00, $CC, $00, $0C
	.byte $A7,$00, $CC, $00, $CC, $A3,$00, $CC, $0C
	.byte $A8,$00, $CC, $C0, $AC,$00, $CC, $A9,$00, $CC
	.byte $00, $CC, $00,$00, $C0, $CC, $A9,$00, $44
	.byte $CC, $C0, $A5,$00, $A6,$04, $CC, $04,$04, $A5,$40
	.byte $04,$04, $CC, $04, $CC, $04,$04, $CC, $AC,$04
	.byte $CC, $A4,$04, $A7,$00, $CC, $A9,$00, $CC, $00
	.byte $CC, $00,$00, $CC, $AC,$00, $CC, $AB,$00, $CC
	.byte $A9,$00, $CC, $00, $CC, $00,$00, $CC, $AA,$00
	.byte $40, $00, $CC, $AB,$00, $CC, $00, $0C
	.byte $A7,$00, $CC, $00, $CC, $00,$00, $CC, $AA,$00
	.byte $44, $00, $CC, $AB,$00, $CC, $A9,$0C, $CC
	.byte $00, $CC, $00,$00, $CC, $AC,$00, $CC, $AB,$00
	.byte $CC, $A7,$00, $0C, $00, $CC, $00, $CC
	.byte $00,$00, $CC, $AB,$00, $CC, $0C, $AB,$00, $CC
	.byte $00, $0C, $A7,$00, $CC, $00, $CC, $00,$00
	.byte $CC,$CC, $A9,$00, $C0, $CC, $AC,$00, $CC, $00
	.byte $0C, $A7,$00, $CC, $00, $CC, $00,$00, $CC,$CC
	.byte $C0, $A8,$00, $CC, $AD,$00, $CC, $00, $0C
	.byte $A7,$00, $CC, $00, $CC, $00,$00, $CC, $00
	.byte $0C, $CC, $C0, $A4,$00, $C0, $0C,$0C, $AD,$00
	.byte $CC, $00, $0C, $A7,$00, $CC, $00, $CC
	.byte $00,$00, $CC, $A3,$00, $A4,$0C, $CC, $0C, $AF,$00
	.byte $CC, $00, $0C, $A7,$00, $CC, $00, $CC
	.byte $00,$00, $6C, $A6,$00, $60, $0C, $A0,$10,$00, $CC
	.byte $00, $0C, $A7,$00, $CC, $00, $CC, $00,$00
	.byte $66, $A5,$00, $66, $06, $A0,$11,$00, $CC, $00
	.byte $0C, $A7,$00, $CC, $00, $CC, $AD,$00, $40
	.byte $A7,$00, $A6,$44, $CC, $C4, $CC, $A7,$C4, $6C
	.byte $64, $CC, $AE,$C4, $A6,$44, $00, $A5,$44, $C4
	.byte $AB,$C6, $A0,$11,$CC, $C4, $A4,$44, $A0,$A1,$00
	.byte $A1
collider_p200_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A4,$AA, $A5,$CA, $A0,$23,$AA, $CC, $00
	.byte $66, $00, $CC, $A0,$21,$AA, $CA, $CC,$CC, $60
	.byte $00, $60, $CC, $A0,$1F,$AA, $CA, $A4,$CC, $00
	.byte $05, $00, $CC, $A0,$1F,$AA, $A3,$0C, $CC,$CC, $66
	.byte $00, $66, $CC, $A0,$1F,$AA, $A4,$A0, $A5,$AC, $A0,$F1,$AA
	.byte $A1
collider_p201_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A4,$AA, $A5,$CA, $A0,$23,$AA, $CC, $00
	.byte $66, $00, $CC, $A0,$1C,$AA, $0A,$0A, $CA, $0A
	.byte $00, $C0, $CC,$CC, $60, $00, $60, $CC
	.byte $A0,$1C,$AA, $C0, $2C, $CC, $C0, $A4,$CC, $00
	.byte $05, $00, $CC, $A0,$1C,$AA, $CC, $C2, $CC
	.byte $A3,$0C, $CC,$CC, $66, $00, $66, $CC, $A0,$1C,$AA
	.byte $00, $0C, $A3,$00, $A0,$02,$A0, $A5,$AC, $A0,$F1,$AA
	.byte $A1
collider_p202_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A4,$AA, $A5,$CA, $A0,$23,$AA, $CC, $00
	.byte $66, $00, $CC, $A0,$21,$AA, $C0, $CC,$CC, $20
	.byte $22, $20, $CC, $A0,$1F,$AA, $C0, $A4,$CC, $02
	.byte $22, $02, $CC, $A0,$1F,$AA, $A3,$0C, $CC,$CC, $66
	.byte $00, $66, $CC, $A0,$1F,$AA, $A4,$A0, $A5,$AC, $A0,$F1,$AA
	.byte $A1
collider_p203_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A4,$AA, $A5,$CA, $0A, $A0,$22,$AA, $CC
	.byte $C0, $CC, $C0, $CC, $00, $A0,$20,$AA, $C0
	.byte $CC,$CC, $2C, $22, $2C, $CC,$CC, $A0,$1F,$AA, $A4,$CC
	.byte $C2, $22, $C2, $CC,$CC, $A0,$1F,$AA, $0C,$0C, $A6,$CC
	.byte $00, $A0,$1F,$AA, $A3,$A0, $A0,$01,$AC, $A0,$01,$A0, $A3,$AC, $A0,$01,$A0
	.byte $A0,$F0,$AA
	.byte $A1
