;=========================
; zero page
;=========================

; ZX02 addresses

ZP=$00

offset          = ZP+0
ZX0_src         = ZP+2
ZX0_dst         = ZP+4
bitr            = ZP+6
pntr            = ZP+7


GBASL	= $26
GBASH	= $27
V2	= $2D

APPLEII_MODEL	= $8B

HGRPAGE = $E6

TEMPY		= $F0
XX		= $F1

INL		= $F2
INH		= $F3

MB_VALUE	= $F5
MB_ADDR_L	= $F6
MB_ADDR_H	= $F7
YPOS		= $FE
TCOLOR		= $FF


