ZX02 = ~/research/6502_compression/zx02.git/build/zx02


all:	bugsy_still_alive.pt3.zx02

bugsy_still_alive.pt3.zx02:   bugsy_still_alive.pt3
	$(ZX02) bugsy_still_alive.pt3 bugsy_still_alive.pt3.zx02


clean:
	rm -f *~ *.zx02

