ship_flame0_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$7B,$AA, $DA, $A0,$26,$AA, $DA, $DD, $A0,$26,$AA
	.byte $DD,$DD, $A0,$26,$AA, $DD,$DD, $A0,$26,$AA, $DD, $9D, $A0,$25,$AA
	.byte $DD,$DD, $99, $A0,$25,$AA, $A0,$01,$AD, $DD, $99, $A0,$26,$AA
	.byte $DD,$DD, $A0,$26,$AA, $DD,$DD, $A0,$26,$AA, $DD,$DD, $A0,$27,$AA, $DD
	.byte $A0,$B5,$AA
	.byte $A1
ship_flame1_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$7B,$AA, $DA, $A0,$22,$AA, $DA, $A5,$DD, $A0,$1F,$AA
	.byte $DA, $A7,$DD, $99, $A0,$1D,$AA, $DA, $A9,$DD, $99
	.byte $A0,$1B,$AA, $DA, $AA,$DD, $99,$99, $A0,$19,$AA, $DA, $AB,$DD
	.byte $A3,$99, $A0,$1A,$AA, $A0,$01,$AD, $AA,$DD, $D9, $99,$99, $A0,$1C,$AA
	.byte $A0,$01,$AD, $A9,$DD, $D9, $99, $A0,$1E,$AA, $A0,$01,$AD, $A8,$DD
	.byte $99, $A0,$20,$AA, $A0,$02,$AD, $A5,$DD, $D9, $A0,$23,$AA, $A4,$AD
	.byte $DD, $A0,$B5,$AA
	.byte $A1
ship_flame2_rle:	.byte $28 ; ysize=48
	.byte $A0,$17,$CC, $A6,$AA, $A0,$22,$CC, $A7,$AA, $A0,$21,$CC, $A8,$AA, $A0,$20,$CC
	.byte $A9,$AA, $A0,$1F,$CC, $AA,$AA, $A0,$1E,$CC, $AB,$AA, $A0,$1D,$CC, $AC,$AA
	.byte $A9,$CC, $A7,$77, $AC,$CC, $AD,$AA, $A8,$CC, $77, $DD
	.byte $77, $DD, $77, $73, $77, $A8,$CC, $A0,$01,$AC
	.byte $A3,$CC, $AE,$AA, $A3,$AC, $A4,$CC, $77, $7D, $77
	.byte $7D, $77, $7B, $77, $A7,$CC, $DC, $A0,$02,$AA
	.byte $A0,$01,$AC, $CC, $A0,$11,$AA, $A4,$CC, $A7,$C7, $CC,$CC, $DC
	.byte $A5,$DD, $A0,$15,$AA, $A4,$D9, $A7,$9C, $A7,$DD, $99, $A0,$15,$AA
	.byte $FD, $AB,$DD, $FD, $A5,$DD, $99, $A0,$15,$AA, $FF
	.byte $ED, $A9,$DD, $EE, $FF, $A4,$DD, $99,$99, $A0,$15,$AA
	.byte $FF, $FE,$FE, $A7,$ED, $FE,$FE, $FF, $F9, $FD
	.byte $A4,$99, $A0,$15,$AA, $FF, $EE, $DE, $A7,$DD, $DE
	.byte $EE, $FF, $D9, $DD, $D9,$D9, $99,$99, $A0,$15,$AA
	.byte $FF, $AA,$DD, $DE, $DF, $A4,$DD, $D9, $99
	.byte $A0,$15,$AA, $A4,$DD, $A7,$9D, $A7,$DD, $99, $A0,$15,$AA, $A4,$B9
	.byte $A7,$BB, $BD,$BD, $A5,$DD, $D9, $A0,$15,$AA, $AE,$BB, $A4,$BD
	.byte $DD, $A3,$AA, $BA, $A0,$11,$AA, $A0,$13,$BB, $A0,$01,$AA, $BA
	.byte $BB,$BB, $A0,$11,$AA, $A0,$28,$BB, $A0,$28,$DB, $A0,$28,$DD
	.byte $A1
ship_flame3_rle:	.byte $28 ; ysize=48
	.byte $A0,$17,$CC, $A6,$AA, $A0,$22,$CC, $A7,$AA, $A0,$21,$CC, $A8,$AA, $A0,$20,$CC
	.byte $A9,$AA, $A0,$1F,$CC, $AA,$AA, $A0,$1E,$CC, $AB,$AA, $A0,$1D,$CC, $AC,$AA
	.byte $A0,$1C,$CC, $AD,$AA, $A0,$17,$CC, $A0,$01,$AC, $A3,$CC, $AE,$AA, $A3,$AC
	.byte $A0,$12,$CC, $DC, $A0,$02,$AA, $A0,$01,$AC, $CC, $A0,$11,$AA, $A3,$9C
	.byte $1C, $A9,$CC, $DC, $A4,$9D, $DD, $A0,$15,$AA, $A4,$D9
	.byte $A7,$9C, $D1, $D9,$D9, $A4,$DD, $99, $A0,$15,$AA, $FD
	.byte $A5,$DD, $A4,$D9, $DD,$DD, $FD, $A5,$DD, $99, $A0,$15,$AA
	.byte $FF, $ED, $DD,$DD, $DC, $A3,$DD, $9D, $DD,$DD
	.byte $EE, $FF, $A4,$DD, $99, $11, $A0,$15,$AA, $FF
	.byte $FE,$FE, $A7,$ED, $FE,$FE, $FF, $F9, $FD, $A3,$99
	.byte $11, $A0,$15,$AA, $FF, $EE, $DE, $A5,$DD, $9D
	.byte $DD, $DE, $EE, $FF, $D9, $DD, $D9,$D9
	.byte $99, $11, $A0,$15,$AA, $FF, $A3,$DD, $DC, $A6,$DD
	.byte $DE, $FF, $A4,$DD, $D9, $91, $A0,$15,$AA, $A4,$DD
	.byte $9D,$9D, $A4,$99, $9D, $A7,$DD, $99, $A0,$15,$AA, $A3,$99
	.byte $19, $A7,$BB, $B1, $B9, $D9, $A4,$9D, $D9
	.byte $A0,$15,$AA, $AE,$BB, $A4,$BD, $DD, $A3,$AA, $BA, $A0,$11,$AA
	.byte $A0,$13,$BB, $A0,$01,$AA, $BA, $BB,$BB, $A0,$11,$AA, $A0,$28,$BB, $A0,$28,$DB
	.byte $A0,$28,$DD
	.byte $A1
ship_flame4_rle:	.byte $28 ; ysize=48
	.byte $A0,$17,$CC, $A6,$AA, $A0,$22,$CC, $A7,$AA, $A0,$21,$CC, $A8,$AA, $A0,$20,$CC
	.byte $A9,$AA, $A0,$1F,$CC, $AA,$AA, $A0,$1E,$CC, $AB,$AA, $A0,$1D,$CC, $AC,$AA
	.byte $A0,$1C,$CC, $AD,$AA, $A0,$17,$CC, $A0,$01,$AC, $A3,$CC, $AE,$AA, $A3,$AC
	.byte $A0,$12,$CC, $DC, $A0,$02,$AA, $A0,$01,$AC, $CC, $A0,$11,$AA, $A3,$9C
	.byte $1C, $A9,$CC, $DC, $A4,$9D, $DD, $A0,$15,$AA, $A4,$DD
	.byte $A7,$9C, $DC,$DC, $D9, $A4,$DD, $99, $A0,$15,$AA, $FD
	.byte $DD,$DD, $CD, $A8,$DD, $FD, $A5,$DD, $99, $A0,$15,$AA
	.byte $FF, $ED, $A5,$DD, $9D, $A3,$DD, $EE, $FF
	.byte $A4,$DD, $99, $11, $A0,$15,$AA, $FF, $FE,$FE, $A7,$ED
	.byte $A3,$FE, $FD,$FD, $9D, $99,$99, $11, $A0,$15,$AA, $FF
	.byte $EE, $DE, $A4,$DD, $9D, $DD,$DD, $DE, $EE
	.byte $FE, $A3,$DD, $D9, $99, $11, $A0,$15,$AA, $FF
	.byte $DD,$DD, $CD, $A7,$DD, $DE, $FF, $A4,$DD, $D9
	.byte $91, $A0,$15,$AA, $A4,$DD, $A7,$9D, $A7,$DD, $99, $A0,$15,$AA
	.byte $A3,$9D, $1D, $A9,$BB, $D9, $A4,$9D, $D9, $A0,$15,$AA
	.byte $AE,$BB, $A4,$BD, $DD, $A3,$AA, $BA, $A0,$11,$AA, $A0,$13,$BB
	.byte $A0,$01,$AA, $BA, $BB,$BB, $A0,$11,$AA, $A0,$28,$BB, $A0,$28,$DB, $A0,$28,$DD
	.byte $A1
ship_flame5_rle:	.byte $28 ; ysize=48
	.byte $A0,$17,$CC, $A6,$AA, $A0,$22,$CC, $A7,$AA, $A0,$21,$CC, $A8,$AA, $A0,$20,$CC
	.byte $A9,$AA, $A0,$1F,$CC, $AA,$AA, $A0,$1E,$CC, $AB,$AA, $A0,$1D,$CC, $AC,$AA
	.byte $A0,$1C,$CC, $AD,$AA, $A0,$17,$CC, $A0,$01,$AC, $A3,$CC, $AE,$AA, $A3,$AC
	.byte $A0,$12,$CC, $DC, $A0,$02,$AA, $A0,$01,$AC, $CC, $A0,$11,$AA, $A3,$9C
	.byte $1C, $A9,$CC, $DC, $A4,$9D, $DD, $A0,$15,$AA, $A4,$DD
	.byte $9D,$9D, $A4,$9C, $9D, $DD,$DD, $D9, $A4,$DD, $99
	.byte $A0,$15,$AA, $FD, $DD, $DC, $A9,$DD, $FD, $A5,$DD
	.byte $99, $A0,$15,$AA, $FF, $ED, $A3,$DD, $DC, $A5,$DD
	.byte $EE, $FF, $A4,$DD, $9D, $11, $A0,$15,$AA, $FF
	.byte $FE,$FE, $A7,$ED, $FE,$FE, $A3,$FD, $9D, $99, $19
	.byte $11, $A0,$15,$AA, $FF, $EE, $DE, $A7,$DD, $DE
	.byte $EE, $FD, $A3,$DD, $D9, $99, $11, $A0,$15,$AA
	.byte $FF, $A4,$DD, $DC, $A5,$DD, $DE, $FF, $A5,$DD
	.byte $91, $A0,$15,$AA, $DD,$DD, $DC, $DD, $A6,$9D, $A8,$DD
	.byte $99, $A0,$15,$AA, $A3,$9D, $1D, $BD,$BD, $A4,$BB, $A3,$BD
	.byte $D9, $A4,$9D, $D9, $A0,$15,$AA, $AE,$BB, $A4,$BD, $DD
	.byte $A3,$AA, $BA, $A0,$11,$AA, $A0,$13,$BB, $A0,$01,$AA, $BA, $BB,$BB
	.byte $A0,$11,$AA, $A0,$28,$BB, $A0,$28,$DB, $A0,$28,$DD
	.byte $A1
