walking00_rle:	.byte $28 ; ysize=48
	.byte $A0,$3A,$AA, $89, $99,$99, $9A, $A0,$23,$AA, $88,$88, $B9,$B9
	.byte $99, $A0,$23,$AA, $88, $A3,$BB, $99, $A0,$23,$AA, $B8
	.byte $BF, $BB, $BF, $B9, $A0,$23,$AA, $A0,$01,$AB, $BB
	.byte $B3, $BB, $A0,$01,$AB, $A0,$24,$AA, $BB, $3B, $BB
	.byte $A0,$25,$AA, $3B, $BB,$BB, $A0,$25,$AA, $A3,$33, $A0,$23,$AA, $0A
	.byte $00, $A3,$03, $00, $0A, $A0,$20,$AA, $A9,$00, $0A
	.byte $A0,$1D,$AA, $AB,$00, $0A, $A0,$1B,$AA, $AD,$00, $A0,$1B,$AA, $AE,$00
	.byte $A0,$1A,$AA, $AE,$00, $A0,$1A,$AA, $AC,$00, $B0, $A0,$01,$A0, $A0,$1A,$AA
	.byte $BB,$BB, $A9,$00, $B0, $BB, $A0,$1B,$AA, $BB,$BB, $A9,$00
	.byte $BB,$BB, $A0,$1B,$AA, $BB,$BB, $A9,$00, $BB,$BB, $A0,$1B,$AA, $BB,$BB
	.byte $A9,$00, $BB,$BB, $A0,$AE,$AA
	.byte $A1
walking01_rle:	.byte $28 ; ysize=48
	.byte $A0,$3A,$AA, $89, $99,$99, $9A, $A0,$23,$AA, $88,$88, $B9,$B9
	.byte $99, $A0,$23,$AA, $88, $A3,$BB, $99, $A0,$23,$AA, $B8
	.byte $BF, $BB, $BF, $B9, $A0,$23,$AA, $A0,$01,$AB, $BB
	.byte $B3, $BB, $A0,$01,$AB, $A0,$24,$AA, $BB, $3B, $BB
	.byte $A0,$25,$AA, $3B, $BB,$BB, $A0,$25,$AA, $A3,$33, $A0,$23,$AA, $0A
	.byte $00, $A3,$03, $00, $0A, $A0,$20,$AA, $A9,$00, $0A
	.byte $A0,$1D,$AA, $AB,$00, $0A, $A0,$1B,$AA, $AD,$00, $A0,$1B,$AA, $AE,$00
	.byte $A0,$1A,$AA, $AE,$00, $A0,$1A,$AA, $AC,$00, $B0, $A0,$01,$A0, $A0,$1A,$AA
	.byte $BB,$BB, $A9,$00, $B0, $BB, $A0,$1B,$AA, $BB,$BB, $A9,$00
	.byte $BB,$BB, $A0,$1B,$AA, $BB,$BB, $A9,$00, $BB,$BB, $A0,$1B,$AA, $BB,$BB
	.byte $A9,$00, $BB,$BB, $A0,$AE,$AA
	.byte $A1
walking02_rle:	.byte $28 ; ysize=48
	.byte $A0,$12,$AA, $89, $99, $B9,$B9, $99, $9A, $A0,$21,$AA
	.byte $88, $A5,$BB, $99, $A0,$21,$AA, $88, $BB, $FB
	.byte $BB, $FB, $BB, $99, $A0,$21,$AA, $A0,$01,$A8, $A5,$BB
	.byte $A0,$01,$A9, $A0,$22,$AA, $BB,$BB, $B3, $BB,$BB, $A0,$23,$AA, $BB,$BB
	.byte $B3, $BB,$BB, $A0,$24,$AA, $A3,$BB, $A0,$25,$AA, $A3,$33, $A0,$23,$AA
	.byte $0A, $3A, $A3,$33, $3A, $0A, $A0,$1F,$AA, $0A
	.byte $A9,$00, $0A, $A0,$1C,$AA, $AD,$00, $A0,$1A,$AA, $AF,$00, $A0,$18,$AA
	.byte $0A, $AF,$00, $A0,$18,$AA, $A0,$11,$00, $A0,$16,$AA, $A0,$12,$00, $A0,$16,$AA
	.byte $A0,$01,$A0, $A0,$11,$00, $A0,$17,$AA, $AE,$00, $B0,$B0, $A0,$19,$AA, $BB
	.byte $B0, $AB,$00, $BB,$BB, $A0,$19,$AA, $BB,$BB, $AB,$00, $BB,$BB
	.byte $A0,$19,$AA, $BB,$BB, $AB,$00, $BB,$BB, $A0,$AC,$AA
	.byte $A1
walking03_rle:	.byte $28 ; ysize=48
	.byte $A0,$10,$AA, $99, $FB, $8B, $BB, $FB, $8B
	.byte $99, $A0,$21,$AA, $A7,$BB, $A0,$21,$AA, $A3,$BB, $3B, $A3,$BB
	.byte $A0,$21,$AA, $A0,$01,$AB, $A5,$BB, $A0,$01,$AB, $A0,$22,$AA, $BB, $A3,$B3
	.byte $BB, $A0,$23,$AA, $A0,$01,$AB, $A3,$BB, $A0,$01,$AB, $A0,$24,$AA, $A3,$33
	.byte $A0,$23,$AA, $0A, $A5,$33, $0A, $A0,$1F,$AA, $0A, $00,$00
	.byte $A5,$03, $00,$00, $0A, $A0,$1C,$AA, $AD,$00, $0A, $A0,$19,$AA
	.byte $AF,$00, $0A, $A0,$17,$AA, $A0,$11,$00, $A0,$16,$AA, $0A, $A0,$12,$00
	.byte $A0,$15,$AA, $A0,$13,$00, $A0,$15,$AA, $A0,$13,$00, $A0,$15,$AA, $A0,$13,$00, $A0,$15,$AA
	.byte $A0,$13,$00, $A0,$16,$AA, $BB,$BB, $AD,$00, $B0, $BB, $A0,$17,$AA
	.byte $BB,$BB, $AD,$00, $BB,$BB, $A0,$17,$AA, $BB,$BB, $AD,$00, $BB,$BB
	.byte $A0,$AC,$AA
	.byte $A1
walking04_rle:	.byte $28 ; ysize=48
	.byte $AF,$AA, $A8,$BB, $A0,$21,$AA, $BB,$BB, $3B,$3B, $BB,$BB, $A0,$22,$AA
	.byte $A6,$BB, $A0,$23,$AA, $A4,$3B, $A0,$23,$AA, $3A, $A4,$33, $3A
	.byte $A0,$22,$AA, $A6,$33, $0A, $A0,$20,$AA, $0A, $03,$03, $33,$33
	.byte $03,$03, $00, $0A, $A0,$1D,$AA, $0A, $AB,$00, $0A
	.byte $A0,$19,$AA, $0A,$0A, $AE,$00, $0A, $A0,$16,$AA, $A0,$12,$00, $0A
	.byte $A0,$14,$AA, $0A, $A0,$13,$00, $0A, $A0,$13,$AA, $A0,$15,$00, $A0,$12,$AA
	.byte $0A, $A0,$15,$00, $0A, $A0,$11,$AA, $A0,$17,$00, $A0,$10,$AA, $0A
	.byte $A0,$17,$00, $0A, $AF,$AA, $A0,$19,$00, $A0,$10,$AA, $A0,$16,$00, $A0,$01,$A0
	.byte $A0,$11,$AA, $A0,$01,$A0, $A0,$14,$00, $B0, $A0,$13,$AA, $BB,$BB, $A0,$10,$00
	.byte $B0, $BB,$BB, $A0,$13,$AA, $A3,$BB, $AF,$00, $A3,$BB, $A0,$AA,$AA
	.byte $A1
walking05_rle:	.byte $28 ; ysize=48
	.byte $A0,$12,$AA, $A6,$BB, $A0,$01,$A5, $A0,$21,$AA, $3B, $A4,$BB, $3B
	.byte $A0,$22,$AA, $A6,$33, $A0,$21,$AA, $3A, $A7,$33, $A0,$1F,$AA, $0A
	.byte $A8,$33, $3A, $0A, $A0,$1B,$AA, $0A, $00,$00, $A8,$03
	.byte $A3,$00, $0A, $A0,$17,$AA, $0A, $A0,$11,$00, $0A, $A0,$13,$AA
	.byte $0A, $A0,$14,$00, $0A, $A0,$11,$AA, $A0,$17,$00, $0A, $A0,$10,$AA
	.byte $A0,$18,$00, $AF,$AA, $0A, $A0,$19,$00, $AE,$AA, $A0,$1A,$00, $0A
	.byte $AC,$AA, $A0,$1C,$00, $AC,$AA, $A0,$1C,$00, $AB,$AA, $A0,$1D,$00, $0A
	.byte $A9,$AA, $0A, $A0,$1E,$00, $A9,$AA, $A0,$1F,$00, $AA,$AA, $A0,$1D,$00
	.byte $AC,$AA, $A0,$18,$00, $B0,$B0, $A0,$02,$A0, $AC,$AA, $BB, $B0
	.byte $A0,$15,$00, $A3,$BB, $A0,$A7,$AA
	.byte $A1
walking06_rle:	.byte $28 ; ysize=48
	.byte $AE,$AA, $A9,$33, $A0,$1D,$AA, $0A, $AB,$33, $05, $A0,$19,$AA
	.byte $0A, $A3,$00, $03, $A8,$33, $03, $00, $0A,$0A
	.byte $A0,$16,$AA, $A0,$14,$00, $0A, $A0,$11,$AA, $0A, $A0,$16,$00, $A0,$10,$AA
	.byte $A0,$19,$00, $0A, $AD,$AA, $A0,$1B,$00, $0A, $AA,$AA, $0A
	.byte $A0,$1E,$00, $A9,$AA, $A0,$1F,$00, $0A, $A7,$AA, $0A, $A0,$20,$00
	.byte $A7,$AA, $A0,$21,$00, $A7,$AA, $A0,$22,$00, $A5,$AA, $A0,$23,$00, $A5,$AA
	.byte $A0,$24,$00, $A3,$AA, $A0,$25,$00, $A3,$AA, $A0,$26,$00, $A0,$02,$AA, $A0,$26,$00
	.byte $A0,$02,$AA, $A0,$01,$A0, $A0,$24,$00, $A4,$AA, $A0,$01,$A0, $A0,$21,$00, $A0,$01,$A0
	.byte $A6,$AA, $A0,$01,$A0, $A0,$1F,$00, $BB, $A0,$A5,$AA
	.byte $A1
walking07_rle:	.byte $28 ; ysize=48
	.byte $A9,$AA, $A3,$0A, $AB,$33, $A0,$18,$AA, $0A, $A0,$12,$00, $A4,$0A
	.byte $AF,$AA, $0A, $A0,$19,$00, $AC,$AA, $0A, $A0,$1C,$00, $0A
	.byte $A9,$AA, $A0,$20,$00, $0A, $A6,$AA, $A0,$22,$00, $0A, $A4,$AA
	.byte $A0,$24,$00, $A4,$AA, $A0,$25,$00, $A3,$AA, $A0,$25,$00, $A3,$AA, $A0,$26,$00
	.byte $A0,$02,$AA, $A0,$26,$00, $A0,$02,$AA, $A0,$26,$00, $0A, $A0,$01,$AA, $A0,$27,$00
	.byte $A0,$01,$AA, $A0,$27,$00, $A0,$01,$AA, $A0,$EF,$00, $A0,$01,$A0, $A0,$A0,$AA
	.byte $A1
walking08_rle:	.byte $28 ; ysize=48
	.byte $A4,$AA, $0A, $A0,$20,$00, $0A, $A4,$AA, $0A, $A0,$23,$00
	.byte $0A, $A0,$02,$AA, $0A, $A0,$26,$00, $0A, $A0,$FF,$00, $A0,$FF,$00
	.byte $A0,$A9,$00, $A0,$A0,$AA
	.byte $A1
