5 HOME
10 PRINT "  LOADING MIST V0.7"
20 PRINT
30 PRINT "       ______"
40 PRINT "     A \/\/\/ SOFTWARE PRODUCTION"
50 PRINT:PRINT:PRINT:PRINT
60 PRINT "CONTROLS:  ARROWS OR WASD"
70 PRINT "           ENTER MOVES/ACTION"
80 PRINT
90 PRINT "SPOILERS (BECAUSE NOT ALL IMPLEMENTED)"
100 PRINT "    CLOCK: 2:40 2-2-1"
105 PRINT "    ALL SWITCHES DOWN EXCEPT DOCK"
110 PRINT "    FIREPLACE PATTERN IN BOOK"
120 PRINT CHR$(4);"BRUN LOADER"
