5 HOME
10 PRINT "LOADING MIST V0.82"
20 PRINT:PRINT
40 PRINT "CONTROLS:  ARROWS OR WASD"
50 PRINT "           ENTER MOVES/ACTION"
60 PRINT:PRINT
70 PRINT "BASED ON MYST BY CYAN INC"
80 PRINT "APPLE II PORT: VINCE WEAVER"
90 PRINT "DISK CODE    : QKUMBA"
92 PRINT "SOUND CODE   : OLIVER SCHMIDT"
94 PRINT "LZSA CODE    : EMMANUEL MARTY"
95 PRINT
100 PRINT "       ______"
110 PRINT "     A \/\/\/ SOFTWARE PRODUCTION"
120 PRINT CHR$(4);"BRUN LOADER"
