5 HOME
10 PRINT "LOADING MIST V0.88"
20 PRINT:PRINT
40 PRINT "CONTROLS: "
42 PRINT "     MOVE CURSOR    : ARROWS OR WASD"
44 PRINT "     FORWARD/ACTION : ENTER"
45 PRINT "     ENABLE JOYSTICK: CONTROL-J"
46 PRINT "     LOAD GAME      : CONTROL-L"
48 PRINT "     SAVE GAME      : CONTROL-S"
60 PRINT:PRINT
70 PRINT "BASED ON MYST BY CYAN INC"
80 PRINT "APPLE II PORT: VINCE WEAVER"
90 PRINT "DISK CODE    : QKUMBA"
92 PRINT "SOUND CODE   : OLIVER SCHMIDT"
94 PRINT "LZSA CODE    : EMMANUEL MARTY"
95 PRINT
100 PRINT "       ______"
110 PRINT "     A \/\/\/ SOFTWARE PRODUCTION"
120 PRINT CHR$(4);"BRUN LOADER"
