blue_page_sprite:
	.byte 5,4
	.byte $66,$66,$66,$66,$aa
	.byte $66,$66,$66,$66,$aa
	.byte $aa,$66,$66,$66,$66
	.byte $aa,$66,$66,$66,$66

red_page_sprite:
	.byte 5,4
	.byte $33,$33,$33,$33,$aa
	.byte $33,$33,$33,$33,$aa
	.byte $aa,$33,$33,$33,$33
	.byte $aa,$33,$33,$33,$33

white_page_sprite:
	.byte 5,4
	.byte $ff,$ff,$ff,$ff,$aa
	.byte $ff,$ff,$ff,$ff,$aa
	.byte $aa,$ff,$ff,$ff,$ff
	.byte $aa,$ff,$ff,$ff,$ff

blue_page_small_sprite:
	.byte 2,3
	.byte $6A,$6A
	.byte $66,$66
	.byte $66,$66

red_page_small_sprite:
	.byte 2,3
	.byte $3A,$3A
	.byte $33,$33
	.byte $33,$33

