HGR_SPRITE = ../../../../utils/hgr-utils/hgr_make_sprite

all:	sprites_jhonka.inc


sprites_jhonka.inc:	sprites_jhonka.png
	$(HGR_SPRITE) -s -l note_sprite sprites_jhonka.png 217 105  230 116 > sprites_jhonka.inc
	

clean:
	rm -f *~ sprites_jhonka.inc

