5 HOME
10 PRINT "      BUBBLE GR"
15 PRINT "  BY DEATER / FAST CODE BY SERATO_FIG"
20 PRINT
25 PRINT "THIS VERSION YOU CAN CHANGE"
27 PRINT "PARAMETERS ON THE FLY"
28 PRINT "+ TRY PRESSING A/Z TO INC/DEC I"
29 PRINT "+ TRY PRESSING J/M TO INC/DEC J"
30 PRINT:PRINT "PRESS ANY KEY TO START"
40 GET A$
50 IF A$="Q" THEN END
60 PRINT:PRINT CHR$(4)"BRUN BUBBLE_GR"

