HGR_SPRITE = ../../../../utils/hgr-utils/hgr_make_sprite
SPRITE_DIR = ../../location_kerrek1/sprites_kerrek1/

all:	peasant_shoot_sprites_right.inc peasant_shoot_sprites_left.inc \
	kerrek_walk_sprites_left.inc kerrek_walk_sprites_right.inc \
	kerrek_hit_sprites_left.inc kerrek_hit_sprites_right.inc


kerrek_walk_sprites_right.inc:	$(SPRITE_DIR)/kerrek_walk_right_sprites.png
	$(HGR_SPRITE) -l kerrek_walk0r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png  14  59  34 107 > kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk0r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png  14 112  34 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk1r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png  42  59  62 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk1r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png  42 112  62 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk2r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png  70  59  90 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk2r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png  70 112  90 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk3r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png  98  59 118 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk3r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png  98 112 118 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk4r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png 126  59 146 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk4r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png 126 112 146 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk5r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png 154  59 174 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk5r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png 154 112 174 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk6r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png 182  59 202 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk6r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png 182 112 202 160 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk7r_sprite $(SPRITE_DIR)/kerrek_walk_right_sprites.png 210  59 230 107 >> kerrek_walk_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_walk7r_mask   $(SPRITE_DIR)/kerrek_walk_right_sprites.png 210 112 230 160 >> kerrek_walk_sprites_right.inc

kerrek_walk_sprites_left.inc:	$(SPRITE_DIR)/kerrek_walk_left_sprites.png
	$(HGR_SPRITE) -l kerrek_walk0l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png  14  59  34 107 > kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk0l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png  14 112  34 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk1l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png  42  59  62 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk1l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png  42 112  62 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk2l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png  70  59  90 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk2l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png  70 112  90 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk3l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png  98  59 118 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk3l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png  98 112 118 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk4l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png 126  59 146 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk4l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png 126 112 146 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk5l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png 154  59 174 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk5l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png 154 112 174 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk6l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png 182  59 202 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk6l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png 182 112 202 160 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk7l_sprite $(SPRITE_DIR)/kerrek_walk_left_sprites.png 210  59 230 107 >> kerrek_walk_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_walk7l_mask   $(SPRITE_DIR)/kerrek_walk_left_sprites.png 210 112 230 160 >> kerrek_walk_sprites_left.inc

$(SPRITE_DIR)/kerrek_body_sprites.inc:	$(SPRITE_DIR)/kerrek_body_sprites.png
	$(HGR_SPRITE) -l kerrek_body1r_sprite $(SPRITE_DIR)/kerrek_body_sprites.png 154  28 202  42 > $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body1r_mask   $(SPRITE_DIR)/kerrek_body_sprites.png 154  49 202  63 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body0r_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  14  28  62  42 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body0r_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  14  49  62  63 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body2r_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  14  91  62 105 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body2r_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  14 112  62 126 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body3r_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  14 154  62 168 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body3r_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  14 175  62 189 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body1l_sprite $(SPRITE_DIR)/kerrek_body_sprites.png 224  28 272  42 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body1l_mask   $(SPRITE_DIR)/kerrek_body_sprites.png 224  49 272  63 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body0l_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  84  28 132  42 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body0l_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  84  49 132  63 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body2l_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  84  91 132 105 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body2l_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  84 112 132 126 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body3l_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  84 154 132 168 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_body3l_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  84 175 132 189 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_flies0_sprite $(SPRITE_DIR)/kerrek_body_sprites.png 210  70 230  81 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_flies0_mask   $(SPRITE_DIR)/kerrek_body_sprites.png 210  84 230  95 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_flies1_sprite $(SPRITE_DIR)/kerrek_body_sprites.png 210  99 230 110 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_flies1_mask   $(SPRITE_DIR)/kerrek_body_sprites.png 210 113 230 124 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_flies2_sprite $(SPRITE_DIR)/kerrek_body_sprites.png 210 130 230 140 >> $(SPRITE_DIR)/kerrek_body_sprites.inc
	$(HGR_SPRITE) -l kerrek_flies2_mask   $(SPRITE_DIR)/kerrek_body_sprites.png 210 143 230 153 >> $(SPRITE_DIR)/kerrek_body_sprites.inc

peasant_shoot_sprites_left.inc:	$(SPRITE_DIR)/peasant_shot_left.png
	$(HGR_SPRITE) -l shoot0_l_sprite $(SPRITE_DIR)/peasant_shot_left.png  14  32  34  62 > peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot0_l_mask   $(SPRITE_DIR)/peasant_shot_left.png  14  63  34  93 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot1_l_sprite $(SPRITE_DIR)/peasant_shot_left.png  56  32  76  62 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot1_l_mask   $(SPRITE_DIR)/peasant_shot_left.png  56  63  76  93 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot2_l_sprite $(SPRITE_DIR)/peasant_shot_left.png  98  32 118  62 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot2_l_mask   $(SPRITE_DIR)/peasant_shot_left.png  98  63 118  93 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot3_l_sprite $(SPRITE_DIR)/peasant_shot_left.png 140  32 160  62 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot3_l_mask   $(SPRITE_DIR)/peasant_shot_left.png 140  63 160  93 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot4_l_sprite $(SPRITE_DIR)/peasant_shot_left.png 182  32 202  62 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot4_l_mask   $(SPRITE_DIR)/peasant_shot_left.png 182  63 202  93 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot5_l_sprite $(SPRITE_DIR)/peasant_shot_left.png   0 130  27 160 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot5_l_mask   $(SPRITE_DIR)/peasant_shot_left.png   0 161  27 191 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot6_l_sprite $(SPRITE_DIR)/peasant_shot_left.png  42 130  69 160 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot6_l_mask   $(SPRITE_DIR)/peasant_shot_left.png  42 161  69 191 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot7_l_sprite $(SPRITE_DIR)/peasant_shot_left.png  84 130 111 160 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot7_l_mask   $(SPRITE_DIR)/peasant_shot_left.png  84 161 111 191 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot8_l_sprite $(SPRITE_DIR)/peasant_shot_left.png 140 130 160 160 >> peasant_shoot_sprites_left.inc
	$(HGR_SPRITE) -l shoot8_l_mask   $(SPRITE_DIR)/peasant_shot_left.png 140 161 160 191 >> peasant_shoot_sprites_left.inc

peasant_shoot_sprites_right.inc:	$(SPRITE_DIR)/peasant_shot_right.png
	$(HGR_SPRITE) -l shoot0_r_sprite $(SPRITE_DIR)/peasant_shot_right.png  14  33  34  63 > peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot0_r_mask   $(SPRITE_DIR)/peasant_shot_right.png  14  64  34  94 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot1_r_sprite $(SPRITE_DIR)/peasant_shot_right.png  56  33  76  63 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot1_r_mask   $(SPRITE_DIR)/peasant_shot_right.png  56  64  76  94 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot2_r_sprite $(SPRITE_DIR)/peasant_shot_right.png  98  33 118  63 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot2_r_mask   $(SPRITE_DIR)/peasant_shot_right.png  98  64 118  94 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot3_r_sprite $(SPRITE_DIR)/peasant_shot_right.png 140  33 160  63 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot3_r_mask   $(SPRITE_DIR)/peasant_shot_right.png 140  64 160  94 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot4_r_sprite $(SPRITE_DIR)/peasant_shot_right.png 182  33 202  63 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot4_r_mask   $(SPRITE_DIR)/peasant_shot_right.png 182  64 202  94 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot5_r_sprite $(SPRITE_DIR)/peasant_shot_right.png  14 130  41 160 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot5_r_mask   $(SPRITE_DIR)/peasant_shot_right.png  14 161  41 191 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot6_r_sprite $(SPRITE_DIR)/peasant_shot_right.png  56 130  83 160 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot6_r_mask   $(SPRITE_DIR)/peasant_shot_right.png  56 161  83 191 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot7_r_sprite $(SPRITE_DIR)/peasant_shot_right.png  98 130 125 160 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot7_r_mask   $(SPRITE_DIR)/peasant_shot_right.png  98 161 125 191 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot8_r_sprite $(SPRITE_DIR)/peasant_shot_right.png 140 130 160 160 >> peasant_shoot_sprites_right.inc
	$(HGR_SPRITE) -l shoot8_r_mask   $(SPRITE_DIR)/peasant_shot_right.png 140 161 160 191 >> peasant_shoot_sprites_right.inc


kerrek_hit_sprites_left.inc:	$(SPRITE_DIR)/kerrek_hit_sprites_left.png $(SPRITE_DIR)/kerrek_body_sprites.png
	$(HGR_SPRITE) -l kerrek_hit_left0_sprite $(SPRITE_DIR)/kerrek_hit_sprites_left.png  14  60  41 108 > kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left0_mask   $(SPRITE_DIR)/kerrek_hit_sprites_left.png  14 113  41 161 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left1_sprite $(SPRITE_DIR)/kerrek_hit_sprites_left.png  56  60 104 108 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left1_mask   $(SPRITE_DIR)/kerrek_hit_sprites_left.png  56 113 104 161 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left2_sprite $(SPRITE_DIR)/kerrek_hit_sprites_left.png 112  63 146 108 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left2_mask   $(SPRITE_DIR)/kerrek_hit_sprites_left.png 112 116 146 161 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left3_sprite $(SPRITE_DIR)/kerrek_hit_sprites_left.png 154  63 195 108 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left3_mask   $(SPRITE_DIR)/kerrek_hit_sprites_left.png 154 116 195 161 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left4_sprite $(SPRITE_DIR)/kerrek_hit_sprites_left.png 210  35 258  58 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left4_mask   $(SPRITE_DIR)/kerrek_hit_sprites_left.png 210  63 258  86 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left5_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  84  28 132  42 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left5_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  84  49 132  63 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left6_sprite $(SPRITE_DIR)/kerrek_hit_sprites_left.png 210 136 251 159 >> kerrek_hit_sprites_left.inc
	$(HGR_SPRITE) -l kerrek_hit_left6_mask   $(SPRITE_DIR)/kerrek_hit_sprites_left.png 210 162 251 185 >> kerrek_hit_sprites_left.inc

kerrek_hit_sprites_right.inc:	$(SPRITE_DIR)/kerrek_hit_sprites_right.png $(SPRITE_DIR)/kerrek_body_sprites.png
	$(HGR_SPRITE) -l kerrek_hit_right0_sprite $(SPRITE_DIR)/kerrek_hit_sprites_right.png  14  60  41 108 > kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right0_mask   $(SPRITE_DIR)/kerrek_hit_sprites_right.png  14 113  41 161 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right1_sprite $(SPRITE_DIR)/kerrek_hit_sprites_right.png  56  60 104 108 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right1_mask   $(SPRITE_DIR)/kerrek_hit_sprites_right.png  56 113 104 161 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right2_sprite $(SPRITE_DIR)/kerrek_hit_sprites_right.png 112  63 146 108 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right2_mask   $(SPRITE_DIR)/kerrek_hit_sprites_right.png 112 116 146 161 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right3_sprite $(SPRITE_DIR)/kerrek_hit_sprites_right.png 154  63 195 108 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right3_mask   $(SPRITE_DIR)/kerrek_hit_sprites_right.png 154 116 195 161 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right4_sprite $(SPRITE_DIR)/kerrek_hit_sprites_right.png 210  35 258  58 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right4_mask   $(SPRITE_DIR)/kerrek_hit_sprites_right.png 210  63 258  86 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right5_sprite $(SPRITE_DIR)/kerrek_body_sprites.png  14  28  62  42 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right5_mask   $(SPRITE_DIR)/kerrek_body_sprites.png  14  49  62  63 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right6_sprite $(SPRITE_DIR)/kerrek_hit_sprites_right.png 210 136 251 159 >> kerrek_hit_sprites_right.inc
	$(HGR_SPRITE) -l kerrek_hit_right6_mask   $(SPRITE_DIR)/kerrek_hit_sprites_right.png 210 162 251 185 >> kerrek_hit_sprites_right.inc









clean:
	rm -f *~ kerrek_sprites.inc kerrek_body_sprites.inc \
		peasant_belt.inc peasant_belt_robe.inc \
		kerrek_hit_sprites.inc peasant_shoot_sprites.inc \
		peasant_shoot_sprites_left.inc peasant_shoot_sprites_right.inc \
		kerrek_smash_sprites.inc kerrek_walk_sprites.inc \
		kerrek_walk_sprites_right.inc kerrek_walk_sprites_left.inc \
		kerrek_hit_sprites_right.inc kerrek_hit_sprites_left.inc

