5 HOME
10 PRINT " PARALLAX -- A 116 BYTE APPLE II INTRO"
12 PRINT "          FOR  LOVEBYTE 2023"
15 PRINT "           BY DEATER / DSR"
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN PAR_TINY'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN PAR_TINY"
