include ../../../../Makefile.inc

ZX02 = ~/research/6502_compression/zx02.git/build/zx02
PNG_TO_HGR = ../../../../utils/hgr-utils/png2hgr
PNG2GR = ../../../../utils/gr-utils/png2gr

all:	cho_graphics.inc

cho_graphics.inc:	\
	captured_bg.gr.zx02 \
	captured_cage_bg.gr.zx02 \
	empty.gr.zx02 \
	cho_overlay006.gr.zx02 cho_overlay007.gr.zx02 \
	cho_overlay008.gr.zx02 cho_overlay009.gr.zx02 \
	cho_overlay010.gr.zx02 cho_overlay011.gr.zx02 \
	cho_overlay012.gr.zx02 cho_overlay013.gr.zx02 \
	cho_overlay014.gr.zx02 cho_overlay015.gr.zx02 \
	cho_overlay016.gr.zx02 cho_overlay017.gr.zx02 \
	cho_overlay018.gr.zx02 cho_overlay019.gr.zx02 \
	cho_overlay020.gr.zx02 cho_overlay021.gr.zx02 \
	cho_overlay022.gr.zx02 cho_overlay023.gr.zx02 \
	cho_overlay024.gr.zx02 cho_overlay025.gr.zx02 \
	cho_overlay026.gr.zx02 cho_overlay027.gr.zx02 \
	cho_overlay028.gr.zx02 cho_overlay029.gr.zx02 \
	cho_overlay030.gr.zx02 cho_overlay031.gr.zx02 \
	cho_overlay032.gr.zx02 cho_overlay033.gr.zx02 \
	cho_overlay034.gr.zx02 cho_overlay035.gr.zx02 \
	cho_overlay036.gr.zx02 cho_overlay037.gr.zx02 \
	cho_overlay038.gr.zx02 cho_overlay039.gr.zx02 \
	cho_overlay040.gr.zx02 cho_overlay041.gr.zx02 \
	cho_overlay042.gr.zx02 cho_overlay043.gr.zx02 \
	cho_overlay044.gr.zx02 cho_overlay045.gr.zx02 \
	cho_overlay046.gr.zx02 cho_overlay047.gr.zx02 \
	cho_overlay048.gr.zx02 cho_overlay049.gr.zx02 \
	cho_overlay050.gr.zx02 cho_overlay051.gr.zx02 \
	cho_overlay052.gr.zx02 cho_overlay053.gr.zx02 \
	cho_overlay054.gr.zx02 cho_overlay055.gr.zx02 \
	cho_overlay056.gr.zx02 cho_overlay057.gr.zx02 \
	cho_overlay058.gr.zx02 cho_overlay059.gr.zx02 \
	cho_overlay060.gr.zx02 cho_overlay061.gr.zx02 \
	cho_overlay062.gr.zx02 cho_overlay063.gr.zx02 \
	cho_overlay064.gr.zx02 cho_overlay065.gr.zx02 \
	cho_overlay066.gr.zx02 cho_overlay067.gr.zx02 \
	cho_overlay068.gr.zx02 cho_overlay069.gr.zx02 \
	cho_overlay070.gr.zx02 cho_overlay071.gr.zx02 \
	cho_overlay072.gr.zx02 cho_overlay073.gr.zx02 \
	cho_overlay074.gr.zx02 cho_overlay075.gr.zx02 \
	cho_overlay076.gr.zx02 cho_overlay077.gr.zx02 \
	cho_overlay078.gr.zx02 cho_overlay079.gr.zx02 \
	cho_overlay080.gr.zx02 cho_overlay081.gr.zx02 \
	cho_overlay082.gr.zx02 cho_overlay083.gr.zx02 \
	cho_overlay084.gr.zx02 cho_overlay085.gr.zx02 \
	cho_overlay086.gr.zx02 cho_overlay087.gr.zx02 \
	cho_overlay088.gr.zx02 cho_overlay089.gr.zx02 \
	cho_overlay090.gr.zx02 cho_overlay091.gr.zx02 \
	cho_overlay092.gr.zx02 cho_overlay093.gr.zx02 \
	cho_overlay094.gr.zx02 cho_overlay095.gr.zx02 \
	cho_overlay096.gr.zx02 cho_overlay097.gr.zx02 \
	cho_overlay098.gr.zx02 cho_overlay099.gr.zx02 \
	cho_overlay100.gr.zx02 cho_overlay101.gr.zx02 \
	cho_overlay102.gr.zx02 cho_overlay103.gr.zx02 \
	cho_overlay104.gr.zx02 cho_overlay105.gr.zx02 \
	cho_overlay106.gr.zx02 cho_overlay107.gr.zx02 \
	cho_overlay108.gr.zx02 cho_overlay109.gr.zx02 \
	cho_overlay110.gr.zx02 cho_overlay111.gr.zx02 \
	cho_overlay112.gr.zx02 cho_overlay113.gr.zx02 \
	cho_overlay114.gr.zx02 cho_overlay115.gr.zx02 \
	cho_overlay116.gr.zx02 cho_overlay117.gr.zx02 \
	cho_overlay118.gr.zx02 cho_overlay119.gr.zx02 \
	cho_overlay120.gr.zx02 cho_overlay121.gr.zx02 \
	cho_overlay122.gr.zx02 cho_overlay123.gr.zx02 \
	cho_overlay124.gr.zx02 cho_overlay125.gr.zx02 \
	cho_overlay126.gr.zx02 cho_overlay127.gr.zx02 \
	cho_overlay128.gr.zx02 cho_overlay129.gr.zx02 \
	cho_overlay130.gr.zx02 cho_overlay131.gr.zx02 \
	cho_overlay132.gr.zx02 cho_overlay133.gr.zx02 \
	cho_overlay134.gr.zx02 cho_overlay135.gr.zx02 \
	cho_overlay136.gr.zx02 cho_overlay137.gr.zx02 \
	cho_overlay138.gr.zx02 cho_overlay139.gr.zx02 \
	cho_overlay140.gr.zx02 cho_overlay141.gr.zx02 \
	cho_overlay142.gr.zx02 cho_overlay143.gr.zx02 \
	cho_overlay144.gr.zx02 cho_overlay145.gr.zx02
	echo "captured_bg: .incbin \"captured_bg.gr.zx02\"" > cho_graphics.inc
	echo "captured_cage_bg: .incbin \"captured_cage_bg.gr.zx02\"" >> cho_graphics.inc
	echo "empty: .incbin \"empty.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay006: .incbin \"cho_overlay006.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay007: .incbin \"cho_overlay007.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay008: .incbin \"cho_overlay008.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay009: .incbin \"cho_overlay009.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay010: .incbin \"cho_overlay010.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay011: .incbin \"cho_overlay011.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay012: .incbin \"cho_overlay012.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay013: .incbin \"cho_overlay013.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay014: .incbin \"cho_overlay014.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay015: .incbin \"cho_overlay015.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay016: .incbin \"cho_overlay016.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay017: .incbin \"cho_overlay017.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay018: .incbin \"cho_overlay018.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay019: .incbin \"cho_overlay019.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay020: .incbin \"cho_overlay020.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay021: .incbin \"cho_overlay021.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay022: .incbin \"cho_overlay022.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay023: .incbin \"cho_overlay023.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay024: .incbin \"cho_overlay024.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay025: .incbin \"cho_overlay025.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay026: .incbin \"cho_overlay026.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay027: .incbin \"cho_overlay027.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay028: .incbin \"cho_overlay028.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay029: .incbin \"cho_overlay029.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay030: .incbin \"cho_overlay030.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay031: .incbin \"cho_overlay031.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay032: .incbin \"cho_overlay032.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay033: .incbin \"cho_overlay033.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay034: .incbin \"cho_overlay034.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay035: .incbin \"cho_overlay035.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay036: .incbin \"cho_overlay036.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay037: .incbin \"cho_overlay037.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay038: .incbin \"cho_overlay038.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay039: .incbin \"cho_overlay039.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay040: .incbin \"cho_overlay040.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay041: .incbin \"cho_overlay041.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay042: .incbin \"cho_overlay042.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay043: .incbin \"cho_overlay043.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay044: .incbin \"cho_overlay044.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay045: .incbin \"cho_overlay045.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay046: .incbin \"cho_overlay046.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay047: .incbin \"cho_overlay047.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay048: .incbin \"cho_overlay048.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay049: .incbin \"cho_overlay049.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay050: .incbin \"cho_overlay050.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay051: .incbin \"cho_overlay051.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay052: .incbin \"cho_overlay052.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay053: .incbin \"cho_overlay053.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay054: .incbin \"cho_overlay054.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay055: .incbin \"cho_overlay055.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay056: .incbin \"cho_overlay056.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay057: .incbin \"cho_overlay057.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay058: .incbin \"cho_overlay058.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay059: .incbin \"cho_overlay059.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay060: .incbin \"cho_overlay060.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay061: .incbin \"cho_overlay061.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay062: .incbin \"cho_overlay062.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay063: .incbin \"cho_overlay063.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay064: .incbin \"cho_overlay064.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay065: .incbin \"cho_overlay065.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay066: .incbin \"cho_overlay066.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay067: .incbin \"cho_overlay067.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay068: .incbin \"cho_overlay068.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay069: .incbin \"cho_overlay069.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay070: .incbin \"cho_overlay070.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay071: .incbin \"cho_overlay071.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay072: .incbin \"cho_overlay072.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay073: .incbin \"cho_overlay073.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay074: .incbin \"cho_overlay074.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay075: .incbin \"cho_overlay075.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay076: .incbin \"cho_overlay076.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay077: .incbin \"cho_overlay077.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay078: .incbin \"cho_overlay078.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay079: .incbin \"cho_overlay079.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay080: .incbin \"cho_overlay080.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay081: .incbin \"cho_overlay081.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay082: .incbin \"cho_overlay082.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay083: .incbin \"cho_overlay083.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay084: .incbin \"cho_overlay084.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay085: .incbin \"cho_overlay085.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay086: .incbin \"cho_overlay086.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay087: .incbin \"cho_overlay087.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay088: .incbin \"cho_overlay088.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay089: .incbin \"cho_overlay089.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay090: .incbin \"cho_overlay090.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay091: .incbin \"cho_overlay091.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay092: .incbin \"cho_overlay092.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay093: .incbin \"cho_overlay093.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay094: .incbin \"cho_overlay094.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay095: .incbin \"cho_overlay095.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay096: .incbin \"cho_overlay096.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay097: .incbin \"cho_overlay097.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay098: .incbin \"cho_overlay098.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay099: .incbin \"cho_overlay099.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay100: .incbin \"cho_overlay100.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay101: .incbin \"cho_overlay101.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay102: .incbin \"cho_overlay102.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay103: .incbin \"cho_overlay103.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay104: .incbin \"cho_overlay104.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay105: .incbin \"cho_overlay105.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay106: .incbin \"cho_overlay106.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay107: .incbin \"cho_overlay107.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay108: .incbin \"cho_overlay108.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay109: .incbin \"cho_overlay109.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay110: .incbin \"cho_overlay110.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay111: .incbin \"cho_overlay111.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay112: .incbin \"cho_overlay112.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay113: .incbin \"cho_overlay113.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay114: .incbin \"cho_overlay114.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay115: .incbin \"cho_overlay115.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay116: .incbin \"cho_overlay116.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay117: .incbin \"cho_overlay117.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay118: .incbin \"cho_overlay118.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay119: .incbin \"cho_overlay119.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay120: .incbin \"cho_overlay120.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay121: .incbin \"cho_overlay121.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay122: .incbin \"cho_overlay122.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay123: .incbin \"cho_overlay123.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay124: .incbin \"cho_overlay124.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay125: .incbin \"cho_overlay125.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay126: .incbin \"cho_overlay126.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay127: .incbin \"cho_overlay127.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay128: .incbin \"cho_overlay128.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay129: .incbin \"cho_overlay129.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay130: .incbin \"cho_overlay130.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay131: .incbin \"cho_overlay131.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay132: .incbin \"cho_overlay132.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay133: .incbin \"cho_overlay133.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay134: .incbin \"cho_overlay134.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay135: .incbin \"cho_overlay135.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay136: .incbin \"cho_overlay136.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay137: .incbin \"cho_overlay137.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay138: .incbin \"cho_overlay138.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay139: .incbin \"cho_overlay139.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay140: .incbin \"cho_overlay140.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay141: .incbin \"cho_overlay141.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay142: .incbin \"cho_overlay142.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay143: .incbin \"cho_overlay143.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay144: .incbin \"cho_overlay144.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay145: .incbin \"cho_overlay145.gr.zx02\"" >> cho_graphics.inc

####

%.gr:	%.png
	$(PNG2GR) $< $@

%.gr.zx02:	%.gr
	$(ZX02) -f $< $@

####

%.hgr: %.png
	$(PNG_TO_HGR) $< > $@

%.hgr.zx02: %.hgr
	$(ZX02) -f $< $@

####

clean:
	rm -f *~ *.o *.lst  *.zx02 *.hgr cho_graphics.inc
