include ../../../../Makefile.inc

ZX02 = ~/research/6502_compression/zx02.git/build/zx02
PNG_TO_HGR = ../../../../utils/hgr-utils/png2hgr
PNG2GR = ../../../../utils/gr-utils/png2gr

all:	cho_graphics.inc

cho_graphics.inc:	\
	captured_bg.gr.zx02 \
	captured_cage_bg.gr.zx02 \
	empty.gr.zx02 \
	cho_overlay006.gr.zx02 cho_overlay007.gr.zx02 \
	cho_overlay008.gr.zx02 cho_overlay009.gr.zx02 \
	cho_overlay010.gr.zx02 cho_overlay011.gr.zx02 \
	cho_overlay012.gr.zx02 cho_overlay013.gr.zx02 \
	cho_overlay014.gr.zx02 cho_overlay015.gr.zx02 \
	cho_overlay016.gr.zx02 cho_overlay017.gr.zx02 \
	cho_overlay018.gr.zx02 cho_overlay019.gr.zx02 \
	cho_overlay020.gr.zx02 cho_overlay021.gr.zx02 \
	cho_overlay022.gr.zx02 cho_overlay023.gr.zx02 \
	cho_overlay024.gr.zx02 cho_overlay025.gr.zx02 \
	cho_overlay026.gr.zx02 cho_overlay027.gr.zx02 \
	cho_overlay028.gr.zx02 cho_overlay029.gr.zx02 \
	cho_overlay030.gr.zx02 cho_overlay031.gr.zx02 \
	cho_overlay032.gr.zx02 cho_overlay033.gr.zx02 \
	cho_overlay034.gr.zx02 cho_overlay035.gr.zx02 \
	cho_overlay036.gr.zx02 cho_overlay037.gr.zx02 \
	cho_overlay038.gr.zx02 cho_overlay039.gr.zx02 \
	cho_overlay040.gr.zx02 cho_overlay041.gr.zx02 \
	cho_overlay042.gr.zx02 cho_overlay043.gr.zx02 \
	cho_overlay044.gr.zx02 cho_overlay045.gr.zx02 \
	cho_overlay046.gr.zx02 cho_overlay047.gr.zx02 \
	cho_overlay048.gr.zx02 cho_overlay049.gr.zx02 \
	cho_overlay050.gr.zx02 cho_overlay051.gr.zx02 \
	cho_overlay052.gr.zx02 cho_overlay053.gr.zx02 \
	cho_overlay054.gr.zx02 cho_overlay055.gr.zx02 \
	cho_overlay056.gr.zx02 cho_overlay057.gr.zx02 \
	cho_overlay058.gr.zx02 cho_overlay059.gr.zx02 \
	cho_overlay060.gr.zx02 cho_overlay061.gr.zx02 \
	cho_overlay062.gr.zx02 cho_overlay063.gr.zx02 \
	cho_overlay064.gr.zx02 cho_overlay065.gr.zx02 \
	cho_overlay066.gr.zx02 cho_overlay067.gr.zx02 \
	cho_overlay068.gr.zx02 cho_overlay069.gr.zx02 \
	cho_overlay070.gr.zx02
	echo "captured_bg: .incbin \"captured_bg.gr.zx02\"" > cho_graphics.inc
	echo "captured_cage_bg: .incbin \"captured_cage_bg.gr.zx02\"" >> cho_graphics.inc
	echo "empty: .incbin \"empty.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay006: .incbin \"cho_overlay006.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay007: .incbin \"cho_overlay007.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay008: .incbin \"cho_overlay008.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay009: .incbin \"cho_overlay009.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay010: .incbin \"cho_overlay010.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay011: .incbin \"cho_overlay011.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay012: .incbin \"cho_overlay012.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay013: .incbin \"cho_overlay013.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay014: .incbin \"cho_overlay014.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay015: .incbin \"cho_overlay015.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay016: .incbin \"cho_overlay016.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay017: .incbin \"cho_overlay017.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay018: .incbin \"cho_overlay018.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay019: .incbin \"cho_overlay019.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay020: .incbin \"cho_overlay020.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay021: .incbin \"cho_overlay021.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay022: .incbin \"cho_overlay022.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay023: .incbin \"cho_overlay023.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay024: .incbin \"cho_overlay024.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay025: .incbin \"cho_overlay025.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay026: .incbin \"cho_overlay026.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay027: .incbin \"cho_overlay027.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay028: .incbin \"cho_overlay028.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay029: .incbin \"cho_overlay029.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay030: .incbin \"cho_overlay030.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay031: .incbin \"cho_overlay031.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay032: .incbin \"cho_overlay032.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay033: .incbin \"cho_overlay033.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay034: .incbin \"cho_overlay034.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay035: .incbin \"cho_overlay035.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay036: .incbin \"cho_overlay036.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay037: .incbin \"cho_overlay037.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay038: .incbin \"cho_overlay038.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay039: .incbin \"cho_overlay039.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay040: .incbin \"cho_overlay040.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay041: .incbin \"cho_overlay041.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay042: .incbin \"cho_overlay042.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay043: .incbin \"cho_overlay043.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay044: .incbin \"cho_overlay044.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay045: .incbin \"cho_overlay045.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay046: .incbin \"cho_overlay046.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay047: .incbin \"cho_overlay047.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay048: .incbin \"cho_overlay048.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay049: .incbin \"cho_overlay049.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay050: .incbin \"cho_overlay050.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay051: .incbin \"cho_overlay051.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay052: .incbin \"cho_overlay052.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay053: .incbin \"cho_overlay053.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay054: .incbin \"cho_overlay054.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay055: .incbin \"cho_overlay055.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay056: .incbin \"cho_overlay056.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay057: .incbin \"cho_overlay057.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay058: .incbin \"cho_overlay058.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay059: .incbin \"cho_overlay059.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay060: .incbin \"cho_overlay060.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay061: .incbin \"cho_overlay061.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay062: .incbin \"cho_overlay062.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay063: .incbin \"cho_overlay063.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay064: .incbin \"cho_overlay064.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay065: .incbin \"cho_overlay065.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay066: .incbin \"cho_overlay066.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay067: .incbin \"cho_overlay067.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay068: .incbin \"cho_overlay068.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay069: .incbin \"cho_overlay069.gr.zx02\"" >> cho_graphics.inc
	echo "cho_overlay070: .incbin \"cho_overlay070.gr.zx02\"" >> cho_graphics.inc




####

%.gr:	%.png
	$(PNG2GR) $< $@

%.gr.zx02:	%.gr
	$(ZX02) -f $< $@

####

%.hgr: %.png
	$(PNG_TO_HGR) $< > $@

%.hgr.zx02: %.hgr
	$(ZX02) -f $< $@

####

clean:
	rm -f *~ *.o *.lst  *.zx02 *.hgr cho_graphics.inc
