5 HOME
10 PRINT CHR$(4);"CATALOG"
20 PRINT:PRINT "FOR THE BRIEF HI-RES MYST DEMO"
30 PRINT "TYPE: BRUN VGI-MYST"
40 PRINT:PRINT "FOR THE DOOM DEMO"
50 PRINT "TYPE: BRUN VGI-DOOM"
70 PRINT:PRINT "NOTE: THERE IS ALSO A FULL-FEATURED"
80 PRINT "LORES VERSION AVAILABLE FOR DOWNLOAD"
90 PRINT "IF YOU WANT TO PLAY ON APPLE II"
