1 FOR X=0TO116:POKE 768+X,(PEEK(2115+X)-64)*16+(PEEK(X+2232))-64:NEXT X:CALL768
9 "BMOJOJOHCNOHOINOLHFHOFOAHFOHOIFOLHFHOFOFOFOFOFOKANOM@NOJOFHHOI@NOCJ@NOHOJ@NOHOJO@BODOHOB@@@JJOCJJOBOMIBNOJOJOJOBEOD@@@HCF@DAJHEBE@HECI@JEAF@HJEBEBHECI@JECFBFDFEFFFG@MFH@BFIE@I@E@@BFAHI@EBEBI@ECECEHJFIEIEHIGIBJEC@CEAI@@M@LFF@DAEB@GDLCC"






