;=============================
; common stuff

VERB_GIVE	= 0
VERB_OPEN	= 1
VERB_CLOSE	= 2
VERB_PICK_UP	= 3
VERB_LOOK_AT	= 4
VERB_TALK_TO	= 5
VERB_USE	= 6
VERB_PUSH	= 7
VERB_PULL	= 8 
VERB_WALK	= 9



;===============================================
; level data structure definitions
;===============================================

LOCATION_BACKGROUND=0			; background

;================================
; Loader definitions

LOAD_TITLE	= 0
LOAD_MONKEY	= 1

;================================
; Level definitions

; Title

; Monkey

MONKEY_LOOKOUT		=	0
MONKEY_POSTER		=	1
MONKEY_DOCK		=	2
MONKEY_BAR		=	3
