;=============================
; common stuff

;===============================================
; level data structure definitions
;===============================================

LOCATION_BACKGROUND=0			; background

;================================
; Loader definitions

LOAD_TITLE	= 0
LOAD_MONKEY	= 1

;================================
; Level definitions

; Title

; Monkey

MONKEY_LOOKOUT		=	0
