5 HOME
10 PRINT "LOADING MONKEY V0.06"
20 PRINT:PRINT
40 PRINT "CONTROLS: "
42 PRINT "     MOVE CURSOR    : ARROWS OR WASD"
44 PRINT "     FORWARD/ACTION : ENTER"
46 PRINT "     JOYSTICK       : J"
48 PRINT
50 PRINT "     G=GIVE   P=PICK UP  U=USE"
52 PRINT "     O=OPEN   L=LOOK AT  H=PUSH"
54 PRINT "     C=CLOSE  T=TALK TO  N=PULL"
56 PRINT "              M=WALK TO"
60 PRINT:PRINT
70 PRINT "WITH APOLOGIES TO LUCAS ARTS"
80 PRINT "APPLE II PORT: VINCE WEAVER"
90 PRINT "DISK CODE    : QKUMBA"
94 PRINT "LZSA CODE    : EMMANUEL MARTY"
95 PRINT "MUSIC        : EPYTEOR/SUTEKH/STARKOS"
96 PRINT
100 PRINT "       ______"
110 PRINT "     A \/\/\/ SOFTWARE PRODUCTION"
120 PRINT CHR$(4);"BRUN LOADER"
