include ../../../Makefile.inc

ZX02 = ~/research/6502_compression/zx02.git/build/zx02
PNG_TO_HGR =	../../../utils/hgr-utils/png2hgr

all:	bbl.hgr.zx02 bbl2.hgr.zx02 \
	grl.hgr.zx02 1bg.hgr.zx02 fup.hgr.zx02 witch.hgr.zx02 \
	mope_a2.hgr.zx02 ob.hgr.zx02 bg2.hgr.zx02 \
	oopb.hgr.zx02 ooc5.hgr.zx02 fze.hgr.zx02 \
	fjj.hgr.zx02 dadz.hgr.zx02 lh.hgr.zx02 \
	fcd.hgr.zx02 facd.hgr.zx02 fif.hgr.zx02 \
	fif2.hgr.zx02 oo4.hgr.zx02 oo2.hgr.zx02 \
	fwq.hgr.zx02 piz.hgr.zx02 cit.hgr.zx02 \
	cel.hgr.zx02 mug.hgr.zx02 quad.hgr.zx02 \
	gb.hgr.zx02 jis.hgr.zx02 ojm.hgr.zx02 \
	nda.hgr.zx02 fri.hgr.zx02 win.hgr.zx02 \
	bar.hgr.zx02 ani.hgr.zx02 gld.hgr.zx02 \
	rnu.hgr.zx02 ooh.hgr.zx02 two.hgr.zx02 \
	rug.hgr.zx02 ndz.hgr.zx02 crd.hgr.zx02 \
	gfa.hgr.zx02 sxy.hgr.zx02

####

bbl.hgr.zx02:	bbl.hgr
	$(ZX02) bbl.hgr bbl.hgr.zx02

bbl.hgr:	bbl.png
	$(PNG_TO_HGR) bbl.png > bbl.hgr

####

bbl2.hgr.zx02:	bbl2.hgr
	$(ZX02) bbl2.hgr bbl2.hgr.zx02

bbl2.hgr:	bbl2.png
	$(PNG_TO_HGR) bbl2.png > bbl2.hgr

####

1bg.hgr.zx02:	1bg.hgr
	$(ZX02) 1bg.hgr 1bg.hgr.zx02

1bg.hgr:	1bg.png
	$(PNG_TO_HGR) 1bg.png > 1bg.hgr


####

fup.hgr.zx02:	fup.hgr
	$(ZX02) fup.hgr fup.hgr.zx02

fup.hgr:	fup.png
	$(PNG_TO_HGR) fup.png > fup.hgr

####

witch.hgr.zx02:	witch.hgr
	$(ZX02) witch.hgr witch.hgr.zx02

witch.hgr:	witch.png
	$(PNG_TO_HGR) witch.png > witch.hgr

####

mope_a2.hgr.zx02:	mope_a2.hgr
	$(ZX02) mope_a2.hgr mope_a2.hgr.zx02

mope_a2.hgr:	mope_a2.png
	$(PNG_TO_HGR) mope_a2.png > mope_a2.hgr

####

ob.hgr.zx02:	ob.hgr
	$(ZX02) ob.hgr ob.hgr.zx02

ob.hgr:	ob.png
	$(PNG_TO_HGR) ob.png > ob.hgr

####

oopb.hgr.zx02:	oopb.hgr
	$(ZX02) oopb.hgr oopb.hgr.zx02

oopb.hgr:	oopb.png
	$(PNG_TO_HGR) oopb.png > oopb.hgr

####

ooc5.hgr.zx02:	ooc5.hgr
	$(ZX02) ooc5.hgr ooc5.hgr.zx02

ooc5.hgr:	ooc5.png
	$(PNG_TO_HGR) ooc5.png > ooc5.hgr


####

bg2.hgr.zx02:	bg2.hgr
	$(ZX02) bg2.hgr bg2.hgr.zx02

bg2.hgr:	bg2.png
	$(PNG_TO_HGR) bg2.png > bg2.hgr

####

fze.hgr.zx02:	fze.hgr
	$(ZX02) fze.hgr fze.hgr.zx02

fze.hgr:	fze.png
	$(PNG_TO_HGR) fze.png > fze.hgr

####

fjj.hgr.zx02:	fjj.hgr
	$(ZX02) fjj.hgr fjj.hgr.zx02

fjj.hgr:	fjj.png
	$(PNG_TO_HGR) fjj.png > fjj.hgr

####

dadz.hgr.zx02:	dadz.hgr
	$(ZX02) dadz.hgr dadz.hgr.zx02

dadz.hgr:	dadz.png
	$(PNG_TO_HGR) dadz.png > dadz.hgr

####

lh.hgr.zx02:	lh.hgr
	$(ZX02) lh.hgr lh.hgr.zx02

lh.hgr:	lh.png
	$(PNG_TO_HGR) lh.png > lh.hgr

####

fcd.hgr.zx02:	fcd.hgr
	$(ZX02) fcd.hgr fcd.hgr.zx02

fcd.hgr:	fcd.png
	$(PNG_TO_HGR) fcd.png > fcd.hgr

####

facd.hgr.zx02:	facd.hgr
	$(ZX02) facd.hgr facd.hgr.zx02

facd.hgr:	facd.png
	$(PNG_TO_HGR) facd.png > facd.hgr

####

fif.hgr.zx02:	fif.hgr
	$(ZX02) fif.hgr fif.hgr.zx02

fif.hgr:	fif.png
	$(PNG_TO_HGR) fif.png > fif.hgr

####

fif2.hgr.zx02:	fif2.hgr
	$(ZX02) fif2.hgr fif2.hgr.zx02

fif2.hgr:	fif2.png
	$(PNG_TO_HGR) fif2.png > fif2.hgr


####

oo4.hgr.zx02:	oo4.hgr
	$(ZX02) oo4.hgr oo4.hgr.zx02

oo4.hgr:	oo4.png
	$(PNG_TO_HGR) oo4.png > oo4.hgr

####

oo2.hgr.zx02:	oo2.hgr
	$(ZX02) oo2.hgr oo2.hgr.zx02

oo2.hgr:	oo2.png
	$(PNG_TO_HGR) oo2.png > oo2.hgr

####

fwq.hgr.zx02:	fwq.hgr
	$(ZX02) fwq.hgr fwq.hgr.zx02

fwq.hgr:	fwq.png
	$(PNG_TO_HGR) fwq.png > fwq.hgr

####

piz.hgr.zx02:	piz.hgr
	$(ZX02) piz.hgr piz.hgr.zx02

piz.hgr:	piz.png
	$(PNG_TO_HGR) piz.png > piz.hgr

####

cit.hgr.zx02:	cit.hgr
	$(ZX02) cit.hgr cit.hgr.zx02

cit.hgr:	cit.png
	$(PNG_TO_HGR) cit.png > cit.hgr

####

cel.hgr.zx02:	cel.hgr
	$(ZX02) cel.hgr cel.hgr.zx02

cel.hgr:	cel.png
	$(PNG_TO_HGR) cel.png > cel.hgr

####

mug.hgr.zx02:	mug.hgr
	$(ZX02) mug.hgr mug.hgr.zx02

mug.hgr:	mug.png
	$(PNG_TO_HGR) mug.png > mug.hgr

####

quad.hgr.zx02:	quad.hgr
	$(ZX02) quad.hgr quad.hgr.zx02

quad.hgr:	quad.png
	$(PNG_TO_HGR) quad.png > quad.hgr


####

gb.hgr.zx02:	gb.hgr
	$(ZX02) gb.hgr gb.hgr.zx02

gb.hgr:	gb.png
	$(PNG_TO_HGR) gb.png > gb.hgr

####

jis.hgr.zx02:	jis.hgr
	$(ZX02) jis.hgr jis.hgr.zx02

jis.hgr:	jis.png
	$(PNG_TO_HGR) jis.png > jis.hgr

####

ojm.hgr.zx02:	ojm.hgr
	$(ZX02) ojm.hgr ojm.hgr.zx02

ojm.hgr:	ojm.png
	$(PNG_TO_HGR) ojm.png > ojm.hgr

####

nda.hgr.zx02:	nda.hgr
	$(ZX02) nda.hgr nda.hgr.zx02

nda.hgr:	nda.png
	$(PNG_TO_HGR) nda.png > nda.hgr

####

fri.hgr.zx02:	fri.hgr
	$(ZX02) fri.hgr fri.hgr.zx02

fri.hgr:	fri.png
	$(PNG_TO_HGR) fri.png > fri.hgr

####

win.hgr.zx02:	win.hgr
	$(ZX02) win.hgr win.hgr.zx02

win.hgr:	win.png
	$(PNG_TO_HGR) win.png > win.hgr

####

bar.hgr.zx02:	bar.hgr
	$(ZX02) bar.hgr bar.hgr.zx02

bar.hgr:	bar.png
	$(PNG_TO_HGR) bar.png > bar.hgr

####

ani.hgr.zx02:	ani.hgr
	$(ZX02) ani.hgr ani.hgr.zx02

ani.hgr:	ani.png
	$(PNG_TO_HGR) ani.png > ani.hgr

####

gld.hgr.zx02:	gld.hgr
	$(ZX02) gld.hgr gld.hgr.zx02

gld.hgr:	gld.png
	$(PNG_TO_HGR) gld.png > gld.hgr

####

rnu.hgr.zx02:	rnu.hgr
	$(ZX02) rnu.hgr rnu.hgr.zx02

rnu.hgr:	rnu.png
	$(PNG_TO_HGR) rnu.png > rnu.hgr

####

ooh.hgr.zx02:	ooh.hgr
	$(ZX02) ooh.hgr ooh.hgr.zx02

ooh.hgr:	ooh.png
	$(PNG_TO_HGR) ooh.png > ooh.hgr

####

two.hgr.zx02:	two.hgr
	$(ZX02) two.hgr two.hgr.zx02

two.hgr:	two.png
	$(PNG_TO_HGR) two.png > two.hgr


####

rug.hgr.zx02:	rug.hgr
	$(ZX02) rug.hgr rug.hgr.zx02

rug.hgr:	rug.png
	$(PNG_TO_HGR) rug.png > rug.hgr

####

ndz.hgr.zx02:	ndz.hgr
	$(ZX02) ndz.hgr ndz.hgr.zx02

ndz.hgr:	ndz.png
	$(PNG_TO_HGR) ndz.png > ndz.hgr

####

crd.hgr.zx02:	crd.hgr
	$(ZX02) crd.hgr crd.hgr.zx02

crd.hgr:	crd.png
	$(PNG_TO_HGR) crd.png > crd.hgr


####

gfa.hgr.zx02:	gfa.hgr
	$(ZX02) gfa.hgr gfa.hgr.zx02

gfa.hgr:	gfa.png
	$(PNG_TO_HGR) gfa.png > gfa.hgr

####

sxy.hgr.zx02:	sxy.hgr
	$(ZX02) sxy.hgr sxy.hgr.zx02

sxy.hgr:	sxy.png
	$(PNG_TO_HGR) sxy.png > sxy.hgr













###

grl.hgr.zx02:	grl.hgr
	$(ZX02) grl.hgr grl.hgr.zx02

###


clean:
		rm -f *~ *.o *.lst *.zx02

