5 HOME
10 PRINT "   ORB -- A 256 BYTE APPLE II INTRO"
15 PRINT "           BY DEATER / DSR"
18 PRINT
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN COMBO'"
30 GET A$
35 PRINT
40 PRINT "]BRUN COMBO"
50 PRINT CHR$(4)"BRUN COMBO"
