0REM& ~ ~ GYG~ 1FG\ U^Ge!/BP\!7Zf~!U[Ue"FM:F"JS/A%GU).%AI,;#RTO~#OUCM"SU8; +F]k"GP\e&_j\p [ifq"itip&^wft ^gfq"_f\e
1HGR:?" o/~ NEVER GONNA GIVE YOU UP o/~":DEFFNP(X)=PEEK(2054+I*5+X)
2FORI=0TO22:IFI=22THENI=15
3HCOLOR=FNP(0)-32:FORY=FNP(3)TOFNP(4):HPLOTFNP(1),YTOFNP(2),Y:NEXTY,I
