; zx02 code
offset  = $10
offseth = $11
ZX0_src = $12
ZX0_dst = $14
ZX0_srch= $15
bitr    = $16
pntr    = $17
pntrh   = $18


;TEMP0	= $10
;TEMP1	= $11
;TEMP2	= $12
;TEMP3	= $13
;TEMP4	= $14
;TEMP5	= $15


HGR_BITS = $1C

CH	= $24
CV	= $25
GBASL	= $26
GBASH	= $27
CURSOR_X	= $62
CURSOR_Y	= $63
HGR_COLOR	= $E4

DRAW_PAGE = $F0
TEXT_X	= $F1
TEXT_Y	= $F2


XSAVE	= $F6
SCROLL_IN=$F7
SCROLL_OUT=$F8

STRING_COUNT = $F9
MEMCOUNT= $FA
LEAD0	= $FB
INL	= $FC
INH	= $FD
OUTL	= $FE
OUTH	= $FF
