swing01_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A5,$AA, $9A,$9A, $A0,$21,$AA, $00, $A4,$AA, $BB, $99
	.byte $A0,$21,$AA, $00, $A5,$AA, $0B, $A0,$21,$AA, $00, $A0,$02,$AA
	.byte $A3,$AB, $00, $A0,$22,$AA, $00, $A0,$02,$AA, $0A,$0A, $40
	.byte $A0,$22,$AA, $A0,$01,$A0, $0A, $A0,$01,$A0, $A0,$02,$AA, $44, $A0,$27,$AA
	.byte $44, $A0,$26,$AA, $A0,$02,$AF, $A0,$FF,$AA, $A0,$AC,$AA
	.byte $A1
swing02_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A4,$AA, $9A,$9A, $A0,$22,$AA, $00, $A0,$01,$AA, $BA, $A0,$01,$AB
	.byte $B9, $99, $A0,$22,$AA, $00, $A0,$01,$AA, $A0,$01,$AB, $BA
	.byte $0A, $00, $A0,$22,$AA, $00, $A4,$AA, $00, $A0,$23,$AA
	.byte $00, $A0,$02,$AA, $0A, $40, $A0,$23,$AA, $A0,$01,$A0, $0A
	.byte $A0,$01,$A0, $A0,$01,$AA, $44, $A0,$26,$AA, $FA, $F4, $A0,$FF,$AA
	.byte $A0,$D5,$AA
	.byte $A1
swing03_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$02,$AA, $9A,$9A, $A0,$24,$AA, $00, $A0,$01,$AB, $99,$99, $A0,$24,$AA
	.byte $00, $A0,$01,$AB, $BA, $00, $A0,$24,$AA, $00, $A0,$02,$AA
	.byte $00, $A0,$25,$AA, $00, $A0,$01,$AA, $44, $0A, $A0,$24,$AA
	.byte $A0,$01,$A0, $44, $CC, $A0,$25,$AA, $FA, $F4, $A0,$FF,$AA
	.byte $A0,$D8,$AA
	.byte $A1
swing04_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$28,$AA, $00, $99,$99, $A0,$25,$AA, $B0, $A0,$01,$A9, $B9
	.byte $A0,$25,$AA, $0B, $A0,$01,$AB, $B0, $A0,$26,$AA, $00,$00, $A3,$0A
	.byte $A0,$23,$AA, $A0,$01,$A0, $00, $A0,$27,$AA, $44, $CA, $A0,$25,$AA
	.byte $44, $A0,$01,$A4, $CC, $A0,$24,$AA, $FA, $F4, $A0,$02,$A5
	.byte $A0,$FF,$AA, $A0,$87,$AA
	.byte $A1
swing05_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$28,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $B0, $A0,$27,$AA
	.byte $BB, $90, $A0,$02,$AA, $0A, $A0,$23,$AA, $BB, $99
	.byte $0A, $A0,$01,$A0, $A0,$25,$AA, $00, $A0,$26,$AA, $4A, $C4
	.byte $A0,$25,$AA, $44, $A0,$01,$A4, $A0,$01,$AC, $7A, $A0,$24,$AA, $A0,$01,$AF
	.byte $A0,$FF,$AA, $A0,$63,$AA
	.byte $A1
swing06_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$28,$AA, $00, $A0,$26,$AA
	.byte $9A,$9A, $BB, $A0,$25,$AA, $99, $BB, $A0,$01,$A0, $A3,$0A
	.byte $A0,$22,$AA, $0A, $00, $A0,$25,$AA, $44, $A0,$01,$A4, $C4
	.byte $A0,$25,$AA, $F4, $A0,$01,$AA, $5C, $A0,$FF,$AA, $A0,$8A,$AA
	.byte $A1
swing08_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $BA
	.byte $A0,$27,$AA, $BB, $9A, $A0,$26,$AA, $BB, $09, $A3,$0A
	.byte $A0,$24,$AA, $00, $A0,$26,$AA, $44, $C4, $A0,$26,$AA, $F4
	.byte $A0,$01,$AC, $7A, $A0,$FF,$AA, $A0,$88,$AA
	.byte $A1
swing10_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$28,$AA, $0A
	.byte $A0,$26,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $BA
	.byte $A0,$27,$AA, $BB, $9A, $A0,$26,$AA, $BB, $09, $A3,$0A
	.byte $A0,$24,$AA, $00, $A0,$26,$AA, $44, $C4, $A0,$26,$AA, $F4
	.byte $A0,$01,$AC, $7A, $A0,$FF,$AA, $A0,$88,$AA
	.byte $A1
swing11_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$28,$AA, $A0,$01,$A0, $A0,$4F,$AA, $0A
	.byte $A0,$28,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $B0, $A0,$27,$AA
	.byte $BB, $9A, $A0,$01,$AA, $0A, $A0,$24,$AA, $BB, $09
	.byte $0A, $A0,$01,$A0, $A0,$25,$AA, $00, $A0,$26,$AA, $44, $C4
	.byte $A0,$26,$AA, $F4, $A0,$01,$AC, $7A, $A0,$FF,$AA, $A0,$5F,$AA
	.byte $A1
swing12_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$C9,$AA
	.byte $A0,$01,$A0, $0A, $A0,$27,$AA, $00, $A0,$02,$AA, $0A, $A0,$24,$AA
	.byte $A0,$01,$A0, $B0, $A0,$01,$AB, $A0,$01,$A0, $A0,$25,$AA, $BB, $99
	.byte $A0,$26,$AA, $A0,$01,$AB, $00, $A0,$26,$AA, $4A, $40, $A0,$26,$AA
	.byte $44, $CC, $A0,$26,$AA, $A0,$01,$AF, $A0,$01,$AA, $A0,$01,$A5, $A0,$FF,$AA
	.byte $AE,$AA
	.byte $A1
swing13_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$CA,$AA
	.byte $0A, $A0,$28,$AA, $00, $A0,$27,$AA, $00, $0A, $BA
	.byte $A0,$26,$AA, $BB, $9A, $A0,$26,$AA, $BB, $09, $A0,$27,$AA
	.byte $00, $A0,$26,$AA, $44, $C4, $A0,$26,$AA, $F4, $5C
	.byte $A0,$FF,$AA, $AE,$AA
	.byte $A1
swing14_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$FF,$AA
	.byte $A0,$1D,$AA, $0A, $A0,$27,$AA, $00, $0A, $A0,$26,$AA, $A0,$02,$A0
	.byte $A0,$51,$AA, $00, $A0,$26,$AA, $44, $C4, $A0,$26,$AA, $F4
	.byte $A0,$01,$AC, $7A, $A0,$E2,$AA
	.byte $A1
swing15_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$FF,$AA
	.byte $A0,$E9,$AA, $00, $A0,$26,$AA, $4A, $40, $A0,$26,$AA, $44
	.byte $CC, $A0,$26,$AA, $A0,$01,$AF, $A0,$01,$AA, $A0,$01,$A7, $A0,$91,$AA
	.byte $A1
swing16_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$FF,$AA
	.byte $A0,$E9,$AA, $0A,$0A, $A0,$26,$AA, $40,$40, $A0,$26,$AA, $44, $A0,$01,$AC
	.byte $5A, $A0,$25,$AA, $A0,$01,$AF, $A0,$92,$AA
	.byte $A1
swing17_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$FF,$AA
	.byte $A0,$FF,$AA, $A0,$3C,$AA, $44, $A0,$01,$AC, $7A, $A0,$25,$AA, $A0,$01,$AF
	.byte $A0,$90,$AA
	.byte $A1
swing18_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$FF,$AA
	.byte $A0,$FF,$AA, $A0,$68,$AA, $F4, $5A, $A0,$8B,$AA
	.byte $A1
swing19_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$26,$AA
	.byte $0A, $00, $A0,$26,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $A0,$FF,$AA
	.byte $A0,$A3,$AA, $BB, $A0,$FF,$AA, $A0,$51,$AA
	.byte $A1
swing20_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$10,$AA, $00, $A0,$16,$AA, $00, $A0,$10,$AA
	.byte $A0,$01,$A0, $0A, $A0,$15,$AA, $00, $A0,$11,$AA, $00, $A0,$14,$AA
	.byte $0A, $00, $A0,$11,$AA, $00, $A0,$14,$AA, $00, $A0,$12,$AA
	.byte $00, $A0,$14,$AA, $A0,$01,$A0, $A0,$12,$AA, $A0,$01,$A0, $0A, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$28,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $A0,$01,$A0, $BA, $A0,$27,$AA, $BB, $A0,$27,$AA
	.byte $99, $A0,$FF,$AA, $A0,$26,$AA
	.byte $A1
swing21_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$12,$AA, $00, $A0,$14,$AA, $00, $A0,$13,$AA
	.byte $00, $A0,$13,$AA, $00, $A0,$13,$AA, $00, $A0,$12,$AA, $0A
	.byte $00, $A0,$14,$AA, $00, $A0,$11,$AA, $00, $A0,$15,$AA, $00
	.byte $A0,$11,$AA, $A0,$01,$A0, $A0,$15,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $0A
	.byte $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$28,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$27,$AA, $00, $A0,$27,$AA, $A0,$01,$A0
	.byte $BA, $A0,$27,$AA, $BB, $A0,$27,$AA, $99, $BB, $A0,$26,$AA
	.byte $00, $A0,$27,$AA, $A0,$01,$A4, $A0,$FA,$AA
	.byte $A1
swing22_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$13,$AA, $00, $A0,$13,$AA, $00, $A0,$14,$AA
	.byte $00, $A0,$12,$AA, $00, $A0,$14,$AA, $00, $A0,$11,$AA, $0A
	.byte $00, $A0,$15,$AA, $00, $A0,$10,$AA, $00, $A0,$16,$AA, $00
	.byte $A0,$10,$AA, $A0,$01,$A0, $A0,$17,$AA, $00, $A0,$27,$AA, $00, $A0,$28,$AA
	.byte $00, $A0,$27,$AA, $00, $A0,$28,$AA, $00, $A0,$27,$AA, $00
	.byte $A0,$28,$AA, $00, $A0,$27,$AA, $A0,$01,$A0, $BA, $A0,$27,$AA, $BB
	.byte $A0,$27,$AA, $99, $BB, $A0,$26,$AA, $00,$00, $A0,$26,$AA, $C4
	.byte $44, $A0,$25,$AA, $A0,$01,$A7, $A0,$01,$AA, $A0,$01,$AF, $A0,$F6,$AA
	.byte $A1
swing23_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$15,$AA, $00, $A0,$11,$AA, $00, $A0,$15,$AA
	.byte $A0,$01,$A0, $0A, $A0,$10,$AA, $00, $A0,$16,$AA, $00, $AF,$AA
	.byte $0A, $00, $A0,$16,$AA, $A0,$01,$A0, $0A, $AE,$AA, $00
	.byte $A0,$18,$AA, $00, $AE,$AA, $A0,$01,$A0, $A0,$19,$AA, $00, $A0,$27,$AA
	.byte $A0,$01,$A0, $0A, $A0,$27,$AA, $A0,$01,$A0, $0A, $A0,$27,$AA, $00
	.byte $A0,$27,$AA, $A0,$01,$A0, $0A, $A0,$27,$AA, $00, $A0,$27,$AA, $A0,$01,$A0
	.byte $BA, $A0,$27,$AA, $BB, $A0,$27,$AA, $99, $BB, $A0,$26,$AA
	.byte $00, $A0,$27,$AA, $44, $A0,$26,$AA, $7A, $A0,$01,$AC, $F4
	.byte $A0,$FF,$AA, $A0,$1D,$AA
	.byte $A1
swing24_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$18,$AA, $00, $AE,$AA, $00, $A0,$18,$AA
	.byte $A0,$01,$A0, $0A, $AD,$AA, $00, $A0,$19,$AA, $00, $AC,$AA
	.byte $0A, $00, $A0,$1A,$AA, $00, $AB,$AA, $00, $A0,$1B,$AA
	.byte $A0,$01,$A0, $0A, $AA,$AA, $A0,$01,$A0, $A0,$1C,$AA, $00, $A0,$28,$AA
	.byte $00, $A0,$27,$AA, $A0,$01,$A0, $0A, $A0,$27,$AA, $00, $A0,$28,$AA
	.byte $00, $A0,$28,$AA, $00, $A0,$28,$AA, $BB, $A0,$27,$AA, $9B
	.byte $BA, $A0,$26,$AA, $09, $0B, $A0,$26,$AA, $40, $00
	.byte $A0,$25,$AA, $7A, $A0,$01,$AC, $44, $A0,$27,$AA, $A0,$01,$AF, $A0,$FF,$AA
	.byte $A0,$19,$AA
	.byte $A1
swing25_rle:	.byte $28 ; ysize=48
	.byte $A5,$AA, $00, $A0,$19,$AA, $00, $AD,$AA, $00, $A0,$19,$AA
	.byte $A0,$01,$A0, $0A, $AC,$AA, $00, $A0,$1A,$AA, $00, $AB,$AA
	.byte $0A, $00, $A0,$1B,$AA, $00, $AA,$AA, $00, $A0,$1C,$AA
	.byte $A0,$01,$A0, $0A, $A9,$AA, $A0,$01,$A0, $A0,$1D,$AA, $00, $A0,$28,$AA
	.byte $00, $A0,$28,$AA, $00, $A0,$28,$AA, $00, $A0,$28,$AA, $00
	.byte $A0,$28,$AA, $BB, $A0,$27,$AA, $9B, $A0,$27,$AA, $09, $A0,$27,$AA
	.byte $00, $A0,$27,$AA, $C4, $A0,$27,$AA, $A0,$01,$A7, $A0,$FF,$AA, $A0,$41,$AA
	.byte $A1
