all:
	cd l2_cage && make
	cd l2_city && make
	cd l2_intro && make
	cd l2_jail && make
	cd l2_laser && make

clean:
	cd l2_cage && make clean
	cd l2_city && make clean
	cd l2_intro && make clean
	cd l2_jail && make clean
	cd l2_laser && make clean

