scan01_rle:	.byte $28 ; ysize=48
	.byte $A0,$34,$AA, $A5,$1A, $A0,$FF,$AA, $A0,$EF,$AA, $22, $62,$62, $22
	.byte $62,$62, $22, $A0,$21,$AA, $22, $66,$66, $22, $66,$66
	.byte $22, $A0,$21,$AA, $A7,$A2, $A0,$FF,$AA, $A0,$43,$AA
	.byte $A1
scan02_rle:	.byte $28 ; ysize=48
	.byte $A0,$5B,$AA, $A5,$1A, $A0,$FF,$AA, $A0,$BD,$AA, $22, $62,$62, $22
	.byte $62,$62, $22, $A0,$21,$AA, $22, $66,$66, $22, $66,$66
	.byte $22, $A0,$21,$AA, $A7,$A2, $A0,$3F,$AA, $1A,$1A, $A0,$28,$AA, $A0,$01,$A1
	.byte $A0,$01,$A3, $3A, $1A, $A0,$28,$AA, $A0,$01,$A1, $A0,$B7,$AA
	.byte $A1
scan03_rle:	.byte $28 ; ysize=48
	.byte $A0,$D2,$AA, $A7,$A1, $A0,$FF,$AA, $A0,$62,$AA, $1A,$1A, $A0,$28,$AA, $A0,$01,$A1
	.byte $A0,$01,$A3, $3A, $1A, $A0,$28,$AA, $A0,$01,$A1, $A0,$01,$A3, $A0,$FF,$AA
	.byte $A0,$2F,$AA
	.byte $A1
scan04_rle:	.byte $28 ; ysize=48
	.byte $A0,$FC,$AA, $A4,$1A, $A0,$C2,$AA, $11, $A0,$27,$AA, $11, $A0,$24,$AA
	.byte $2A, $22, $62, $11, $A0,$01,$A1, $1A, $3A
	.byte $A0,$1F,$AA, $2A, $62, $66, $22, $66, $11
	.byte $A3,$AA, $A0,$01,$A3, $A0,$01,$A1, $1A, $3A, $A0,$1B,$AA, $22
	.byte $66, $26, $A0,$02,$A2, $A0,$01,$A1, $A0,$22,$AA, $A0,$02,$A2, $A0,$FF,$AA
	.byte $A0,$3A,$AA
	.byte $A1
scan05_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A0,$4C,$AA, $11, $A0,$26,$AA, $1A, $11, $A5,$1A
	.byte $A0,$22,$AA, $11, $A0,$26,$AA, $1A, $11, $A0,$27,$AA, $11
	.byte $A0,$01,$A1, $A0,$01,$A3, $3A, $1A, $A0,$23,$AA, $11, $A4,$AA
	.byte $A0,$02,$A1, $A0,$19,$AA, $2A, $A7,$AA, $11, $A0,$1D,$AA, $2A
	.byte $62, $22, $A7,$AA, $11, $A0,$1D,$AA, $22, $66
	.byte $22, $A7,$AA, $11, $A0,$1D,$AA, $22, $66, $22
	.byte $A7,$AA, $11, $A0,$1D,$AA, $22, $26, $A0,$01,$A2, $A7,$AA
	.byte $11, $A0,$1D,$AA, $A0,$01,$A2, $A9,$AA, $A0,$01,$A1, $A0,$BC,$AA
	.byte $A1
scan06_rle:	.byte $28 ; ysize=48
	.byte $A0,$5B,$AA, $1A, $A0,$27,$AA, $A0,$01,$A1, $A0,$C7,$AA, $11, $1A
	.byte $A0,$26,$AA, $11, $A0,$01,$AA, $A0,$02,$A1, $1A, $A0,$22,$AA, $A0,$01,$A1
	.byte $11, $A5,$A1, $A0,$22,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$1F,$AA, $22, $62, $2A, $A5,$AA, $11
	.byte $A0,$1F,$AA, $22, $66,$66, $62, $2A, $A3,$AA, $11
	.byte $A0,$1F,$AA, $22, $A3,$66, $22, $A3,$AA, $11, $A0,$1F,$AA
	.byte $22, $A3,$66, $22, $A3,$AA, $11, $A0,$1F,$AA, $22
	.byte $A3,$66, $22, $A3,$AA, $11, $A0,$1F,$AA, $A0,$01,$A2, $A3,$A6
	.byte $A0,$01,$A2, $A3,$AA, $A0,$01,$A1, $A0,$BC,$AA
	.byte $A1
scan07_rle:	.byte $28 ; ysize=48
	.byte $A0,$34,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $A0,$01,$A1, $A0,$76,$AA, $A0,$01,$A1, $11, $1A
	.byte $A0,$26,$AA, $11, $A0,$01,$AA, $A0,$01,$A1, $1A, $A0,$24,$AA, $11
	.byte $A3,$AA, $A0,$01,$A1, $A0,$23,$AA, $11, $A0,$25,$AA, $1A,$1A, $11
	.byte $A5,$1A, $A0,$22,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A3,$AA, $A9,$2A, $A0,$1B,$AA, $11, $A3,$AA, $22, $A7,$66
	.byte $22, $A0,$1B,$AA, $11, $A3,$AA, $22, $A7,$66, $22
	.byte $A0,$1B,$AA, $11, $A3,$AA, $22, $A7,$66, $22, $A0,$1B,$AA
	.byte $A0,$01,$A1, $A3,$AA, $A0,$01,$A2, $A7,$A6, $A0,$01,$A2, $A0,$AF,$AA
	.byte $A1
scan08_rle:	.byte $28 ; ysize=48
	.byte $AC,$AA, $1A, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $A0,$01,$A1, $A0,$27,$AA, $1A
	.byte $A0,$27,$AA, $11, $1A, $A0,$26,$AA, $11, $A0,$01,$AA, $A0,$01,$A1
	.byte $1A, $A0,$24,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$25,$AA
	.byte $A0,$02,$A1, $11, $A5,$A1, $A0,$22,$AA, $11, $A0,$16,$AA, $22
	.byte $A4,$62, $AC,$AA, $11, $A0,$16,$AA, $22, $A4,$66, $AC,$AA
	.byte $11, $A0,$16,$AA, $22, $A4,$66, $AC,$AA, $A0,$01,$A1, $A0,$16,$AA
	.byte $A0,$01,$A2, $A4,$A6, $A0,$A0,$AA
	.byte $A1
scan09_rle:	.byte $28 ; ysize=48
	.byte $AD,$AA, $11, $A0,$25,$AA, $A0,$01,$A1, $1A, $11, $A0,$27,$AA
	.byte $11, $1A, $A0,$26,$AA, $11, $A0,$01,$AA, $A0,$01,$A1, $1A
	.byte $A0,$24,$AA, $11, $A3,$AA, $A0,$01,$A1, $A0,$23,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$24,$AA, $A3,$A1, $11, $A4,$A1, $A0,$23,$AA
	.byte $A0,$01,$A1, $A0,$BA,$AA
	.byte $A1
scan10_rle:	.byte $28 ; ysize=48
	.byte $AD,$AA, $11, $1A, $A0,$26,$AA, $11, $A0,$01,$AA, $A0,$01,$A1
	.byte $1A, $A0,$24,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $A0,$01,$A1, $A0,$BA,$AA
	.byte $A1
scan11_rle:	.byte $28 ; ysize=48
	.byte $AE,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $A0,$01,$A1, $A0,$B9,$AA
	.byte $A1
scan12_rle:	.byte $28 ; ysize=48
	.byte $AF,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $AA,$AA
	.byte $00,$00, $CC, $A0,$1A,$AA, $11, $AA,$AA, $00,$00, $CC
	.byte $A0,$1A,$AA, $11, $AA,$AA, $00, $C0, $0C, $A0,$1A,$AA
	.byte $11, $AA,$AA, $00, $CC, $00, $A0,$1A,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $A0,$01,$A1, $A0,$B8,$AA
	.byte $A1
scan13_rle:	.byte $28 ; ysize=48
	.byte $A0,$10,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A9,$AA
	.byte $00, $CC, $00, $A0,$1B,$AA, $11, $A9,$AA, $00
	.byte $CC, $0C, $A0,$1B,$AA, $11, $A9,$AA, $C0, $0C
	.byte $C0, $A0,$1B,$AA, $11, $A9,$AA, $0C, $00, $0C
	.byte $A0,$1B,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11
	.byte $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA
	.byte $11, $A0,$27,$AA, $11, $A0,$27,$AA, $11, $A0,$27,$AA, $A0,$01,$A1
	.byte $A0,$B7,$AA
	.byte $A1
scan14_rle:	.byte $28 ; ysize=48
	.byte $A0,$6A,$AA, $00, $CC, $00, $A0,$25,$AA, $0C, $CC
	.byte $0C, $A0,$25,$AA, $C0, $0C, $C0, $A0,$25,$AA, $0C
	.byte $00, $0C, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$DD,$AA
	.byte $A1
scan15_rle:	.byte $28 ; ysize=48
	.byte $A0,$6A,$AA, $40, $4C, $40, $A0,$25,$AA, $A3,$4C, $A0,$25,$AA
	.byte $40, $4C, $40, $A0,$25,$AA, $0C, $00, $0C
	.byte $A0,$FF,$AA, $A0,$FF,$AA, $A0,$DD,$AA
	.byte $A1
scan16_rle:	.byte $28 ; ysize=48
	.byte $A0,$6A,$AA, $40, $CC, $40, $A0,$25,$AA, $4C, $C4
	.byte $0C, $A0,$25,$AA, $C0, $4C, $C4, $A0,$25,$AA, $04
	.byte $00, $04, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$DD,$AA
	.byte $A1
scan17_rle:	.byte $28 ; ysize=48
	.byte $A0,$6A,$AA, $CC, $C0, $00, $A0,$25,$AA, $CC, $00
	.byte $0C, $A0,$25,$AA, $CC, $0C, $C0, $A0,$25,$AA, $0C
	.byte $00,$00, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$DD,$AA
	.byte $A1
scan18_rle:	.byte $28 ; ysize=48
	.byte $A0,$6A,$AA, $4C, $C0, $40, $A0,$25,$AA, $4C, $04
	.byte $4C, $A0,$25,$AA, $4C, $04, $40, $A0,$25,$AA, $0C
	.byte $00,$00, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$DD,$AA
	.byte $A1
scan19_rle:	.byte $28 ; ysize=48
	.byte $A0,$6A,$AA, $C0, $4C, $C0, $A0,$25,$AA, $CC, $44
	.byte $CC, $A0,$25,$AA, $CC, $44, $CC, $A0,$25,$AA, $00
	.byte $0C, $00, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$DD,$AA
	.byte $A1
