all:
	cd 01_building && make
	cd 02_outer_door && make
	cd 03_elevator && make
	cd 04_keypad && make
	cd 05_scanner && make
	cd 06_console && make
	cd 07_soda && make
	cd 08_lightning && make
	cd 09_tunnel && make
	cd 10_gone && make

clean:
	cd 01_building && make clean
	cd 02_outer_door && make clean
	cd 03_elevator && make clean
	cd 04_keypad && make clean
	cd 05_scanner && make clean
	cd 06_console && make clean
	cd 07_soda && make clean
	cd 08_lightning && make clean
	cd 09_tunnel && make clean
	cd 10_gone && make clean

