
slug_background:
	.byte 10,10
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22
	.byte $22,$22,$22,$22,$22,$22,$22,$22,$22,$22


; sluggy freelance

sluggy1:
	.byte 10,6
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$0A,$0A,$0A,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$77,$00,$00,$00
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$07,$00,$00,$00
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00

sluggy2:
	.byte 10,6
	.byte $AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$0A,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$77,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$07,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA

sluggy3:
	.byte 10,6
	.byte $AA,$AA,$AA,$AA,$AA,$0A,$0A,$0A,$AA,$AA
	.byte $AA,$AA,$AA,$AA,$7A,$07,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$A1,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA

sluggy4:
	.byte 10,6
	.byte $AA,$1A,$AA,$7A,$7A,$70,$00,$00,$0A,$AA
	.byte $AA,$AA,$AA,$AA,$1A,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA

sluggy5:
	.byte 10,6
	.byte $1A,$AA,$AA,$7A,$7A,$70,$00,$00,$0A,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$1A,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA

sluggy6:
	.byte 10,6
	.byte $AA,$AA,$AA,$7A,$7A,$70,$00,$00,$0A,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$1A,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA
	.byte $AA,$AA,$AA,$AA,$AA,$00,$00,$00,$00,$AA


leg_background:
	.byte 10,10
	.byte $44,$cc,$cc,$cc,$77,$77,$77,$77,$77,$77
	.byte $44,$cc,$cc,$cc,$27,$27,$77,$77,$77,$77
	.byte $44,$cc,$cc,$cc,$42,$22,$77,$77,$77,$77
	.byte $44,$cc,$cc,$cc,$44,$22,$22,$22,$27,$27
	.byte $44,$4c,$cc,$cc,$c4,$42,$22,$22,$22,$22
	.byte $22,$44,$cc,$cc,$cc,$44,$22,$22,$22,$22
	.byte $22,$44,$cc,$cc,$cc,$44,$22,$22,$22,$22
	.byte $22,$44,$cc,$cc,$4c,$44,$22,$22,$22,$22
	.byte $22,$44,$cc,$cc,$c4,$44,$22,$22,$22,$22
	.byte $22,$44,$cc,$cc,$cc,$44,$22,$22,$22,$22

leg1:
	.byte $5,$6
	.byte $AA,$AA,$AA,$AA,$AA
	.byte $AA,$AA,$AA,$0A,$AA
	.byte $AA,$AA,$A7,$00,$00
	.byte $AA,$AA,$AA,$00,$00
	.byte $AA,$AA,$AA,$00,$00
	.byte $AA,$AA,$AA,$00,$00

leg2:
	.byte $4,$6
	.byte $AA,$AA,$AA,$AA
	.byte $bA,$AA,$0A,$AA
	.byte $AA,$A7,$00,$00
	.byte $AA,$AA,$00,$00
	.byte $AA,$AA,$00,$00
	.byte $AA,$AA,$00,$00

leg3:
	.byte $4,$6
	.byte $AA,$AA,$AA,$AA
	.byte $bA,$AA,$AA,$AA
	.byte $bb,$AA,$0A,$AA
	.byte $AB,$A7,$00,$00
	.byte $AA,$AA,$00,$00
	.byte $AA,$AA,$00,$00

leg4:
	.byte $4,$6
	.byte $AA,$AA,$AA,$AA
	.byte $bA,$AA,$AA,$AA
	.byte $1B,$AA,$AA,$AA
	.byte $BB,$AA,$0A,$AA
	.byte $AA,$A7,$00,$00
	.byte $AA,$AA,$00,$00
leg5:
	.byte $1,$4
	.byte $AA
	.byte $bA
	.byte $11
	.byte $b1
