frame15:					; handmade / auto
	.include "auto/frame015.inc"
	.include "auto/frame016.inc"
	.include "handmade/frame017.inc"	; 51 / 52 (1 byte)
	.include "auto/frame018.inc"		; 54 / 52
	.include "handmade/frame019.inc"	; 65 / 70 (5 bytes)
	.include "handmade/frame020.inc"	; 71 / 76 (5 bytes)
	.include "auto/frame021.inc"		; 68 / 68
	.include "auto/frame022.inc"		; 103 / 103
	.include "handmade/frame023.inc"	; 127 / 135 (8 bytes)
	.include "handmade/frame024.inc"	; 139 / 166 (27 bytes)
	.include "handmade/frame025.inc"	; 143 / 166 (23 bytes)
	.include "handmade/frame026.inc"	; 151 / 156 (5 bytes)
	.include "handmade/frame027.inc"	; 131 / 146 (15 bytes)
	.include "handmade/frame028.inc"	; 134 / 160 (26 bytes)
	.include "handmade/frame029.inc"	; 109 / 115 (6 bytes)
	.include "handmade/frame030.inc"	; 81 / 86 (5 bytes)
	.include "auto/frame031.inc"		; 60 / 55 (-5 bytes)
	.include "auto/frame032.inc"		; 62 / 57 (-5 bytes)
	.include "auto/frame033.inc"		; 87 / 83 (-4 bytes)
	.include "handmade/frame034.inc"	; 116 / 123 (7 bytes)
	.include "handmade/frame035.inc"	; 147 / 156 (9 bytes)
	.include "handmade/frame036.inc"	; 155 / 156 (1 byte)
	.include "handmade/frame037.inc"	; 154 / 179 (25 bytes)
	.include "handmade/frame038.inc"	; 148 / 166 (18 bytes)
	.include "handmade/frame039.inc"	; 136 / 139 ( 3 bytes)
	.include "handmade/frame040.inc"	; 102 / 104 (3 bytes)
	.include "handmade/frame041.inc"	; 65  / 66 (1 byte)
	.include "auto/frame042.inc"		; 92  / 78 (-14 bytes)
	.include "handmade/frame043.inc"	; 233 / 273 (40 bytes)
	.include "handmade/frame044.inc"	; 199 / 220 (21 bytes)
	.include "handmade/frame045.inc"	; 182 / 204 (22 bytes)
	.include "handmade/frame046.inc"	; 172 / 174 (2 bytes)
	.include "handmade/frame047.inc"	; 191 / 202 (11 bytes)
	.include "handmade/frame048.inc"	; 218 / 226 (8 bytes)
	.include "handmade/frame049.inc"	; 186 / 198 (12 bytes)
	.include "handmade/frame050.inc"	; 253 / 288 (35 bytes)
	.include "auto/frame051.inc"	;
	.include "auto/frame052.inc"	;
	.include "auto/frame053.inc"	;
	.include "auto/frame054.inc"	;
	.include "auto/frame055.inc"	;
	.include "auto/frame056.inc"	;
	.include "auto/frame057.inc"	;
	.include "auto/frame058.inc"	;
	.include "auto/frame059.inc"	;
	.include "auto/frame060.inc"	;
	.include "auto/frame061.inc"	;
	.include "auto/frame062.inc"	;
	.include "auto/frame063.inc"	;
	.include "auto/frame064.inc"	;
	.include "auto/frame065.inc"	;
	.include "auto/frame066.inc"	;
	.include "auto/frame067.inc"	;
	.include "auto/frame068.inc"	;
	.include "auto/frame069.inc"	;
	.include "auto/frame070.inc"	;
	.include "auto/frame071.inc"	;
	.include "auto/frame072.inc"	;
	.include "auto/frame073.inc"	;
	.include "auto/frame074.inc"	;
	.include "auto/frame075.inc"	;
	.include "auto/frame076.inc"	;
	.include "auto/frame077.inc"	;
	.include "auto/frame078.inc"	;
	.include "auto/frame079.inc"	;
	.include "auto/frame080.inc"	;
	.include "auto/frame081.inc"	;
	.include "auto/frame082.inc"	;
	.include "auto/frame083.inc"	;
	.include "auto/frame084.inc"	;
	.include "auto/frame085.inc"	;
	.include "auto/frame086.inc"	;
	.include "auto/frame087.inc"	;
	.include "auto/frame088.inc"	;
	.include "auto/frame089.inc"	;
	.include "auto/frame090.inc"	;
	.include "auto/frame091.inc"	;
	.include "auto/frame092.inc"	;
	.include "auto/frame093.inc"	;
	.include "auto/frame094.inc"	;
	.include "auto/frame095.inc"	;
	.include "auto/frame096.inc"	;
	.include "auto/frame097.inc"	;
	.include "auto/frame098.inc"	;
	.include "auto/frame099.inc"	;
	.include "auto/frame100.inc"	;
	.include "auto/frame101.inc"	;
	.include "auto/frame102.inc"	;
	.include "auto/frame103.inc"	;
	.include "auto/frame104.inc"	;
	.include "auto/frame105.inc"	;
	.include "auto/frame106.inc"	;
	.include "auto/frame107.inc"	;
	.include "auto/frame108.inc"	;
	.include "auto/frame109.inc"	;
	.include "auto/frame110.inc"	;
	.include "auto/frame111.inc"	;
	.include "auto/frame112.inc"	;
	.include "auto/frame113.inc"	;
	.include "auto/frame114.inc"	;
	.include "auto/frame115.inc"	;
	.include "auto/frame116.inc"	;
	.include "auto/frame117.inc"	;
	.include "auto/frame118.inc"	;
	.include "auto/frame119.inc"	;
	.include "auto/frame120.inc"	;
	.include "auto/frame121.inc"	;
	.include "auto/frame122.inc"	;
	.include "auto/frame123.inc"	;
	.include "auto/frame124.inc"	;
	.include "auto/frame125.inc"	;
	.include "auto/frame126.inc"	;
	.include "auto/frame127.inc"	;
	.include "auto/frame128.inc"	;
	.include "auto/frame129.inc"	;
	.include "auto/frame130.inc"	;
	.include "auto/frame131.inc"	;
	.include "auto/frame132.inc"	;
	.include "auto/frame133.inc"	;
	.include "auto/frame134.inc"	;
	.include "auto/frame135.inc"	;
	.include "auto/frame136.inc"	;
	.include "auto/frame137.inc"	;
	.include "auto/frame138.inc"	;
	.include "auto/frame139.inc"	;
	.include "auto/frame140.inc"	;
	.include "auto/frame141.inc"	;
	.include "auto/frame142.inc"	;
	.include "auto/frame143.inc"	;
	.include "auto/frame144.inc"	;
	.include "auto/frame145.inc"	;
	.include "auto/frame146.inc"	;
	.include "auto/frame147.inc"	;
	.include "auto/frame148.inc"	;
	.include "auto/frame149.inc"	;
	.include "auto/frame150.inc"	;
	.include "auto/frame151.inc"	;
	.include "auto/frame152.inc"	;
	.include "auto/frame153.inc"	;
	.include "auto/frame154.inc"	;
	.include "auto/frame155.inc"	;
	.include "auto/frame156.inc"	;
	.include "auto/frame157.inc"	;
	.include "auto/frame158.inc"	;
	.include "auto/frame159.inc"	;
	.include "auto/frame160.inc"	;
	.include "auto/frame161.inc"	;
	.include "auto/frame162.inc"	;
	.include "auto/frame163.inc"	;
	.include "auto/frame164.inc"	;
	.include "auto/frame165.inc"	;
	.include "auto/frame166.inc"	;
	.include "auto/frame167.inc"	;
	.include "auto/frame168.inc"	;
	.include "auto/frame169.inc"	;
	.include "auto/frame170.inc"	;
	.include "auto/frame171.inc"	;
	.include "auto/frame172.inc"	;
	.include "auto/frame173.inc"	;
	.include "auto/frame174.inc"	;
	.include "auto/frame175.inc"	;
	.include "auto/frame176.inc"	;
	.include "auto/frame177.inc"	;
	.include "auto/frame178.inc"	;
	.include "auto/frame179.inc"	;
	.include "auto/frame180.inc"	;
	.include "auto/frame181.inc"	;
	.include "auto/frame182.inc"	;
	.include "auto/frame183.inc"	;
	.include "auto/frame184.inc"	;
	.include "auto/frame185.inc"	;
	.include "auto/frame186.inc"	;
	.include "auto/frame187.inc"	;
	.include "auto/frame188.inc"	;
	.include "auto/frame189.inc"	;
	.include "auto/frame190.inc"	;
	.include "auto/frame191.inc"	;
	.include "auto/frame192.inc"	;
	.include "auto/frame193.inc"	;
	.include "auto/frame194.inc"	;
	.include "auto/frame195.inc"	;
	.include "auto/frame196.inc"	;
	.include "auto/frame197.inc"	;
	.include "auto/frame198.inc"	;
	.include "auto/frame199.inc"	;
	.include "auto/frame200.inc"	;
	.include "auto/frame201.inc"	;
	.include "auto/frame202.inc"	;
	.include "auto/frame203.inc"	;
	.include "auto/frame204.inc"	;
	.include "auto/frame205.inc"	;

num_scenes=(205-15)+1

