frame15:
	.include "auto/frame015.inc"
	.include "auto/frame016.inc"
	.include "handmade/frame017.inc"	; handmade 1 byte smaller
	.include "handmade/frame018.inc"	; handmade 2 bytes smaller
	.include "handmade/frame019.inc"	; handmade 12 bytes smaller
	.include "handmade/frame020.inc"	; handmade 7 bytes smaller
	.include "handmade/frame021.inc"	; handmade 1 byte smaller
	.include "handmade/frame022.inc"	; handmade 12 bytes smaller
	.include "handmade/frame023.inc"	; handmade 40 bytes smaller
	.include "handmade/frame024.inc"	; handmade 42 bytes smaller
	.include "handmade/frame025.inc"	; handmade 50 bytes smaller
	.include "handmade/frame026.inc"	; handmade 26 bytes smaller
	.include "handmade/frame027.inc"	; handmade 17 bytes smaller
	.include "handmade/frame028.inc"	; handmade 27 bytes smaller
	.include "handmade/frame029.inc"	; handmade 30 bytes smaller
	.include "handmade/frame030.inc"	; handmade 5 bytes smaller
	.include "handmade/frame031.inc"	; handmade 7 bytes smaller
	.include "auto/frame032.inc"		; handmade -4 bytes smaller
	.include "auto/frame033.inc"		; handmade -3 bytes smaller
	.include "handmade/frame034.inc"	; handmade 16 bytes smaller
	.include "handmade/frame035.inc"	; handmade 11 bytes smaller
	.include "handmade/frame036.inc"	; handmade  6 bytes smaller
	.include "handmade/frame037.inc"	; handmade 32 bytes smaller
	.include "handmade/frame038.inc"	; handmade 54 bytes smaller
	.include "handmade/frame039.inc"	; handmade 18 bytes smaller
	.include "handmade/frame040.inc"	; handmade 8 bytes smaller
	.include "handmade/frame041.inc"	; handmade 3 bytes smaller
	.include "auto/frame042.inc"		; handmade -11 bytes smaller
	.include "handmade/frame043.inc"	; handmade 63 bytes smaller
	.include "handmade/frame044.inc"	; handmade 35 bytes smaller
	.include "handmade/frame045.inc"	; handmade 26 bytes smaller
	.include "handmade/frame046.inc"	; handmade 18 bytes smaller
	.include "handmade/frame047.inc"	; handmade 18 bytes smaller
	.include "handmade/frame048.inc"	; handmade 15 bytes smaller
	.include "handmade/frame049.inc"	; handmade 18 bytes smaller
	.include "handmade/frame050.inc"	; handmade 28 bytes smaller



num_scenes=(50-15)+1

