frame15:
	.include "auto/frame015.inc"
	.include "auto/frame016.inc"
	.include "handmade/frame017.inc"	; handmade 1 byte smaller
	.include "handmade/frame018.inc"	; handmade 2 bytes smaller
	.include "handmade/frame019.inc"	; handmade 12 bytes smaller
	.include "handmade/frame020.inc"	; handmade 7 bytes smaller
	.include "handmade/frame021.inc"	; handmade 1 byte smaller
	.include "handmade/frame022.inc"	; handmade 12 bytes smaller
	.include "handmade/frame023.inc"	; handmade 40 bytes smaller
	.include "handmade/frame024.inc"	; handmade 42 bytes smaller
	.include "handmade/frame025.inc"	; handmade 50 bytes smaller
	.include "handmade/frame026.inc"	; handmade 26 bytes smaller
	.include "handmade/frame027.inc"	; handmade 17 bytes smaller
	.include "handmade/frame028.inc"	; handmade 27 bytes smaller
	.include "handmade/frame029.inc"	; handmade 30 bytes smaller
	.include "handmade/frame030.inc"	; handmade 5 bytes smaller
	.include "handmade/frame031.inc"	; handmade 7 bytes smaller
	.include "auto/frame032.inc"		; handmade -4 bytes smaller
	.include "auto/frame033.inc"		; handmade -3 bytes smaller
	.include "handmade/frame034.inc"	; handmade 16 bytes smaller
	.include "handmade/frame035.inc"	; handmade 11 bytes smaller
	.include "handmade/frame036.inc"	; handmade  6 bytes smaller
	.include "handmade/frame037.inc"	; handmade 32 bytes smaller
	.include "handmade/frame038.inc"	; handmade 54 bytes smaller
	.include "handmade/frame039.inc"	; handmade 18 bytes smaller
	.include "handmade/frame040.inc"	; handmade 8 bytes smaller
	.include "handmade/frame041.inc"	; handmade 3 bytes smaller
	.include "auto/frame042.inc"		; handmade -11 bytes smaller
	.include "handmade/frame043.inc"	; handmade 63 bytes smaller
	.include "handmade/frame044.inc"	; handmade 35 bytes smaller
	.include "handmade/frame045.inc"	; handmade 26 bytes smaller
	.include "handmade/frame046.inc"	; handmade 18 bytes smaller
	.include "handmade/frame047.inc"	; handmade 18 bytes smaller
	.include "handmade/frame048.inc"	; handmade 15 bytes smaller
	.include "handmade/frame049.inc"	; handmade 18 bytes smaller
	.include "handmade/frame050.inc"	; handmade 28 bytes smaller
	.include "auto/frame051.inc"	;
	.include "auto/frame052.inc"	;
	.include "auto/frame053.inc"	;
	.include "auto/frame054.inc"	;
	.include "auto/frame055.inc"	;
	.include "auto/frame056.inc"	;
	.include "auto/frame057.inc"	;
	.include "auto/frame058.inc"	;
	.include "auto/frame059.inc"	;
	.include "auto/frame060.inc"	;
	.include "auto/frame061.inc"	;
	.include "auto/frame062.inc"	;
	.include "auto/frame063.inc"	;
	.include "auto/frame064.inc"	;
	.include "auto/frame065.inc"	;
	.include "auto/frame066.inc"	;
	.include "auto/frame067.inc"	;
	.include "auto/frame068.inc"	;
	.include "auto/frame069.inc"	;
	.include "auto/frame070.inc"	;
	.include "auto/frame071.inc"	;
	.include "auto/frame072.inc"	;
	.include "auto/frame073.inc"	;
	.include "auto/frame074.inc"	;
	.include "auto/frame075.inc"	;
	.include "auto/frame076.inc"	;
	.include "auto/frame077.inc"	;
	.include "auto/frame078.inc"	;
	.include "auto/frame079.inc"	;
	.include "auto/frame080.inc"	;
	.include "auto/frame081.inc"	;
	.include "auto/frame082.inc"	;
	.include "auto/frame083.inc"	;
	.include "auto/frame084.inc"	;
	.include "auto/frame085.inc"	;
	.include "auto/frame086.inc"	;
	.include "auto/frame087.inc"	;
	.include "auto/frame088.inc"	;
	.include "auto/frame089.inc"	;
	.include "auto/frame090.inc"	;
	.include "auto/frame091.inc"	;
	.include "auto/frame092.inc"	;
	.include "auto/frame093.inc"	;
	.include "auto/frame094.inc"	;
	.include "auto/frame095.inc"	;
	.include "auto/frame096.inc"	;
	.include "auto/frame097.inc"	;
	.include "auto/frame098.inc"	;
	.include "auto/frame099.inc"	;
	.include "auto/frame100.inc"	;
	.include "auto/frame101.inc"	;
	.include "auto/frame102.inc"	;
	.include "auto/frame103.inc"	;
	.include "auto/frame104.inc"	;
	.include "auto/frame105.inc"	;

num_scenes=(105-15)+1

