5 HOME
10 PRINT CHR$(4);"CATALOG"
20 PRINT:PRINT "FOR THE SARCASTIC HI-RES MYST DEMO"
30 PRINT "TYPE: BRUN VGI-MYST"
70 PRINT:PRINT "NOTE: THERE IS ALSO A FULL-FEATURED"
80 PRINT "LORES VERSION AVAILABLE FOR DOWNLOAD"
90 PRINT "IF YOU WANT TO PLAY ON APPLE II"
