; zero page

TEMP0		= $10
TEMP1		= $11
TEMP2		= $12
TEMP3		= $13
TEMP4		= $14
TEMP5		= $15

;; Zero page addresses

HGR_BITS	= $1C

GBASL		= $26
GBASH		= $27

ORNAMENT_L      = $60
ORNAMENT_H      = $61
SAMPLE_L        = $62
SAMPLE_H        = $63

LOOP            = $64
MB_ADDR_L       = $65
MB_ADDR_H       = $66
MB_VALUE        = $67
DONE_PLAYING    = $68
DONE_SONG       = $69
PT3_TEMP        = $6A
APPLEII_MODEL   = $6B

AY_REGISTERS    = $50
A_FINE_TONE     = $50
A_COARSE_TONE   = $51
B_FINE_TONE     = $52
B_COARSE_TONE   = $53
C_FINE_TONE     = $54
C_COARSE_TONE   = $55
NOISE           = $56
ENABLE          = $57
PT3_MIXER_VAL   = $57
A_VOLUME        = $58
B_VOLUME        = $59
C_VOLUME        = $5A
ENVELOPE_FINE   = $5B
ENVELOPE_COARSE = $5C
ENVELOPE_SHAPE  = $5D

PATTERN_L       = $5E
PATTERN_H       = $5F



HGR_X		= $E0
HGR_XH		= $E1
HGR_Y		= $E2
HGR_COLOR	= $E4
HGR_PAGE	= $E6

VGI_BUFFER	= $F0
VGI_TYPE	= $F0
P0		= $F1
P1		= $F2
P2		= $F3
P3		= $F4
P4		= $F5
P5		= $F6
P6		= $F7
VGIL		= $F8
VGIH		= $F9

OUTL		= $FC
OUTH		= $FD

COLOR1		= $FE
COLOR2		= $FF

