5 HOME
10 PRINT "            -= TRI_SCROLL =-"
12 PRINT "    --------------------------------"
15 PRINT "    128 BYTE INTRO FOR LOVEBYTE 2025"
17 PRINT
20 PRINT CHR$(4)"CATALOG"
25 PRINT:PRINT "PRESS ANY KEY TO 'BRUN TRI_SCROLL'"
30 GET A$
35 PRINT
40 PRINT CHR$(4)"BRUN TRI_SCROLL"
