tunnel1_rle:	.byte $28 ; ysize=48
	.byte $A8,$00, $A3,$22, $02, $A6,$00, $A7,$56, $A4,$00, $02
	.byte $A3,$22, $20, $AC,$00, $20,$20, $22,$22, $66, $60
	.byte $A6,$00, $20, $A6,$22, $A4,$00, $60, $62, $A3,$22
	.byte $AC,$00, $A4,$22, $66,$66, $A5,$00, $20, $22, $02
	.byte $A4,$56, $02, $22, $00,$00, $55, $66,$66, $A4,$22
	.byte $AA,$00, $A4,$22, $66,$66, $55,$55, $00,$00, $20, $22
	.byte $62, $A7,$00, $62, $22, $20, $55, $56
	.byte $66,$66, $A4,$22, $A9,$00, $A3,$22, $62, $66, $56
	.byte $55,$55, $00,$00, $22, $66, $56, $00,$00, $20
	.byte $02,$02, $56, $02, $56, $66, $22, $05
	.byte $55, $66,$66, $A4,$22, $A8,$00, $A3,$22, $62, $66,$66
	.byte $55,$55, $00,$00, $22, $62, $66, $55, $00
	.byte $22, $66, $A4,$00, $55, $66, $22, $00
	.byte $55, $66,$66, $A4,$22, $20, $A6,$00, $20, $A3,$22
	.byte $A3,$66, $55, $05, $00,$00, $22, $66, $55
	.byte $00,$00, $22, $66, $00, $20, $02,$02, $05
	.byte $06, $22,$22, $55, $A3,$66, $A4,$22, $A6,$00, $A3,$22
	.byte $06,$06, $56, $55,$55, $A3,$00, $22, $A3,$00, $22
	.byte $A3,$00, $25, $00, $20, $02,$02, $00, $22
	.byte $05, $55, $66,$66, $A4,$22, $A6,$00, $22, $50
	.byte $22, $A8,$00, $22, $A3,$00, $22, $60, $50
	.byte $00, $52, $00, $55, $00, $55, $00
	.byte $22, $00, $05, $06,$06, $A4,$22, $A6,$00, $A3,$22
	.byte $A8,$00, $22, $66, $55, $00, $02, $26
	.byte $55, $00, $55, $00, $02, $00, $05
	.byte $00, $22, $A4,$00, $A4,$22, $A6,$00, $A3,$22, $A3,$60
	.byte $50, $A4,$00, $22, $66, $55, $00,$00, $02
	.byte $05, $A5,$00, $55, $66, $22, $A4,$00, $A4,$22
	.byte $A6,$00, $A3,$22, $A3,$66, $55, $A4,$00, $22, $66
	.byte $55, $00,$00, $A3,$02, $A3,$00, $50, $55, $66
	.byte $22, $A4,$00, $A4,$22, $A6,$00, $A3,$22, $A3,$66, $55,$55
	.byte $A3,$00, $02, $22, $05, $A6,$00, $02, $00
	.byte $65, $66, $26, $22, $00, $55, $66,$66
	.byte $A3,$22, $02, $A7,$00, $A3,$22, $66,$66, $55,$55, $AF,$00
	.byte $26, $22, $00, $55,$55, $66,$66, $A3,$22, $A8,$00
	.byte $A3,$22, $66,$66, $55,$55, $A0,$11,$00, $55,$55, $65, $66
	.byte $A4,$22, $A9,$00, $22,$22, $66,$66, $65, $55,$55, $A7,$00
	.byte $02, $05, $A3,$02, $A4,$00, $55, $66,$66, $A4,$22
	.byte $AA,$00, $02, $22,$22, $66,$66, $55,$55, $AF,$00, $55,$55
	.byte $66,$66, $A3,$22, $02, $AB,$00, $22,$22, $26, $66,$66
	.byte $05, $AF,$00, $55, $66,$66, $A4,$22, $AC,$00, $02
	.byte $22,$22, $06, $A3,$00, $02, $22, $20, $AC,$00
	.byte $66, $26, $A3,$22, $AE,$00, $22, $02, $A8,$00
	.byte $05, $A5,$00, $50, $A5,$00, $A3,$22, $A0,$A8,$00
	.byte $A1
tunnel1_01_rle:	.byte $28 ; ysize=48
	.byte $A0,$12,$11, $A7,$33, $A0,$19,$11, $33, $31, $A0,$11,$11, $31,$31
	.byte $A0,$13,$11, $33,$33, $A8,$11, $A4,$33, $A4,$11, $A3,$33, $A0,$12,$11
	.byte $A4,$33, $A4,$11, $31, $A7,$11, $31, $11,$11, $A4,$33
	.byte $A0,$10,$11, $31, $A3,$33, $63, $A3,$61, $63,$63, $61
	.byte $A4,$11, $33, $11, $33,$33, $11, $13, $A3,$33
	.byte $AF,$11, $31, $33, $63,$63, $A9,$66, $63, $A4,$11
	.byte $33,$33, $11,$11, $A3,$33, $AF,$11, $33, $63, $66,$66
	.byte $F6, $A7,$FF, $F6, $66,$66, $A3,$11, $13,$13, $11,$11
	.byte $A4,$33, $AD,$11, $13,$13, $66,$66, $AB,$FF, $66, $13
	.byte $A6,$11, $13, $A3,$33, $AB,$11, $31, $A3,$11, $66,$66
	.byte $AB,$FF, $66, $31, $11, $33, $11, $33
	.byte $A3,$11, $A3,$13, $AF,$11, $66,$66, $AB,$FF, $66, $33
	.byte $A3,$11, $13, $A0,$13,$11, $31,$31, $66,$66, $6F, $A9,$FF
	.byte $6F, $66, $A4,$11, $33,$33, $A0,$12,$11, $A3,$33, $A3,$66
	.byte $A6,$6F, $A3,$66, $16, $A3,$11, $31, $33,$33, $A0,$12,$11
	.byte $A3,$33, $AB,$66, $16, $A4,$11, $33,$33, $13, $11,$11
	.byte $A3,$33, $AE,$11, $A3,$33, $36, $A8,$16, $A7,$11, $13
	.byte $11,$11, $A4,$33, $AE,$11, $A4,$33, $A0,$11,$11, $A4,$33, $AF,$11
	.byte $A5,$33, $A8,$11, $13, $A7,$11, $A3,$33, $A0,$11,$11, $A4,$33
	.byte $AF,$11, $A4,$33, $A0,$11,$11, $13, $33,$33, $13, $AF,$11
	.byte $A3,$33, $A0,$13,$11, $13, $A0,$12,$11, $33, $13, $A0,$1B,$11
	.byte $13, $A5,$11, $31, $A0,$B0,$11
	.byte $A1
tunnel1_02_rle:	.byte $28 ; ysize=48
	.byte $A0,$14,$AA, $A3,$3A, $A0,$25,$AA, $A3,$11, $A0,$25,$AA, $11,$11, $A0,$26,$AA
	.byte $11, $A0,$27,$AA, $11, $A7,$AA, $1A, $A0,$15,$AA, $3A,$3A
	.byte $A3,$1A, $A5,$AA, $11, $A5,$AA, $1A, $11,$11, $A0,$15,$AA
	.byte $A0,$02,$A3, $A0,$02,$A1, $11, $1A, $A4,$AA, $11, $A5,$AA
	.byte $A3,$11, $3A, $A0,$19,$AA, $A0,$02,$A1, $A3,$1A, $11, $A4,$1A
	.byte $A4,$A1, $A0,$01,$A3, $A0,$1B,$AA, $11, $EE, $A4,$FE, $EE
	.byte $11, $A0,$20,$AA, $11, $EE, $A3,$EF, $FF, $EE
	.byte $11, $A0,$20,$AA, $11, $A3,$A1, $11, $1E,$1E, $11
	.byte $A0,$1F,$AA, $1A, $A0,$01,$A1, $A7,$AA, $A0,$01,$A1, $1A, $A0,$19,$AA
	.byte $A0,$01,$A1, $11, $A0,$02,$A1, $AB,$AA, $11, $A0,$15,$AA, $3A,$3A
	.byte $A3,$1A, $11, $AC,$AA, $11,$11, $A0,$14,$AA, $33,$33, $11
	.byte $AF,$AA, $11, $33,$33, $A0,$FF,$AA, $A0,$73,$AA
	.byte $A1
tunnel1_03_rle:	.byte $28 ; ysize=48
	.byte $A0,$65,$AA, $3A, $A0,$26,$AA, $11, $A0,$24,$AA, $3A, $1A,$1A
	.byte $11, $A0,$27,$AA, $11, $A0,$02,$AA, $11, $A0,$01,$A1, $A0,$02,$A3
	.byte $A0,$1F,$AA, $11, $A5,$E1, $11, $A0,$21,$AA, $11, $EE
	.byte $A3,$FF, $EE, $11, $A0,$21,$AA, $11, $EE, $A3,$EF
	.byte $EE, $11, $A0,$21,$AA, $11, $A5,$A1, $11, $A0,$20,$AA
	.byte $1A, $11, $A5,$AA, $A0,$01,$A1, $1A, $A0,$1E,$AA, $A0,$01,$A3
	.byte $A8,$AA, $31, $A0,$FF,$AA, $A0,$EF,$AA
	.byte $A1
tunnel1_04_rle:	.byte $28 ; ysize=48
	.byte $A0,$B7,$AA, $3A, $A0,$24,$AA, $A0,$01,$A3, $11, $1A, $11
	.byte $A0,$25,$AA, $11, $A0,$01,$AA, $11, $A0,$25,$AA, $11, $A3,$E1
	.byte $A0,$23,$AA, $3A, $11, $EE, $EF, $EE, $1A
	.byte $A0,$22,$AA, $33, $A0,$02,$A1, $A0,$01,$AA, $11, $A0,$23,$AA, $A0,$01,$A3
	.byte $A3,$AA, $11, $A0,$27,$AA, $A0,$01,$A1, $A0,$FF,$AA, $A0,$F0,$AA
	.byte $A1
tunnel1_05_rle:	.byte $28 ; ysize=48
	.byte $A0,$FF,$AA, $A9,$AA, $1A, $A0,$26,$AA, $1A, $E1, $A0,$27,$AA
	.byte $1F, $A0,$26,$AA, $A0,$02,$A1, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$41,$AA
	.byte $A1
tunnel1_06_rle:	.byte $28 ; ysize=48
	.byte $AE,$AA, $66, $EE, $FF, $EE, $A0,$24,$AA, $66
	.byte $EE, $FF, $EE, $A0,$24,$AA, $66, $EE, $FF
	.byte $EE, $A0,$24,$AA, $66, $EE, $FF, $EE, $A0,$24,$AA
	.byte $66, $EE, $FF, $EE, $A0,$24,$AA, $66, $EE
	.byte $FF, $EE, $A0,$24,$AA, $66, $EE, $FF, $A0,$25,$AA
	.byte $66, $EE, $FF, $A0,$25,$AA, $66, $EE, $FF
	.byte $A0,$25,$AA, $A0,$01,$A6, $EE, $FF, $A0,$26,$AA, $EE, $FF
	.byte $A0,$26,$AA, $EE, $FF, $A0,$26,$AA, $EE, $FF, $A0,$26,$AA
	.byte $A0,$01,$AE, $FF, $A0,$27,$AA, $FF, $A0,$27,$AA, $A0,$01,$AF, $A0,$FF,$AA
	.byte $A0,$58,$AA
	.byte $A1
tunnel1_07_rle:	.byte $28 ; ysize=48
	.byte $AE,$AA, $EE,$EE, $FF,$FF, $EE, $A6,$FE, $A0,$19,$AA, $A0,$01,$AE
	.byte $EA, $A0,$02,$AA, $EE, $FF,$FF, $EF, $A0,$01,$AE, $A0,$20,$AA
	.byte $EE, $A0,$01,$AA, $EA, $FE, $FF, $EF, $A0,$01,$AE
	.byte $A0,$21,$AA, $FF,$FF, $EE, $FF,$FF, $EE, $A0,$22,$AA, $FF,$FF
	.byte $A0,$01,$AE, $EF, $FF, $EE, $EA, $A0,$24,$AA, $EE
	.byte $FF,$FF, $EE,$EE, $A0,$23,$AA, $EE,$EE, $FF,$FF, $EE,$EE, $EA
	.byte $A0,$21,$AA, $A3,$EE, $FF,$FF, $A3,$EE, $EA, $A0,$1F,$AA, $A4,$EE
	.byte $FF,$FF, $FE, $EE,$EE, $A0,$01,$AE, $A0,$1E,$AA, $A4,$EE, $EF
	.byte $FF, $EF, $EE, $A0,$01,$AE, $A0,$1F,$AA, $A3,$EE, $FE
	.byte $FF,$FF, $EE,$EE, $A0,$20,$AA, $EE, $FE, $EF, $EE
	.byte $FF,$FF, $EE, $A0,$1D,$AA, $FA, $A0,$02,$AA, $EA, $FE
	.byte $EF, $EE, $FF,$FF, $EF, $A0,$01,$AE, $A0,$1C,$AA, $EF,$EF
	.byte $EA, $FE, $A0,$01,$AF, $A0,$01,$AA, $EE,$EE, $FF,$FF, $EE
	.byte $A0,$02,$AE, $EA,$EA, $A0,$19,$AA, $EE, $FF, $A0,$01,$AF, $A3,$AA
	.byte $EE, $FF,$FF, $EE,$EE, $A4,$AA, $A0,$02,$AE, $EA,$EA, $FA
	.byte $A0,$14,$AA, $A0,$01,$AE, $FE,$FE, $A3,$AA, $EE, $FF,$FF, $EE,$EE
	.byte $A8,$AA, $FE, $A0,$15,$AA, $FF,$FF, $A0,$02,$AA, $EE, $FF,$FF
	.byte $A3,$EE, $A0,$1E,$AA, $A0,$01,$AE, $A0,$01,$AF, $A0,$02,$AA, $EE, $FF,$FF
	.byte $A3,$EE, $A0,$21,$AA, $EE, $A3,$FF, $A3,$EE, $A0,$21,$AA, $EE
	.byte $A4,$FF, $FE, $EE, $EA, $A0,$1F,$AA, $A0,$01,$AE, $A7,$AF
	.byte $A0,$02,$AE, $A0,$8A,$AA
	.byte $A1
tunnel1_08_rle:	.byte $28 ; ysize=48
	.byte $A0,$12,$AA, $FA, $EA, $FA, $EA, $A3,$FA, $A0,$22,$AA
	.byte $A0,$01,$AE, $EF, $FF, $EE, $A0,$25,$AA, $EE, $FF
	.byte $EE, $FE, $A4,$AA, $FF, $A0,$1C,$AA, $FA, $A3,$AA
	.byte $EE, $FF, $EE, $A4,$AA, $EE, $EA, $A0,$17,$AA
	.byte $A3,$EA, $EF,$EF, $A3,$EA, $EE, $FF, $EE, $A4,$EA
	.byte $EE,$EE, $A0,$17,$AA, $EE, $FE, $FF, $A6,$EF, $EE
	.byte $FF, $EE, $A5,$EF, $A0,$17,$AA, $A0,$01,$AE, $EE, $FF
	.byte $EE, $A5,$AA, $EE, $FF, $EE, $A4,$AA, $A0,$01,$AF
	.byte $A0,$18,$AA, $EE, $FF, $EE, $A6,$AA, $EE, $FF
	.byte $EE, $A0,$1C,$AA, $EE, $FF, $EE, $A6,$AA, $EE
	.byte $FF, $EE, $A0,$1C,$AA, $EE, $FF,$FF, $EE, $A6,$AA
	.byte $EE, $FF, $EE, $A0,$16,$AA, $FA, $A4,$AA, $EE
	.byte $FF,$FF, $EE, $A6,$AA, $EE, $FF, $EE, $EA
	.byte $A0,$15,$AA, $EF, $A4,$EA, $EE, $FF,$FF, $EE, $A7,$AA
	.byte $EE, $FF, $EE, $A0,$15,$AA, $EE, $A6,$FF, $EF
	.byte $EE, $A8,$AA, $EE, $FF, $EE, $A0,$14,$AA, $FE,$FE
	.byte $A6,$AE, $A9,$AA, $EE, $FF, $EE, $FA,$FA, $A0,$12,$AA
	.byte $FF,$FF, $FA, $AF,$AA, $EE,$EE, $FF, $A0,$01,$AF, $A0,$12,$AA
	.byte $A0,$01,$AF, $FF,$FF, $A0,$10,$AA, $FE, $A0,$15,$AA, $FF,$FF, $AF,$AA
	.byte $FF,$FF, $A0,$16,$AA, $A0,$01,$AF, $A0,$FF,$AA, $AD,$AA
	.byte $A1
tunnel1_09_rle:	.byte $28 ; ysize=48
	.byte $A0,$14,$AA, $EA, $A0,$28,$AA, $A0,$01,$AE, $EA, $A0,$28,$AA, $EE
	.byte $EA, $A0,$1A,$AA, $EF,$EF, $AB,$AA, $EE, $FE,$FE, $EA
	.byte $FA,$FA, $A0,$14,$AA, $FA, $FF, $FE,$FE, $EE, $EA,$EA
	.byte $A8,$AA, $EE, $FF,$FF, $FE, $EE, $A0,$14,$AA, $A5,$FF
	.byte $EF, $EE, $A9,$AA, $EE, $FF,$FF, $FE, $A0,$14,$AA
	.byte $EF,$EF, $FF, $FE, $A0,$02,$AE, $A8,$AA, $EA, $FE
	.byte $FF,$FF, $EF, $EE, $A0,$12,$AA, $FA, $FF,$FF, $A0,$01,$AA
	.byte $A0,$02,$AE, $EF, $FF, $FA, $A5,$AA, $EA, $FE
	.byte $FF, $EF,$EF, $A0,$01,$AE, $A0,$01,$AA, $A0,$02,$AF, $A0,$18,$AA, $A0,$01,$AE
	.byte $EF,$EF, $FF, $FA, $EA, $FE, $FF, $EF
	.byte $A0,$01,$AE, $A0,$21,$AA, $EE, $FE, $FF, $EF, $A0,$01,$AE
	.byte $A0,$1A,$AA, $FA, $A6,$AA, $EA, $FE, $FF,$FF, $EF
	.byte $EE, $EF, $FF, $FA, $A0,$01,$AA, $FF, $A0,$16,$AA
	.byte $FF, $A5,$EA, $FE, $FF, $EF,$EF, $A0,$01,$AE, $A3,$AA
	.byte $A0,$01,$AE, $EF,$EF, $FF, $A0,$16,$AA, $EE, $A5,$FF, $EF
	.byte $A0,$01,$AE, $A8,$AA, $A0,$01,$AF, $A0,$17,$AA, $EE, $A4,$FF, $A0,$01,$AE
	.byte $A0,$22,$AA, $EE, $FF,$FF, $EF, $A0,$01,$AE, $A0,$23,$AA, $A0,$01,$AE
	.byte $EF,$EF, $A0,$26,$AA, $FF,$FF, $A0,$27,$AA, $A0,$01,$AF, $A0,$FF,$AA, $AD,$AA
	.byte $A1
tunnel1_10_rle:	.byte $28 ; ysize=48
	.byte $A0,$64,$AA, $EA, $FA,$FA, $EA, $A0,$1B,$AA, $FF,$FF, $A6,$AA
	.byte $EA, $FE, $EF, $A0,$01,$AE, $A0,$1B,$AA, $FA, $EE,$EE
	.byte $A4,$AA, $FA, $FE, $FF, $EE, $A4,$AA, $FA
	.byte $A0,$18,$AA, $FF,$FF, $EE, $EA, $A3,$AA, $A0,$01,$AF, $A0,$01,$AE
	.byte $EF, $FF, $EA, $A0,$02,$AA, $EA, $FE, $A0,$18,$AA
	.byte $EE,$EE, $A4,$AA, $FA, $A3,$AA, $A0,$01,$AE, $FF, $FE,$FE
	.byte $FF, $EF, $A0,$16,$AA, $FA, $FF,$FF, $A5,$AA, $FF
	.byte $A4,$AA, $EE, $FF, $EF, $A0,$01,$AE, $A4,$AA, $A0,$01,$AF
	.byte $EF, $A0,$19,$AA, $FF, $A0,$02,$AA, $EA, $FE, $FF
	.byte $EF, $A7,$AA, $A0,$01,$AF, $EE, $A0,$18,$AA, $FF, $A0,$01,$AA
	.byte $EA, $FF, $EF, $A0,$01,$AE, $A7,$AA, $EA, $A0,$01,$AE
	.byte $A0,$19,$AA, $FF, $FE, $EF, $A0,$01,$AE, $A6,$AA, $EE
	.byte $A0,$01,$AA, $EE, $A0,$1B,$AA, $FE, $A0,$01,$AE, $A7,$AA, $EA
	.byte $EE, $A0,$02,$AA, $EE, $A0,$1A,$AA, $FF, $A7,$AA, $EE
	.byte $A0,$01,$AE, $A3,$AA, $EE, $FF, $A0,$19,$AA, $FF, $AC,$AA
	.byte $A0,$02,$AF, $A0,$16,$AA, $A3,$AF, $A0,$FF,$AA, $A0,$81,$AA
	.byte $A1
tunnel1_11_rle:	.byte $28 ; ysize=48
	.byte $A0,$64,$AA, $FA, $A3,$FE, $A0,$1B,$AA, $FF,$FF, $A4,$AA, $EA
	.byte $A3,$AA, $FF, $A0,$1B,$AA, $EA, $FA, $FF,$FF, $A3,$AA
	.byte $EE, $FE, $A3,$AA, $FF, $A0,$19,$AA, $EA, $EE,$EE
	.byte $FF,$FF, $A4,$AA, $A0,$01,$AE, $EF, $A3,$EA, $FF, $A3,$FA
	.byte $FF, $A0,$15,$AA, $A0,$01,$AE, $EE,$EE, $FF, $A0,$01,$AF, $A5,$AA
	.byte $A4,$AF, $FE, $EE, $A3,$AE, $A0,$16,$AA, $FE, $FF,$FF
	.byte $AA,$AA, $A0,$01,$AF, $FF, $EA, $A6,$AA, $FF, $EA
	.byte $A0,$1F,$AA, $FF, $EA, $A5,$AA, $EF, $A0,$01,$AE, $A0,$1B,$AA
	.byte $EA, $FA, $A3,$AA, $FF, $FE, $A5,$AA, $EE
	.byte $A0,$1A,$AA, $FA, $A0,$02,$AF, $A4,$AA, $A0,$01,$AF, $FE, $A4,$AA
	.byte $EE, $A0,$17,$AA, $EE, $FE, $A0,$01,$AF, $A7,$AA, $FA
	.byte $EF, $A4,$AA, $EE, $A0,$15,$AA, $EA,$EA, $A0,$02,$AE, $A8,$AA
	.byte $A0,$01,$AE, $A4,$AA, $FF, $EE, $A0,$14,$AA, $EA, $A0,$01,$AE
	.byte $A0,$24,$AA, $EA, $A0,$02,$AA, $EE, $A0,$22,$AA, $A0,$01,$AE, $EF
	.byte $FE, $EE, $A0,$01,$AE, $A0,$24,$AA, $EE, $FF, $EE
	.byte $A0,$26,$AA, $A0,$01,$AE, $A0,$01,$AF, $A0,$FF,$AA, $AD,$AA
	.byte $A1
tunnel1_12_rle:	.byte $28 ; ysize=48
	.byte $A0,$B1,$AA, $FA, $A4,$AA, $FE,$FE, $A0,$21,$AA, $EF, $A0,$02,$AA
	.byte $FA, $A0,$02,$AA, $FF, $A0,$20,$AA, $FF, $A0,$01,$AE, $A0,$02,$AA
	.byte $A0,$01,$AE, $EA, $A0,$01,$AA, $A0,$01,$AF, $FA, $A0,$26,$AA, $FF
	.byte $A0,$23,$AA, $FA,$FA, $A0,$01,$AA, $FA, $A0,$01,$AF, $FA, $A6,$AA
	.byte $FA, $A0,$1B,$AA, $A0,$01,$AF, $FF, $A0,$01,$AA, $FF, $A0,$01,$AA
	.byte $A0,$01,$AF, $FA, $A4,$AA, $FA, $A0,$01,$AF, $A0,$1C,$AA, $A3,$AF
	.byte $A3,$AA, $FF, $A0,$02,$AA, $FA, $A0,$01,$AF, $A0,$22,$AA, $FA
	.byte $FF, $A3,$AA, $FF, $A0,$22,$AA, $A0,$01,$AF, $A0,$3F,$AA, $FF,$FF
	.byte $A0,$26,$AA, $A0,$01,$AF, $FF,$FF, $A0,$26,$AA, $FF,$FF, $A0,$FF,$AA, $A0,$35,$AA
	.byte $A1
tunnel1_13_rle:	.byte $28 ; ysize=48
	.byte $A0,$12,$AA, $FA, $A0,$9E,$AA, $FA, $A5,$AA, $FE, $A0,$20,$AA
	.byte $EA, $FF, $A5,$AA, $FF, $A0,$20,$AA, $FF, $A6,$AA
	.byte $A0,$01,$AF, $A0,$26,$AA, $A0,$01,$AF, $A0,$01,$AA, $EA, $A0,$01,$AE, $A0,$21,$AA
	.byte $EA, $FA, $A0,$01,$AA, $EA, $A0,$01,$AE, $A0,$01,$AA, $FA
	.byte $A0,$21,$AA, $A0,$01,$AE, $FF, $A0,$01,$AA, $EE, $A0,$25,$AA, $A0,$01,$AF
	.byte $A5,$AA, $EA, $A0,$26,$AA, $EF, $EE, $A0,$2B,$AA, $FF
	.byte $A0,$FF,$AA, $A0,$C2,$AA
	.byte $A1
tunnel1_14_rle:	.byte $28 ; ysize=48
	.byte $A0,$13,$AA, $FA, $A0,$C8,$AA, $FA, $A0,$1D,$AA, $EA, $AD,$AA
	.byte $EA, $A0,$18,$AA, $A0,$02,$AE, $AF,$AA, $EA, $A0,$23,$AA, $FA
	.byte $A0,$02,$AA, $A0,$01,$AE, $EE, $A0,$23,$AA, $FE, $A0,$2B,$AA, $EE
	.byte $EA, $A0,$25,$AA, $EA, $FE, $A0,$26,$AA, $A0,$01,$AE, $EA
	.byte $A0,$FF,$AA, $A0,$C6,$AA
	.byte $A1
tunnel1_15_rle:	.byte $28 ; ysize=48
	.byte $A0,$14,$AA, $EA, $A0,$A1,$AA, $FA,$FA, $A0,$24,$AA, $A0,$01,$AF, $A0,$1D,$AA
	.byte $FF, $A0,$5B,$AA, $FA, $A3,$AA, $EE, $A0,$23,$AA, $A0,$01,$AF
	.byte $A0,$2B,$AA, $FF, $A0,$26,$AA, $FA, $FF, $A0,$26,$AA, $A0,$01,$AF
	.byte $A0,$FF,$AA, $A0,$C7,$AA
	.byte $A1
tunnel1_16_rle:	.byte $28 ; ysize=48
	.byte $A0,$15,$AA, $FA, $A0,$A1,$AA, $FA, $A0,$1A,$AA, $EE, $EA
	.byte $A0,$5C,$AA, $FA, $A0,$27,$AA, $EE, $A0,$01,$AA, $EA, $A0,$23,$AA
	.byte $FF, $A0,$01,$AA, $A0,$01,$AF, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$41,$AA
	.byte $A1
tunnel1_17_rle:	.byte $28 ; ysize=48
	.byte $A0,$16,$AA, $FA, $A0,$93,$AA, $EA, $EE, $EA, $A0,$AD,$AA
	.byte $A0,$01,$AE, $A0,$27,$AA, $A0,$01,$AE, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$3F,$AA
	.byte $A1
tunnel1_18_rle:	.byte $28 ; ysize=48
	.byte $A0,$17,$AA, $EA, $A0,$6B,$AA, $EE,$EE, $A0,$D5,$AA, $A0,$01,$AE, $A0,$27,$AA
	.byte $A0,$01,$AE, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$3F,$AA
	.byte $A1
tunnel1_19_rle:	.byte $28 ; ysize=48
	.byte $A0,$18,$AA, $FA, $A0,$6A,$AA, $A0,$02,$AF, $A0,$FF,$AA, $A0,$FF,$AA, $A0,$FF,$AA
	.byte $A0,$3E,$AA
	.byte $A1
